Repository element-plus/element-plus, pull requests merged in 2021-10, with the labels that each got.

#3770 refactor(components): refactor image
  packages/components/image/__tests__/image.spec.ts
  packages/components/image/index.ts
  packages/components/image/src/image.ts
  packages/components/image/src/image.vue
  packages/components/image/src/index.vue
  packages/hooks/use-attrs/index.ts
  packages/theme-chalk/src/image.scss
  packages/utils/dom.ts
Labels: Refactor

#4091 feat(components): el-switch add inline content support
  docs/en-US/component/switch.md
  docs/examples/switch/custom-icons.vue
  docs/examples/switch/text-description.vue
  packages/components/switch/__tests__/switch.spec.ts
  packages/components/switch/src/index.vue
  packages/theme-chalk/src/switch.scss
Labels: needs discussion

#4012 feat(components): [el-message] & [el-notification] appendTo option added
  docs/en-US/component/message.md
  docs/en-US/component/notification.md
  packages/components/message/__tests__/message-manager.spec.ts
  packages/components/message/src/message-method.ts
  packages/components/message/src/message.ts
  packages/components/notification/__tests__/notify.spec.ts
  packages/components/notification/src/notification.ts
  packages/components/notification/src/notify.ts
Labels: Community Contribution

#3260 fix(components): [el-cascader] can not use keyboard select node(#3254)
  packages/components/cascader-panel/src/index.vue
  packages/components/cascader-panel/src/utils.ts
  packages/components/cascader/__tests__/cascader.spec.ts
  packages/components/cascader/src/index.vue
  packages/utils/aria.ts
Labels: ready to merge
