Repository element-plus/element-plus, pull requests merged in 2021-09, with the labels that each got.

#3133 fix: el-image-viewer drag have problem
  packages/components/image-viewer/src/index.vue
Labels: Community Contribution

#2505 docs(components): [el-collapse] add collapse item slot
  website/docs/en-US/collapse.md
  website/docs/es/collapse.md
  website/docs/fr-FR/collapse.md
  website/docs/jp/collapse.md
  website/docs/zh-CN/collapse.md
Labels: documentation, Community Contribution

#3147 docs/test: [el-form] add scrollToField docs and test
  packages/components/form/__tests__/form.spec.ts
  website/docs/en-US/form.md
  website/docs/es/form.md
  website/docs/fr-FR/form.md
  website/docs/jp/form.md
  website/docs/zh-CN/form.md
Labels: lack of tests

#3189 fix(components): lazy image is not work when it changes src
  packages/components/image/src/index.vue
Labels: Community Contribution

#3294 [Form]: ensure form validation always triggers callback
  packages/components/form/src/form.vue
Labels: Community Contribution

#3342 docs: update guide
  docs/.vitepress/crowdin/en-US/pages/guide.json
  docs/en-US/guide/installation.md
  docs/en-US/guide/migration.md
  docs/en-US/guide/quickstart.md
  docs/en-US/guide/transitions.md
Labels: documentation

#3316 feat(components): calendar component header support slot
  packages/components/calendar/src/index.vue
Labels: Community Contribution

#3337 feat(components): [el-input-number] add focus & blur methods
  packages/components/input-number/src/index.vue
  website/docs/en-US/input-number.md
  website/docs/fr-FR/input-number.md
  website/docs/jp/input-number.md
  website/docs/zh-CN/input-number.md
Labels: ready to merge

#3341 refactor(components): refactor button
  .eslintrc.js
  packages/components/button/index.ts
  packages/components/button/src/button.ts
  packages/components/button/src/button.vue
  packages/components/button/src/types.ts
  packages/utils/props.ts
  packages/utils/tsconfig.json
  tsconfig.json
Labels: ready to merge

#3385 docs: [locale] update tr.ts
  packages/locale/lang/tr.ts
Labels: ready to merge

#3409 D2M
  .github/azure-pipelines.yml
  .github/workflows/preview-build.yml
  .github/workflows/preview-deploy.yml
  .github/workflows/publish-npm.yml
  CHANGELOG.en-US.md
  build/.eslintrc.js
  build/build-indices.ts
  build/build-locale.ts
  build/components.ts
  build/full-bundle.ts
  build/gen-dts.ts
  build/gen-entry-dts.ts
  build/get-deps.ts
  build/getCpus.ts
  build/getPkgs.ts
  build/paths.ts
  build/rollup.config.ts
  build/size-reporter.ts
  build/utils.ts
  build/webpack.config.js
  build/worker.js
  package.json
  packages/components/package.json
  packages/element-plus/package.json
  packages/hooks/package.json
  packages/locale/lang/tr.ts
  scripts/build.sh
  scripts/publish.sh
  website/webpack.config.js
  yarn.lock
Labels: 🚀 Ready for takeoff

#3411 D2M
  .github/workflows/publish-npm.yml
Labels: 🚀 Ready for takeoff

#3415 fix(build): external packages
  build/build-locale.ts
  build/utils.ts
  package.json
  scripts/build.sh
Labels: hotfix

#3406 fix(utils): add type remove the ts error
  packages/utils/scrollbar-width.ts
  packages/utils/vnode.ts
Labels: Community Contribution

#3356 Feat/remove mitt
  packages/components/cascader/src/index.vue
  packages/components/checkbox/src/checkbox-group.vue
  packages/components/checkbox/src/useCheckbox.ts
  packages/components/collapse/src/collapse-item.vue
  packages/components/collapse/src/collapse.type.ts
  packages/components/collapse/src/collapse.vue
  packages/components/color-picker/src/index.vue
  packages/components/form/src/form-item.vue
  packages/components/form/src/form.vue
  packages/components/input/src/index.vue
  packages/components/menu/src/menu.ts
  packages/components/menu/src/menu.type.ts
  packages/components/menu/src/menuItem.vue
  packages/components/menu/src/submenu.vue
  packages/components/package.json
  packages/components/radio/src/radio-group.vue
  packages/components/select/src/option-group.vue
  packages/components/select/src/select.vue
  packages/components/select/src/token.ts
  packages/components/select/src/useOption.ts
  packages/components/select/src/useSelect.ts
  packages/components/slider/src/index.vue
  packages/components/switch/src/index.vue
  packages/components/time-picker/src/common/picker.vue
  packages/components/transfer/src/index.vue
  packages/components/tree/src/model/useDragNode.ts
  packages/components/tree/src/tree-node.vue
  packages/element-plus/package.json
  packages/tokens/form.ts
  packages/tokens/package.json
Labels: ready to merge, Community Contribution

#3436 feat(components): [el-timeline] add center prop
  docs/en-US/component/timeline.md
  docs/examples/timeline/center.vue
  packages/components/timeline/__tests__/timeline.spec.ts
  packages/components/timeline/src/item.vue
  packages/theme-chalk/src/timeline.scss
Labels: Community Contribution

#3477 chore(docs): website UI updates
  docs/.vitepress/crowdin/en-US/component/demo-block.json
  docs/.vitepress/plugins.js
  docs/.vitepress/vitepress/components/globals/vp-demo.vue
  docs/.vitepress/vitepress/components/icons/copy-icon.vue
  docs/.vitepress/vitepress/components/vp-demo.vue
  docs/.vitepress/vitepress/utils.ts
Labels: ready to merge

#3537 feat(components): [el-message-box] add inline style prop
  docs/en-US/component/message-box.md
  packages/components/message-box/__tests__/message-box.spec.ts
  packages/components/message-box/src/index.vue
  packages/components/message-box/src/message-box.type.ts
Labels: Community Contribution

#3512 refactor(components): el-notification icon
  docs/en-US/component/notification.md
  packages/components/notification/__tests__/notification.spec.ts
  packages/components/notification/src/index.vue
  packages/components/notification/src/notification.type.ts
  packages/theme-chalk/src/notification.scss
Labels: icon

#3505 refactor(components): el-dialog icon
  packages/components/dialog/src/dialog.vue
  packages/theme-chalk/src/dialog.scss
Labels: icon

#3550 chore(project): compatible windows the shell command
  package.json
  scripts/ifBuild.sh
Labels: Community Contribution

#3567 D2M
  DEV_FAQ.md
  docs/.vitepress/config.js
  docs/.vitepress/crowdin/en-US/pages/component.json
  docs/.vitepress/vitepress/components/vp-navbar.vue
  docs/.vitepress/vitepress/styles/base.scss
  docs/en-US/component/menu.md
  docs/examples/cascader/any-level.vue
  docs/examples/cascader/basic.vue
  docs/examples/cascader/clearable.vue
  docs/examples/cascader/custom-content.vue
  docs/examples/cascader/filterable.vue
  docs/examples/cascader/last-level.vue
  docs/examples/cascader/option-disabling.vue
  docs/examples/cascader/panel.vue
  package.json
  packages/components/affix/src/affix.ts
  packages/components/avatar/src/avatar.ts
  packages/components/badge/src/badge.ts
  packages/components/breadcrumb/src/breadcrumb-item.ts
  packages/components/breadcrumb/src/breadcrumb.ts
  packages/components/breadcrumb/src/breadcrumb.vue
  packages/components/card/src/card.ts
  packages/components/dialog/src/dialog.ts
  packages/components/input/src/index.vue
  packages/components/menu/__tests__/menu.spec.ts
  packages/components/menu/src/menu.ts
  packages/components/menu/src/menuItem.vue
  packages/components/menu/src/submenu.vue
  packages/components/menu/src/use-menu-color.ts
  packages/components/menu/src/use-menu-css-var.ts
  packages/components/menu/src/use-menu.ts
  packages/components/message/src/message.ts
  packages/components/notification/src/notification.ts
  packages/components/overlay/src/overlay.ts
  packages/components/pagination/src/components/sizes.vue
  packages/components/pagination/src/pagination.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/components/virtual-list/index.ts
  packages/components/virtual-list/src/builders/buildGrid.ts
  packages/components/virtual-list/src/builders/buildList.ts
  packages/components/virtual-list/src/components/dynamic-size-list.ts
  packages/components/virtual-list/src/components/scrollbar.ts
  packages/components/virtual-list/src/defaults.ts
  packages/components/virtual-list/src/hooks/useCache.ts
  packages/components/virtual-list/src/props.ts
  packages/element-plus/component.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/menu.scss
  packages/utils/props.ts
  packages/utils/tests/prop.spec.ts
  scripts/ifBuild.sh
  yarn.lock
Labels: 🚀 Ready for takeoff

#3574 D2M
  .eslintignore
  .github/workflows/master-deploy.yml
  .github/workflows/preview-build.yml
  .github/workflows/publish-npm.yml
  .github/workflows/staging-preview.yml
  .github/workflows/unit-test.yml
  .gitignore
  .npmrc
  .nvmrc
  .prettierignore
  DEV_FAQ.md
  README.md
  build/components.ts
  build/full-bundle.ts
  build/gen-dts.ts
  build/rollup.config.ts
  build/utils.ts
  commitlint.config.js
  docs/package.json
  docs/yarn.lock
  jest.config.js
  lerna.json
  package.json
  packages/components/package.json
  packages/components/select-v2/src/select-dropdown.vue
  packages/directives/package.json
  packages/element-plus/package.json
  packages/hooks/package.json
  packages/locale/package.json
  packages/test-utils/package.json
  packages/tokens/package.json
  packages/utils/package.json
  play/package.json
  play/vite.config.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/build.sh
  scripts/gc.sh
  scripts/publish.sh
  yarn.lock
Labels: 🚀 Ready for takeoff

#3507 refactor(components): el-message-box icon
  docs/en-US/component/message-box.md
  docs/en-US/component/message.md
  packages/components/message-box/__tests__/message-box.spec.ts
  packages/components/message-box/src/index.vue
  packages/components/message-box/src/message-box.type.ts
  packages/components/message/__tests__/message.spec.ts
  packages/components/message/src/message.ts
  packages/components/message/src/message.vue
  packages/theme-chalk/src/message-box.scss
  packages/theme-chalk/src/message.scss
Labels: icon

#3513 refactor(components): el-popconfirm icon
  docs/en-US/component/popconfirm.md
  docs/examples/popconfirm/customize.vue
  docs/examples/popconfirm/trigger-event.vue
  packages/components/popconfirm/src/popconfirm.ts
  packages/components/popconfirm/src/popconfirm.vue
Labels: icon

#3518 refactor(components): el-page-header icon
  docs/en-US/component/page-header.md
  packages/components/page-header/__tests__/page-header.spec.ts
  packages/components/page-header/src/page-header.ts
  packages/components/page-header/src/page-header.vue
Labels: icon

#3520 refactor(components): el-steps icon
  packages/components/steps/__tests__/steps.spec.ts
  packages/components/steps/src/item.vue
Labels: icon

#3514 refactor(components): el-backtop icon
  packages/components/backtop/__tests__/backtop.spec.ts
  packages/components/backtop/src/backtop.vue
  packages/theme-chalk/src/backtop.scss
Labels: icon

#3536 refactor(components): el-button icon
  docs/en-US/component/button.md
  docs/examples/button/basic.vue
  docs/examples/button/group.vue
  docs/examples/button/icon.vue
  docs/examples/button/size.vue
  packages/components/button/__tests__/button.spec.ts
  packages/components/button/src/button.ts
  packages/components/button/src/button.vue
  packages/theme-chalk/src/button.scss
Labels: icon

#3590 refactor(components): el-tree icon
  docs/en-US/component/tree.md
  packages/components/tree/src/tree-node.vue
  packages/components/tree/src/tree.type.ts
  packages/components/tree/src/tree.vue
Labels: icon

#3599 refactor(components): el-avatar icon
  docs/en-US/component/avatar.md
  docs/examples/avatar/types.vue
  packages/components/avatar/__tests__/avatar.spec.ts
  packages/components/avatar/src/avatar.ts
  packages/components/avatar/src/avatar.vue
Labels: icon

#3602 refactor(components): el-carousel icon
  packages/components/carousel/src/main.vue
Labels: icon

#3607 refactor(components): el-progress icon
  packages/components/progress/__tests__/progress.spec.ts
  packages/components/progress/src/index.vue
Labels: icon

#3609 refactor(components): el-result icon
  packages/components/result/src/icon-error.vue
  packages/components/result/src/icon-info.vue
  packages/components/result/src/icon-success.vue
  packages/components/result/src/icon-warning.vue
  packages/components/result/src/index.vue
  packages/theme-chalk/src/result.scss
Labels: icon

#3646 refactor(components): el-timeline icon
  docs/en-US/component/timeline.md
  docs/examples/timeline/custom-node.vue
  packages/components/timeline/__tests__/timeline.spec.ts
  packages/components/timeline/src/item.vue
Labels: icon

#3611 refactor(components): el-table icon
  docs/examples/table/custom-column.vue
  packages/components/table/src/config.ts
  packages/components/table/src/filter-panel.vue
  packages/theme-chalk/src/table.scss
Labels: icon

#3660 fix(components): trigger update:modelValue by itself
  packages/components/slider/src/index.vue
  packages/components/slider/src/useSlide.ts
Labels: Community Contribution

#3680 chore(project): revise rm rf to rimraf
  packages/directives/package.json
  packages/hooks/package.json
  packages/locale/package.json
  packages/theme-chalk/package.json
  packages/tokens/package.json
  packages/utils/package.json
Labels: Community Contribution

#3683 feat(docs): enable mirror site redirection
  docs/.vitepress/vitepress/components/vp-app.vue
  docs/.vitepress/vitepress/styles/content/doc-content.scss
Labels: documentation

#3639 refactor(components): refactor menu
  packages/components/menu/__tests__/menu.spec.ts
  packages/components/menu/index.ts
  packages/components/menu/src/menu-collapse-transition.vue
  packages/components/menu/src/menu-item-group.ts
  packages/components/menu/src/menu-item-group.vue
  packages/components/menu/src/menu-item.ts
  packages/components/menu/src/menu-item.vue
  packages/components/menu/src/menu.ts
  packages/components/menu/src/menu.type.ts
  packages/components/menu/src/menuItem.vue
  packages/components/menu/src/menuItemGroup.vue
  packages/components/menu/src/sub-menu.ts
  packages/components/menu/src/submenu.vue
  packages/components/menu/src/types.ts
  packages/components/menu/src/use-menu-color.ts
  packages/components/menu/src/use-menu-css-var.ts
  packages/components/menu/src/use-menu.ts
Labels: enhancement

#3721 fix sideEffects at package.json
  packages/element-plus/package.json
Labels: Community Contribution

#3749 D2M
  .github/workflows/deploy-docs.yml
  CHANGELOG.en-US.md
  DEV_FAQ.md
  build/helper.ts
  docs/.gitignore
  docs/.vitepress/build/.eslintrc.js
  docs/.vitepress/build/crowdin-generate.ts
  docs/.vitepress/config.js
  docs/.vitepress/config/.eslintrc.js
  docs/.vitepress/config/features.ts
  docs/.vitepress/config/head.ts
  docs/.vitepress/config/index.ts
  docs/.vitepress/config/nav.ts
  docs/.vitepress/config/plugins.ts
  docs/.vitepress/config/sidebars.ts
  docs/.vitepress/dark-mode.js
  docs/.vitepress/features.js
  docs/.vitepress/nav.js
  docs/.vitepress/sidebars.js
  docs/.vitepress/site-utils.js
  docs/.vitepress/utils/lang.ts
  docs/.vitepress/utils/paths.ts
  docs/.vitepress/vitepress/components/vp-app.vue
  docs/en-US/guide/migration.md
  docs/en-US/guide/theming.md
  docs/examples/card/simple.vue
  docs/examples/color-picker/basic.vue
  docs/examples/tooltip/basic.vue
  docs/package.json
  docs/tsconfig.json
  docs/vite.config.ts
  package.json
  packages/components/autocomplete/src/index.vue
  packages/components/menu/src/menu.ts
  packages/components/table/src/store/tree.ts
  packages/element-plus/package.json
  packages/theme-chalk/src/tabs.scss
  packages/utils/aria.ts
  packages/utils/color.ts
  packages/utils/props.ts
  packages/utils/tests/prop.spec.ts
  pnpm-lock.yaml
  scripts/if-build.sh
Labels: 🚀 Ready for takeoff

#3659 fix(components): fix composition event bug
  packages/components/cascader/__tests__/cascader.spec.ts
  packages/components/cascader/src/index.vue
Labels: Community Contribution
