Repository element-plus/element-plus, pull requests merged in 2021-08, with the labels that each got.

#2778 feat(var): var sass map for components
  packages/theme-chalk/src/alert.scss
  packages/theme-chalk/src/autocomplete.scss
  packages/theme-chalk/src/avatar.scss
  packages/theme-chalk/src/backtop.scss
  packages/theme-chalk/src/calendar.scss
  packages/theme-chalk/src/carousel.scss
  packages/theme-chalk/src/cascader.scss
  packages/theme-chalk/src/checkbox.scss
  packages/theme-chalk/src/common/popup.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/date-picker/var.scss
  packages/theme-chalk/src/descriptions.scss
  packages/theme-chalk/src/dialog.scss
  packages/theme-chalk/src/empty.scss
  packages/theme-chalk/src/form.scss
  packages/theme-chalk/src/input-number.scss
  packages/theme-chalk/src/input.scss
  packages/theme-chalk/src/loading.scss
  packages/theme-chalk/src/menu.scss
  packages/theme-chalk/src/message-box.scss
  packages/theme-chalk/src/notification.scss
  packages/theme-chalk/src/option-group.scss
  packages/theme-chalk/src/option-item.scss
  packages/theme-chalk/src/option.scss
  packages/theme-chalk/src/pagination.scss
  packages/theme-chalk/src/popover.scss
  packages/theme-chalk/src/radio-button.scss
  packages/theme-chalk/src/radio.scss
  packages/theme-chalk/src/result.scss
  packages/theme-chalk/src/scrollbar.scss
  packages/theme-chalk/src/select-dropdown-v2.scss
  packages/theme-chalk/src/select-dropdown.scss
  packages/theme-chalk/src/select-v2.scss
  packages/theme-chalk/src/select.scss
  packages/theme-chalk/src/slider.scss
  packages/theme-chalk/src/switch.scss
  packages/theme-chalk/src/table.scss
  packages/theme-chalk/src/tag.scss
  packages/theme-chalk/src/timeline-item.scss
  packages/theme-chalk/src/tooltip.scss
  packages/theme-chalk/src/transfer.scss
  packages/theme-chalk/src/tree.scss
Labels: css migration, enhancement

#2791 fix: select-v2's dropdown width wrong if create in style(display: none)
  packages/select-v2/src/useSelect.ts
Labels: Community Contribution

#2789 fix(locale): update Norwegian translation file
  packages/locale/lang/nb-no.ts
Labels: Community Contribution, Translation

#2787 docs(result): fix typo
  website/docs/en-US/result.md
  website/docs/es/result.md
  website/docs/fr-FR/result.md
  website/docs/jp/result.md
  website/docs/zh-CN/result.md
Labels: Community Contribution, documentation

#2808 refactor(var): move css var from root to class
  packages/theme-chalk/src/alert.scss
  packages/theme-chalk/src/aside.scss
  packages/theme-chalk/src/avatar.scss
  packages/theme-chalk/src/backtop.scss
  packages/theme-chalk/src/badge.scss
  packages/theme-chalk/src/button.scss
  packages/theme-chalk/src/calendar.scss
  packages/theme-chalk/src/card.scss
  packages/theme-chalk/src/carousel.scss
  packages/theme-chalk/src/cascader.scss
  packages/theme-chalk/src/checkbox.scss
  packages/theme-chalk/src/collapse.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/descriptions.scss
  packages/theme-chalk/src/dialog.scss
  packages/theme-chalk/src/dropdown.scss
  packages/theme-chalk/src/empty.scss
  packages/theme-chalk/src/footer.scss
  packages/theme-chalk/src/form.scss
  packages/theme-chalk/src/header.scss
  packages/theme-chalk/src/input-number.scss
  packages/theme-chalk/src/input.scss
  packages/theme-chalk/src/link.scss
  packages/theme-chalk/src/main.scss
  packages/theme-chalk/src/menu.scss
  packages/theme-chalk/src/message-box.scss
  packages/theme-chalk/src/message.scss
  packages/theme-chalk/src/notification.scss
  packages/theme-chalk/src/pagination.scss
  packages/theme-chalk/src/popover.scss
  packages/theme-chalk/src/popper.scss
  packages/theme-chalk/src/radio.scss
  packages/theme-chalk/src/rate.scss
  packages/theme-chalk/src/result.scss
  packages/theme-chalk/src/scrollbar.scss
  packages/theme-chalk/src/select.scss
  packages/theme-chalk/src/skeleton-item.scss
  packages/theme-chalk/src/skeleton.scss
  packages/theme-chalk/src/slider.scss
  packages/theme-chalk/src/switch.scss
  packages/theme-chalk/src/table.scss
  packages/theme-chalk/src/tag.scss
  packages/theme-chalk/src/time-select.scss
  packages/theme-chalk/src/timeline-item.scss
  packages/theme-chalk/src/timeline.scss
  packages/theme-chalk/src/tooltip.scss
  packages/theme-chalk/src/transfer.scss
  packages/theme-chalk/src/tree.scss
Labels: css migration, enhancement

#2821 fix(var): fix input/radio/checkbox used by other components
  packages/theme-chalk/src/checkbox-button.scss
  packages/theme-chalk/src/checkbox-group.scss
  packages/theme-chalk/src/checkbox.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/date-picker/picker.scss
  packages/theme-chalk/src/input.scss
  packages/theme-chalk/src/radio-button.scss
  packages/theme-chalk/src/radio.scss
Labels: css migration

#2879 refactor(transition): use sass map refactor & rename some transition
  packages/theme-chalk/src/breadcrumb.scss
  packages/theme-chalk/src/check-tag.scss
  packages/theme-chalk/src/checkbox-button.scss
  packages/theme-chalk/src/common/transition.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/input.scss
  packages/theme-chalk/src/radio-button.scss
  packages/theme-chalk/src/select-v2.scss
  packages/theme-chalk/src/select.scss
  packages/theme-chalk/src/slider.scss
  packages/theme-chalk/src/upload.scss
  packages/theme-chalk/src/var.scss
Labels: css migration

#2878 refactor(tag): use inherit css var way to simplify tag
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/tag.scss
Labels: css migration

#2869 refactor(color): add css var color for button & fix style for datepicker
  packages/theme-chalk/src/alert.scss
  packages/theme-chalk/src/button-group.scss
  packages/theme-chalk/src/button.scss
  packages/theme-chalk/src/color-picker.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/date-picker.scss
  packages/theme-chalk/src/date-picker/date-picker.scss
  packages/theme-chalk/src/date-picker/date-range-picker.scss
  packages/theme-chalk/src/date-picker/picker-panel.scss
  packages/theme-chalk/src/date-picker/var.scss
  packages/theme-chalk/src/date-picker/year-table.scss
  packages/theme-chalk/src/message.scss
  packages/theme-chalk/src/mixins/_button.scss
  packages/theme-chalk/src/mixins/_var.scss
  packages/theme-chalk/src/pagination.scss
  packages/theme-chalk/src/reset.scss
  packages/theme-chalk/src/var.scss
  yarn.lock
Labels: css migration

#2892 refactor(var): alert/badge/link/message/message-box/notification/tag
  packages/theme-chalk/src/alert.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/link.scss
  packages/theme-chalk/src/message-box.scss
  packages/theme-chalk/src/message.scss
  packages/theme-chalk/src/notification.scss
  packages/theme-chalk/src/result.scss
Labels: css migration

#2943 fix(badge): fix dot-badge color
  packages/badge/src/index.vue
Labels: Community Contribution

#2933 feat(switch): add border color
  packages/switch/src/index.vue
  website/docs/en-US/switch.md
  website/docs/es/switch.md
  website/docs/fr-FR/switch.md
  website/docs/jp/switch.md
  website/docs/zh-CN/switch.md
Labels: Community Contribution

#2939 Added an example of the popconfirm button click event
  website/docs/en-US/popconfirm.md
  website/docs/es/popconfirm.md
  website/docs/fr-FR/popconfirm.md
  website/docs/jp/popconfirm.md
  website/docs/zh-CN/popconfirm.md
Labels: Community Contribution

#2944 更新骨架屏自定义模板时的key值
  packages/skeleton/src/index.vue
Labels: Community Contribution

#3001 fix(form): token.ts parameter bug
  packages/form/src/token.ts
Labels: type related, Community Contribution

#3033 D2M
  CHANGELOG.en-US.md
  package.json
  packages/components/package.json
  packages/directives/package.json
  packages/element-plus/package.json
  packages/hooks/package.json
  packages/locale/package.json
  packages/test-utils/package.json
  packages/tokens/package.json
  packages/utils/package.json
  scripts/gc.sh
  scripts/update-versions.sh
  yarn.lock
Labels: 🚀 Ready for takeoff

#3036 D2M
  CHANGELOG.en-US.md
  build/full-bundle.ts
  package.json
  packages/components/virtual-list/src/components/fixed-size-list.ts
  yarn.lock
Labels: 🚀 Ready for takeoff

#3043 D2M
  CHANGELOG.en-US.md
  build/full-bundle.ts
  packages/components/descriptions/src/descriptions-cell.ts
  packages/components/descriptions/src/index.vue
  packages/components/form/src/label-wrap.ts
  packages/components/menu/__tests__/menu.spec.ts
  packages/components/menu/src/menu.ts
  packages/components/menu/src/menu.vue
  packages/components/menu/src/menuItemGroup.vue
  packages/components/menu/src/submenu.vue
  packages/components/menu/src/useMenu.ts
  packages/components/message-box/src/message-box.type.ts
  packages/element-plus/index.ts
  packages/hooks/use-locale/index.ts
  packages/theme-chalk/src/descriptions.scss
  packages/theme-chalk/src/menu.scss
  website/components/demo-block.vue
  website/docs/en-US/container.md
  website/docs/en-US/menu.md
  website/docs/fr-FR/container.md
  website/docs/fr-FR/menu.md
  website/docs/jp/container.md
  website/docs/jp/menu.md
  website/docs/zh-CN/container.md
  website/docs/zh-CN/menu.md
Labels: 🚀 Ready for takeoff

#3011 fix(rate):use constant
  packages/components/rate/src/index.vue
Labels: Community Contribution

#3051 fix: stop pinning vue peer dependency version
  package.json
  packages/components/package.json
  packages/directives/package.json
  packages/element-plus/package.json
  packages/hooks/package.json
  packages/test-utils/package.json
  packages/tokens/package.json
  packages/utils/package.json
  yarn.lock
Labels: Community Contribution

#3048 fixed resolve font path errors
  website/docs/zh-CN/custom-theme.md
Labels: Community Contribution

#3057 D2M
  CHANGELOG.en-US.md
  build/build-locale.ts
  build/components.ts
  package.json
  packages/components/head/style/index.ts
  packages/components/header/style/css.ts
  packages/components/header/style/index.ts
  packages/components/menu-item-group/style/css.ts
  packages/components/menu-item-group/style/index.ts
  packages/components/menu-item/style/css.ts
  packages/components/menu-item/style/index.ts
  packages/components/menu/src/menu.ts
  packages/components/menu/src/menuItem.vue
  packages/components/package.json
  packages/components/radio-button/style/css.ts
  packages/components/radio-button/style/index.ts
  packages/components/radio-group/style/css.ts
  packages/components/radio-group/style/index.ts
  packages/components/radio/src/radio-group.vue
  packages/components/rate/src/index.vue
  packages/components/select-v2/__tests__/select.spec.ts
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/option-item.vue
  packages/components/select-v2/src/select-dropdown.vue
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/token.ts
  packages/components/select-v2/src/useAllowCreate.ts
  packages/components/select-v2/src/useOption.ts
  packages/components/select-v2/src/useSelect.ts
  packages/components/step/style/css.ts
  packages/components/step/style/index.ts
  packages/components/sub-menu/style/css.ts
  packages/components/sub-menu/style/index.ts
  packages/components/table/src/table-body/render-helper.ts
  packages/components/tree/src/tree.vue
  packages/components/virtual-list/src/builders/buildList.ts
  packages/components/virtual-list/src/components/scrollbar.ts
  packages/directives/package.json
  packages/element-plus/package.json
  packages/hooks/package.json
  packages/locale/lang/zh-tw.ts
  packages/test-utils/package.json
  packages/theme-chalk/src/color-picker.scss
  packages/theme-chalk/src/select-dropdown-v2.scss
  packages/theme-chalk/src/select-v2.scss
  packages/tokens/package.json
  packages/utils/package.json
  scripts/monorepo.sh
  website/docs/en-US/i18n.md
  website/docs/en-US/select-v2.md
  website/docs/es/i18n.md
  website/docs/es/select-v2.md
  website/docs/fr-FR/i18n.md
  website/docs/fr-FR/select-v2.md
  website/docs/jp/i18n.md
  website/docs/jp/select-v2.md
  website/docs/zh-CN/custom-theme.md
  website/docs/zh-CN/i18n.md
  website/docs/zh-CN/select-v2.md
  yarn.lock
Labels: 🚀 Ready for takeoff

#3062 refactor: enhance type definition
  build/build-indices.ts
  package.json
  packages/components/autocomplete/src/index.vue
  packages/components/button/src/button.vue
  packages/components/button/src/types.ts
  packages/components/calendar/src/date-table.vue
  packages/components/calendar/src/index.vue
  packages/components/cascader/src/index.vue
  packages/components/checkbox/src/checkbox-button.vue
  packages/components/checkbox/src/checkbox.vue
  packages/components/checkbox/src/useCheckbox.ts
  packages/components/collapse/src/collapse.vue
  packages/components/color-picker/src/components/alpha-slider.vue
  packages/components/color-picker/src/index.vue
  packages/components/dropdown/src/dropdown.vue
  packages/components/image-viewer/src/index.vue
  packages/components/loading/src/index.ts
  packages/components/menu/src/menuItem.vue
  packages/components/popconfirm/src/index.vue
  packages/components/popper/src/renderers/popper.ts
  packages/components/popper/src/use-popper/defaults.ts
  packages/components/popper/src/use-popper/popper-options.ts
  packages/components/progress/src/index.vue
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/select.vue
  packages/components/slider/src/index.vue
  packages/components/slider/src/slider.type.ts
  packages/components/slider/src/useSlide.ts
  packages/components/slider/src/useSliderButton.ts
  packages/components/slider/src/useStops.ts
  packages/components/table/src/filter-panel.vue
  packages/components/table/src/table-column/defaults.ts
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/common/props.ts
  packages/components/time-picker/src/time-picker-com/panel-time-pick.vue
  packages/components/time-picker/src/time-picker-com/panel-time-range.vue
  packages/components/time-select/src/time-select.vue
  packages/components/tree/src/model/useKeydown.ts
  packages/components/tree/src/tree-node.vue
  packages/components/upload/src/upload-list.vue
  packages/hooks/use-popper/use-popper-options.ts
  packages/utils/dom.ts
  tsconfig.json
  typings/vue-test-utils.d.ts
  website/components/side-nav.vue
  yarn.lock
Labels: type related

#3137 fix(locale): update korean translation
  packages/locale/lang/ko.ts
Labels: i18n, Translation

#3114 fix: [image-viewer] two-finger zoom in and out
  packages/components/image/src/index.vue
Labels: Community Contribution

#3151 D2M
  CHANGELOG.en-US.md
  package.json
  packages/components/dropdown/src/dropdown.vue
  packages/components/image/src/index.vue
  packages/directives/package.json
  packages/hooks/package.json
  packages/locale/package.json
  packages/theme-chalk/package.json
  packages/theme-chalk/src/checkbox-button.scss
  packages/theme-chalk/src/radio-button.scss
  packages/tokens/package.json
  packages/utils/package.json
  scripts/build.sh
  scripts/publish.sh
  yarn.lock
Labels: 🚀 Ready for takeoff
