Repository element-plus/element-plus, pull requests merged in 2021-12, with the labels that each got.

#4599 chore(deps): update dependency vue to 3.2.23
  package.json
  pnpm-lock.yaml
Labels: dependencies

#4598 fix(utils): setTimeout & config-provider type
  packages/components/config-provider/index.ts
  packages/tokens/config-provider.ts
  packages/utils/types.ts
Labels: type related, hotfix

#4388 fix(theme-chalk): Added !optional to @extend
  packages/theme-chalk/src/image.scss
  packages/theme-chalk/src/mixins/mixins.scss
Labels: style related

#4563 fix(components): [el-date-picker] can't use numpadEnter
  packages/components/date-picker/__tests__/date-picker.spec.ts
  packages/components/time-picker/src/common/picker.vue
  packages/utils/aria.ts
Labels: lack of tests

#4619 fix(hooks): fix translate option
  packages/hooks/use-locale/index.ts
Labels: i18n, hotfix

#4664 fix(hooks): locale return key name if not defined
  packages/hooks/__tests__/use-locale.spec.ts
  packages/hooks/use-locale/index.ts
  packages/locale/__test__/locale.spec.ts
  packages/locale/index.ts
Labels: enhancement, i18n

#4615 refactor(style): rename $background-color-base to --el-bg-color
  docs/.vitepress/vitepress/styles/vars.scss
  packages/theme-chalk/src/check-tag.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/date-picker/date-table.scss
  packages/theme-chalk/src/date-picker/month-table.scss
  packages/theme-chalk/src/date-picker/time-spinner.scss
  packages/theme-chalk/src/date-picker/year-table.scss
  packages/theme-chalk/src/image.scss
  packages/theme-chalk/src/input-number.scss
  packages/theme-chalk/src/input.scss
  packages/theme-chalk/src/select-v2.scss
  packages/theme-chalk/src/steps.scss
  packages/theme-chalk/src/table.scss
  packages/theme-chalk/src/tabs.scss
  packages/theme-chalk/src/time-select.scss
  packages/theme-chalk/src/upload.scss
  packages/theme-chalk/src/var.scss
Labels: style related

#4696 fix: vue type errors
  package.json
  pnpm-lock.yaml
Labels: hotfix

#4679 fix(docs): fix code not working in Codepen (#4678)
  docs/examples/input-number/basic.vue
Labels: ready to merge

#4514 feat(components): [el-dialog] support custom close icon
  packages/components/dialog/__tests__/dialog.spec.ts
  packages/components/dialog/src/dialog.ts
  packages/components/dialog/src/dialog.vue
Labels: Community Contribution

#4723 docs: update quickstart.md
  docs/en-US/guide/quickstart.md
Labels: documentation, ready to merge

#4435 feat(components): [el-divider] support setting the dividing line style
  docs/en-US/component/divider.md
  docs/examples/divider/custom-content.vue
  docs/examples/divider/line-dashed.vue
  docs/examples/divider/vertical-divider.vue
  packages/components/divider/__tests__/divider.spec.ts
  packages/components/divider/src/divider.ts
  packages/components/divider/src/divider.vue
  packages/theme-chalk/src/divider.scss
Labels: enhancement

#4674 refactor(components): [el-checkbox] simplify the value
  packages/components/checkbox/src/useCheckbox.ts
Labels: Community Contribution

#4271 refactor(components): refactor switch
  packages/components/switch/__tests__/switch.spec.ts
  packages/components/switch/index.ts
  packages/components/switch/src/switch.ts
  packages/components/switch/src/switch.vue
Labels: ready to merge

#4717 fix(components): [el-form] vertical aligin
  packages/theme-chalk/src/form.scss
  packages/theme-chalk/src/radio-group.scss
Labels: style related

#5002 docs: [el-input] add password type
  docs/examples/input/password.vue
Labels: ready to merge

#4930 fix(locale): update translation/spelling of Khmer
  packages/locale/lang/km.ts
Labels: ready to merge
