Repository element-plus/element-plus, pull requests merged in 2021-06, with the labels that each got.

#2122 fix: checkbox checked optional cannot control state issue
  packages/checkbox/__tests__/checkbox.spec.ts
  packages/checkbox/src/useCheckbox.ts
Labels: lack of tests

#2344 fix(cascader-panel): should not re-init when props's value not change
  packages/cascader-panel/__tests__/cascader-panel.spec.ts
  packages/cascader-panel/src/index.vue
  packages/utils/util.ts
Labels: ready to merge

#2322 perf(scrollbar): scrollbar update when slot changed
  packages/scrollbar/src/index.vue
Labels: lack of tests, ready to merge

#2389 chore(deploy): use prod vue for prod bundle
  website/webpack.config.js
Labels: ready to merge
