Repository element-plus/element-plus, pull requests merged in 2021-11, with the labels that each got.

#3932 fix(components): [el-affix] fix target resize bug
  packages/components/affix/src/affix.vue
Labels: Community Contribution

#3912 feat(components): [el-tree] allow tree node to have customizable class
  docs/en-US/component/tree.md
  docs/examples/tree/custom-node-class.vue
  packages/components/tree/__tests__/tree.spec.ts
  packages/components/tree/src/tree-node.vue
  packages/components/tree/src/tree.type.ts
Labels: Community Contribution, Component: Tree

#3722 feat(components): [el-select-v2] mouse trigger scrollbar show/hide
  docs/en-US/component/select-v2.md
  packages/components/select-v2/__tests__/select.spec.ts
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/select-dropdown.vue
  packages/components/select-v2/src/select.vue
  packages/components/virtual-list/src/builders/build-list.ts
  packages/components/virtual-list/src/components/scrollbar.ts
  packages/components/virtual-list/src/props.ts
  packages/theme-chalk/src/virtual-list.scss
Labels: Community Contribution

#3979 fix(components): ensure table size affects inner selection
  packages/components/table/src/config.ts
  packages/components/table/src/store/watcher.ts
Labels: Community Contribution

#3988 feat(components): [el-message] merge the same content messages(#3836)
  docs/en-US/component/message.md
  docs/examples/message/grouping.vue
  packages/components/message/src/message-method.ts
  packages/components/message/src/message.ts
  packages/components/message/src/message.vue
  packages/theme-chalk/src/message.scss
Labels: ready to merge

#3758 fix(components): [el-cascader] empty children set leaf
  packages/components/cascader-panel/__tests__/cascader-panel.spec.ts
  packages/components/cascader-panel/src/node.ts
Labels: lack of tests

#4310 fix: side-effects
  packages/element-plus/package.json
Labels: hotfix

#4314 D2M
  CHANGELOG.en-US.md
  build/types-definitions.ts
  docs/en-US/component/image.md
  docs/en-US/component/input-number.md
  docs/en-US/component/popover.md
  docs/en-US/index.md
  docs/examples/image/image-preview.vue
  docs/index.md
  docs/package.json
  package.json
  packages/components/cascader-panel/__tests__/cascader-panel.spec.ts
  packages/components/cascader-panel/src/node.ts
  packages/components/checkbox/src/checkbox-button.vue
  packages/components/checkbox/src/checkbox.vue
  packages/components/checkbox/src/useCheckbox.ts
  packages/components/radio/index.ts
  packages/components/radio/src/radio-button.ts
  packages/components/radio/src/radio-button.vue
  packages/components/radio/src/radio-group.ts
  packages/components/radio/src/radio-group.vue
  packages/components/radio/src/radio.ts
  packages/components/radio/src/radio.vue
  packages/components/radio/src/token.ts
  packages/components/radio/src/useRadio.ts
  packages/components/rate/__tests__/rate.spec.ts
  packages/components/rate/index.ts
  packages/components/rate/src/rate.ts
  packages/components/rate/src/rate.vue
  packages/components/result/__tests__/result.spec.ts
  packages/components/result/index.ts
  packages/components/result/src/result.ts
  packages/components/result/src/result.vue
  packages/components/row/index.ts
  packages/components/row/src/row.ts
  packages/element-plus/package.json
  packages/hooks/use-form-item/index.ts
  packages/theme-chalk/src/menu.scss
  packages/theme-chalk/src/radio-group.scss
  packages/tokens/index.ts
  packages/tokens/radio.ts
  play/package.json
  pnpm-lock.yaml
  renovate.json5
Labels: 🚀 Ready for takeoff

#3664 feat(components): add custom color for button & rename css var bg-color
  docs/en-US/component/button.md
  docs/en-US/guide/theming.md
  docs/examples/button/custom.vue
  docs/vite.config.ts
  packages/components/button/src/button.ts
  packages/components/button/src/button.vue
  packages/theme-chalk/src/button.scss
  packages/theme-chalk/src/checkbox-button.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/mixins/_button.scss
  packages/theme-chalk/src/radio-button.scss
  packages/utils/color.ts
Labels: style related

#4446 docs(components): [el-upload] add upload 'file' slot
  docs/en-US/component/upload.md
Labels: ready to merge

#4476 fix(locale): improve Indonesian (Bahasa) translations and fix typo
  docs/examples/button/custom.vue
  packages/locale/lang/id.ts
Labels: ready to merge
