Repository element-plus/element-plus, pull requests merged in 2022-10, with the labels that each got.

#9979 docs(components): [table-v2] add row-expand event
  docs/en-US/component/table-v2.md
Labels: CommitMessage::Qualified

#8904 fix(components): [carousel] improper active item
  packages/components/carousel/__tests__/carousel.test.tsx
  packages/components/carousel/src/carousel.vue
  packages/hooks/index.ts
  packages/hooks/use-ordered-children/index.ts
  packages/tokens/carousel.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9965 fix(components): [input] memory leak
  packages/components/input/src/input.vue
Labels: CommitMessage::Qualified

#9989 fix(components): [tabs] arrow icon centered horizontally
  packages/theme-chalk/src/tabs.scss
Labels: CommitMessage::Qualified

#9974 feat: add vue-i18n for docs & editor
  docs/.vitepress/crowdin/en-US/pages/home.json
  docs/.vitepress/locales/en-US.yml
  docs/.vitepress/locales/es-US.yml
  docs/.vitepress/locales/zh-CN.yml
  docs/.vitepress/theme/index.ts
  docs/.vitepress/vitepress/components/globals/parallax-home.vue
  docs/.vitepress/vitepress/components/globals/vp-footer.vue
  docs/.vitepress/vitepress/components/home/home-cards.vue
  docs/.vitepress/vitepress/components/sponsors/sponsors-button.vue
  docs/.vitepress/vitepress/components/theme-editor/ep-theme-color-box.vue
  docs/.vitepress/vitepress/components/theme-editor/ep-theme-primary-colors.vue
  docs/.vitepress/vitepress/components/theme-editor/ep-theme-secondary-colors.vue
  docs/.vitepress/vitepress/composables/translation.ts
  docs/.vitepress/vitepress/modules/i18n.ts
  docs/.vitepress/vitepress/types.ts
  docs/package.json
  docs/vite.config.ts
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#9889 fix(components): [el-form] adjust the warn about label
  packages/components/form/src/utils.ts
Labels: CommitMessage::Qualified

#9888 fix(components): [select-v2] dynamic update popper
  packages/components/select-v2/src/select-dropdown.tsx
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/token.ts
Labels: CommitMessage::Qualified

#9990 fix(components): [tabs] prevent scroll tab into view after focusing it
  packages/components/tabs/src/tab-nav.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9932 fix(components): [table] wrong hover style in nested tables
  packages/components/table/src/table-body/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9995 fix(build): fix Window build locale
  internal/build/src/tasks/full-bundle.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9993 fix(components): [form-item] do not validate without `prop` property
  packages/components/form/src/form-item.vue
Labels: CommitMessage::Qualified

#9998 docs: optimize the format of some types in the document
  docs/en-US/component/calendar.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/form.md
  docs/en-US/component/icon.md
  docs/en-US/component/image.md
  docs/en-US/component/input.md
  docs/en-US/component/space.md
  docs/en-US/component/table.md
  docs/en-US/component/tooltip.md
  docs/en-US/component/transfer.md
  docs/en-US/component/upload.md
Labels: CommitMessage::Qualified

#9970 refactor(build): optimize the conversion of attributes in documents
  internal/build/package.json
  internal/build/src/tasks/helper.ts
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#10009 feat(theme-editor): can download and upload theme css var
  docs/.vitepress/vitepress/components/theme-editor/ep-theme-drawer.vue
  docs/.vitepress/vitepress/components/theme-editor/ep-theme-editor.vue
  docs/.vitepress/vitepress/components/theme-editor/ep-theme-primary-colors.vue
  docs/.vitepress/vitepress/components/theme-editor/ep-theme-primary.vue
  docs/.vitepress/vitepress/components/theme-editor/ep-theme-upload-theme.vue
  docs/.vitepress/vitepress/components/vp-app.vue
  docs/.vitepress/vitepress/store/theme.ts
  docs/.vitepress/vitepress/utils/helper/download.ts
  docs/.vitepress/vitepress/utils/helper/index.ts
  docs/.vitepress/vitepress/utils/index.ts
  docs/.vitepress/vitepress/utils/theme/helper.ts
  docs/.vitepress/vitepress/utils/theme/index.ts
  docs/.vitepress/vitepress/utils/theme/parse.ts
  docs/.vitepress/vitepress/utils/theme/store/high-contrast.ts
  docs/.vitepress/vitepress/utils/theme/types.ts
  docs/components.d.ts
  docs/package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#9994 feat(components): [select] Simplified API
  docs/en-US/component/select.md
  docs/examples/select/remote-search.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#10029 fix(components): [dropdown] button group style missing
  packages/components/dropdown/style/css.ts
  packages/components/dropdown/style/index.ts
Labels: CommitMessage::Qualified

#10004 fix(locale): update estonian translations
  packages/locale/lang/et.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9991 fix(components): the label causes the click event to trigger twice
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/checkbox/src/composables/use-checkbox-event.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10044 fix(components): [tooltip] update popper after content change
  packages/components/tooltip/src/content.vue
Labels: CommitMessage::Qualified

#10031 feat(components): [rate] add clearable attribute
  docs/en-US/component/rate.md
  docs/examples/rate/clearable.vue
  packages/components/rate/__tests__/rate.test.tsx
  packages/components/rate/src/rate.ts
  packages/components/rate/src/rate.vue
Labels: CommitMessage::Qualified

#10059 docs: update table-v2 demo
  docs/examples/table-v2/inline-editing.vue
  docs/examples/table-v2/selection.vue
Labels: CommitMessage::Qualified

#10021 feat: export type TableInstance TableColumnInstance
  packages/components/table/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10036 fix(components): [cascader] placeholder disappear when resetForm
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/src/index.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10006 fix(components): [tabs] fix typo of PaneName
  docs/en-US/component/tabs.md
  packages/components/tabs/__tests__/tabs.test.tsx
  packages/components/tabs/src/tab-nav.tsx
  packages/components/tabs/src/tabs.tsx
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9941 fix(components): [time-picker] fix popup not showing
  packages/components/focus-trap/src/focus-trap.vue
  packages/components/focus-trap/src/tokens.ts
  packages/components/focus-trap/src/utils.ts
  packages/components/popper/src/content.vue
  packages/components/select/src/useSelect.ts
  packages/components/time-picker/__tests__/time-picker.test.tsx
  packages/components/time-picker/src/common/picker.vue
Labels: CommitMessage::Qualified

#10082 docs: fix missing title
  docs/en-US/guide/commit-examples.md
  docs/en-US/guide/dev-faq.md
  docs/en-US/guide/dev-guide.md
Labels: CommitMessage::Qualified

#10083 docs: fix doc tag
  docs/en-US/guide/dev-faq.md
  docs/en-US/guide/dev-guide.md
Labels: CommitMessage::Qualified

#10093 fix(components): [input] missing native form attribute
  packages/components/input/src/input.ts
  packages/components/input/src/input.vue
Labels: CommitMessage::Qualified

#10092 perf(components): [input] remove useless calculation
  packages/components/input/src/input.vue
Labels: CommitMessage::Qualified

#10094 docs: update messsage
  docs/en-US/component/message.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10115 docs: fix a typo
  docs/en-US/component/popover.md
  docs/en-US/component/rate.md
  docs/en-US/component/select.md
  docs/en-US/component/tabs.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10117 style(docs): change DocSearch colors
  docs/.vitepress/vitepress/components/navbar/vp-search.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9931 fix(components): [date-picker] fix readonly picker can be triggered
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9959 fix(components): [table-v2] fix scroll to bottom
  packages/components/table-v2/src/composables/use-styles.ts
  packages/components/table-v2/src/use-table.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10060 fix(component): [table] row-key due to current-change trigger
  packages/components/table/src/table/style-helper.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10136 docs: fix dialog demo display error
  docs/en-US/component/dialog.md
Labels: CommitMessage::Qualified

#10071 feat(components): [message-box] add append-to option
  docs/en-US/component/message-box.md
  packages/components/message-box/__tests__/message-box.test.ts
  packages/components/message-box/src/message-box.type.ts
  packages/components/message-box/src/messageBox.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10095 fix(components): [table] fix merge cell cannot show side shadow
  packages/components/table/src/table-body/render-helper.ts
  packages/components/table/src/table-body/styles-helper.ts
  packages/components/table/src/util.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10081 fix(components): [switch] clipped text
  packages/components/switch/__tests__/switch.test.tsx
  packages/components/switch/src/switch.vue
  packages/theme-chalk/src/switch.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10119 fix(components): [cascader] modelValue update problem
  packages/components/cascader-panel/src/index.vue
  packages/components/cascader/src/index.vue
Labels: CommitMessage::Qualified

#10151 refactor(components): [backtop]
  packages/components/backtop/index.ts
  packages/components/backtop/src/backtop.ts
  packages/components/backtop/src/backtop.vue
  packages/components/backtop/src/instance.ts
  packages/components/backtop/src/use-backtop.ts
Labels: Refactor, CommitMessage::Qualified

#10152 refactor(components): [button]
  packages/components/button/index.ts
  packages/components/button/src/button-group.ts
  packages/components/button/src/button.ts
  packages/components/button/src/button.vue
  packages/components/button/src/instance.ts
  packages/components/button/src/use-button.ts
Labels: Refactor, CommitMessage::Qualified

#10155 refactor(components): [calendar]
  packages/components/calendar/index.ts
  packages/components/calendar/src/date-table.ts
  packages/components/calendar/src/date-table.vue
  packages/components/calendar/src/instance.ts
  packages/components/calendar/src/use-date-table.ts
Labels: Refactor, CommitMessage::Qualified

#10160 fix(components): [dialog] click allow focus out
  packages/components/dialog/src/dialog.vue
  packages/components/dialog/src/use-dialog.ts
Labels: CommitMessage::Qualified

#10158 refactor(components): [calendar]
  packages/components/calendar/src/calendar.ts
  packages/components/calendar/src/calendar.vue
  packages/components/calendar/src/instance.ts
  packages/components/calendar/src/use-calendar.ts
Labels: Refactor, CommitMessage::Qualified

#10133 refactor(components): [tree-v2] switch to script-setup syntax
  packages/components/tree-v2/src/composables/useCheck.ts
  packages/components/tree-v2/src/composables/useTree.ts
  packages/components/tree-v2/src/tree-node.vue
  packages/components/tree-v2/src/tree.vue
  packages/components/tree-v2/src/types.ts
  packages/components/tree-v2/src/virtual-tree.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10180 chore: rm error doc
  docs/en-US/guide/commit-examples.md
  docs/en-US/guide/dev-faq.md
  docs/en-US/guide/dev-guide.md
Labels: CommitMessage::Qualified, Needs Review

#10174 docs(components): [Autocomplete] add h1 to autocomplete docs and little tweaking
  docs/en-US/component/autocomplete.md
Labels: ready to merge, Contribution::Community, CommitMessage::Qualified

#10163 refactor(components): [calendar]
  packages/components/calendar/src/calendar.vue
  packages/components/calendar/src/use-calendar.ts
Labels: CommitMessage::Qualified

#10189 fix(components): [select-v2] empty value should be undefined
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/useSelect.ts
Labels: CommitMessage::Qualified

#10190 fix(components): [popover] abnormal style when effect is dark
  packages/components/popover/style/css.ts
  packages/components/popover/style/index.ts
  packages/theme-chalk/src/popover.scss
Labels: CommitMessage::Qualified

#10096 fix(components): [table] fixed column supported in grouped header
  docs/en-US/component/table.md
  docs/examples/table/fixed-column-and-group-header.vue
  packages/components/table/__tests__/table-column.test.ts
  packages/components/table/src/store/watcher.ts
  packages/components/table/src/table-body/styles-helper.ts
  packages/components/table/src/table-header/style.helper.ts
  packages/components/table/src/util.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10188 refactor(components): [carousel]
  packages/components/carousel/__tests__/carousel.test.tsx
  packages/components/carousel/index.ts
  packages/components/carousel/src/carousel.ts
  packages/components/carousel/src/carousel.vue
  packages/components/carousel/src/instance.ts
  packages/components/carousel/src/use-carousel.ts
Labels: Refactor, CommitMessage::Qualified

#10223 chore: remove duplicate code
  packages/hooks/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10234 Revert "fix(components): [loading] prevent click through, closes #5646"
  packages/theme-chalk/src/loading.scss
Labels: CommitMessage::Qualified

#10104 fix(components): [popper] enable the adaptive configuration
  packages/components/popper/src/utils.ts
Labels: CommitMessage::Qualified

#10219 refactor(components): [carousel-item]
  packages/components/carousel/index.ts
  packages/components/carousel/src/carousel-item.ts
  packages/components/carousel/src/carousel-item.vue
  packages/components/carousel/src/instance.ts
  packages/components/carousel/src/use-carousel-item.ts
Labels: Refactor, CommitMessage::Qualified

#10224 refactor(components): [tabs] simplify logic with hooks
  packages/components/tabs/__tests__/tabs.test.tsx
  packages/components/tabs/src/tabs.tsx
  packages/components/tabs/src/utils/pane.ts
Labels: CommitMessage::Qualified

#10218 fix(components): [select] blur trigger remote event should pass string
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#10255 fix(components): [form] throw non-validation error
  packages/components/form/src/form.vue
Labels: CommitMessage::Qualified

#10278 fix(components): [checkbox] circular reference
  packages/components/checkbox/src/composables/use-checkbox.ts
Labels: CommitMessage::Qualified

#10067 fix(components): [input-number] increase and decrease error
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10264 fix(components): [tooltip] remove deprecated api
  docs/en-US/component/tooltip.md
  packages/components/tooltip/__tests__/tooltip.test.tsx
  packages/components/tooltip/src/tooltip.ts
  packages/components/tooltip/src/tooltip.vue
Labels: CommitMessage::Qualified

#10268 ci: use env files to replace the deprecated set-output command
  .github/workflows/lint-commit-message-post.yml
  .github/workflows/lint-commit-message.yml
  .github/workflows/pr-docs-build.yml
  .github/workflows/pr-docs-deploy.yml
  .github/workflows/publish-build-product.yml
  .github/workflows/publish-docs-deploy-manual.yml
  .github/workflows/publish-docs-deploy.yml
  .github/workflows/publish-npm-nightly.yml
  .github/workflows/publish-npm.yml
  .github/workflows/publish-size-report.yml
  .github/workflows/staging-docs.yml
  .github/workflows/test-coverage.yml
  .github/workflows/test-ssr.yml
  .github/workflows/test-unit.yml
Labels: CommitMessage::Qualified

#10012 feat(components): [dropdown] add props for teleported API
  docs/en-US/component/dropdown.md
  packages/components/dropdown/__tests__/dropdown.test.ts
  packages/components/dropdown/src/dropdown.ts
  packages/components/dropdown/src/dropdown.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10214 fix(components): [cascader] consistent component height
  packages/components/cascader/src/index.vue
  packages/theme-chalk/src/cascader.scss
Labels: CommitMessage::Qualified

#10286 refactor(components): [select] use util function
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#10292 fix(components): [date-picker] monthRange mode switching month sync
  packages/components/date-picker/src/composables/use-month-range-header.ts
Labels: CommitMessage::Qualified

#9876 fix(components): [upload] add uid for file handleStart
  packages/components/upload/src/use-handlers.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10312 fix(components): [carousel] missing root ref
  packages/components/carousel/src/carousel.vue
  packages/components/carousel/src/use-carousel.ts
Labels: CommitMessage::Qualified

#10306 style(components): [slider] fix text line feed
  packages/theme-chalk/src/slider.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10325 docs: update tooltip.md
  docs/en-US/component/tooltip.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10298 fix(utils): [vnode] flattedChildren support subTree
  packages/components/tabs/__tests__/tabs.test.tsx
  packages/utils/vue/vnode.ts
Labels: CommitMessage::Qualified

#10289 refactor(components): [collapse]
  packages/components/collapse/__tests__/collapse.test.tsx
  packages/components/collapse/index.ts
  packages/components/collapse/src/collapse-item.ts
  packages/components/collapse/src/collapse-item.vue
  packages/components/collapse/src/collapse.ts
  packages/components/collapse/src/collapse.vue
  packages/components/collapse/src/instance.ts
  packages/components/collapse/src/use-collapse-item.ts
  packages/components/collapse/src/use-collapse.ts
Labels: Refactor, CommitMessage::Qualified
