Repository element-plus/element-plus, pull requests merged in 2022-04, with the labels that each got.

#6934 fix(docs): [el-divider] Document case error, String to string
  docs/en-US/component/divider.md
Labels: Project::Documentation, Contribution::Community, Contribution::First Time Contribution

#6952 fix(docs): documentation style
  docs/.vitepress/vitepress/styles/base.scss
Labels: Project::Documentation

#6843 feat(components): add tree select component
  docs/.vitepress/crowdin/en-US/pages/component.json
  docs/en-US/component/tree-select.md
  docs/examples/tree-select/basic.vue
  docs/examples/tree-select/check-strictly.vue
  docs/examples/tree-select/disabled.vue
  docs/examples/tree-select/filterable.vue
  docs/examples/tree-select/lazy.vue
  docs/examples/tree-select/multiple.vue
  docs/examples/tree-select/slots.vue
  packages/components/index.ts
  packages/components/tree-select/__tests__/tree-select.spec.ts
  packages/components/tree-select/index.ts
  packages/components/tree-select/src/select.ts
  packages/components/tree-select/src/tree-select-option.ts
  packages/components/tree-select/src/tree-select.vue
  packages/components/tree-select/src/tree.ts
  packages/components/tree-select/style/css.ts
  packages/components/tree-select/style/index.ts
  packages/element-plus/component.ts
  packages/theme-chalk/src/index.scss
  packages/theme-chalk/src/tree-select.scss
Labels: Contribution::Community

#7074 feat(docs): add PWA support for docs
  docs/.vitepress/build/rebuild-pwa.ts
  docs/.vitepress/config/head.ts
  docs/.vitepress/crowdin/en-US/component/pwa.json
  docs/.vitepress/vitepress/components/vp-app.vue
  docs/.vitepress/vitepress/components/vp-reload-prompt.vue
  docs/package.json
  docs/public/android-chrome-192x192.png
  docs/public/android-chrome-512x512.png
  docs/public/apple-touch-icon.png
  docs/public/browserconfig.xml
  docs/public/mstile-150x150.png
  docs/public/safari-pinned-tab.svg
  docs/vite.config.ts
  pnpm-lock.yaml
Labels: Project::Documentation, Contribution::Community

#7009 fix(components): [tree-select] won't import succcessfully
  packages/components/tree-select/style/css.ts
Labels: Contribution::Community

#7003 chore(style): refine repetitive code
  docs/.vitepress/vitepress/styles/base.scss
  docs/.vitepress/vitepress/styles/code.scss
  packages/components/table/src/table-column/watcher-helper.ts
  packages/theme-chalk/src/color-picker.scss
  packages/theme-chalk/src/date-picker/date-picker.scss
  packages/theme-chalk/src/date-picker/month-table.scss
  packages/theme-chalk/src/input.scss
  packages/theme-chalk/src/notification.scss
  packages/theme-chalk/src/pagination.scss
  packages/theme-chalk/src/radio.scss
  packages/theme-chalk/src/select.scss
  packages/theme-chalk/src/tabs.scss
  packages/theme-chalk/src/upload.scss
Labels: Contribution::Community

#7076 fix(components): [popper-container] recreate container when unmounted
  packages/hooks/use-popper-container/index.ts
Labels: Contribution::Community

#7064 fix: popover esc after visible invalid
  packages/components/popover/src/index.vue
Labels: Contribution::Community

#7001 fix(components): [input] improved when both `suffix` and `prefix` are displayed
  packages/components/input/__tests__/input.spec.tsx
  packages/components/input/src/input.vue
Labels: Contribution::Community

#7012 fix: [popper] with dialog use zIndex loop
  packages/components/popper/src/content.vue
Labels: Contribution::Community

#7089 fix(play): vite exclude dts deps
  play/vite.config.ts
Labels: Contribution::Community

#6992 fix(components): [table]emit "current-change" when currentRowKey changed
  packages/components/table/src/store/current.ts
Labels: Contribution::Community

#7110 perf(components): [loading] unmount instance when loading end
  packages/components/loading/__tests__/loading.spec.ts
  packages/components/loading/src/loading.ts
  packages/components/loading/src/service.ts
Labels: Contribution::Community

#7100 fix(docs): outDir error of VitePWA
  docs/.vitepress/crowdin/en-US/component/pwa.json
  docs/.vitepress/vitepress/components/vp-reload-prompt.vue
  docs/vite.config.ts
Labels: Contribution::Community

#7115 fix(components): [popper] zIndex bug
  packages/components/popper/src/content.vue
Labels: Contribution::Community

#7194 test: vitest disable ssr for tsx files
  vitest.config.ts
Labels: Contribution::Community

#7192 docs: [form] add FormRules type assertion
  docs/examples/form/validation.vue
Labels: Contribution::Community

#7214 chore: typo
  packages/theme-chalk/src/select/common.scss
Labels: Contribution::Community

#7206 fix(components): [el-table] fix SummaryMethod type(#7090)
  packages/components/table/src/table/defaults.ts
Labels: Contribution::Community

#6951 fix(components): [el-upload] icon is covered
  packages/components/upload/src/upload-list.vue
  packages/theme-chalk/src/upload.scss
Labels: Contribution::Community

#7237 test: fix console output errors and warnings
  packages/components/button/__tests__/button.test.tsx
  packages/components/image-viewer/__tests__/image-viewer.test.ts
  packages/components/notification/__tests__/notification.test.ts
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/switch/__tests__/switch.test.ts
  packages/components/virtual-list/__tests__/fixed-size-list.test.ts
Labels: Contribution::Community

#7263 test: enable clearMocks in vitest config
  packages/components/form/__tests__/form-item.test.tsx
  packages/components/form/__tests__/form.test.tsx
  packages/components/roving-focus-group/__tests__/roving-focus-group.test.ts
  packages/components/roving-focus-group/__tests__/roving-focus-item.test.ts
  packages/components/slot/__tests__/only-child.test.tsx
  packages/components/tooltip/__tests__/content.test.ts
  packages/components/tooltip/__tests__/tooltip.test.ts
  packages/components/tooltip/__tests__/trigger.test.ts
  packages/components/virtual-list/__tests__/dynamic-size-grid.test.ts
  packages/components/virtual-list/__tests__/dynamic-size-list.test.ts
  packages/components/virtual-list/__tests__/fixed-size-grid.test.ts
  packages/components/virtual-list/__tests__/fixed-size-list.test.ts
  packages/directives/__tests__/click-outside.test.ts
  packages/directives/__tests__/repeat-click.test.ts
  packages/hooks/__tests__/use-model-toggle.test.tsx
  packages/hooks/__tests__/use-prevent-global.test.ts
  vitest.config.ts
Labels: Contribution::Community

#7257 fix(docs): radio-group
  docs/en-US/component/radio.md
Labels: Contribution::Community

#7304 fix(components): [el-upload] no bubble
  packages/components/upload/src/upload-content.vue
Labels: Contribution::Community

#7309 chore(components): [table] remove redundant if else
  packages/components/table/src/table/style-helper.ts
Labels: Contribution::Community

#7227 fix(components): [calendar] fix range year bug
  packages/components/calendar/__tests__/calendar.test.tsx
  packages/components/calendar/src/calendar.vue
Labels: Contribution::Community

#6876 feat(components): [input] add input formatter
  docs/en-US/component/input.md
  docs/examples/input/formatter.vue
  packages/components/input/__tests__/input.test.tsx
  packages/components/input/src/input.ts
  packages/components/input/src/input.vue
  packages/hooks/__tests__/use-cursor.vitest.tsx
  packages/hooks/index.ts
  packages/hooks/use-cursor/index.ts
Labels: ready to merge, Contribution::Community

#7358 fix(components): [input-number] suffix icon position
  packages/theme-chalk/src/input-number.scss
Labels: Contribution::Community

#7305 fix(components): [el-select-v2] clear created options
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community

#7315 fix(components): [autocomplete] fetch-suggestions support AsyncFunction
  packages/components/autocomplete/__tests__/autocomplete.test.tsx
  packages/components/autocomplete/src/autocomplete.vue
Labels: ready to merge

#7389 feat(components): [slider] aria keyboard controls and attrs
  docs/en-US/component/slider.md
  packages/components/slider/__tests__/slider.test.ts
  packages/components/slider/src/button.vue
  packages/components/slider/src/index.vue
  packages/components/slider/src/slider.type.ts
  packages/components/slider/src/useSlide.ts
  packages/components/slider/src/useSliderButton.ts
  packages/locale/lang/en.ts
Labels: Contribution::Community, Contribution::First Time Contribution

#7330 style(components): [upload] dragger unlimited width
  packages/components/upload/src/upload-content.vue
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/upload.scss
Labels: Contribution::Community

#7377 style(components): [switch] complete switch size styles
  docs/en-US/component/switch.md
  packages/components/switch/src/switch.ts
  packages/components/switch/src/switch.vue
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/switch.scss
Labels: Contribution::Community

#7420 fix(components): [pagination] fix typo
  packages/components/pagination/src/components/sizes.vue
Labels: Contribution::Community

#7440 feat(docs): [@element-plus/icons-vue] 修复图标组件示例代码中的错误
  docs/en-US/component/icon.md
Labels: ready to merge, Contribution::Community
