Repository element-plus/element-plus, pull requests merged in 2022-02, with the labels that each got.

#5817 D2M
  CHANGELOG.en-US.md
  README.md
  docs/.vitepress/vitepress/components/globals/parallax-home.vue
  packages/components/pagination/src/pagination.ts
  packages/components/popconfirm/src/popconfirm.vue
  packages/theme-chalk/src/pagination.scss
Labels: 🚀 Ready for takeoff

#5779 fix(components): [el-dropdown] use custom attributes for dropdown items
  packages/components/dropdown/__tests__/dropdown.spec.ts
  packages/components/dropdown/src/dropdown-item-impl.vue
  packages/components/dropdown/src/dropdown-item.vue
Labels: Community Contribution

#5835 fix(components): [el-popover] fix popover placement reactive
  packages/components/popper/src/content.vue
Labels: Community Contribution

#5926 fix(docs): algolia searching
  docs/.vitepress/vitepress/components/globals/parallax-home.vue
  docs/.vitepress/vitepress/components/navbar/vp-search.vue
Labels: documentation, Algolia search

#5952 fix(components): [el-select] el-select will not show label of origin selection tags when search via remote-methods and the new options do not includes the origin selection
  packages/components/select/__tests__/select.spec.ts
  packages/components/select/src/useSelect.ts
Labels: Community Contribution

#5972 fix: namespace typo
  packages/components/dropdown/src/dropdown.vue
  packages/components/select-v2/src/select.vue
  packages/components/select/src/select.vue
Labels: regression

#5973 fix(utils): restore scrollIntoView method
  packages/components/cascader-panel/src/index.vue
  packages/components/select/src/useSelect.ts
  packages/utils/dom/scroll.ts
Labels: regression

#5977 fix(components): fix [el-select] infinite bounce for issues #5905
  packages/components/select/src/useSelect.ts
Labels: Community Contribution

#5983 fix(components): [el-select] tag default theme
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/theme-chalk/src/select.scss
Labels: regression

#6037 style(components): [el-select] collapse-tags存在时，增加左边距
  packages/components/select/src/select.vue
Labels: Community Contribution

#6017 fix(components): [el-input] missing margin between two icons (#5942)
  packages/components/input/src/input.vue
  packages/theme-chalk/src/input.scss
Labels: Community Contribution

#6186 fix: formatter func parameter type miss
  packages/components/time-picker/src/common/picker.vue
Labels: Community Contribution

#6084 fix(components): [select-v2] fix suffix default height and set different placeholder line-height for large/small
  packages/theme-chalk/src/select-v2.scss
Labels: Community Contribution

#6135 docs(components): [el-popover] add missing `effect` option
  docs/en-US/component/popover.md
Labels: Community Contribution, First time contribution

#6213 fix: deps
  .github/workflows/unit-test.yml
  package.json
  pnpm-lock.yaml
Labels: hotfix

#6223 feat(components): [el-row] enhancement for supporting space-evenly
  docs/en-US/component/layout.md
  docs/examples/layout/alignment.vue
  packages/components/row/src/row.ts
  packages/theme-chalk/src/row.scss
Labels: Community Contribution, First time contribution

#6187 fix(components):[el-date-picker] styles
  packages/theme-chalk/src/date-picker/date-table.scss
Labels: Community Contribution, style related, First time contribution

#6256 refactor(components): [button-group] switch to script-setup syntax
  docs/en-US/component/button.md
  packages/components/button/src/button-group.vue
Labels: ready to merge

#6231 fix(components): [el-dropdown-menu] adjust html tag
  packages/components/dropdown/src/dropdown-item-impl.vue
  packages/components/dropdown/src/dropdown.vue
Labels: ready to merge

#6249 fix(components): [el-time-picker] lags when open range picker
  packages/components/time-picker/src/common/picker.vue
Labels: ready to merge

#6250 chore(components): [el-input] override default border
  packages/theme-chalk/src/input.scss
Labels: ready to merge

#6346 fix(components): [el-dialog] revert focus trapping feature
  docs/en-US/component/dialog.md
  packages/components/dialog/src/dialog-content.vue
  packages/components/dialog/src/dialog.ts
  packages/components/dialog/src/dialog.vue
Labels: regression, hotfix
