Repository element-plus/element-plus, pull requests merged in 2022-05, with the labels that each got.

#7455 fix: pin pnpm version
  .github/workflows/pr-docs-build.yml
  .github/workflows/publish-build-product.yml
  .github/workflows/publish-docs-deploy-manual.yml
  .github/workflows/publish-docs-deploy.yml
  .github/workflows/publish-npm-nightly.yml
  .github/workflows/publish-npm.yml
  .github/workflows/publish-size-report.yml
  .github/workflows/staging-docs.yml
  .github/workflows/test-coverage.yml
  .github/workflows/test-ssr.yml
  .github/workflows/test-unit.yml
Labels: hotfix, Project::CI

#7416 refactor(theme-chalk): [tabs] use font-size-base
  packages/theme-chalk/src/tabs.scss
Labels: Contribution::Community

#7474 fix(components): [descriptions] style
  packages/components/descriptions/src/index.vue
Labels: ready to merge

#7054 fix(components): [select] label is not shown when value is a object
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community

#7482 chore: update publisher of volar
  .vscode/extensions.json
Labels: Contribution::Community

#7419 docs(docs): [el-badge] fix badge.md prop description error
  docs/en-US/component/badge.md
Labels: Contribution::Community

#7488 ci: respect config packageManager
  .github/workflows/pr-docs-build.yml
  .github/workflows/publish-build-product.yml
  .github/workflows/publish-docs-deploy-manual.yml
  .github/workflows/publish-docs-deploy.yml
  .github/workflows/publish-npm-nightly.yml
  .github/workflows/publish-npm.yml
  .github/workflows/publish-size-report.yml
  .github/workflows/staging-docs.yml
  .github/workflows/test-coverage.yml
  .github/workflows/test-ssr.yml
  .github/workflows/test-unit.yml
Labels: Contribution::Community

#7518 fix(components): [el-tree-v2]prop `icon` support Component. fix [#7517]
  packages/components/tree-v2/src/virtual-tree.ts
Labels: Contribution::Community, Contribution::First Time Contribution

#7540 fix(component): [el-cascader] searching placeholder does not disappear
  packages/components/cascader/src/index.vue
Labels: Contribution::Community

#7562 fix(components): circle progress 0 percent transition effect
  packages/components/progress/src/progress.vue
Labels: Contribution::Community

#7612 fix(theme-chalk): [input] add not-allowed when disabled
  packages/theme-chalk/src/input.scss
Labels: Contribution::Community

#7550 feat(components): [dialog] a11y and focus trap on dialog components
  docs/en-US/component/dialog.md
  docs/en-US/component/drawer.md
  docs/examples/dialog/customization-content.vue
  docs/examples/dialog/customization-header.vue
  docs/examples/drawer/customization-header.vue
  packages/components/dialog/__tests__/dialog.test.ts
  packages/components/dialog/src/dialog-content.vue
  packages/components/dialog/src/dialog.vue
  packages/components/dialog/src/use-dialog.ts
  packages/components/drawer/__tests__/drawer.test.ts
  packages/components/drawer/src/drawer.vue
  packages/components/dropdown/src/dropdown.vue
  packages/components/focus-trap/__tests__/focus-trap.test.ts
  packages/components/focus-trap/src/focus-trap.vue
  packages/components/focus-trap/src/tokens.ts
  packages/components/message-box/__tests__/message-box.test.ts
  packages/components/message-box/src/index.vue
  packages/locale/lang/en.ts
  packages/theme-chalk/src/dialog.scss
  packages/theme-chalk/src/drawer.scss
  packages/theme-chalk/src/message-box.scss
  packages/tokens/dialog.ts
Labels: Contribution::Community

#7621 ci: add strategy & use setup-node cache for workflows
  .github/workflows/pr-docs-build.yml
  .github/workflows/publish-build-product.yml
  .github/workflows/publish-docs-deploy-manual.yml
  .github/workflows/publish-docs-deploy.yml
  .github/workflows/publish-npm-nightly.yml
  .github/workflows/publish-npm.yml
  .github/workflows/publish-size-report.yml
  .github/workflows/staging-docs.yml
  .github/workflows/test-coverage.yml
  .github/workflows/test-ssr.yml
  .github/workflows/test-unit.yml
Labels: ready to merge

#7598 feat(components): [date-picker] work with modal focus trap; a11y controls and attributes
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/src/date-picker-com/basic-date-table.vue
  packages/components/date-picker/src/date-picker-com/basic-month-table.vue
  packages/components/date-picker/src/date-picker-com/basic-year-table.vue
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/input/src/input.ts
  packages/components/input/src/input.vue
  packages/components/popper/src/content.ts
  packages/components/popper/src/content.vue
  packages/components/popper/src/popper.ts
  packages/components/popper/src/popper.vue
  packages/components/popper/src/trigger.vue
  packages/components/time-picker/__tests__/time-picker.test.ts
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/time-picker-com/panel-time-pick.vue
  packages/components/time-picker/src/time-picker-com/panel-time-range.vue
  packages/components/time-picker/src/time-picker.ts
  packages/components/tooltip/src/content.vue
  packages/components/tooltip/src/tooltip.vue
  packages/hooks/__tests__/use-attrs.test.tsx
  packages/hooks/use-attrs/index.ts
  packages/hooks/use-delayed-toggle/index.ts
  packages/locale/lang/en.ts
  packages/theme-chalk/src/date-picker/date-picker.scss
  packages/theme-chalk/src/date-picker/date-table.scss
  packages/theme-chalk/src/date-picker/month-table.scss
  packages/theme-chalk/src/date-picker/picker-panel.scss
  packages/theme-chalk/src/date-picker/year-table.scss
  packages/theme-chalk/src/mixins/mixins.scss
  packages/tokens/popper.ts
Labels: Contribution::Community

#7609 feat(ci): enforce commit message lint on pull request
  .github/workflows/lint-commit-message.yml
  .husky/commit-msg
  commit-example.md
  commitlint.config.js
  package.json
Labels: Engineering Excellence, CommitMessage::Qualified

#7625 fix(ci): replace token for lint notification
  .github/workflows/lint-commit-message.yml
Labels: CommitMessage::Qualified

#7640 chore: update change-log
  CHANGELOG.en-US.md
Labels: CommitMessage::Qualified

#7634 chore(ci): optimizing the generated code hint file
  docs/en-US/component/config-provider.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/tree-v2.md
  internal/build/src/tasks/helper.ts
Labels: Contribution::Community

#7647 fix(ci): token limitation for commit lint
  .github/workflows/lint-commit-message.yml
Labels: CommitMessage::Qualified

#7549 feat(components): support specifying level padding in submenu
  docs/en-US/component/menu.md
  packages/components/menu/src/menu-item-group.vue
  packages/components/menu/src/menu-item.vue
  packages/components/menu/src/menu.ts
  packages/components/menu/src/sub-menu.ts
  packages/components/menu/src/types.ts
  packages/components/menu/src/use-menu-css-var.ts
  packages/components/menu/src/use-menu.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/menu.scss
Labels: Contribution::Community

#7568 docs: only cache the user preferred language pages in the PWA
  docs/.vitepress/crowdin/en-US/component/pwa.json
  docs/.vitepress/lang.js
  docs/.vitepress/sw.ts
  docs/.vitepress/vitepress/components/vp-reload-prompt.vue
  docs/.vitepress/vitepress/composables/translation.ts
  docs/tsconfig.json
  docs/vite.config.ts
Labels: Contribution::Community

#7666 chore: doc temp remove PWA to fix server error
  docs/.vitepress/config/head.ts
  docs/.vitepress/vitepress/components/sponsors/sponsors-button.vue
  docs/.vitepress/vitepress/components/vp-app.vue
  docs/vite.config.ts
Labels: CommitMessage::Qualified

#7667 chore: fix sw.js error
  docs/.vitepress/config/head.ts
  docs/.vitepress/vitepress/components/vp-app.vue
  docs/public/sw.js
Labels: CommitMessage::Qualified

#7665 fix(components): tabs focus visible
  packages/theme-chalk/src/tabs.scss
Labels: Contribution::Community

#7678 improvement(components) [divider] add separator role
  packages/components/divider/src/divider.vue
Labels: Contribution::Community

#7696 fix(components): [upload] show close tip text
  packages/components/upload/src/upload-list.vue
  packages/theme-chalk/src/upload.scss
Labels: Contribution::Community

#7536 fix(components): date-picker add keydown events(#7506)
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/time-picker/__tests__/time-picker.test.ts
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, Contribution::First Time Contribution

#7707 refactor(components): [main] switch to script-setup syntax
  packages/components/container/index.ts
  packages/components/container/src/main.vue
  packages/theme-chalk/src/main.scss
Labels: Contribution::Community

#7705 refactor(components): [timeline] switch to script-setup syntax
  packages/components/timeline/__tests__/timeline.test.ts
  packages/components/timeline/src/timeline-item.vue
Labels: Contribution::Community, Contribution::First Time Contribution

#7710 refactor(components): [collection] switch to script-setup syntax
  packages/components/collection/__tests__/collection-item.test.ts
  packages/components/collection/src/collection-item.vue
  packages/components/collection/src/collection.ts
  packages/components/collection/src/collection.vue
Labels: Contribution::Community

#7724 feat(components): [input-number] make it nullable
  docs/en-US/component/input-number.md
  packages/components/input-number/__tests__/input-number.test.ts
  packages/components/input-number/src/input-number.ts
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community

#7731 fix(ci): lint commit message error
  .github/workflows/lint-commit-message.yml
  .github/workflows/post-lint-commit-message.yml
Labels: Project::CI, Engineering Excellence

#7725 refactor(components): [container] switch to script-setup syntax
  packages/components/container/index.ts
  packages/components/container/src/aside.vue
  packages/components/container/src/container.vue
  packages/components/container/src/footer.vue
  packages/components/container/src/header.vue
Labels: CommitMessage::Qualified

#7741 test: remove deprecated done callback
  package.json
  packages/components/carousel/__tests__/carousel.test.tsx
  packages/components/form/__tests__/form.test.tsx
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/slider/__tests__/slider.test.ts
  pnpm-lock.yaml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7757 docs(type-unsafe): [radio] remove
  internal/build/src/type-unsafe.json
Labels: CommitMessage::Qualified

#7761 feat(components): [button] restore type="text"
  docs/en-US/component/button.md
  packages/components/button/src/button.ts
  packages/components/button/src/button.vue
  packages/theme-chalk/src/button.scss
Labels: CommitMessage::Qualified

#7746 refactor(components): [pagination/pager] switch to script-setup syntax
  packages/components/pagination/src/components/pager.ts
  packages/components/pagination/src/components/pager.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7750 refactor(components): [pagination/total] switch to script-setup syntax
  packages/components/pagination/src/components/total.ts
  packages/components/pagination/src/components/total.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7703 fix(theme-chalk): [DatetimePicker] change inner to wrapper & use css var
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/time-picker/src/common/picker.vue
  packages/theme-chalk/src/date-picker/picker.scss
Labels: CommitMessage::Unqualified

#7748 refactor(components): [pagination/next] switch to script-setup syntax
  packages/components/pagination/src/components/next.ts
  packages/components/pagination/src/components/next.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7779 fix(components): [time-picker] can not hide panel when click frequently
  packages/components/time-picker/src/common/picker.vue
Labels: CommitMessage::Qualified

#7790 fix(components): [popper-content] don't provide formItemContext when unnecessary
  packages/components/popper/src/content.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7799 docs: update Space / Switch doc
  docs/en-US/component/space.md
  docs/en-US/component/switch.md
Labels: CommitMessage::Qualified

#7793 fix(hooks): use-form-item circular reference
  packages/hooks/use-form-item/index.ts
Labels: CommitMessage::Qualified

#7794 refactor(components): [checkbox] switch to script-setup syntax
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/checkbox/index.ts
  packages/components/checkbox/src/checkbox-button.vue
  packages/components/checkbox/src/checkbox-group.vue
  packages/components/checkbox/src/checkbox.ts
  packages/components/checkbox/src/checkbox.vue
Labels: CommitMessage::Qualified

#7749 refactor(components): [pagination/sizes] switch to script-setup syntax
  packages/components/pagination/__tests__/pagination.test.ts
  packages/components/pagination/src/components/sizes.ts
  packages/components/pagination/src/components/sizes.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7763 fix: improve deps
  .npmrc
  docs/package.json
  internal/build-utils/package.json
  internal/build/package.json
  internal/eslint-config/package.json
  package.json
  packages/element-plus/package.json
  play/package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#7807 refactor(theme-chalk): [table] remove useless style
  packages/theme-chalk/src/table.scss
Labels: CommitMessage::Qualified

#7627 feat(components): [table] ensure minimum-size doesn't follow the content
  docs/en-US/component/table.md
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/table/defaults.ts
  packages/components/table/src/table/style-helper.ts
Labels: ready to merge, CommitMessage::Qualified

#7736 feat(components): [popper] focus trap and a11y
  packages/components/autocomplete/src/autocomplete.vue
  packages/components/cascader-panel/src/index.vue
  packages/components/cascader/src/index.vue
  packages/components/dialog/src/dialog-content.vue
  packages/components/dialog/src/dialog.vue
  packages/components/dialog/src/use-dialog.ts
  packages/components/drawer/src/drawer.vue
  packages/components/dropdown/src/dropdown.vue
  packages/components/focus-trap/__tests__/focus-trap.test.ts
  packages/components/focus-trap/src/focus-trap.vue
  packages/components/focus-trap/src/utils.ts
  packages/components/message-box/src/index.vue
  packages/components/popper/__tests__/content.test.ts
  packages/components/popper/src/content.ts
  packages/components/popper/src/content.vue
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/components/tooltip/src/content.vue
  packages/components/tooltip/src/tooltip.vue
  packages/hooks/use-escape-keydown/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7782 refactor(components): [step] switch to script-setup syntax
  internal/build/src/type-unsafe.json
  packages/components/steps/src/item.ts
  packages/components/steps/src/item.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7783 refactor(components): [steps] switch to script-setup syntax
  internal/build/src/type-unsafe.json
  packages/components/steps/__tests__/steps.test.ts
  packages/components/steps/index.ts
  packages/components/steps/src/index.vue
  packages/components/steps/src/steps.ts
  packages/components/steps/src/steps.vue
Labels: Contribution::Community, CommitMessage::Unqualified, Needs Review

#7810 fix(radio-group): restore name
  packages/components/radio/src/radio-group.vue
Labels: CommitMessage::Unqualified

#7820 fix(components): [menu] the styles link error
  packages/components/menu-item-group/style/css.ts
  packages/components/menu-item/style/css.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7817 docs: enable verbose crowdin
  .github/workflows/publish-docs-deploy-manual.yml
Labels: CommitMessage::Qualified, Needs Review

#7633 feat(dialog): expose dialogContentRef
  packages/components/dialog/src/dialog.vue
Labels: ready to merge, Contribution::Community

#7826 fix(components): [form] align label width if it exists
  packages/theme-chalk/src/form.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7854 fix: correct the deprecated note for el-button
  packages/components/button/src/button.vue
Labels: CommitMessage::Qualified

#7859 fix(components): [radio-group] unique id
  packages/components/radio/__tests__/radio.test.tsx
  packages/components/radio/src/radio-group.vue
Labels: CommitMessage::Qualified

#7860 D2M
  .github/workflows/publish-docs-deploy-manual.yml
  CHANGELOG.en-US.md
  packages/components/button/src/button.vue
  packages/components/dialog/src/dialog.vue
  packages/components/menu-item-group/style/css.ts
  packages/components/menu-item/style/css.ts
  packages/components/radio/__tests__/radio.test.tsx
  packages/components/radio/src/radio-group.vue
  packages/theme-chalk/src/form.scss
Labels: 🚀 Ready for takeoff, CommitMessage::Unqualified, Needs Review

#7855 fix(docs): [infinite-scroll] fix error when use directive
  docs/examples/infinite-scroll/disable-loading.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#7777 fix(components): [input-number] enhanced precision
  packages/components/input-number/__tests__/input-number.test.ts
  packages/components/input-number/src/input-number.vue
Labels: CommitMessage::Unqualified, 🤖️ automerge

#7814 improvement(components): [pagination] focusing tab border
  packages/theme-chalk/src/pagination.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7830 fix(components): [form-item] fix top label height
  packages/theme-chalk/src/form.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7822 fix(components): [dialog] set destory-on-close drag position abnormal
  packages/components/dialog/src/dialog-content.vue
  packages/components/dialog/src/dialog.vue
Labels: CommitMessage::Qualified

#7838 fix(components): [form] label-position props default value
  packages/components/form/__tests__/form.test.tsx
  packages/components/form/src/form.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7857 fix(components): [loading] namespace
  packages/components/loading/src/loading.ts
  packages/components/loading/src/service.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7825 refactor(components): [checkbox-group] switch to script-setup syntax
  packages/components/checkbox/src/checkbox-group.vue
Labels: CommitMessage::Qualified

#7827 refactor(components): [checkbox-button] switch to script-setup syntax
  packages/components/checkbox/src/checkbox-button.vue
Labels: CommitMessage::Qualified

#7876 refactor(build): use esbuild and tsx
  .github/renovate.json5
  docs/package.json
  internal/build/package.json
  internal/metadata/package.json
  package.json
  packages/theme-chalk/package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#7879 refactor(metadata): deduplicate commits
  internal/metadata/src/contributor.ts
Labels: CommitMessage::Qualified

#7880 fix(build): enhance type check
  .github/workflows/test-unit.yml
  internal/build/src/tasks/types-definitions.ts
  internal/build/src/type-unsafe-stricter.json
  internal/build/tsconfig.json
  internal/metadata/package.json
  package.json
  packages/theme-chalk/tsconfig.json
  play/env.d.ts
  play/tsconfig.json
  pnpm-lock.yaml
  scripts/update-version.ts
  ssr-testing/tsconfig.json
  tsconfig.base.json
  tsconfig.json
  tsconfig.node.json
  tsconfig.play.json
  tsconfig.vite-config.json
  tsconfig.vitest.json
  tsconfig.web.json
  typings/env.d.ts
Labels: CommitMessage::Qualified

#7858 fix(component): [date-picker] fix error: "Cannot read properties of null (reading 'toDate')"
  packages/components/date-picker/src/date-picker-com/basic-date-table.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#7877 chore: upgrade @vue/test-utils
  .github/renovate.json5
  docs/.vitepress/config.mts
  package.json
  packages/components/focus-trap/__tests__/focus-trap.test.ts
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#7884 refactor(components): [date-picker] extract props
  packages/components/date-picker/src/date-picker-com/basic-date-table.vue
  packages/components/date-picker/src/props/basic-date-table.ts
Labels: CommitMessage::Qualified

#7831 fix(theme-chalk): [date-picker] basic & range height size
  docs/examples/date-picker/date-range.vue
  docs/examples/date-picker/enter-date.vue
  packages/theme-chalk/src/date-picker/picker.scss
Labels: CommitMessage::Qualified

#7840 improvement(components): [tabs] card type fixed height
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/tabs.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7893 feat(components): [date-picker] extract props
  packages/components/date-picker/src/date-picker-com/basic-month-table.vue
  packages/components/date-picker/src/props/basic-date-table.ts
  packages/components/date-picker/src/props/basic-month-table.ts
  packages/components/date-picker/src/props/shared.ts
Labels: CommitMessage::Qualified

#7835 fix(components): [select-v2] status-icon position
  docs/examples/form/validation.vue
  packages/theme-chalk/src/select-v2.scss
Labels: CommitMessage::Qualified

#7894 chore(components): [date-picker] extract props
  packages/components/date-picker/src/date-picker-com/basic-year-table.vue
  packages/components/date-picker/src/props/basic-year-table.ts
  packages/components/date-picker/src/props/shared.ts
  packages/utils/arrays.ts
Labels: CommitMessage::Qualified

#7833 refactor(components): [time-select] switch to script-setup syntax
  internal/build/src/type-unsafe.json
  packages/components/time-select/__tests__/time-select.test.ts
  packages/components/time-select/src/time-select.ts
  packages/components/time-select/src/time-select.vue
  packages/components/time-select/src/utils.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7891 refactor(components): [result] switch to script-setup syntax
  packages/components/result/src/result.ts
  packages/components/result/src/result.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7886 refactor(components): [input-number] export component instance type
  packages/components/input-number/src/input-number.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#7895 chore(components): [date-picker] extract props
  package.json
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  packages/components/date-picker/src/props/panel-date-pick.ts
  packages/components/date-picker/src/props/panel-date-range.ts
  packages/components/date-picker/src/props/shared.ts
Labels: CommitMessage::Qualified

#7899 refactor(components): [date-picker] extract props
  packages/components/date-picker/src/date-picker-com/panel-month-range.vue
  packages/components/date-picker/src/props/panel-date-range.ts
  packages/components/date-picker/src/props/panel-month-range.ts
  packages/components/date-picker/src/props/shared.ts
Labels: CommitMessage::Qualified

#7914 fix(components): [button] style compatible issue with :not
  packages/theme-chalk/src/button.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#7911 refactor(components): useNamespace for date-picker
  packages/components/date-picker/src/date-picker-com/basic-date-table.vue
  packages/components/date-picker/src/date-picker-com/basic-month-table.vue
  packages/components/date-picker/src/date-picker-com/basic-year-table.vue
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  packages/components/date-picker/src/date-picker-com/panel-month-range.vue
Labels: CommitMessage::Qualified

#7915 fix(components): [focus-trap] respect focusout null relatedTarget
  packages/components/focus-trap/src/focus-trap.vue
Labels: CommitMessage::Qualified

#7908 refactor(components): [time-picker] setup migration
  packages/components/date-picker/src/date-picker-com/panel-month-range.vue
  packages/components/date-picker/src/props/panel-month-range.ts
  packages/components/date-picker/src/props/shared.ts
Labels: CommitMessage::Qualified

#7923 refactor(components): [time-picker] date-picker
  packages/components/date-picker/src/date-picker-com/basic-cell-render.ts
  packages/components/date-picker/src/date-picker.tsx
  packages/components/date-picker/src/date-picker.type.ts
  packages/components/date-picker/src/props/date-picker.ts
  packages/components/date-picker/src/utils.ts
  packages/components/time-picker/src/common/constant.ts
  packages/tokens/date-picker.ts
  packages/tokens/index.ts
Labels: CommitMessage::Qualified

#7924 refactor(components): [date-picker] basic cell
  packages/components/date-picker/src/date-picker-com/basic-cell-render.ts
  packages/components/date-picker/src/date-picker-com/basic-cell-render.tsx
  packages/components/date-picker/src/props/basic-cell.ts
Labels: CommitMessage::Qualified

#7931 refactor(components): [date-picker] date-range
  packages/components/date-picker/__tests__/date-time-picker.test.ts
  packages/components/date-picker/src/composables/use-range-picker.ts
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  packages/components/date-picker/src/date-picker-com/panel-month-range.vue
  packages/components/date-picker/src/date-picker.tsx
  packages/components/date-picker/src/props/shared.ts
  packages/components/date-picker/src/utils.ts
  packages/tokens/date-picker.ts
Labels: CommitMessage::Qualified

#7910 fix(theme-chalk): [dark-model] vue-cli tree sharking
  packages/element-plus/package.json
Labels: CommitMessage::Qualified

#7934 chore: update design resource text
  docs/.vitepress/crowdin/en-US/pages/resource.json
  docs/.vitepress/vitepress/components/globals/resource.vue
Labels: CommitMessage::Qualified, Needs Review

#7639 build(build): extract constants
  internal/build-constants/src/pkg.ts
  internal/build/src/tasks/full-bundle.ts
  internal/build/src/utils/pkg.ts
Labels: Contribution::Community, CommitMessage::Unqualified

#7890 refactor(components): [input-number] use JSX in Unit test
  packages/components/input-number/__tests__/input-number.test.tsx
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#7936 refactor: add useMonthRangeHeader hook
  packages/components/date-picker/src/composables/use-month-range-header.ts
  packages/components/date-picker/src/date-picker-com/panel-month-range.vue
Labels: CommitMessage::Qualified, Needs Review

#7944 docs(components): [form] delete unused variables
  docs/examples/form/accessibility.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7949 refactor(components): [rate] props and emits validation
  packages/components/rate/src/rate.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7950 refactor(components): [tooltip] transition use useNamespace
  packages/components/tooltip/src/tooltip.ts
Labels: CommitMessage::Qualified

#7953 refactor(components): [collapse-transition] switch to script-setup syntax
  packages/components/collapse-transition/src/collapse-transition.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7888 refactor(components): [input-number] switch to script-setup syntax
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#7795 refactor(components): [progress] switch to script-setup syntax
  packages/components/progress/__tests__/progress.test.tsx
  packages/components/progress/src/progress.ts
  packages/components/progress/src/progress.vue
Labels: CommitMessage::Unqualified

#7951 chore(build): remove `input-number` from type-unsafe.json
  internal/build/src/type-unsafe.json
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7698 fix(components): [date-picker] Make shortcuts reactive
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified

#7945 refactor(components): [affix] props and emits validation
  packages/components/affix/src/affix.ts
Labels: Contribution::Community, CommitMessage::Unqualified, Needs Review

#7957 chore(build): remove upload in type unsafe
  internal/build/src/type-unsafe-stricter.json
Labels: CommitMessage::Qualified

#7959 refactor(components): improve code
  internal/build/src/type-unsafe-stricter.json
  packages/components/alert/src/alert.vue
  packages/components/autocomplete/src/autocomplete.ts
  packages/components/autocomplete/src/autocomplete.vue
  packages/components/avatar/src/avatar.ts
  packages/components/backtop/src/backtop.ts
  packages/components/backtop/src/backtop.vue
  packages/components/breadcrumb/src/breadcrumb-item.vue
  packages/components/calendar/src/calendar.ts
  packages/components/calendar/src/calendar.vue
  packages/components/calendar/src/date-table.vue
  packages/components/card/src/card.ts
  packages/components/check-tag/src/check-tag.ts
  packages/components/check-tag/src/check-tag.vue
Labels: CommitMessage::Unqualified

#7905 fix(components): [table] the scrollbar not change when table width change
  packages/components/table/src/table/style-helper.ts
Labels: CommitMessage::Qualified

#7948 refactor(components): [date-picker] month range
  packages/components/date-picker/src/date-picker-com/panel-month-range.vue
Labels: CommitMessage::Qualified

#7956 fix(components): [tree] remove form item context
  packages/components/tree-v2/src/tree.vue
  packages/components/tree/src/tree.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7941 fix(hooks): type error
  internal/build/src/type-unsafe-stricter.json
  packages/element-plus/make-installer.ts
  packages/hooks/use-floating/index.ts
  packages/hooks/use-forward-ref/index.ts
  packages/hooks/use-global-config/index.ts
  packages/hooks/use-prop/index.ts
Labels: CommitMessage::Qualified

#7973 refactor(components): [alert] use JSX in Unit test
  packages/components/alert/__tests__/alert.test.tsx
Labels: CommitMessage::Qualified

#7972 refactor(components): [badge] use JSX in Unit test
  packages/components/badge/__tests__/badge.test.ts
  packages/components/badge/__tests__/badge.test.tsx
Labels: CommitMessage::Qualified

#7967 refactor(components): [popconfirm] export instance type
  packages/components/popconfirm/src/popconfirm.ts
Labels: CommitMessage::Qualified

#7969 refactor(components): [popconfirm] use JSX in Unit test
  packages/components/popconfirm/__tests__/popconfirm.test.tsx
Labels: CommitMessage::Qualified

#7935 chore(locale): update fr.ts
  packages/locale/lang/fr.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#7960 docs: fix markdown block
  docs/en-US/guide/namespace.md
  docs/en-US/guide/theming.md
Labels: CommitMessage::Qualified

#7940 fix(components): [collection] type error
  internal/build/src/type-unsafe-stricter.json
  packages/components/collection/src/collection.ts
Labels: CommitMessage::Qualified

#7979 refactor(components): [config-provider] export component instance type
  packages/components/config-provider/src/config-provider.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7980 refactor(components): [config-provider] use JSX in Unit test
  packages/components/config-provider/__tests__/config-provider.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7938 fix(components): [image-viewer] typescript error
  internal/build/src/type-unsafe-stricter.json
  packages/components/image-viewer/src/image-viewer.ts
  packages/components/image-viewer/src/image-viewer.vue
Labels: CommitMessage::Qualified

#7982 refactor(components): [config-provider] refactor tokens
  packages/tokens/config-provider.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7971 refactor(components): [col] switch to script-setup syntax
  packages/components/col/__tests__/layout.test.tsx
  packages/components/col/index.ts
  packages/components/col/src/col.ts
  packages/components/col/src/col.tsx
  packages/components/col/src/col.vue
Labels: CommitMessage::Qualified, Needs Review

#7946 feat(components): [dropdown] a11y
  docs/en-US/component/dropdown.md
  packages/components/dropdown/__tests__/dropdown.test.ts
  packages/components/dropdown/src/dropdown-item-impl.vue
  packages/components/dropdown/src/dropdown-item.vue
  packages/components/dropdown/src/dropdown-menu.vue
  packages/components/dropdown/src/dropdown.ts
  packages/components/dropdown/src/dropdown.vue
  packages/components/dropdown/src/tokens.ts
  packages/components/popper/src/content.ts
  packages/components/popper/src/content.vue
  packages/components/popper/src/trigger.vue
  packages/components/tooltip/src/content.vue
  packages/components/tooltip/src/tooltip.ts
  packages/components/tooltip/src/tooltip.vue
  packages/components/tooltip/src/trigger.vue
  packages/hooks/use-model-toggle/index.ts
  packages/locale/lang/en.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7939 fix(utils): type error
  internal/build/src/type-unsafe-stricter.json
  packages/utils/dom/style.ts
Labels: CommitMessage::Qualified

#7947 refactor(components): [steps] validate values ​​and export values
  packages/components/steps/index.ts
  packages/components/steps/src/item.ts
  packages/components/steps/src/item.vue
  packages/components/steps/src/steps.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7965 docs: theming
  docs/en-US/guide/theming.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#7977 fix(components): [button] :not overrides the disabled style
  packages/theme-chalk/src/button.scss
Labels: CommitMessage::Qualified

#7999 chore: update resource track
  docs/.vitepress/vitepress/components/globals/resource.vue
Labels: CommitMessage::Qualified, Needs Review

#7987 refactor(components): [scrollbar] use JSX in Unit test
  internal/build/src/type-unsafe.json
  packages/components/scrollbar/__tests__/scrollbar.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7670 chore(docs): use `defineConfig` for vite
  docs/en-US/guide/quickstart.md
Labels: Contribution::Community, 1st contribution

#7986 refactor(components): [scrollbar] switch to script-setup syntax
  packages/components/scrollbar/src/bar.ts
  packages/components/scrollbar/src/bar.vue
  packages/components/scrollbar/src/scrollbar.ts
  packages/components/scrollbar/src/scrollbar.vue
  packages/components/scrollbar/src/thumb.ts
  packages/components/scrollbar/src/thumb.vue
  packages/components/scrollbar/src/util.ts
  packages/tokens/scrollbar.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8004 fix(build): remove type safe (not stricter)
  internal/build/src/index.ts
  internal/build/src/tasks/types-definitions.ts
  internal/build/src/type-unsafe.json
Labels: hotfix, CommitMessage::Qualified

#8002 docs(components): [time-picker] event parameters
  docs/en-US/component/date-picker.md
  docs/en-US/component/time-picker.md
Labels: Project::Documentation, CommitMessage::Qualified

#8001 fix(components): [picker] Click to focus fires emit
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8011 refactor(components): [date-picker] panel-date-pick
  packages/components/date-picker/src/composables/use-range-picker.ts
  packages/components/date-picker/src/composables/use-shortcut.ts
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/date-picker/src/props/basic-date-table.ts
  packages/components/date-picker/src/props/shared.ts
Labels: CommitMessage::Qualified
