Repository element-plus/element-plus, pull requests merged in 2022-03, with the labels that each got.

#6321 refactor(components): [page-header] switch to script-setup syntax
  packages/components/page-header/src/page-header.ts
  packages/components/page-header/src/page-header.vue
Labels: ready to merge

#6361 fix(components): [button] space is not added
  packages/components/button/__tests__/button.spec.tsx
  packages/components/button/src/button.vue
Labels: lack of tests

#6380 fix(components): work around #6378
  packages/components/tooltip/src/content.vue
Labels: Community Contribution

#6379 feat(components): [el-messagebox] add context for message box
  docs/en-US/component/message-box.md
  packages/components/message-box/__tests__/message-box.spec.ts
  packages/components/message-box/index.ts
  packages/components/message-box/src/message-box.type.ts
  packages/components/message-box/src/messageBox.ts
Labels: enhancement, Component: MessageBox

#6416 fix(theme-chalk): namespace
  packages/theme-chalk/src/cascader-panel.scss
  packages/theme-chalk/src/date-picker/date-table.scss
  packages/theme-chalk/src/menu.scss
  packages/theme-chalk/src/option-item.scss
  packages/theme-chalk/src/page-header.scss
  packages/theme-chalk/src/pagination.scss
  packages/theme-chalk/src/table.scss
Labels: Community Contribution

#6414 fix(components):[el-collapse-transition] styles
  packages/theme-chalk/src/common/transition.scss
Labels: Community Contribution, style related

#6412 feat(components): [el-dialog] add border-radius css variable
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/dialog.scss
Labels: style related, Component: Dialog

#6400 fix: [el-table] selection cell when double clicking expand icon
  packages/theme-chalk/src/table.scss
Labels: style related

#6474 fix(components):[el-select] selected value as placeholder typing issue
  packages/components/select/src/useSelect.ts
Labels: Community Contribution

#6496 docs(theme-chalk): update the modification guide introduced by webpack on demand
  docs/en-US/guide/theming.md
Labels: Community Contribution, First time contribution

#6473 fix(components): el-select-allow-dynamically-update-options
  packages/components/select/__tests__/select.spec.ts
  packages/components/select/src/option.vue
  packages/components/select/src/useSelect.ts
Labels: Community Contribution

#6492 fix(components): [upload] fileList prop should sync uploadFiles
  build/type-safe.json
  packages/components/upload/src/upload-content.ts
  packages/components/upload/src/upload.ts
  packages/components/upload/src/use-handlers.ts
Labels: Community Contribution, First time contribution

#6456 fix(components): [rate] fix disbaledVoidIcon typo
  packages/components/rate/src/rate.ts
  packages/components/rate/src/rate.vue
Labels: Contribution::Community, Contribution::First Time Contribution

#6506 fix(components): [el-input] pass input-style props to input-wrapper
  packages/components/input/src/input.vue
Labels: Contribution::Community, Contribution::First Time Contribution

#6342 fix(components): [autocomplete] fix shaking at first open
  packages/components/autocomplete/src/autocomplete.vue
Labels: Contribution::Community

#6505 fix(components): [el-upload] jitter when remove file in the list
  packages/components/upload/src/upload-list.vue
  packages/theme-chalk/src/common/transition.scss
  packages/theme-chalk/src/upload.scss
Labels: ready to merge

#6547 ci(project): compressed actions for PRs
  .github/workflows/size-report.yml
  package.json
Labels: Project::CI

#6550 fix(ci): remove clean script
  .github/workflows/size-report.yml
  package.json
Labels: Project::CI

#6553 fix(build): move eslint config to internal
  internal/eslint-config/index.js
  internal/eslint-config/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: hotfix

#6558 test(ci): add build product checking for prs
  .github/workflows/build-product.yml
  .gitignore
  package.json
  scripts/build-table.ts
  scripts/file-check.sh
Labels: Project::CI

#6564 ci(build): add threshold to build product workflow
  .github/workflows/build-product.yml
  .github/workflows/welcome.yml
  scripts/build-table.ts
Labels: Project::CI

#6560 D2M
  .github/workflows/build-product.yml
  .github/workflows/size-report.yml
  .github/workflows/welcome.yml
  .gitignore
  CHANGELOG.en-US.md
  build/type-safe.json
  docs/en-US/component/message.md
  docs/en-US/component/upload.md
  docs/examples/link/with-icon.vue
  docs/examples/upload/photo-wall.vue
  internal/eslint-config/index.js
  internal/eslint-config/package.json
  package.json
  packages/components/avatar/__tests__/avatar.spec.tsx
  packages/components/button/__tests__/button.spec.tsx
  packages/components/cascader-panel/src/index.vue
  packages/components/link/__tests__/link.vitest.ts
  packages/components/link/src/link.vue
  packages/components/message/__tests__/message-manager.spec.tsx
  packages/components/message/src/message-method.ts
  packages/components/message/src/message.ts
  packages/components/page-header/__tests__/page-header.spec.ts
  packages/components/select-v2/__tests__/select.spec.ts
  packages/components/steps/__tests__/steps.spec.ts
  packages/components/switch/__tests__/switch.spec.ts
  packages/components/timeline/__tests__/timeline.spec.ts
  packages/components/upload/src/upload-list.vue
  packages/components/upload/src/upload.vue
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/link.scss
  packages/theme-chalk/src/mixins/utils.scss
  packages/theme-chalk/src/upload.scss
  play/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  scripts/build-table.ts
  scripts/file-check.sh
Labels: 🚀 Ready for takeoff

#6563 fix(component): [el-tabs] the initial pane should only render for once
  packages/components/tabs/__tests__/tabs.spec.ts
  packages/components/tabs/src/tab-pane.vue
Labels: Contribution::Community

#6556 refactor(components): [divider] switch to script-setup
  packages/components/divider/src/divider.vue
Labels: Contribution::Community

#6576 docs: [layout] fix a mistyped value
  docs/en-US/component/layout.md
Labels: Contribution::Community

#6590 fix(components): [dialog] remove footer when not existed
  packages/components/dialog/src/dialog.vue
Labels: Component::Dialog

#6395 refactor(components): [skeleton] switch to script-setup syntax
  docs/en-US/component/skeleton.md
  packages/components/skeleton/__tests__/skeleton-item.vitest.ts
  packages/components/skeleton/__tests__/skeleton.vitest.ts
  packages/components/skeleton/index.ts
  packages/components/skeleton/src/image-placeholder.vue
  packages/components/skeleton/src/skeleton-item.vue
  packages/components/skeleton/src/skeleton.vue
Labels: Contribution::Community

#6586 fix: Upload component remove status label box shadow
  packages/theme-chalk/src/upload.scss
Labels: Quality::Style Related

#6610 fix(components): [el-form] Form not emitting validation result
  packages/components/form/__tests__/form.spec.tsx
  packages/components/form/src/form-item.vue
  packages/components/form/src/form.vue
  packages/components/form/src/types.ts
  packages/components/input/src/input.vue
  packages/tokens/form.ts
Labels: Quality::Regression

#6619 fix(theme-chalk): [cascader/checkbox] fix unexpected fill color is appiled
  packages/theme-chalk/src/common/var.scss
Labels: Contribution::Community

#6641 fix: form item instance was not destroyed
  packages/components/form/__tests__/form.spec.tsx
  packages/components/form/mocks/mock-data.tsx
  packages/components/form/src/form-item.vue
  packages/components/form/src/form.vue
  packages/components/form/src/types.ts
  packages/tokens/form.ts
  tsconfig.jest.json
Labels: Quality::Regression

#6636 fix(components): [result] rename slot's name from 'subTitle' to 'sub-title'
  docs/en-US/component/result.md
  packages/components/result/__tests__/result.spec.ts
  packages/components/result/src/result.vue
Labels: Contribution::Community

#6649 fix(docs): [README] fix wrong link in README.md
  README.md
Labels: Contribution::Community, Contribution::First Time Contribution

#6647 test(ssr): add ssr testing cases
  commitlint.config.js
  packages/components/affix/ssr/basic.vue
  packages/components/alert/ssr/basic.vue
  packages/components/autocomplete/ssr/basic.vue
  packages/components/avatar/ssr/basic.vue
  ssr-testing/demo.spec.puppeteer.tsx
  ssr-testing/tsconfig.json
Labels: Eco::SSR

#6655 chore(ssr): moveout ssr testing files
  ssr-testing/cases/affix.vue
  ssr-testing/cases/alert.vue
  ssr-testing/cases/autocomplete.vue
  ssr-testing/cases/avatar.vue
  ssr-testing/demo.spec.puppeteer.tsx
Labels: Eco::SSR

#6615 fix(components): [table] not scroll empty block when scrolling table
  packages/components/table/src/table/style-helper.ts
  packages/theme-chalk/src/table.scss
Labels: Contribution::Community

#6669 fix(components): [el-form] validation with callbacks throws
  packages/components/form/__tests__/form-item.spec.tsx
  packages/components/form/__tests__/form.spec.tsx
  packages/components/form/index.ts
  packages/components/form/mocks/mock-data.tsx
  packages/components/form/src/form-item.ts
  packages/components/form/src/form-item.vue
  packages/components/form/src/form.ts
  packages/components/form/src/form.vue
Labels: Quality::Regression

#6675 fix(components): [el-dialog] DoneFn parameter should be optional
  packages/components/dialog/src/dialog.ts
  packages/components/dialog/src/use-dialog.ts
Labels: Contribution::Community

#6662 fix: input-number in step-strictly onChange bug
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community

#6678 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/vitepress/components/globals/parallax-home.vue
  docs/.vitepress/vitepress/components/navbar/vp-menu-link.vue
  docs/.vitepress/vitepress/components/navbar/vp-search.vue
  docs/.vitepress/vitepress/components/vp-app.vue
  docs/.vitepress/vitepress/components/vp-demo.vue
  docs/.vitepress/vitepress/components/vp-nav.vue
  docs/.vitepress/vitepress/components/vp-not-found.vue
  docs/.vitepress/vitepress/composables/active-bar.ts
  docs/.vitepress/vitepress/composables/back-top.ts
  docs/.vitepress/vitepress/composables/toggle-widgets.ts
  docs/.vitepress/vitepress/composables/translation.ts
  docs/index.md
  packages/components/dialog/src/dialog.ts
  packages/components/dialog/src/use-dialog.ts
  packages/components/form/__tests__/form-item.spec.tsx
  packages/components/form/__tests__/form.spec.tsx
  packages/components/form/index.ts
  packages/components/form/mocks/mock-data.tsx
  packages/components/form/src/form-item.ts
  packages/components/form/src/form-item.vue
  packages/components/form/src/form.ts
  packages/components/form/src/form.vue
  packages/components/input-number/src/input-number.vue
  packages/components/menu/src/menu.ts
  packages/components/table/src/table/style-helper.ts
  packages/theme-chalk/src/table.scss
  packages/utils/types.ts
Labels: 🚀 Ready for takeoff

#6684 fix(components): [menu-item] fix unvisible tooltip while menu is on the right side
  packages/components/menu/src/menu-item.vue
Labels: Contribution::Community

#6710 feat(ci): enable ssr testing in CI
  .github/workflows/sst-testing.yml
Labels: Eco::SSR, Project::CI, Eco::Nuxt Related

#6714 fix(docs): fix "Invalid date" display error in docs site
  docs/.vitepress/config.ts
Labels: Contribution::Community

#6691 fix(components): [el-input] keydown event validator warning
  packages/components/input/src/input.ts
Labels: Contribution::Community

#6688 fix(style): [el-checkbox-group] vertical align in form-item
  packages/theme-chalk/src/checkbox-group.scss
Labels: Contribution::Community

#6695 feat(components): [autocomplete] fetchSuggestions supports Promise
  packages/components/autocomplete/__tests__/autocomplete.spec.tsx
  packages/components/autocomplete/src/autocomplete.ts
  packages/components/autocomplete/src/autocomplete.vue
Labels: Contribution::Community

#6720 fix(components): [dropdown] ignore show/hide timeouts for click trigger
  packages/components/dropdown/__tests__/dropdown.spec.ts
  packages/components/dropdown/src/dropdown.vue
Labels: Contribution::Community

#6735 fix(components): [time-picker] cancel button not work correctly
  packages/components/time-picker/__tests__/time-picker.spec.ts
  packages/components/time-picker/src/time-picker-com/panel-time-range.vue
Labels: Contribution::Community

#6753 docs: fix link error
  docs/en-US/guide/transitions.md
Labels: Contribution::Community

#6768 fix(components): [input] textarea border does not display on ios
  packages/theme-chalk/src/input.scss
Labels: Contribution::Community

#6774 fix(components): [message-box] textarea can not use multiline text
  packages/components/message-box/src/index.vue
Labels: Contribution::Community

#6523 refactor(components): [time-picker] use useNamespace
  packages/components/date-picker/__tests__/date-time-picker.spec.ts
  packages/components/time-picker/__tests__/time-picker.spec.ts
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
  packages/components/time-picker/src/time-picker-com/panel-time-pick.vue
  packages/components/time-picker/src/time-picker-com/panel-time-range.vue
  packages/theme-chalk/src/date-picker/time-spinner.scss
Labels: ready to merge

#6794 feat(components): [el-config-provider] experimental feature toggle
  docs/en-US/component/config-provider.md
  packages/components/config-provider/__tests__/config-provider.spec.ts
  packages/components/config-provider/src/config-provider.ts
  packages/tokens/experimental-features.ts
  packages/tokens/index.ts
Labels: Project::Enhancement, :test_tube: Experimental

#6769 fix(components): [el-select] reset selectedLabel when toggle multiple
  packages/components/select/__tests__/select.spec.ts
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community

#6812 feat(project): adapt floating ui
  package.json
  packages/element-plus/package.json
  pnpm-lock.yaml
Labels: Project::Dependencies

#6683 perf(components): [input-number] components review
  packages/components/input-number/src/input-number.ts
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community

#6815 fix: Cascader Unexpected display 'No Data'
  packages/components/cascader-panel/src/index.vue
Labels: Contribution::Community

#6851 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/config/head.ts
  docs/.vitepress/crowdin/en-US/pages/resource.json
  docs/.vitepress/vitepress/components/globals/resource.vue
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
  packages/components/tooltip-v2/index.ts
  packages/components/tooltip-v2/src/arrow.ts
  packages/components/tooltip-v2/src/arrow.vue
  packages/components/tooltip-v2/src/common.ts
  packages/components/tooltip-v2/src/content.ts
  packages/components/tooltip-v2/src/content.vue
  packages/components/tooltip-v2/src/forward-ref.tsx
  packages/components/tooltip-v2/src/root.ts
  packages/components/tooltip-v2/src/root.vue
  packages/components/tooltip-v2/src/tooltip.ts
  packages/components/tooltip-v2/src/tooltip.vue
  packages/components/tooltip-v2/src/trigger.ts
  packages/components/tooltip-v2/src/trigger.vue
  packages/tokens/index.ts
  packages/tokens/tooltip-v2.ts
  packages/utils/types.ts
  packages/utils/vue/refs.ts
  packages/utils/vue/vnode.ts
Labels: 🚀 Ready for takeoff

#6874 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/vitepress/components/navbar/vp-translation.vue
  docs/.vitepress/vitepress/styles/code.scss
  docs/examples/backtop/basic.vue
  docs/examples/backtop/custom.vue
  docs/examples/border/shadow.vue
  packages/components/backtop/src/backtop.vue
  packages/components/tabs/__tests__/tabs.spec.ts
  packages/components/tabs/src/tabs.ts
  packages/theme-chalk/src/backtop.scss
  packages/theme-chalk/src/button.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/drawer.scss
  packages/theme-chalk/src/dropdown.scss
  packages/theme-chalk/src/loading.scss
  packages/theme-chalk/src/overlay.scss
  packages/theme-chalk/src/tabs.scss
  packages/theme-chalk/src/upload.scss
  packages/theme-chalk/src/var.scss
Labels: 🚀 Ready for takeoff

#6846 fix(components): [el-input] change icon when toggling password visibility
  packages/components/input/__tests__/input.spec.tsx
  packages/components/input/src/input.vue
Labels: Contribution::Community

#6468 refactor(components): [tabs] switch to script-setup syntax
  internal/build/src/type-safe.json
  packages/components/tabs/index.ts
  packages/components/tabs/src/tab-bar.ts
  packages/components/tabs/src/tab-bar.vue
  packages/components/tabs/src/tab-nav.tsx
  packages/components/tabs/src/tab-pane.ts
  packages/components/tabs/src/tab-pane.vue
  packages/components/tabs/src/tabs.tsx
  typings/env.d.ts
Labels: Contribution::Community

#6878 locale: Added Azerbaijani language
  docs/en-US/guide/i18n.md
  packages/locale/index.ts
  packages/locale/lang/az.ts
Labels: Contribution::Community, locale related, Contribution::First Time Contribution, Locale::new

#6704 refactor(components): [image, image-viewer] refactor
  docs/en-US/component/image.md
  packages/components/image-viewer/src/image-viewer.ts
  packages/components/image-viewer/src/image-viewer.vue
  packages/components/image/__tests__/image.spec.tsx
  packages/components/image/src/image.vue
Labels: ready to merge

#6836 fix: [ElMessage] grouping mode default type
  packages/components/message/src/message-method.ts
Labels: Contribution::Community

#6885 fix(components): [upload] fix onChange double trigger
  packages/components/upload/src/upload-content.vue
Labels: Contribution::Community

#6694 fix(components): [el-table] use table width as empty block width
  packages/components/table/src/table/style-helper.ts
Labels: Contribution::Community

#6923 docs: [el-table] add self-close issue
  docs/en-US/component/table.md
Labels: Project::Documentation

#6756 fix(components): [input] clearable when prepend or append exists
  packages/theme-chalk/src/input.scss
Labels: Contribution::Community, Quality::Style Related, Component: Input
