Repository element-plus/element-plus, pull requests merged in 2022-01, with the labels that each got.

#5199 chore(project): avoid workflow running in fork
  .github/workflows/issue-inactive.yml
  .github/workflows/issue-statistics.yml
  .github/workflows/publish-npm-nightly.yml
Labels: CI

#5145 fix(components): [el-form] fix form style
  docs/examples/form/size-control.vue
  packages/components/form/src/form.vue
  packages/components/input/src/input.vue
  packages/theme-chalk/src/form.scss
Labels: ready to merge

#5139 fix(components): [el-transfer] improve styles
  docs/examples/transfer/basic.vue
  packages/components/transfer/src/transfer-panel.vue
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/transfer.scss
Labels: ready to merge

#5064 feat(components): [el-cascader] cascader panel loading placeholder
  packages/components/cascader-panel/src/index.vue
  packages/components/cascader-panel/src/menu.vue
  packages/components/cascader-panel/src/types.ts
Labels: Community Contribution

#5229 ci: add jest coverage workflow
  .github/workflows/unit-test.yml
Labels: CI

#5187 feat(components): make `value-format="x"` emit number value
  packages/components/date-picker/__tests__/date-picker.spec.ts
  packages/components/time-picker/src/common/picker.vue
Labels: enhancement, Community Contribution

#5253 D2M
  .github/workflows/unit-test.yml
  CHANGELOG.en-US.md
  packages/components/autocomplete/src/index.vue
  packages/components/color-picker/src/index.vue
  packages/components/date-picker/__tests__/date-picker.spec.ts
  packages/components/dropdown/src/dropdown.vue
  packages/components/menu/src/menu-item.vue
  packages/components/popconfirm/src/popconfirm.vue
  packages/components/popover/src/index.vue
  packages/components/select-v2/src/select.vue
  packages/components/select/src/select.vue
  packages/components/slider/src/button.vue
  packages/components/table/src/filter-panel.vue
  packages/components/time-picker/src/common/picker.vue
Labels: 🚀 Ready for takeoff

#5255 chore(project): add code of conduct and commit example
  CONTRIBUTING.md
  LOCAL_DEV.md
  README.md
  commit-example.md
Labels: documentation

#5228 test(components): [el-config-provider] use useFakeTimers
  packages/components/config-provider/__tests__/config-provider.spec.ts
Labels: bug

#5257 fix: dropdowm item can not click
  packages/components/dropdown/src/dropdown-item.vue
Labels: regression

#5223 feat(components): [el-tabs] add active-bar width transition (#5206)
  packages/theme-chalk/src/tabs.scss
Labels: Community Contribution

#5298 docs(components): [el-tooltip] enhance el-tooltip documentations
  docs/en-US/component/tooltip.md
  docs/examples/tooltip/basic.vue
Labels: documentation

#5320 D2M
  .env
  .github/workflows/cypress.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/manual-deploy-docs.yml
  .github/workflows/staging-preview.yml
  .github/workflows/unit-test.yml
  .gitignore
  CHANGELOG.en-US.md
  CONTRIBUTING.md
  LOCAL_DEV.md
  README.md
  commit-example.md
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/components/button.spec.ts
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  docs/.vitepress/vitepress/components/navbar/vp-menu-link.vue
  docs/en-US/component/dropdown.md
  docs/en-US/component/tooltip.md
  docs/examples/dropdown/triggering-element.vue
  docs/examples/tooltip/basic.vue
  docs/package.json
  jest.config.js
  package.json
  packages/components/calendar/__tests__/calendar.spec.ts
  packages/components/calendar/src/calendar.vue
  packages/components/config-provider/__tests__/config-provider.spec.ts
  packages/components/date-picker/__tests__/date-picker.spec.ts
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/dropdown/__tests__/dropdown.spec.ts
  packages/components/dropdown/src/dropdown-item-impl.vue
  packages/components/dropdown/src/dropdown-item.vue
  packages/components/dropdown/src/dropdown-menu.vue
  packages/components/popconfirm/__test__/popconfirm.spec.ts
  packages/components/popover/__tests__/directive.spec.ts
  packages/components/popper/__tests__/trigger.spec.ts
  packages/components/popper/src/content.vue
  packages/components/popper/src/trigger.vue
  packages/components/time-picker/__tests__/time-picker.spec.ts
  packages/components/time-picker/src/common/picker.vue
  packages/components/tooltip/__tests__/content.spec.ts
  packages/components/tooltip/__tests__/tooltip.spec.ts
  packages/components/tooltip/__tests__/trigger.spec.ts
  packages/components/tooltip/index.ts
  packages/components/tooltip/src/content.vue
  packages/components/tooltip/src/tokens.ts
  packages/components/tooltip/src/tooltip.ts
  packages/components/tooltip/src/tooltip.vue
  packages/components/tooltip/src/trigger.vue
  packages/components/tree/src/model/useDragNode.ts
  packages/components/tree/src/tree-node.vue
  packages/theme-chalk/src/dropdown.scss
  packages/theme-chalk/src/tabs.scss
  packages/theme-chalk/src/tree.scss
  pnpm-lock.yaml
  tsconfig.json
Labels: 🚀 Ready for takeoff

#5336 D2M
  .github/workflows/coverage.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/manual-deploy-docs.yml
  CHANGELOG.en-US.md
  docs/en-US/component/time-picker.md
  docs/en-US/component/tooltip.md
  docs/examples/time-picker/basic-range.vue
  docs/examples/time-picker/basic.vue
  package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: 🚀 Ready for takeoff

#5490 chore: upgrade dependencies
  docs/package.json
  package.json
  packages/element-plus/package.json
  pnpm-lock.yaml
Labels: dependencies

#4182 fix(components): [el-cascader] checkStrict and lazyLoad need click twice
  packages/components/cascader-panel/__tests__/cascader-panel.spec.ts
  packages/components/cascader-panel/src/node.vue
Labels: needs discussion

#5559 D2M
  CHANGELOG.en-US.md
  build/modules.ts
  package.json
  packages/components/image-viewer/src/image-viewer.vue
  packages/components/image/src/image.vue
  packages/components/pagination/src/components/jumper.vue
  pnpm-lock.yaml
Labels: 🚀 Ready for takeoff

#5564 docs: [el-progress] fix default slot description
  docs/en-US/component/progress.md
Labels: Community Contribution

#5603 D2M
  CHANGELOG.en-US.md
  build/full-bundle.ts
  build/modules.ts
  docs/en-US/component/progress.md
  docs/en-US/guide/i18n.md
  docs/en-US/guide/quickstart.md
  docs/vite.config.ts
  package.json
  packages/components/autocomplete/src/index.vue
  packages/components/backtop/src/backtop.vue
  packages/components/checkbox/src/checkbox-button.vue
  packages/components/checkbox/src/checkbox-group.vue
  packages/components/checkbox/src/checkbox.vue
  packages/components/dialog/src/dialog.ts
  packages/utils/validators.ts
  play/package.json
  play/tsconfig.json
  play/vite.config.ts
  pnpm-lock.yaml
Labels: 🚀 Ready for takeoff

#5630 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/config.ts
  docs/.vitepress/crowdin/en-US/pages/home.json
  docs/.vitepress/vitepress/components/globals/parallax-home.vue
  docs/.vitepress/vitepress/styles/content/hero-content.scss
  docs/en-US/component/tooltip.md
  docs/examples/tooltip/basic.vue
  docs/examples/tooltip/controlled.vue
  docs/examples/tooltip/html-content.vue
  docs/vite.config.ts
  package.json
  packages/components/carousel/src/item.vue
  packages/components/carousel/src/main.vue
  packages/components/checkbox/__tests__/checkbox.spec.ts
  packages/components/checkbox/src/useCheckbox.ts
  packages/components/message-box/src/index.vue
  packages/components/popover/src/popover.ts
  packages/components/transfer/__tests__/transfer.spec.ts
  packages/components/transfer/src/index.vue
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/popper.scss
  packages/theme-chalk/src/tooltip.scss
  play/vite.config.ts
  pnpm-lock.yaml
Labels: 🚀 Ready for takeoff

#5597 fix(theme-chalk): el-breadcrumb__item style
  docs/en-US/component/breadcrumb.md
  packages/theme-chalk/src/breadcrumb.scss
Labels: Community Contribution

#5698 fix: upgrade vueuse
  package.json
  packages/element-plus/package.json
  pnpm-lock.yaml
Labels: hotfix

#5739 refactor(components): [skeleton,skeleton-item] use useNamespace
  packages/components/skeleton/src/skeleton-item.vue
  packages/components/skeleton/src/skeleton.vue
Labels: ready to merge
