Repository element-plus/element-plus, pull requests merged in 2022-08, with the labels that each got.

#9141 D2M
  CHANGELOG.en-US.md
  README.md
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/vitepress/components/navbar/vp-theme-toggler.vue
  docs/en-US/component/input.md
  docs/en-US/component/notification.md
  packages/components/carousel/src/carousel.vue
  packages/components/color-picker/src/draggable.ts
  packages/components/menu/src/menu.ts
  packages/components/notification/src/notify.ts
  packages/components/space/src/space.ts
  packages/components/switch/__tests__/switch.test.tsx
  packages/components/table/src/table/style-helper.ts
  packages/components/time-select/__tests__/time-select.test.tsx
  packages/hooks/__tests__/use-namespace.test.tsx
  packages/hooks/use-namespace/index.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/menu.scss
  packages/theme-chalk/src/message.scss
Labels: 🚀 Ready for takeoff, CommitMessage::Unqualified, Needs Review

#9143 style(message): fix message
  packages/theme-chalk/src/message.scss
Labels: CommitMessage::Qualified

#9153 docs(docs): remove chinese button
  docs/examples/button/basic.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9156 feat(components): [tree-v2] expose several helpful methods
  docs/en-US/component/tree-v2.md
  packages/components/tree-v2/src/composables/useTree.ts
  packages/components/tree-v2/src/tree.vue
  packages/components/tree/src/model/tree-store.ts
Labels: CommitMessage::Qualified

#9050 refactor(components): [tabs] use JSX in Unit test
  packages/components/tabs/__tests__/tabs.test.ts
  packages/components/tabs/__tests__/tabs.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8592 fix(components): [table-body] keep row data reactive
  packages/components/table/src/table-body/events-helper.ts
  packages/components/table/src/table-body/index.ts
  packages/components/table/src/table-body/render-helper.ts
  packages/components/table/src/util.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9103 feat(components): [popconfirm] add width prop
  docs/en-US/component/popconfirm.md
  packages/components/popconfirm/src/popconfirm.ts
  packages/components/popconfirm/src/popconfirm.vue
  packages/theme-chalk/src/popover.scss
Labels: CommitMessage::Qualified

#9179 fix(components): [table] fix selection style
  packages/theme-chalk/src/table.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8822 fix(locale): update zh-tw translation
  packages/locale/lang/zh-tw.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8860 fix(components): [select] injected form context may be undefined
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8861 fix(components): [cascader] injected form context may be undefined
  packages/components/cascader/src/index.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8866 fix(components): [time-picker] injected form context may be undefined
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8865 fix(components): [checkbox] injected form context may be undefined
  packages/components/checkbox/src/checkbox-group.vue
  packages/components/checkbox/src/checkbox.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9106 refactor(components): [notification] switch to script-setup syntax
  packages/components/notification/src/notification.ts
  packages/components/notification/src/notification.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8618 refactor(utils): drop `resize-event`
  packages/utils/dom/index.ts
  packages/utils/dom/resize-event.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8842 fix(element-plus): dts entry
  packages/element-plus/package.json
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8850 fix: [timer-pick] automatically skip disabled items
  packages/components/time-picker/__tests__/time-picker.test.ts
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8893 docs(components): fix url of @element-plus/icon-vue to unpkg
  docs/en-US/component/icon.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9226 fix(components): [table] the empty slot height error
  packages/components/table/src/table/style-helper.ts
Labels: CommitMessage::Qualified

#9151 refactor(hooks): [use-lockscreen] change from padding to width
  packages/hooks/use-lockscreen/index.ts
Labels: CommitMessage::Qualified

#9286 docs: icons categories and update icon-vue package
  docs/.vitepress/vitepress/components/globals/icons-categories.json
  docs/.vitepress/vitepress/components/globals/icons.vue
  docs/package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#9293 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/vitepress/components/globals/icons-categories.json
  docs/.vitepress/vitepress/components/globals/icons.vue
  docs/en-US/component/icon.md
  docs/en-US/component/popconfirm.md
  docs/en-US/component/tree-v2.md
  docs/examples/button/basic.vue
  docs/package.json
  packages/components/cascader/src/index.vue
  packages/components/checkbox/src/checkbox-group.vue
  packages/components/checkbox/src/checkbox.ts
  packages/components/color-picker/src/index.vue
  packages/components/notification/src/notification.ts
  packages/components/notification/src/notification.vue
  packages/components/popconfirm/src/popconfirm.ts
  packages/components/popconfirm/src/popconfirm.vue
  packages/components/select/src/useSelect.ts
  packages/components/table/src/table-body/events-helper.ts
  packages/components/table/src/table-body/index.ts
  packages/components/table/src/table-body/render-helper.ts
  packages/components/table/src/table/style-helper.ts
  packages/components/table/src/util.ts
  packages/components/tabs/__tests__/tabs.test.ts
  packages/components/tabs/__tests__/tabs.test.tsx
  packages/components/time-picker/__tests__/time-picker.test.ts
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
  packages/components/tree-v2/src/composables/useTree.ts
  packages/components/tree-v2/src/tree.vue
  packages/components/tree/src/model/tree-store.ts
  packages/element-plus/package.json
  packages/hooks/use-lockscreen/index.ts
  packages/locale/lang/zh-tw.ts
  packages/theme-chalk/src/message.scss
  packages/theme-chalk/src/popover.scss
  packages/theme-chalk/src/table.scss
  packages/utils/dom/index.ts
  packages/utils/dom/resize-event.ts
  pnpm-lock.yaml
Labels: 🚀 Ready for takeoff, CommitMessage::Unqualified, Needs Review

#9299 fix(components): use namespace
  packages/components/color-picker/src/index.vue
  packages/components/popover/src/popover.vue
  packages/components/slot/src/only-child.tsx
  packages/components/table/src/table-body/render-helper.ts
  packages/hooks/use-id/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9278 style(docs): change DocSearch z-index
  docs/.vitepress/vitepress/components/navbar/vp-search.vue
Labels: CommitMessage::Qualified

#9319 docs(components): [menu] typo
  docs/examples/menu/vertical.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Unqualified, Needs Review

#9331 docs: update link component docs
  docs/en-US/component/link.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9338 refactor(components): [table] fix typo
  packages/components/table/src/table/style-helper.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9209 fix(components): [dialog] should emit open event after nextTick
  packages/components/dialog/src/use-dialog.ts
  packages/components/drawer/__tests__/drawer.test.ts
Labels: CommitMessage::Qualified

#9320 perf(components): [virtual-list] RTLOffsetType compare
  packages/components/virtual-list/src/builders/build-list.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9305 fix(theme-chalk): [select] text overflow shows ellipsis
  packages/theme-chalk/src/select/common.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9240 docs: fix typo
  docs/en-US/component/table.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9355 docs(components): [menu] fix typo
  docs/examples/menu/vertical.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9362 fix(components): [tree] calc parentNode state after doCreateChildren
  packages/components/tree/src/model/node.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9173 docs(components): [switch] perfect befor-change type
  docs/en-US/component/switch.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9171 fix(components): [switch] fix type error
  packages/components/switch/__tests__/switch.test.tsx
  packages/components/switch/src/switch.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9287 fix(components): [select] option value is object
  packages/components/select/src/useOption.ts
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#9190 fix(components): [el-cascader] placeholder disappeared after clear value
  packages/components/cascader/src/index.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9372 feat(components): [pagination] btns icon can be customized VueComponent
  docs/en-US/component/pagination.md
  packages/components/pagination/__tests__/pagination.test.tsx
  packages/components/pagination/src/components/next.ts
  packages/components/pagination/src/components/next.vue
  packages/components/pagination/src/components/prev.ts
  packages/components/pagination/src/components/prev.vue
  packages/components/pagination/src/pagination.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9342 fix(components): [menu] resize event infinite invoke
  packages/components/menu/__tests__/menu.test.ts
  packages/components/menu/src/menu.ts
Labels: Contribution::Community, CommitMessage::Unqualified, Needs Review

#9390 D2M
  .github/workflows/pr-docs-deploy.yml
  .github/workflows/pr-docs-start.yml
  .github/workflows/publish-build-product.yml
  CHANGELOG.en-US.md
  docs/.vitepress/vitepress/components/navbar/vp-search.vue
  docs/en-US/component/link.md
  docs/en-US/component/pagination.md
  docs/en-US/component/switch.md
  docs/en-US/component/table.md
  docs/examples/menu/vertical.vue
  docs/package.json
  internal/eslint-config/package.json
  package.json
  packages/components/cascader/src/index.vue
  packages/components/color-picker/src/index.vue
  packages/components/dialog/src/use-dialog.ts
  packages/components/drawer/__tests__/drawer.test.ts
  packages/components/menu/__tests__/menu.test.ts
  packages/components/menu/src/menu.ts
  packages/components/pagination/__tests__/pagination.test.tsx
  packages/components/pagination/src/components/next.ts
  packages/components/pagination/src/components/next.vue
  packages/components/pagination/src/components/prev.ts
  packages/components/pagination/src/components/prev.vue
  packages/components/pagination/src/pagination.ts
  packages/components/popover/src/popover.vue
  packages/components/select/src/useOption.ts
  packages/components/select/src/useSelect.ts
  packages/components/slider/src/composables/use-marks.ts
  packages/components/slot/src/only-child.tsx
  packages/components/switch/__tests__/switch.test.tsx
  packages/components/switch/src/switch.vue
  packages/components/table/src/table-body/render-helper.ts
  packages/components/table/src/table/style-helper.ts
  packages/components/tree/src/model/node.ts
  packages/components/virtual-list/src/builders/build-list.ts
  packages/element-plus/package.json
  packages/hooks/use-id/index.ts
  packages/theme-chalk/src/input.scss
  packages/theme-chalk/src/select/common.scss
  pnpm-lock.yaml
Labels: 🚀 Ready for takeoff, CommitMessage::Unqualified, Needs Review

#9388 docs: add missing slot `header` of Card
  docs/en-US/component/card.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9134 refactor(components): [time-picker] use JSX in Unit test
  packages/components/time-picker/__tests__/time-picker.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9356 style(docs): change the example mask and overlay z-index
  docs/examples/loading/basic.vue
  docs/examples/loading/customization.vue
  docs/examples/table-v2/overlay.vue
Labels: CommitMessage::Qualified

#9386 docs(components): [date-picker] update example
  docs/examples/datetime-picker/date-and-time-formats.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9399 docs: hosting nav zindex
  docs/.vitepress/vitepress/styles/css-vars.scss
Labels: CommitMessage::Qualified

#8399 fix(components): [message-box] fix Wrong type checking
  packages/components/message-box/src/message-box.type.ts
  packages/components/message-box/src/messageBox.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9412 feat(components): [tree-v2] add `setExpendKeys` method
  docs/en-US/component/tree-v2.md
  packages/components/tree-v2/src/composables/useTree.ts
  packages/components/tree-v2/src/tree.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9413 fix(components): [tree-v-2] `setExpandedKeys` instead of `setExpendKeys`
  docs/en-US/component/tree-v2.md
  packages/components/tree-v2/src/composables/useTree.ts
  packages/components/tree-v2/src/tree.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9152 docs: adjust with use-lockscreen
  docs/.vitepress/vitepress/styles/base.scss
  docs/.vitepress/vitepress/styles/navbar.scss
  docs/.vitepress/vitepress/styles/sidebar.scss
Labels: CommitMessage::Qualified

#9408 fix(components): [el-menu] childNodes is null
  packages/components/menu/src/menu.ts
Labels: CommitMessage::Qualified

#9415 fix(components): [cascader] when multiple is true keyboard delete error
  packages/components/cascader/src/index.vue
Labels: CommitMessage::Qualified

#8967 fix(components): [table] repetition labelCellName
  packages/components/table/src/table-header/index.ts
Labels: need reproduction, Contribution::Community, CommitMessage::Qualified, Needs Review

#9378 fix(components): [message] the value of exposeProxy may be null
  packages/components/message/src/instance.ts
  packages/components/message/src/method.ts
Labels: CommitMessage::Qualified

#9417 fix(components): [notification] closeAll invalid
  packages/components/notification/src/notify.ts
Labels: CommitMessage::Qualified

#9343 fix(theme-chalk): [input] scss variables transpile
  packages/theme-chalk/src/input.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Unqualified, Needs Review

#9445 fix(components): [opover] effect dark mode title color
  docs/en-US/component/popover.md
  packages/theme-chalk/src/popover.scss
Labels: CommitMessage::Qualified

#9433 feat(components): [form] add require-asterisk-position prop
  docs/en-US/component/form.md
  packages/components/form/src/form-item.vue
  packages/components/form/src/form.ts
  packages/theme-chalk/src/form.scss
Labels: CommitMessage::Qualified

#9380 fix(components): [space] complete the prop of space
  docs/en-US/component/space.md
  packages/components/space/src/space.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9084 refactor(components): [table] style of the footer-wrapper
  packages/components/table/src/table/style-helper.ts
  packages/theme-chalk/src/table.scss
Labels: CommitMessage::Qualified

#9149 fix(components): [table] bodyWrapper resized calculate scrollbarStyle
  packages/components/table/src/table/style-helper.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9271 fix(components): [checkbox] label is object in group
  packages/components/checkbox/src/checkbox.ts
Labels: CommitMessage::Qualified

#8800 fix(theme-chalk): [select] set `vertical-align`
  packages/theme-chalk/src/select.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9444 feat(components): [menu] add `expand-close-icon`、`expand-open-icon`、`collapse-close-icon`、`collapse-open-icon` props
  docs/en-US/component/menu.md
  packages/components/menu/src/sub-menu.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/menu.scss
Labels: CommitMessage::Unqualified

#9396 style(components): [rate] in safari has outline
  packages/theme-chalk/src/rate.scss
Labels: CommitMessage::Qualified

#9389 feat(components): [image-viewer] add `setActiveItem` method
  docs/en-US/component/image.md
  packages/components/image-viewer/__tests__/image-viewer.test.ts
  packages/components/image-viewer/src/image-viewer.ts
  packages/components/image-viewer/src/image-viewer.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9477 refactor(components): [tree] fix typo
  packages/components/tree/__tests__/tree.test.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9471 refactor(components): [popper]redfine the prop role type
  packages/components/popper/src/popper.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9352 fix(theme-chalk): fix datepicker sidebar of panel is covered by footer
  packages/theme-chalk/src/date-picker/date-range-picker.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9465 fix(components): [date-picker] use lodash flatten
  packages/components/date-picker/src/date-picker-com/basic-date-table.vue
Labels: CommitMessage::Qualified

#9145 fix(components): [upload] onExceed is not called
  packages/components/upload/src/upload.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9448 fix(components): [upload] `onPreview` not work when `picture` list type
  packages/components/upload/src/upload-list.vue
  packages/theme-chalk/src/upload.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9242 fix(components): [time-select] inherit disabled from form
  packages/components/time-select/src/time-select.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9159 fix(components): [affix] expose `updateRoot`
  packages/components/affix/src/affix.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8337 refactor(components): [popover] use JSX in Unit test
  packages/components/popover/__tests__/directive.test.tsx
  packages/components/popover/__tests__/popover.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9502 refactor(utils): refactor `iconPropType`
  docs/en-US/component/autocomplete.md
  docs/en-US/component/breadcrumb.md
  docs/en-US/component/button.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/dropdown.md
  docs/en-US/component/input.md
  docs/en-US/component/link.md
  docs/en-US/component/menu.md
  docs/en-US/component/message-box.md
  docs/en-US/component/notification.md
  docs/en-US/component/page-header.md
  docs/en-US/component/pagination.md
  docs/en-US/component/popconfirm.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/steps.md
  docs/en-US/component/switch.md
  docs/en-US/component/time-picker.md
  docs/en-US/component/time-select.md
  docs/en-US/component/timeline.md
  docs/en-US/component/tree-v2.md
  docs/en-US/component/tree.md
  packages/components/breadcrumb/src/breadcrumb.ts
  packages/components/button/src/button.ts
  packages/components/dialog/src/dialog-content.ts
  packages/components/input/src/input.ts
  packages/components/link/src/link.ts
  packages/components/menu/src/sub-menu.ts
  packages/components/message/src/message.ts
  packages/components/popconfirm/src/popconfirm.ts
  packages/components/switch/src/switch.ts
  packages/components/timeline/src/timeline-item.ts
  packages/components/tree/src/tree.type.ts
  packages/components/tree/src/tree.vue
  packages/utils/vue/icon.ts
Labels: CommitMessage::Qualified

#9504 docs: uniform the attribute name
  docs/en-US/component/image.md
  docs/en-US/component/input.md
Labels: CommitMessage::Qualified

#9498 fix(components): [notification] custom icon not work
  packages/components/notification/__tests__/notification.test.ts
  packages/components/notification/src/notification.ts
  packages/components/notification/src/notification.vue
Labels: CommitMessage::Qualified

#9506 fix(utils): fix `iconPropType`
  docs/en-US/component/breadcrumb.md
  docs/en-US/component/button.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/dropdown.md
  docs/en-US/component/input.md
  docs/en-US/component/link.md
  docs/en-US/component/menu.md
  docs/en-US/component/message-box.md
  docs/en-US/component/notification.md
  docs/en-US/component/page-header.md
  docs/en-US/component/pagination.md
  docs/en-US/component/popconfirm.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/steps.md
  docs/en-US/component/switch.md
  docs/en-US/component/time-picker.md
  docs/en-US/component/time-select.md
  docs/en-US/component/timeline.md
  docs/en-US/component/tree-v2.md
  docs/en-US/component/tree.md
  packages/components/menu/src/sub-menu.ts
  packages/components/tree/src/tree.type.ts
  packages/utils/vue/icon.ts
Labels: CommitMessage::Qualified

#9503 fix(components): [cascader] collapse-tags-tooltip drop first item
  packages/components/cascader/__tests__/cascader.test.ts
  packages/components/cascader/src/index.vue
Labels: CommitMessage::Qualified

#8947 feat(components): [dialog] add align center prop
  docs/en-US/component/dialog.md
  docs/examples/dialog/align-center.vue
  packages/components/dialog/src/dialog-content.ts
  packages/components/dialog/src/dialog-content.vue
  packages/components/dialog/src/dialog.vue
  packages/components/dialog/src/use-dialog.ts
  packages/theme-chalk/src/dialog.scss
Labels: Contribution::Community, Documentation needed, 1st contribution, CommitMessage::Qualified, Needs Review

#9510 fix(components): [table-v2] fix style import
  packages/components/table-v2/style/css.ts
  packages/components/table-v2/style/index.ts
Labels: CommitMessage::Qualified

#9515 refactor(utils): refine `iconPropType`
  docs/en-US/component/breadcrumb.md
  docs/en-US/component/button.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/dropdown.md
  docs/en-US/component/input.md
  docs/en-US/component/link.md
  docs/en-US/component/menu.md
  docs/en-US/component/message-box.md
  docs/en-US/component/notification.md
  docs/en-US/component/page-header.md
  docs/en-US/component/pagination.md
  docs/en-US/component/popconfirm.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/steps.md
  docs/en-US/component/switch.md
  docs/en-US/component/time-picker.md
  docs/en-US/component/time-select.md
  docs/en-US/component/timeline.md
  docs/en-US/component/tree-v2.md
  docs/en-US/component/tree.md
  packages/components/tree/src/tree.type.ts
  packages/utils/vue/icon.ts
Labels: CommitMessage::Qualified

#9455 fix(components): [dialog] bind `$attrs`
  docs/.vitepress/vitepress/components/dev/DeprecatedTag.vue
  docs/components.d.ts
  docs/en-US/component/dialog.md
  packages/components/dialog/src/dialog.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9530 refactor(components): [notification] use JSX in Unit test
  packages/components/notification/__tests__/notification.test.tsx
  packages/components/notification/__tests__/notify.test.tsx
Labels: CommitMessage::Qualified

#9537 fix(components): [date-picker] only `td` tags with content can be select
  packages/components/date-picker/src/date-picker-com/basic-year-table.vue
Labels: CommitMessage::Qualified

#4640 fix(components): [table] fix sort-change event behavior
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/store/index.ts
Labels: Component::Table, CommitMessage::Unqualified

#9360 refactor(icon): reduce getter access.
  packages/components/icon/src/icon.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Unqualified, Needs Review

#9549 chore: update doc
  README.md
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/vitepress/components/sponsors/right-logo-small-list.vue
  docs/components.d.ts
  docs/public/images/bit-l.png
Labels: CommitMessage::Qualified

#9496 style(components): [select, select-v2] adjust style
  packages/theme-chalk/src/select/common.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9553 fix(components): [slider] trigger change event correctly
  packages/components/slider/src/composables/use-slider-button.ts
Labels: CommitMessage::Qualified

#9545 feat(components): [input-number] add new prop `readonly`
  docs/en-US/component/input-number.md
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.ts
  packages/components/input-number/src/input-number.vue
Labels: CommitMessage::Qualified

#9547 fix(components): [select-v2] emit('blur') does not carry parameter
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9529 fix(components): [table] `el-table__placeholder` class disappear
  packages/components/table/src/table-column/render-helper.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9528 docs(components): [date-time-picker] perfect type
  docs/en-US/component/datetime-picker.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9531 fix(components): [table-v2] cell slots invalid
  packages/components/table-v2/__tests__/table-v2.test.tsx
  packages/components/table-v2/src/components/header.tsx
  packages/components/table-v2/src/table-v2.tsx
Labels: CommitMessage::Qualified

#9475 fix(components): [select] update finished calculating optionsInDropdown
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9397 Table using load to click to expand will trigger multiple load callbacks
  packages/components/table/src/config.ts
Labels: need reproduction, Contribution::Community, 1st contribution, CommitMessage::Unqualified, Needs Review

#9501 fix(components): [input] formatted values are out of sync
  packages/components/input/src/input.vue
Labels: CommitMessage::Qualified

#9466 fix(directives): [repeat-click] Interval time is too short for single clicks
  packages/directives/__tests__/repeat-click.test.tsx
  packages/directives/repeat-click/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9222 fix(components): [tabs] nav offset error when use both number and string
  packages/components/tabs/__tests__/tabs.test.tsx
  packages/components/tabs/src/tab-bar.vue
  packages/components/tabs/src/tab-nav.tsx
Labels: CommitMessage::Qualified

#9220 fix(components): [select] support dynamic value for option
  packages/components/select/src/option.vue
  packages/components/select/src/useOption.ts
Labels: CommitMessage::Qualified

#8393 perf(components): [table] export table defaults
  packages/components/table/index.ts
Labels: CommitMessage::Qualified

#7017 fix: [el-date-picker] fix DatePicker render error
  docs/.vitepress/vitepress/composables/lang.ts
Labels: Contribution::Community, CommitMessage::Qualified

#9548 docs: [skeleton-item] remove duplicate type variant
  docs/en-US/component/skeleton.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Unqualified, Needs Review

#7166 fix(components): [form] reset field validate invalid
  packages/components/form/src/form-item.vue
Labels: CommitMessage::Qualified

#7743 fix(components): [el-form] clear validate after reset fields
  packages/components/form/src/form-item.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7175 docs: [select-v2] add demo of how to use value-key
  docs/en-US/component/select-v2.md
  docs/examples/select-v2/use-valueKey.vue
Labels: CommitMessage::Unqualified

#8234 docs(components): [select] v-model add array type
  docs/en-US/component/select.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9566 fix(components): [el-menu] compatible `menu.value` is null
  packages/components/menu/src/menu.ts
Labels: CommitMessage::Qualified

#9564 fix(components): [page-header] fix styles introduced on demand
  packages/components/page-header/style/css.ts
  packages/components/page-header/style/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9563 fix(components): [pagination] add validate-event
  packages/components/pagination/src/components/jumper.vue
  packages/components/pagination/src/components/sizes.vue
Labels: CommitMessage::Qualified

#8330 Fixing a typo in the documentation
  docs/en-US/component/layout.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Unqualified, Needs Review

#8228 fix(components): [tree-v2] should updated when pass dynamic `defaultCheckedKeys`
  packages/components/tree-v2/src/composables/useCheck.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8973 fix(components): [tree-select] `expand-on-click-node` not work
  packages/components/tree-select/__tests__/tree-select.test.ts
  packages/components/tree-select/src/tree.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review
