Repository element-plus/element-plus, pull requests merged in 2022-09, with the labels that each got.

#9512 fix(components): [table] toggleRowExpansion typing
  packages/components/table/src/store/watcher.ts
  packages/components/table/src/table/utils-helper.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8881 fix(components): [tree] fix setCurrentKey setCurrentNode emit
  packages/components/tree/src/tree.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9578 fix(components): [select] fix typo
  packages/components/select/__tests__/select.test.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9402 fix(components): [date-picker] Component ElInput validateEvent pass true
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9520 refactor(components): [date-time-picker] use JSX in Unit test
  packages/components/date-picker/__tests__/date-time-picker.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9572 feat(components): [time-picker] add open and close handlers
  docs/en-US/component/time-picker.md
  packages/components/time-picker/__tests__/time-picker.test.tsx
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/time-picker.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9585 fix(components): [table-v2] header-cell slots invalid
  packages/components/table-v2/__tests__/table-v2.test.tsx
  packages/components/table-v2/src/table-v2.tsx
Labels: CommitMessage::Qualified

#9298 perf(hooks): [use-namespace] simplify code
  packages/hooks/use-namespace/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9577 feat(components): el-tree set currentNodekey field to responsive. close #9576
  packages/components/tree/src/tree.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9265 feat(components): CascaderProps expandTrigger enum to type
  packages/components/cascader-panel/src/config.ts
  packages/components/cascader-panel/src/index.vue
  packages/components/cascader-panel/src/node.ts
  packages/components/cascader-panel/src/types.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9591 fix(components): [tree-v2] 修复tree-v2组件开启accordion模式后展开不了的问题
  packages/components/tree-v2/src/composables/useTree.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Unqualified, Needs Review

#9601 fix(components): [date-picker] lodash path
  packages/components/date-picker/src/date-picker-com/basic-date-table.vue
Labels: CommitMessage::Qualified

#9605 chore: update doc footer design
  docs/.vitepress/crowdin/en-US/pages/home.json
  docs/.vitepress/vitepress/components/globals/parallax-home.vue
  docs/.vitepress/vitepress/components/globals/vp-footer.vue
  docs/.vitepress/vitepress/components/vp-content.vue
  docs/.vitepress/vitepress/styles/content/doc-content.scss
  docs/components.d.ts
Labels: CommitMessage::Qualified, Needs Review

#9609 fix(components): [select-v2] support empty string value
  packages/components/select-v2/src/useSelect.ts
Labels: CommitMessage::Qualified

#9614 docs: [tree] fix node-click parameter description
  docs/en-US/component/tree.md
Labels: CommitMessage::Qualified

#9613 fix(components): [tree-node-content] slot inherit styles
  packages/components/tree/src/tree-node-content.vue
Labels: CommitMessage::Qualified

#9610 fix(hooks): [useLockscreen] close shake
  packages/hooks/__tests__/use-lockscreen.test.tsx
  packages/hooks/use-lockscreen/index.ts
Labels: CommitMessage::Qualified

#9611 fix(components): [button] type text deprecated
  packages/components/button/src/button.vue
Labels: CommitMessage::Qualified

#9607 fix(components): [upload] always display upload trigger
  packages/components/upload/src/upload.vue
Labels: CommitMessage::Qualified

#9590 refactor(components): [calendar] rename slot dateCell to date-cell
  docs/en-US/component/calendar.md
  docs/examples/calendar/customize.vue
  docs/examples/calendar/header.vue
  packages/components/calendar/__tests__/calendar.test.tsx
  packages/components/calendar/src/calendar.vue
  packages/components/calendar/src/date-table.vue
Labels: CommitMessage::Qualified

#9569 fix(components): [popover] fix ElPopover is not defined component dts
  global.d.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8793 docs(components): fix popper-options to provide working example
  docs/en-US/component/dropdown.md
  docs/en-US/component/popover.md
  docs/en-US/component/tooltip.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review, conflict pending

#9617 chore: fix footer dark
  docs/.vitepress/vitepress/components/globals/vp-footer.vue
Labels: CommitMessage::Qualified, Needs Review

#9620 docs(components): adjust the type of focus event
  docs/en-US/component/cascader.md
  docs/en-US/component/input-number.md
  docs/en-US/component/input.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/time-select.md
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#9618 fix(components): [form-item] don't add required rule repeatedly
  packages/components/form/src/form-item.vue
Labels: CommitMessage::Qualified

#9584 fix(components): [popper] default flip feature
  packages/components/popper/src/content.ts
  packages/components/popper/src/utils.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9621 feat(components): [select] add placement
  docs/en-US/component/select.md
  packages/components/select/src/select.vue
Labels: CommitMessage::Qualified

#9622 feat(components): [select-v2] add placement
  docs/en-US/component/select-v2.md
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/select.vue
Labels: CommitMessage::Qualified

#9603 feat(components): [el-steps] support custom icon when status is error
  packages/components/steps/src/item.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9405 feat(components): [message-box] allow pass function to `message` option
  docs/en-US/component/message-box.md
  docs/examples/message-box/use-vnode.vue
  packages/components/message-box/src/message-box.type.ts
  packages/components/message-box/src/messageBox.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9593 fix(components): [table] column using `type`, `min-width`will not effect
  packages/components/table/src/table-column/render-helper.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9625 perf(components): [message] prefer function slots
  packages/components/message/src/method.ts
Labels: CommitMessage::Qualified

#9635 fix(components): [tree-select] fix typo
  packages/components/tree-select/__tests__/tree-select.test.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9637 fix(components): [table] selection column don't create table placeholder
  packages/components/table/src/table-column/render-helper.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9639 fix(theme-chalk): [select] missing the is-small style
  packages/theme-chalk/src/select.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9633 fix(components): [select] fix content overflow
  packages/components/select/src/select.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9654 fix(components): [table] fix namespace
  packages/components/table/src/table.vue
Labels: CommitMessage::Qualified

#9645 fix(components): [tree] repeat trigger change event on the same node
  packages/components/tree/src/model/util.ts
  packages/components/tree/src/tree-node.vue
  packages/components/tree/src/tree.vue
Labels: CommitMessage::Qualified

#9644 fix(components): [select] keep hover after clearing
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#9630 fix(components): [loading] remove `el-loading-parent--relative` correctly
  packages/components/loading/src/loading.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9655 fix(hooks): [use-popper-container] fix namespace
  packages/components/popper/src/container.ts
  packages/hooks/__tests__/use-popper-container.test.tsx
  packages/hooks/use-popper-container/index.ts
Labels: CommitMessage::Qualified

#9608 fix(components): [rate] fast move mouseLeave not triggered
  packages/components/rate/src/rate.vue
Labels: CommitMessage::Qualified

#8795 docs(components): [Slider] size attributes
  docs/en-US/component/slider.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9619 feat(components): [select] enhanced suffix
  docs/en-US/component/select.md
  docs/examples/select/remote-search.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/theme-chalk/src/select.scss
Labels: CommitMessage::Qualified

#9674 refactor(components): [cascader] use JSX in Unit test
  packages/components/cascader/__tests__/cascader.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9677 fix(components): [select-v2] Tags content overflow wrap
  packages/theme-chalk/src/select-v2.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9666 refactor(components)!: rename emit name to camelCase
  docs/.vitepress/vitepress/components/vp-subnav.vue
  internal/eslint-config/index.js
  packages/components/cascader-panel/src/index.vue
  packages/components/cascader/src/index.vue
  packages/components/color-picker/src/index.vue
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  packages/components/date-picker/src/date-picker-com/panel-month-range.vue
  packages/components/date-picker/src/props/panel-month-range.ts
  packages/components/dropdown/src/dropdown.vue
  packages/components/focus-trap/__tests__/focus-trap.test.ts
  packages/components/focus-trap/src/focus-trap.vue
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/menu/src/menu-item.ts
  packages/components/menu/src/menu-item.vue
  packages/components/pagination/__tests__/pagination.test.tsx
  packages/components/pagination/src/components/sizes.vue
  packages/components/pagination/src/pagination.ts
  packages/components/popover/__tests__/popover.test.tsx
  packages/components/popover/src/popover.ts
  packages/components/popover/src/popover.vue
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/components/table/src/store/current.ts
  packages/components/table/src/store/expand.ts
  packages/components/table/src/store/index.ts
  packages/components/table/src/store/tree.ts
  packages/components/table/src/store/watcher.ts
  packages/components/table/src/table-body/events-helper.ts
  packages/components/table/src/table-header/event-helper.ts
  packages/components/table/src/table.vue
  packages/components/tabs/__tests__/tabs.test.tsx
  packages/components/tabs/src/tabs.tsx
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
  packages/components/time-picker/src/time-picker-com/panel-time-pick.vue
  packages/components/time-picker/src/time-picker-com/panel-time-range.vue
  packages/components/tooltip/src/tooltip.vue
  packages/components/transfer/src/transfer-panel.ts
  packages/components/transfer/src/transfer.ts
  packages/components/tree-v2/src/virtual-tree.ts
  packages/components/tree/src/model/useDragNode.ts
  packages/components/tree/src/model/util.ts
  packages/components/tree/src/tree-node.vue
  packages/components/tree/src/tree.vue
  packages/components/virtual-list/src/components/scrollbar.ts
  packages/hooks/use-transition-fallthrough/index.ts
  vitest.config.ts
Labels: CommitMessage::Unqualified

#9682 fix(components): [table] throw error when no matching column
  packages/components/table/src/util.ts
Labels: Contribution::Community, CommitMessage::Unqualified, Needs Review

#9694 chore: move eslint ignore
  .eslintignore
  docs/.eslintignore
Labels: CommitMessage::Qualified

#9665 fix(components): [table-v2] cell and header-cell slots parmas
  packages/components/table-v2/__tests__/table-v2.test.tsx
  packages/components/table-v2/src/table-v2.tsx
Labels: CommitMessage::Qualified

#9693 refactor(build): use pnpm `shell-emulator` instead of `cross-env`
  .npmrc
  docs/package.json
  internal/metadata/package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#9707 fix(components): [select-v2] fix default placeholder style
  packages/components/select-v2/src/select.vue
Labels: CommitMessage::Qualified

#9706 fix(components): [select-v2] respect `--el-component-size`
  packages/theme-chalk/src/select-v2.scss
Labels: CommitMessage::Qualified

#9709 fix(components): [tree] setCurrentKey() type error
  packages/components/tree/src/model/tree-store.ts
  packages/components/tree/src/tree.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9428 fix(components): [cascader] fix large interval when multiple checkboxes
  packages/theme-chalk/src/cascader-panel.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9357 docs(components): [date-picker] attribute type description
  docs/en-US/component/date-picker.md
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/time-picker.md
  docs/examples/date-picker/default-time.vue
  docs/examples/datetime-picker/date-and-time-range.vue
  docs/examples/datetime-picker/default-time.vue
  docs/examples/time-picker/range.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9710 refactor(components): [cascader-panel] use JSX in Unit test
  packages/components/cascader-panel/__tests__/cascader-panel.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9717 refactor(components): [image-viewer] use JSX in Unit test
  packages/components/image-viewer/__tests__/image-viewer.test.tsx
Labels: CommitMessage::Qualified

#9521 fix(components): [select] fix select hover flicker
  packages/components/select/src/select.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9663 chore: add attribute enum autosuggestion for WebStorm
  docs/en-US/component/autocomplete.md
  docs/en-US/component/badge.md
  docs/en-US/component/breadcrumb.md
  docs/en-US/component/button.md
  docs/en-US/component/calendar.md
  docs/en-US/component/card.md
  docs/en-US/component/carousel.md
  docs/en-US/component/cascader.md
  docs/en-US/component/checkbox.md
  docs/en-US/component/collapse.md
  docs/en-US/component/color-picker.md
  docs/en-US/component/config-provider.md
  docs/en-US/component/container.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/descriptions.md
  docs/en-US/component/dialog.md
  docs/en-US/component/divider.md
  docs/en-US/component/drawer.md
  docs/en-US/component/dropdown.md
  docs/en-US/component/empty.md
  docs/en-US/component/form.md
  docs/en-US/component/icon.md
  docs/en-US/component/image.md
  docs/en-US/component/input-number.md
  docs/en-US/component/input.md
  docs/en-US/component/layout.md
  docs/en-US/component/link.md
  docs/en-US/component/menu.md
  docs/en-US/component/page-header.md
  docs/en-US/component/pagination.md
  docs/en-US/component/popconfirm.md
  docs/en-US/component/popover.md
  docs/en-US/component/progress.md
  docs/en-US/component/radio.md
  docs/en-US/component/rate.md
  docs/en-US/component/result.md
  docs/en-US/component/scrollbar.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/skeleton.md
  docs/en-US/component/slider.md
  docs/en-US/component/space.md
  docs/en-US/component/steps.md
  docs/en-US/component/switch.md
  docs/en-US/component/table-v2.md
  docs/en-US/component/table.md
  docs/en-US/component/tabs.md
  docs/en-US/component/tag.md
  docs/en-US/component/time-picker.md
  docs/en-US/component/time-select.md
  docs/en-US/component/timeline.md
  docs/en-US/component/tooltip.md
  docs/en-US/component/transfer.md
  docs/en-US/component/tree-v2.md
  docs/en-US/component/tree.md
  docs/en-US/component/upload.md
  internal/build/package.json
  internal/build/src/tasks/helper.ts
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#9726 fix(components): [select] fix option-group get wrong visible
  packages/components/select/src/option-group.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9724 refactor(docs): simplify imports
  docs/.vitepress/config.mts
  docs/.vitepress/config/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Unqualified, Needs Review

#9729 docs: update indent attribute for tree.md
  docs/en-US/component/tree.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Unqualified, Needs Review

#8203 docs: update table v2 doc
  docs/en-US/component/table-v2.md
Labels: CommitMessage::Qualified, Needs Review

#9730 docs: move translation guide to docs
  HELP_TRANSLATING_ZH.md
  README.md
  docs/.vitepress/crowdin/en-US/pages/guide.json
  docs/.vitepress/vitepress/components/full-screen/vp-translation.vue
  docs/.vitepress/vitepress/components/navbar/vp-translation.vue
  docs/en-US/guide/translation.md
Labels: CommitMessage::Qualified

#9720 fix(components): [loading] fix invalid position sticky
  packages/components/loading/src/service.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9738 chore: add linter and formatter cache
  .gitignore
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#9746 fix(components): [checkbox] fix only child element style border-radius
  packages/theme-chalk/src/checkbox-button.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7129 fix(components): [select-v2][tree-v2] add virtual-list style dependency
  packages/components/select-v2/style/css.ts
  packages/components/select-v2/style/index.ts
  packages/components/tree-v2/style/css.ts
  packages/components/tree-v2/style/index.ts
Labels: Contribution::Community, CommitMessage::Qualified

#9632 fix(components): [popper] add missing id
  packages/components/popper/src/content.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9737 ci: simplify workflows
  .github/workflows/lint-commit-message-post.yml
  .github/workflows/lint-commit-message.yml
  .github/workflows/test-ssr.yml
  .github/workflows/test-unit.yml
Labels: CommitMessage::Qualified

#9748 refactor(utils): refactor `flattedChildren`
  packages/components/descriptions/src/description.vue
  packages/components/menu/src/menu.ts
  packages/utils/vue/vnode.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9753 fix(components): [cascader-panel] fix type error
  packages/components/cascader-panel/src/utils.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9763 docs(form): fix hide-required-asterisk desc
  docs/en-US/component/form.md
Labels: CommitMessage::Qualified

#9771 fix: [alert] description value in title's class
  packages/components/alert/src/alert.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9780 fix(components): [virtual-list] fix type error
  packages/components/virtual-list/src/props.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9772 refactor(components): [loading] use JSX in Unit test
  packages/components/loading/__tests__/loading.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9794 chore: typo
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
Labels: CommitMessage::Qualified

#9594 refactor(components): [checkbox] refactor
  packages/components/checkbox/index.ts
  packages/components/checkbox/src/checkbox-button.vue
  packages/components/checkbox/src/checkbox-group.ts
  packages/components/checkbox/src/checkbox-group.vue
  packages/components/checkbox/src/checkbox.ts
  packages/components/checkbox/src/checkbox.type.ts
  packages/components/checkbox/src/checkbox.vue
  packages/components/checkbox/src/composables/index.ts
  packages/components/checkbox/src/composables/use-checkbox-disabled.ts
  packages/components/checkbox/src/composables/use-checkbox-event.ts
  packages/components/checkbox/src/composables/use-checkbox-model.ts
  packages/components/checkbox/src/composables/use-checkbox-status.ts
  packages/components/checkbox/src/composables/use-checkbox.ts
  packages/tokens/checkbox.ts
  packages/tokens/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9683 docs: fix import locale path
  docs/en-US/guide/i18n.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9672 refactor(components): [color-picker] switch to script-setup syntax
  packages/components/color-picker/__tests__/color-picker.test.tsx
  packages/components/color-picker/index.ts
  packages/components/color-picker/src/color-picker.ts
  packages/components/color-picker/src/color-picker.vue
  packages/components/color-picker/src/components/alpha-slider.vue
  packages/components/color-picker/src/components/hue-slider.vue
  packages/components/color-picker/src/components/predefine.vue
  packages/components/color-picker/src/components/sv-panel.vue
  packages/components/color-picker/src/index.vue
  packages/components/color-picker/src/useOption.ts
  packages/components/color-picker/src/utils/color.ts
  packages/components/color-picker/src/utils/draggable.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9797 fix(components): [color-picker] expose color
  packages/components/color-picker/src/color-picker.vue
Labels: Component::ColorPicker, CommitMessage::Qualified

#9785 fix(components): [tabs] tabs order
  packages/components/menu/src/menu.ts
  packages/components/tabs/src/tabs.tsx
  packages/components/tabs/src/utils/pane.ts
  packages/utils/vue/vnode.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9306 refactor(components): switch to vue macros
  docs/package.json
  docs/vite.config.ts
  internal/build/package.json
  internal/build/src/tasks/full-bundle.ts
  internal/build/src/tasks/modules.ts
  package.json
  packages/components/affix/src/affix.vue
  packages/components/autocomplete/src/autocomplete.vue
  packages/components/backtop/src/backtop.vue
  packages/components/calendar/src/calendar.vue
  packages/components/form/src/form.vue
  packages/components/switch/src/switch.vue
  packages/components/tabs/src/tab-bar.vue
  packages/components/tabs/src/tab-pane.vue
  packages/components/upload/src/upload-dragger.vue
  play/package.json
  play/vite.config.ts
  pnpm-lock.yaml
  ssr-testing/vitest.config.ts
  tsconfig.vitest.json
  tsconfig.web.json
  vitest.config.ts
Labels: CommitMessage::Qualified

#9769 refactor(components): [loading] change `viewBox` default value
  packages/components/loading/src/loading.ts
Labels: CommitMessage::Qualified

#9638 refactor(components)!: [select-v2] value-key is used for object select
  docs/examples/select-v2/use-valueKey.vue
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/select-dropdown.tsx
  packages/components/select-v2/src/useSelect.ts
Labels: needs discussion, Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9786 refactor(components): [tree-select] use JSX in Unit test
  packages/components/tree-select/__tests__/tree-select.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9801 docs(components): [popover] remove `v-model` in example (#9201)
  docs/examples/popover/nested-operation.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9811 refactor(components): [upload] use JSX in Unit test
  packages/components/upload/__tests__/upload-dragger.test.tsx
Labels: CommitMessage::Qualified

#9815 docs(components): [select-v2] improve demo
  docs/examples/select-v2/allow-create.vue
  docs/examples/select-v2/basic-usage.vue
  docs/examples/select-v2/clearable.vue
  docs/examples/select-v2/use-valueKey.vue
Labels: CommitMessage::Qualified

#9813 fix(components): [checkbox] fix injection warn
  packages/components/checkbox/src/checkbox-button.vue
  packages/components/checkbox/src/composables/use-checkbox-event.ts
  packages/components/checkbox/src/composables/use-checkbox-model.ts
  packages/components/checkbox/src/composables/use-checkbox-status.ts
Labels: CommitMessage::Qualified

#9814 fix(components): [color-picker] correct event validation
  packages/components/color-picker/__tests__/color-picker.test.tsx
  packages/components/color-picker/src/color-picker.ts
Labels: CommitMessage::Qualified

#9800 refactor(components): [menu] disable ellipsis by default
  breakings/2.3.0/menu.yml
  packages/components/menu/src/menu.ts
Labels: CommitMessage::Qualified

#8400 refactor(components)!: [switch] remove value prop
  breakings/2.3.0/switch.yml
  packages/components/switch/__tests__/switch.test.tsx
  packages/components/switch/src/switch.ts
  packages/components/switch/src/switch.vue
Labels: CommitMessage::Qualified

#9822 fix(components): [date-picker] remove extra prop in unit test
  packages/components/date-picker/__tests__/date-picker.test.ts
Labels: CommitMessage::Qualified

#9823 fix(components): [popper] perfect role types
  packages/components/popper/src/popper.ts
Labels: CommitMessage::Qualified

#9818 fix(components): [select-v2] pressing the up key may cause errors
  packages/components/select-v2/src/useSelect.ts
Labels: CommitMessage::Qualified

#9685 refactor(components): [tooltip] switch to script-setup syntax
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/slider/__tests__/slider.test.tsx
  packages/components/slider/src/composables/use-slider-button.ts
  packages/components/tooltip/__tests__/content.test.tsx
  packages/components/tooltip/__tests__/tooltip.test.tsx
  packages/components/tooltip/__tests__/trigger.test.tsx
  packages/components/tooltip/index.ts
  packages/components/tooltip/src/content.ts
  packages/components/tooltip/src/content.vue
  packages/components/tooltip/src/tooltip.ts
  packages/components/tooltip/src/tooltip.vue
  packages/components/tooltip/src/trigger.ts
  packages/components/tooltip/src/trigger.vue
  packages/components/tooltip/src/utils.ts
  packages/tokens/index.ts
  packages/tokens/tooltip.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9835 fix(components): [select-v2] improve placeholder display
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/useSelect.ts
Labels: CommitMessage::Qualified

#9660 fix(components): [affix] fix affix when scroll container is not window
  packages/components/affix/src/affix.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9824 fix(components): [calendar] show wrong weekday when set weekStart
  packages/components/calendar/__tests__/calendar.test.tsx
  packages/components/calendar/src/date-table.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9850 fix(components): [input-number] correct input event behavior
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
Labels: CommitMessage::Qualified

#9853 refactor(directives): [repeat-click] refactor
  packages/components/input-number/src/input-number.vue
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
  packages/directives/__tests__/repeat-click.test.tsx
  packages/directives/index.ts
  packages/directives/repeat-click/index.ts
Labels: CommitMessage::Qualified

#9854 refactor(components): [calendar] use self-closing element
  packages/components/calendar/__tests__/calendar.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9860 ci: improve cache
  .github/workflows/lint-commit-message-post.yml
  .github/workflows/lint-commit-message.yml
  .github/workflows/pr-docs-build.yml
  .github/workflows/publish-build-product.yml
  .github/workflows/publish-docs-deploy-manual.yml
  .github/workflows/publish-docs-deploy.yml
  .github/workflows/publish-npm-nightly.yml
  .github/workflows/publish-npm.yml
  .github/workflows/publish-size-report.yml
  .github/workflows/staging-docs.yml
  .github/workflows/test-coverage.yml
  .github/workflows/test-ssr.yml
  .github/workflows/test-unit.yml
Labels: CommitMessage::Qualified

#8529 refactor(components): [popper] fix type error
  packages/components/popper/index.ts
  packages/components/popper/src/arrow.ts
  packages/components/popper/src/arrow.vue
  packages/components/popper/src/content.ts
  packages/components/popper/src/content.vue
  packages/components/popper/src/popper.ts
  packages/components/popper/src/popper.vue
  packages/components/popper/src/trigger.ts
  packages/components/popper/src/trigger.vue
  packages/components/popper/src/utils.ts
  packages/components/tooltip/src/content.ts
  packages/components/tooltip/src/tooltip.ts
  packages/components/tooltip/src/trigger.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8462 refactor(components): [popper] use JSX in Unit test
  packages/components/popper/__tests__/arrow.test.tsx
  packages/components/popper/__tests__/content.test.tsx
  packages/components/popper/__tests__/popper.test.tsx
  packages/components/popper/__tests__/trigger.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#6711 fix(components): [dialog] fix document click event invalid
  packages/components/dialog/src/dialog-content.vue
Labels: Contribution::Community, CommitMessage::Qualified

#9866 docs: fix typo
  docs/en-US/component/skeleton.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9875 fix(theme-chalk): [drawer] close btn align style
  packages/theme-chalk/src/drawer.scss
Labels: CommitMessage::Qualified

#8975 docs: refactor the external link icon
  docs/.vitepress/config/plugins.ts
  docs/.vitepress/plugins/external-link-icon.ts
  docs/.vitepress/vitepress/components/vp-doc-content.vue
  docs/.vitepress/vitepress/utils/index.ts
Labels: CommitMessage::Qualified

#9865 fix(components): [steps] step line style
  packages/components/steps/src/item.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9872 fix(components): [tree] tree node click parameter
  packages/components/tree/src/model/util.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9587 fix(components): [select] excute filter/remoteMethod when blur
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9879 fix(components): [radio] fix type error
  packages/components/radio/__tests__/radio.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9839 fix(theme-chalk): [table] remove redundant border styles
  packages/theme-chalk/src/table.scss
Labels: CommitMessage::Qualified

#9878 docs: refactor the table-wrapper
  docs/.vitepress/config/plugins.ts
  docs/.vitepress/plugins/external-link-icon.ts
  docs/.vitepress/plugins/table-wrapper.ts
  docs/.vitepress/vitepress/components/vp-doc-content.vue
  docs/.vitepress/vitepress/utils/index.ts
Labels: CommitMessage::Qualified

#9886 fix(components): [slider] fix type error
  packages/components/slider/__tests__/slider.test.tsx
Labels: CommitMessage::Qualified

#9887 fix(components): [result] fix type error
  packages/components/result/__tests__/result.test.tsx
Labels: CommitMessage::Qualified

#9892 fix(components): [backtop] fix a display bug
  packages/components/backtop/src/backtop.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9894 fix(components): [progress] fix type error
  packages/components/progress/src/progress.vue
Labels: CommitMessage::Qualified

#9884 fix(components): [time-select] fix type error
  packages/components/time-select/__tests__/time-select.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9893 fix(components): [pagination] fix type error
  packages/components/pagination/src/components/sizes.ts
  packages/components/pagination/src/components/sizes.vue
Labels: CommitMessage::Qualified

#9899 fix(components): [descriptions] fix type error
  packages/components/descriptions/__tests__/descriptions.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9896 fix(components): [tabs] correct the position of tab-bar when scaling
  packages/components/tabs/__tests__/tabs.test.tsx
  packages/components/tabs/src/tab-bar.vue
Labels: CommitMessage::Qualified

#9901 chore(metadata): fix typo
  internal/metadata/src/contributor.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9871 fix(locale): added missing strings for Hebrew
  packages/locale/lang/he.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9940 fix(components): [form] no margin when there is no label
  docs/en-US/component/form.md
  packages/components/form/src/form-item.vue
  packages/components/form/src/form-label-wrap.tsx
  packages/tokens/form.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9946 fix: `withInstallDirective` type error
  packages/utils/vue/install.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9967 refactor(docs): filter bot in contributors list
  docs/.vitepress/vitepress/components/globals/contributors.vue
Labels: CommitMessage::Qualified

#9874 feat(docs): add drawer for theme color edit
  docs/.vitepress/theme/index.ts
  docs/.vitepress/vitepress/components/theme-editor/ep-theme-color-bar.vue
  docs/.vitepress/vitepress/components/theme-editor/ep-theme-color-box.vue
  docs/.vitepress/vitepress/components/theme-editor/ep-theme-drawer.vue
  docs/.vitepress/vitepress/components/theme-editor/ep-theme-primary-colors.vue
  docs/.vitepress/vitepress/components/theme-editor/ep-theme-primary.vue
  docs/.vitepress/vitepress/components/theme-editor/ep-theme-secondary-color.vue
  docs/.vitepress/vitepress/components/theme-editor/ep-theme-secondary-colors.vue
  docs/.vitepress/vitepress/components/vp-app.vue
  docs/.vitepress/vitepress/store/theme.ts
  docs/.vitepress/vitepress/utils/colors/helper.ts
  docs/.vitepress/vitepress/utils/colors/hooks.ts
  docs/.vitepress/vitepress/utils/colors/hsv.ts
  docs/.vitepress/vitepress/utils/colors/index.ts
  docs/.vitepress/vitepress/utils/colors/var.ts
  docs/.vitepress/vitepress/utils/theme/helper.ts
  docs/.vitepress/vitepress/utils/theme/index.ts
  docs/.vitepress/vitepress/utils/theme/store/default.ts
  docs/.vitepress/vitepress/utils/theme/store/high-contrast.ts
  docs/.vitepress/vitepress/utils/theme/store/index.ts
  docs/.vitepress/vitepress/utils/theme/types.ts
  docs/components.d.ts
  docs/package.json
  docs/public/images/primary-color-placeholder.png
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#9978 fix(components): [select-v2] Test file code misspelled
  packages/components/select-v2/__tests__/select.test.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9798 fix(components): [select] click label only focus in form
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified
