Repository element-plus/element-plus, pull requests merged in 2022-06, with the labels that each got.

#8024 refactor(components): [button] use JSX in Unit test
  packages/components/button/__tests__/button.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8022 refactor(components): [progress] use JSX in Unit test
  packages/components/progress/__tests__/progress.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8019 refactor(components): [radio] use JSX in Unit test
  packages/components/radio/__tests__/radio.test.tsx
Labels: CommitMessage::Qualified

#8020 refactor(components): [layout] use JSX in Unit test
  packages/components/col/__tests__/layout.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7968 feat(components): [image] support native lazy loading
  breakings/2.2.3/image.yml
  docs/en-US/component/image.md
  packages/components/image/__tests__/image.test.tsx
  packages/components/image/src/image.ts
  packages/components/image/src/image.vue
  packages/theme-chalk/src/image.scss
Labels: CommitMessage::Qualified

#8025 fix(components): [focus-trap] popper input focus
  packages/components/focus-trap/src/focus-trap.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8018 refactor(utils): ep prop
  packages/hooks/use-model-toggle/index.ts
  packages/utils/__tests__/vue/props.test.ts
  packages/utils/vue/props.ts
  packages/utils/vue/props/index.ts
  packages/utils/vue/props/runtime.ts
  packages/utils/vue/props/types.ts
  packages/utils/vue/props/util.ts
  tsconfig.vitest.json
Labels: CommitMessage::Qualified

#8021 refactor(components): [avatar] use JSX in Unit test
  packages/components/avatar/__tests__/avatar.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8043 refactor(components): [date-picker] panel-date-pick
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
Labels: CommitMessage::Qualified

#8037 test: add property "testData" on instance
  packages/components/table/__tests__/table.test.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8012 fix(components): [el-table] hide tooltip when table is scrolling
  packages/components/table/src/table-body/events-helper.ts
  packages/components/table/src/table/defaults.ts
  packages/components/table/src/util.ts
  packages/utils/dom/event.ts
Labels: CommitMessage::Qualified

#8045 refactor(components): [date-picker] basic-year-table
  packages/components/date-picker/src/date-picker-com/basic-year-table.vue
Labels: CommitMessage::Qualified

#8027 refactor(build): duplicate variable name
  internal/build/src/tasks/types-definitions.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8058 test(components): [card] add optional chaining
  packages/components/card/__tests__/card.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8065 refactor(components): [radio] separate hooks
  packages/components/radio/src/radio-button.vue
  packages/components/radio/src/radio.ts
  packages/components/radio/src/radio.vue
  packages/components/radio/src/use-radio.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8059 test(components): [card] correct shadow props
  packages/components/card/__tests__/card.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8054 fix(components): [popper] contextual menu
  packages/components/tooltip/__tests__/content.test.ts
  packages/components/tooltip/src/content.vue
Labels: CommitMessage::Qualified

#8067 fix(components): [form] resetFields object error
  packages/components/form/src/form-item.vue
Labels: CommitMessage::Qualified

#8077 test(components): [checkbox] add data type
  packages/components/checkbox/__tests__/checkbox.test.tsx
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8078 docs: fix typo
  docs/en-US/component/affix.md
  docs/en-US/component/cascader.md
  docs/en-US/component/dialog.md
  docs/en-US/component/image.md
  docs/en-US/component/table.md
  docs/en-US/component/tooltip.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8072 fix(theme-chalk): [message] border width & style css var
  packages/theme-chalk/src/message.scss
Labels: CommitMessage::Qualified

#8074 fix(components): [loading] fix typo
  packages/components/loading/src/loading.ts
Labels: CommitMessage::Qualified

#8070 style: update cascader.css
  packages/theme-chalk/src/cascader.scss
Labels: CommitMessage::Qualified

#8079 fix(components): [upload] beforeUpload hook
  packages/components/upload/src/upload-content.vue
Labels: CommitMessage::Qualified

#8071 chore: ignore jsdom
  .github/renovate.json5
Labels: CommitMessage::Qualified

#8085 Fix/focus trap datepicker pick
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/focus-trap/src/focus-trap.vue
  packages/components/time-picker/src/common/picker.vue
Labels: CommitMessage::Qualified

#8083 fix(components): [timeline-item] props validation
  packages/components/timeline/__tests__/timeline.test.ts
  packages/components/timeline/src/timeline-item.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8075 refactor(components): [tag] add event modifier
  packages/components/tag/src/tag.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8073 refactor(components): [badge] remove unnecessary condition
  packages/components/badge/src/badge.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8086 chore: upgrade element plus icons
  docs/package.json
  package.json
  packages/element-plus/package.json
  play/package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#8082 fix(components): [time-picker] picker missing
  packages/components/time-picker/__tests__/time-picker.test.ts
  packages/components/time-picker/src/common/picker.vue
Labels: CommitMessage::Qualified

#8053 refactor(components): [date-picker] basic-month-table
  packages/components/date-picker/src/date-picker-com/basic-month-table.vue
Labels: CommitMessage::Qualified

#8088 fix(build): tree shaking
  docs/package.json
  internal/build/src/tasks/full-bundle.ts
  package.json
  packages/element-plus/package.json
  play/package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#8057 fix(components): [date-picker] fix style, close #8055
  packages/theme-chalk/src/date-picker/picker.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8093 fix(components): [date-picker] circular dependency
  packages/components/date-picker/src/date-picker.tsx
  packages/components/date-picker/src/panel-utils.ts
  packages/components/date-picker/src/utils.ts
Labels: CommitMessage::Qualified

#8094 docs(components): [menu] add left and right example
  docs/en-US/component/menu.md
  docs/examples/menu/left-and-right.vue
Labels: CommitMessage::Qualified

#8092 docs(components): [table] wrong default value for resizable
  docs/en-US/component/table.md
Labels: CommitMessage::Qualified

#8098 fix(build): copy typings
  internal/build/gulpfile.ts
Labels: hotfix, CommitMessage::Qualified

#8099 D2M
  CHANGELOG.en-US.md
  docs/en-US/component/menu.md
  docs/en-US/component/table.md
  docs/examples/menu/left-and-right.vue
  internal/build/gulpfile.ts
  packages/components/date-picker/src/date-picker.tsx
  packages/components/date-picker/src/panel-utils.ts
  packages/components/date-picker/src/utils.ts
Labels: 🚀 Ready for takeoff, CommitMessage::Unqualified

#8095 refactor(components): [date-picker] basic-date-table
  packages/components/date-picker/src/date-picker-com/basic-date-table.vue
  packages/components/date-picker/src/date-picker-com/basic-month-table.vue
  packages/components/date-picker/src/utils.ts
Labels: CommitMessage::Qualified

#8108 refactor(components): [time-picker] props
  packages/components/time-picker/src/props/basic-time-spinner.ts
  packages/components/time-picker/src/props/panel-time-picker.ts
  packages/components/time-picker/src/props/panel-time-range.ts
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
  packages/components/time-picker/src/time-picker-com/panel-time-pick.vue
  packages/components/time-picker/src/time-picker-com/panel-time-range.vue
Labels: CommitMessage::Qualified

#8115 refactor(components): [time-picker] panel-time-pick
  packages/components/time-picker/src/time-picker-com/panel-time-pick.vue
Labels: CommitMessage::Qualified

#8121 chore: update doc site
  docs/.vitepress/vitepress/components/sponsors/right-richtext-list.vue
  docs/.vitepress/vitepress/components/vp-sponsor-large.vue
  docs/.vitepress/vitepress/components/vp-sponsor-small.vue
  docs/.vitepress/vitepress/components/vp-sponsors.vue
Labels: CommitMessage::Qualified

#8106 fix: the type extends error
  packages/element-plus/make-installer.ts
Labels: CommitMessage::Qualified

#8128 refactor(components): [time-picker] script setup
  packages/components/time-picker/src/composables/use-time-panel.ts
  packages/components/time-picker/src/props/basic-time-spinner.ts
  packages/components/time-picker/src/props/panel-time-picker.ts
  packages/components/time-picker/src/props/panel-time-range.ts
  packages/components/time-picker/src/time-picker-com/panel-time-pick.vue
  packages/components/time-picker/src/time-picker-com/panel-time-range.vue
Labels: CommitMessage::Qualified

#8140 refactor(components): [link] use JSX in Unit test
  packages/components/link/__tests__/link.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8137 fix: vue app typing
  packages/constants/index.ts
  packages/constants/key.ts
  packages/element-plus/index.ts
  packages/element-plus/make-installer.ts
  tsconfig.web.json
  typings/env.d.ts
Labels: CommitMessage::Qualified

#8143 ci: fix build staging
  .github/workflows/staging-docs.yml
Labels: CommitMessage::Qualified

#8145 fix(components): [select-v2] remove private API
  packages/components/select-v2/src/select-dropdown.tsx
  packages/components/select-v2/src/select-dropdown.vue
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/token.ts
  packages/components/select-v2/src/useSelect.ts
Labels: CommitMessage::Qualified

#8105 chore: use cz-git commitizen adapter
  commitlint.config.js
  package.json
  pnpm-lock.yaml
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8154 fix(components): [form] catch validation error when changing rules
  packages/components/form/src/form.vue
Labels: Component::Form, Needs Review

#8160 refactor(components): [time-picker] time-picker
  packages/components/date-picker/src/date-picker.tsx
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/common/props.ts
  packages/components/time-picker/src/time-picker-com/panel-time-range.vue
  packages/components/time-picker/src/time-picker.ts
  packages/components/time-picker/src/time-picker.tsx
Labels: CommitMessage::Qualified

#8161 fix(components): [tag] awrong disable-transitions condition
  packages/components/tag/src/tag.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8117 docs(components): [link] fix type accepted values
  docs/en-US/component/link.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8101 fix(components): [switch] tabindex property doesn't work
  packages/components/switch/__tests__/switch.test.ts
  packages/components/switch/src/switch.ts
  packages/components/switch/src/switch.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8096 fix(components): [input] hide eye icon if no value
  packages/components/input/src/input.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8081 fix(components): [collapse-item] If disabled, no focus
  packages/components/collapse/src/collapse-item.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8119 fix(components): [time-picker] filter invalid value
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/__tests__/date-time-picker.test.ts
  packages/components/time-picker/__tests__/time-picker.test.ts
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8167 fix: components dts
  global.d.ts
  tsconfig.play.json
  typings/components.d.ts
Labels: CommitMessage::Qualified

#8175 docs(components): [layout] unocss cover
  docs/examples/layout/alignment.vue
  docs/examples/layout/basic-layout.vue
  docs/examples/layout/column-offset.vue
  docs/examples/layout/column-spacing.vue
  docs/examples/layout/hybrid-layout.vue
  docs/examples/layout/index.scss
  docs/examples/layout/responsive-layout.vue
  ssr-testing/cases/layout.vue
Labels: CommitMessage::Qualified

#8166 feat: check message when committing
  .husky/commit-msg
  .husky/pre-push-todo-open
  commitlint.config.js
  commitlint.config.ts
  package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#8177 ci: fix publish
  .github/workflows/publish-npm-nightly.yml
  .github/workflows/publish-npm.yml
Labels: CommitMessage::Qualified

#8139 fix(components): [picker] picker-panel not pop up when disabled/readonly
  packages/components/time-picker/__tests__/time-picker.test.ts
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8170 refactor(components): [time-picker] constants
  packages/components/time-picker/__tests__/time-picker.test.ts
  packages/components/time-picker/index.ts
  packages/components/time-picker/src/common/constant.ts
  packages/components/time-picker/src/common/date-utils.ts
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/constants.ts
  packages/components/time-picker/src/time-picker.tsx
  packages/components/time-picker/src/utils.ts
Labels: CommitMessage::Qualified

#8180 ci: fix build
  .github/workflows/publish-build-product.yml
  .github/workflows/publish-size-report.yml
Labels: CommitMessage::Qualified

#8162 fix(components): [table] fix namespace in table's expand icon
  packages/components/table/src/table-body/render-helper.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Unqualified, Needs Review

#8109 fix(components): [image] position styles error when used slots
  packages/components/image/src/image.ts
  packages/components/image/src/image.vue
  packages/theme-chalk/src/image.scss
Labels: CommitMessage::Qualified

#8214 style(components): [button] link button add focus css
  packages/theme-chalk/src/button.scss
Labels: CommitMessage::Qualified

#8219 chore: update readme thanks
  README.md
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/vitepress/components/doc-content/vp-table-of-content.vue
  docs/.vitepress/vitepress/components/sponsors/right-logo-small-list.vue
  docs/.vitepress/vitepress/components/vp-sponsor-small.vue
  docs/components.d.ts
  docs/public/images/sponsors/buildadmin-l.png
  docs/public/images/sponsors/buildadmin.png
Labels: CommitMessage::Qualified

#8191 Refactor/time picker refactor to setup
  internal/build/src/type-unsafe-stricter.json
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/common/props.ts
  packages/components/time-picker/src/composables/use-time-panel.ts
  packages/components/time-picker/src/composables/use-time-picker.ts
  packages/components/time-picker/src/props/basic-time-spinner.ts
  packages/components/time-picker/src/props/panel-time-picker.ts
  packages/components/time-picker/src/props/panel-time-range.ts
  packages/components/time-picker/src/props/shared.ts
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
  packages/components/time-picker/src/time-picker-com/panel-time-pick.vue
  packages/components/time-picker/src/time-picker-com/panel-time-range.vue
  packages/components/time-picker/src/time-picker-com/useTimePicker.ts
  packages/components/time-picker/src/types.ts
  packages/components/time-picker/src/utils.ts
Labels: CommitMessage::Qualified

#8107 fix(components): [pagination] improved keyboard accessibility
  packages/components/pagination/src/components/pager.vue
  packages/theme-chalk/src/pagination.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8187 fix(components):[date-picker] valid value error
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8223 chore: update img style
  docs/.vitepress/vitepress/components/sponsors/right-logo-small-list.vue
  docs/public/images/sponsors/buildadmin-l.png
Labels: CommitMessage::Qualified

#8193 fix(components): inputNumber cursor offset up
  packages/theme-chalk/src/input-number.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8008 refactor(components): [slider] switch to script-setup syntax
  packages/components/slider/__tests__/slider.test.ts
  packages/components/slider/index.ts
  packages/components/slider/src/button.ts
  packages/components/slider/src/button.vue
  packages/components/slider/src/composables/index.ts
  packages/components/slider/src/composables/use-lifecycle.ts
  packages/components/slider/src/composables/use-marks.ts
  packages/components/slider/src/composables/use-slide.ts
  packages/components/slider/src/composables/use-slider-button.ts
  packages/components/slider/src/composables/use-stops.ts
  packages/components/slider/src/composables/use-watch.ts
  packages/components/slider/src/index.vue
  packages/components/slider/src/marker.ts
  packages/components/slider/src/marker.vue
  packages/components/slider/src/slider.ts
  packages/components/slider/src/slider.type.ts
  packages/components/slider/src/slider.vue
  packages/tokens/index.ts
  packages/tokens/slider.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8215 chore(play): fix lint
  play/app.example.vue
  play/vite.init.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8226 fix(components): [table-v2] `column's min-width` should work normal
  packages/components/table-v2/src/composables/utils.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8224 style(components): [button] focus-visible
  packages/theme-chalk/src/button.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/mixins/_button.scss
Labels: CommitMessage::Qualified

#8199 refactor(components): [switch] Simplify color handling
  docs/en-US/component/switch.md
  docs/examples/switch/basic.vue
  docs/examples/switch/extended-value-types.vue
  docs/examples/switch/text-description.vue
  packages/components/switch/__tests__/switch.test.ts
  packages/components/switch/src/switch.vue
  packages/theme-chalk/src/switch.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8235 refactor(utils): import path
  packages/utils/vue/vnode.ts
Labels: CommitMessage::Qualified

#8231 refactor(components): [carousel] complete optional values
  packages/components/carousel/src/carousel.ts
Labels: CommitMessage::Qualified

#8220 fix(theme-chalk): [col] remove float property
  packages/theme-chalk/src/col.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8200 refactor(components): [input] fix ts error
  packages/components/input/src/input.vue
  packages/tokens/form.ts
Labels: CommitMessage::Qualified

#8237 fix(components): [time-picker] template type assertion
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8230 refactor(components): [result] use JSX in Unit test
  packages/components/result/__tests__/result.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8227 refactor(components): [overlay] use JSX in Unit test
  packages/components/overlay/__tests__/overlay.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8233 refactor(components): [tag] use JSX in Unit test
  packages/components/tag/__tests__/tag.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8194 fix(components): [date-picker] validateEvent prop not work
  packages/components/time-picker/src/common/picker.vue
Labels: Component::DatePicker, CommitMessage::Qualified, Needs Review

#8239 fix: vitest typings
  ssr-testing/vitest.config.ts
  tsconfig.vite-config.json
  vitest.config.ts
Labels: CommitMessage::Qualified

#8249 refactor(components): [icon] use JSX in Unit test
  packages/components/icon/__tests__/icon.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8245 refactor(components): [empty] use JSX in Unit test
  packages/components/empty/__tests__/empty.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8248 refactor(components): [divider] use JSX in Unit test
  packages/components/divider/__tests__/divider.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8232 style(components): [button] text-button bg mode add focus
  packages/theme-chalk/src/button.scss
Labels: CommitMessage::Qualified

#8255 fix(components): [virtual-list]fix namespace in virtual-list
  packages/components/virtual-list/src/builders/build-list.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8263 refactor(components): [page-header] use JSX in Unit test
  packages/components/page-header/__tests__/page-header.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#7801 docs(components): [time-picker] remove invalid attribute
  docs/en-US/component/time-picker.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8247 refactor(components): [collapse-transition] type error
  internal/build/src/type-unsafe-stricter.json
  packages/components/collapse-transition/src/collapse-transition.vue
Labels: CommitMessage::Qualified

#8222 fix(components): [pagination] tab enable error if disabled
  packages/components/pagination/__tests__/pagination.test.ts
  packages/components/pagination/src/components/pager.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8281 refactor(components): [scrollbar] simplify emits type checking
  packages/components/scrollbar/src/scrollbar.ts
Labels: Contribution::Community, Component：ScrollBar, CommitMessage::Qualified, Needs Review

#8260 docs(components): [tabs] update tabs.md
  docs/en-US/component/tabs.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8266 style(components): [select] options disabled hover bg
  packages/theme-chalk/src/select-dropdown.scss
Labels: CommitMessage::Qualified

#8315 chore: update typography img
  docs/public/images/typography/term-hiragino-dark.png
  docs/public/images/typography/term-hiragino.png
Labels: CommitMessage::Qualified

#8316 docs: add autocomplete doc
  docs/.vitepress/crowdin/en-US/pages/component.json
  docs/en-US/component/autocomplete.md
  docs/en-US/component/input.md
Labels: CommitMessage::Qualified

#8258 fix(components): [upload] two-way binding fileList
  docs/en-US/component/upload.md
  docs/examples/upload/avatar.vue
  docs/examples/upload/basic.vue
  docs/examples/upload/drag-and-drop.vue
  docs/examples/upload/file-list-with-thumbnail.vue
  docs/examples/upload/file-list.vue
  docs/examples/upload/limit-cover.vue
  docs/examples/upload/manual.vue
  docs/examples/upload/photo-wall.vue
  packages/components/upload/src/upload-content.ts
  packages/components/upload/src/upload.vue
  packages/components/upload/src/use-handlers.ts
Labels: CommitMessage::Qualified

#8221 fix(components): [tabs] DOM update finished calculating navOffset
  packages/components/tabs/__tests__/tabs.test.ts
  packages/components/tabs/src/tab-nav.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8320 docs: add autocomplete doc
  docs/en-US/component/autocomplete.md
  docs/examples/autocomplete/autocomplete-template.vue
  docs/examples/autocomplete/autocomplete.vue
  docs/examples/autocomplete/remote-search.vue
Labels: CommitMessage::Qualified

#8329 refactor(components): [image-viewer] simplify emits type checking
  packages/components/image-viewer/src/image-viewer.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8335 refactor(components): [switch] deprecate value prop
  packages/components/switch/src/switch.vue
  packages/hooks/use-deprecated/index.ts
Labels: CommitMessage::Qualified

#8268 refactor(components): [upload] use JSX in Unit test
  packages/components/upload/__tests__/upload.test.tsx
Labels: CommitMessage::Qualified

#8344 fix(components): [select] collapse-tags-tooltip drop first item
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/select.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
Labels: CommitMessage::Qualified

#8336 fix(components): [message-box] the focus error when used ElMessageBox
  packages/components/message-box/src/index.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8350 fix(components): [autocomplete] the popup still appears after select
  packages/components/autocomplete/src/autocomplete.vue
Labels: CommitMessage::Qualified

#8351 refactor(components): [descriptions] use JSX in Unit test
  packages/components/descriptions/__tests__/descriptions.test.ts
  packages/components/descriptions/__tests__/descriptions.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8376 feat(docs): add gaussian blur to the navigation bar
  docs/.vitepress/vitepress/styles/css-vars.scss
  docs/.vitepress/vitepress/styles/navbar.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8378 refactor(components): [message] fix typings and switch to script setup
  internal/build/src/type-unsafe-stricter.json
  packages/components/message/__tests__/message-manager.test.tsx
  packages/components/message/__tests__/message.test.ts
  packages/components/message/src/message-method.ts
  packages/components/message/src/message.ts
  packages/components/message/src/message.vue
Labels: CommitMessage::Qualified

#8301 fix(components): [tooltip] not disappear when <keep-alive> change
  packages/components/tooltip/src/tooltip.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#7792 refactor(components): [switch] switch to script-setup syntax
  packages/components/switch/__tests__/switch.test.tsx
  packages/components/switch/src/switch.vue
Labels: CommitMessage::Qualified

#8386 refactor(components): [space] refactor
  packages/components/space/index.ts
  packages/components/space/src/item.ts
  packages/components/space/src/item.vue
  packages/components/space/src/space.ts
  packages/components/space/src/use-space.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8225 refactor(components): [slider] use JSX in Unit test
  packages/components/slider/__tests__/slider.test.ts
  packages/components/slider/__tests__/slider.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8273 refactor(components): [popover] switch to script-setup syntax
  packages/components/popover/__tests__/directive.test.ts
  packages/components/popover/__tests__/popover.test.ts
  packages/components/popover/index.ts
  packages/components/popover/src/directive.ts
  packages/components/popover/src/index.vue
  packages/components/popover/src/popover.ts
  packages/components/popover/src/popover.vue
  packages/utils/vue/install.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8039 fix(components): [space] missing empty string size
  packages/components/space/src/use-space.ts
Labels: CommitMessage::Qualified, Needs Review

#8379 fix(components): [message]: offset
  packages/components/message/__tests__/message-manager.test.tsx
  packages/components/message/__tests__/message.test.ts
  packages/components/message/index.ts
  packages/components/message/src/instance.ts
  packages/components/message/src/message.ts
  packages/components/message/src/message.vue
  packages/components/message/src/method.ts
Labels: CommitMessage::Qualified

#8381 docs(components): [message-box] add customized icon for examples
  docs/en-US/component/message-box.md
  docs/examples/message-box/customized-icon.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8407 perf(components): remove unnecessary const assertions
  packages/components/form/src/form.ts
  packages/components/result/src/result.ts
  packages/components/steps/src/item.ts
  packages/components/steps/src/steps.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8413 docs: [tag] add tag theme example
  docs/examples/tag/theme.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8415 feat(components): close all messages of the specified type
  packages/components/message/__tests__/message-manager.test.tsx
  packages/components/message/src/message.ts
  packages/components/message/src/method.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8423 fix(components): [select] multiple init height
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#8433 refactor(components): [space] use JSX in Unit test
  packages/components/space/__tests__/space.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8436 refactor(components): [popconfirm] changed button type
  docs/en-US/component/popconfirm.md
  packages/components/popconfirm/src/popconfirm.ts
Labels: CommitMessage::Qualified

#8447 fix(theme-chalk): [pagination] style if selected value is disabled
  packages/theme-chalk/src/pagination.scss
Labels: CommitMessage::Qualified

#8435 fix(components): [select] fix select dropdown width (#8396)
  packages/components/select/src/select-dropdown.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8463 refactor(components): [drawer] replace with addUnit
  packages/components/drawer/src/drawer.vue
Labels: CommitMessage::Qualified

#8442 fix(components): [select-v2] fix select-v2 dropdown width
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8133 fix(components): [popover] fix dark mode background color
  packages/theme-chalk/src/common/var.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8474 docs: fix popper.js docs link(dropdown, select-v2, tooltip)
  docs/en-US/component/dropdown.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/tooltip.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8446 ci: cancel same in-progress workflow
  .github/workflows/pr-docs-build.yml
  .github/workflows/staging-docs.yml
  .github/workflows/test-unit.yml
Labels: CommitMessage::Qualified

#8445 feat(components): [message-box] add autofocus attribute
  docs/.vitepress/vitepress/styles/css-vars.scss
  docs/en-US/component/message-box.md
  docs/examples/message-box/alert.vue
  packages/components/message-box/__tests__/message-box.test.ts
  packages/components/message-box/src/index.vue
  packages/components/message-box/src/message-box.type.ts
Labels: CommitMessage::Qualified

#8480 refactor(components): [only-child] simplify conditions
  packages/components/slot/src/only-child.tsx
Labels: CommitMessage::Qualified

#8364 feat(components): [autocomplete] expose blur event
  docs/en-US/component/autocomplete.md
  packages/components/autocomplete/src/autocomplete.vue
Labels: CommitMessage::Qualified

#8343 refactor(components): [transfer] switch to script-setup syntax
  packages/components/checkbox/src/checkbox.ts
  packages/components/transfer/__tests__/transfer.test.ts
  packages/components/transfer/index.ts
  packages/components/transfer/src/composables/index.ts
  packages/components/transfer/src/composables/use-check.ts
  packages/components/transfer/src/composables/use-checked-change.ts
  packages/components/transfer/src/composables/use-computed-data.ts
  packages/components/transfer/src/composables/use-move.ts
  packages/components/transfer/src/composables/use-props-alias.ts
  packages/components/transfer/src/index.vue
  packages/components/transfer/src/transfer-panel.ts
  packages/components/transfer/src/transfer-panel.vue
  packages/components/transfer/src/transfer.ts
  packages/components/transfer/src/transfer.vue
  packages/components/transfer/src/useCheckedChange.ts
  packages/components/transfer/src/useComputedData.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8468 chore(play): improve import
  play/app.example.vue
  play/main.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8482 chore: use `czg` replace `commitizen`
  package.json
  pnpm-lock.yaml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8205 fix(components): [color-picker] can't select predefine value
  packages/components/color-picker/src/index.vue
Labels: CommitMessage::Qualified

#8476 fix(components): [radio] Divide attrs into label and input
  packages/components/radio/__tests__/radio.test.tsx
  packages/components/radio/src/radio.vue
Labels: CommitMessage::Qualified

#8469 fix(components): [tabs] name is number 0 become a string
  packages/components/tabs/__tests__/tabs.test.ts
  packages/components/tabs/src/tab-nav.tsx
  packages/components/tabs/src/tab-pane.ts
  packages/components/tabs/src/tab-pane.vue
  packages/components/tabs/src/tabs.tsx
Labels: CommitMessage::Qualified

#8534 fix(docs): config-provider example
  docs/components.d.ts
  docs/examples/config-provider/usage.vue
Labels: CommitMessage::Qualified
