Repository element-plus/element-plus, pull requests merged in 2022-07, with the labels that each got.

#8556 fix(components): [radio] fix typo
  packages/components/radio/src/radio.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8582 fix(components): [message] fix z-index & offset
  packages/components/message/src/instance.ts
  packages/components/message/src/method.ts
Labels: hotfix, CommitMessage::Qualified

#8354 fix(theme-chalk): [select] change style when disalbed and selectded
  packages/theme-chalk/src/select-dropdown-v2.scss
  packages/theme-chalk/src/select-dropdown.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8102 fix(components): [TreeSelect] checkbox interaction
  docs/en-US/component/tree-select.md
  docs/examples/tree-select/basic.vue
  docs/examples/tree-select/check-strictly.vue
  docs/examples/tree-select/multiple.vue
  packages/components/tree-select/__tests__/tree-select.test.ts
  packages/components/tree-select/src/tree-select-option.ts
  packages/components/tree-select/src/tree.ts
  packages/components/tree-select/src/utils.ts
Labels: Component::TreeSelect, CommitMessage::Qualified, Needs Review

#8587 fix(components): [input-number] Fix value decimals miss prop precision
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8173 fix(components): add validate-event for form types component
  docs/en-US/component/cascader.md
  docs/en-US/component/checkbox.md
  docs/en-US/component/color-picker.md
  docs/en-US/component/input-number.md
  docs/en-US/component/radio.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/slider.md
  docs/en-US/component/transfer.md
  packages/components/cascader/src/index.vue
  packages/components/checkbox/src/checkbox-group.vue
  packages/components/checkbox/src/checkbox.ts
  packages/components/checkbox/src/checkbox.type.ts
  packages/components/color-picker/src/index.vue
  packages/components/input-number/src/input-number.ts
  packages/components/input-number/src/input-number.vue
  packages/components/radio/src/radio-group.ts
  packages/components/radio/src/radio-group.vue
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/components/slider/src/composables/use-watch.ts
  packages/components/slider/src/slider.ts
  packages/components/transfer/src/transfer.ts
  packages/components/transfer/src/transfer.vue
Labels: CommitMessage::Qualified, Needs Review

#8283 fix(components): [time-picker] Ignore key down if readonly
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, Component::TimePicker, CommitMessage::Qualified, Needs Review

#8590 refactor(components): [tabs] add deprecated to activeName
  packages/components/tabs/src/tabs.tsx
Labels: CommitMessage::Qualified

#8568 fix(components): [date-picker] fix type of year disabled failure
  packages/components/date-picker/src/date-picker-com/basic-year-table.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8591 fix(components): [autocomplete] error message
  packages/components/autocomplete/src/autocomplete.vue
Labels: CommitMessage::Qualified

#8325 fix(components): [dialog] remove not used style props
  packages/components/dialog/src/dialog.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8500 docs(components): update el-input docs
  docs/en-US/component/input.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8598 fix(components): [dialog] make modelValue be an optional property
  packages/components/dialog/src/dialog.ts
Labels: CommitMessage::Qualified

#8259 refactor(components): [steps] use JSX in Unit test
  packages/components/steps/__tests__/steps.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8596 feat(components): [autocomplete] fit input width
  docs/en-US/component/autocomplete.md
  packages/components/autocomplete/__tests__/autocomplete.test.tsx
  packages/components/autocomplete/src/autocomplete.ts
  packages/components/autocomplete/src/autocomplete.vue
Labels: CommitMessage::Qualified

#8602 fix(components): [dropdown] fix visible-change event delay trigger #8601
  packages/components/dropdown/src/dropdown.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8522 fix(components): [table] table-column expand nested table wrong style
  docs/examples/table/expandable-row.vue
  packages/theme-chalk/src/table.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8471 docs(components): [transfer] improve and complete examples
  docs/en-US/component/transfer.md
  docs/examples/transfer/basic.vue
  docs/examples/transfer/customizable.vue
  docs/examples/transfer/filterable.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8561 feat(components): [slider] placement
  docs/en-US/component/slider.md
  docs/examples/slider/placement.vue
  packages/components/slider/__tests__/slider.test.tsx
  packages/components/slider/src/button.ts
  packages/components/slider/src/button.vue
  packages/components/slider/src/slider.ts
  packages/components/slider/src/slider.vue
Labels: CommitMessage::Qualified

#8631 docs: adjust the navigation bar style
  docs/.vitepress/vitepress/styles/css-vars.scss
  docs/.vitepress/vitepress/styles/navbar.scss
Labels: CommitMessage::Qualified

#8627 fix(components): [steps] fix type error
  packages/components/steps/src/item.vue
Labels: CommitMessage::Qualified

#8662 chore: update readme
  README.md
  docs/.vitepress/config/sponsors.ts
Labels: CommitMessage::Qualified

#8650 docs(components): [form] add scroll-to-error attribute
  docs/en-US/component/form.md
Labels: CommitMessage::Qualified

#8677 revert(components): [radio] revert input id
  packages/components/radio/__tests__/radio.test.tsx
  packages/components/radio/src/radio.vue
Labels: CommitMessage::Qualified

#8655 fix(components): [dropdown] fix A11y when tooltip show
  packages/components/dropdown/src/dropdown.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8654 docs: use el-scrollbar
  docs/.vitepress/vitepress/components/vp-app.vue
  docs/.vitepress/vitepress/components/vp-sidebar.vue
  docs/.vitepress/vitepress/styles/base.scss
Labels: CommitMessage::Qualified

#8538 fix(components): [select-v2] add null check to filter method (#8537)
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8705 fix(components): [select] change disabled color
  packages/theme-chalk/src/select-dropdown-v2.scss
  packages/theme-chalk/src/select-dropdown.scss
Labels: CommitMessage::Qualified

#8603 perf(components): [slider] emit UPDATE_MODEL_EVENT only if the value changes
  packages/components/slider/src/composables/use-slider-button.ts
Labels: CommitMessage::Qualified

#8725 docs: sidebar link anchor invalid
  docs/.vitepress/vitepress/components/doc-content/vp-table-of-content.vue
  docs/.vitepress/vitepress/composables/active-bar.ts
Labels: CommitMessage::Qualified

#8726 fix(hooks): [use-form-item] fix type error
  packages/hooks/__tests__/use-form-item.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8727 fix(hooks): [use-floating] fix type error
  packages/hooks/__tests__/use-floating.test.tsx
  packages/hooks/use-floating/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8706 fix(components): [step] className should be is-icon when using icon slot
  packages/components/steps/src/item.vue
Labels: CommitMessage::Qualified

#8731 fix(components): [input] fix type error
  packages/components/input/__tests__/input.test.tsx
Labels: CommitMessage::Qualified

#8734 fix(theme-chalk): [slider] style error when vertical
  packages/theme-chalk/src/slider.scss
Labels: CommitMessage::Qualified

#8737 fix(components): [slider] not changed marker style
  packages/components/slider/__tests__/slider.test.tsx
  packages/components/slider/src/marker.ts
Labels: CommitMessage::Qualified

#8558 fix(hooks): [use-attrs] fix type error
  packages/hooks/__tests__/use-attrs.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8398 fix(components): [select] automatic-dropdown next focus toggleMenu invalid
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#8270 refactor(components): [dialog] use JSX in Unit test
  packages/components/dialog/__tests__/dialog.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8738 docs(components): [TreeSelect] default value is reversed
  docs/en-US/component/tree-select.md
Labels: CommitMessage::Qualified, Needs Review

#8690 refactor(components): [el-table] using flex to refactor table
  packages/components/scrollbar/src/scrollbar.vue
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/table-layout.ts
  packages/components/table/src/table.vue
  packages/components/table/src/table/style-helper.ts
  packages/components/table/src/util.ts
  packages/theme-chalk/src/table.scss
Labels: CommitMessage::Qualified

#8719 fix(components): [cascader] fix namespace
  packages/components/cascader/src/index.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8733 fix(hooks): [use-locale] fix type error
  packages/hooks/__tests__/use-locale.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8681 fix(components): [tree] allow and node drop-type
  packages/components/tree/src/model/useDragNode.ts
  packages/components/tree/src/tree.type.ts
Labels: CommitMessage::Qualified

#8643 fix(components): [form-item] clearValidate invalid
  packages/components/form/src/form-item.vue
Labels: CommitMessage::Qualified

#8778 refactor(components): [container] use JSX in Unit test
  packages/components/container/__tests__/container.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8785 refactor(directives): [repeat-click] use JSX in Unit test
  packages/directives/__tests__/repeat-click.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8269 refactor(components): [pagination] use JSX in Unit test
  packages/components/pagination/__tests__/pagination.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8339 refactor(components): [timeline] use JSX in Unit test
  packages/components/timeline/__tests__/timeline.test.ts
  packages/components/timeline/__tests__/timeline.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8722 refactor(components): [color-picker] use useNamespace
  packages/components/color-picker/src/components/alpha-slider.vue
  packages/components/color-picker/src/components/hue-slider.vue
  packages/components/color-picker/src/components/predefine.vue
  packages/components/color-picker/src/components/sv-panel.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8768 fix(components): [select] fix select tooltip zIndex
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8829 fix(components): [timeline] fix type error
  packages/components/timeline/__tests__/timeline.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8730 fix(components): [message] set appentTo value
  packages/components/message/src/method.ts
Labels: CommitMessage::Qualified

#8782 fix(directives): [click-outside] fix type error
  packages/directives/click-outside/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8783 refactor(directives): [click-outside] use JSX in Unit test
  packages/directives/__tests__/click-outside.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8818 refactor(directives): [trap-focus] refactor
  packages/directives/__tests__/trap-focus.test.ts
  packages/directives/trap-focus/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8839 fix(locale): update ko translation
  packages/locale/lang/ko.ts
Labels: CommitMessage::Qualified

#8600 fix(components): [tabs] disabled pane can still be focused
  packages/components/tabs/__tests__/tabs.test.ts
  packages/components/tabs/src/tab-nav.tsx
  packages/theme-chalk/src/tabs.scss
Labels: CommitMessage::Qualified

#8780 fix(test-utils): fix type error
  packages/test-utils/make-mount.ts
  packages/test-utils/mock.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8836 docs: search bg opacity
  docs/.vitepress/vitepress/components/navbar/vp-search.vue
  docs/.vitepress/vitepress/styles/css-vars.scss
Labels: CommitMessage::Qualified

#8835 fix(components): [virtual-list] throw non-corresponding error message
  packages/components/virtual-list/src/components/dynamic-size-grid.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8819 refactor(directives): [trap-focus] use JSX in Unit test
  packages/directives/__tests__/trap-focus.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8844 fix(components): [table] spanMethod check return type
  packages/components/table/src/table/defaults.ts
Labels: CommitMessage::Qualified

#8762 feat(components): [tooltip] adjust controlled mode
  docs/en-US/component/popover.md
  docs/en-US/component/tooltip.md
  docs/examples/popover/basic-usage.vue
  docs/examples/tooltip/controlled.vue
  packages/components/popover/__tests__/popover.test.ts
  packages/components/popover/src/popover.ts
  packages/components/popover/src/popover.vue
  packages/components/time-picker/src/common/picker.vue
  packages/components/tooltip/src/tooltip.vue
  packages/hooks/use-model-toggle/index.ts
Labels: CommitMessage::Qualified

#8103 fix(docs): fixed the link icon would be duplicated when switching pages
  docs/.vitepress/vitepress/utils/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8809 fix(components): [message] fix message grouping styles
  packages/components/message/style/css.ts
  packages/components/message/style/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8856 style(message-box): message-box support small screen
  packages/theme-chalk/src/message-box.scss
Labels: CommitMessage::Qualified

#8877 fix(components): [upload] one-way cannot add attachments
  packages/components/upload/src/use-handlers.ts
Labels: CommitMessage::Qualified

#8349 refactor(components): [descriptions] switch to script-setup syntax
  packages/components/descriptions/__tests__/descriptions.test.tsx
  packages/components/descriptions/index.ts
  packages/components/descriptions/src/description.ts
  packages/components/descriptions/src/description.vue
  packages/components/descriptions/src/descriptions-cell.ts
  packages/components/descriptions/src/descriptions-row.ts
  packages/components/descriptions/src/descriptions-row.vue
  packages/components/descriptions/src/index.vue
  packages/components/descriptions/src/token.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8847 fix(docs): fix table v2 filter demo style error
  docs/examples/table-v2/filter.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8896 fix(components): [rate] fix type error
  packages/components/rate/src/rate.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8589 fix: [select] label can be displayed correctly after selecting operation
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/option.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8898 fix(components): [dialog] fix type error
  packages/components/dialog/src/use-dialog.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8588 fix(components): [date-picker] prevent duplicate pick date
  packages/components/date-picker/src/date-picker-com/basic-date-table.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8621 perf(components): [table] improve find the closest ancestor
  packages/components/table/src/table-header/event-helper.ts
  packages/components/table/src/util.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8828 fix(directives): [repeat-click] click handler is fired correctly
  packages/directives/__tests__/repeat-click.test.tsx
  packages/directives/repeat-click/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8616 fix(components): [menu] resize when dynamic data in horizontal mode
  packages/components/menu/__tests__/menu.test.ts
  packages/components/menu/src/menu.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8784 refactor(directives): [repeat-click] use `addEventListener`
  packages/directives/repeat-click/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8617 refactor(directives): drop resize
  packages/directives/index.ts
  packages/directives/resize/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8957 style(message): message support small screen
  docs/components.d.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/message.scss
Labels: CommitMessage::Qualified

#8942 docs(components): [menu] supplement some content
  docs/en-US/component/menu.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8930 docs(components): [datetime-picker] event parameters
  docs/en-US/component/datetime-picker.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8974 docs: update vue link
  docs/en-US/guide/installation.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8986 fix(theme-chalk): [table-v2] long text does not wrap
  packages/theme-chalk/src/table-v2.scss
Labels: CommitMessage::Qualified

#8937 fix(components): [checkbox] fix type error
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/checkbox/src/checkbox-group.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8998 fix(components): [select] sync the tooltip component change
  packages/components/select/src/select.vue
Labels: CommitMessage::Qualified

#9018 fix(build): add target when minify build
  internal/build/src/tasks/full-bundle.ts
Labels: CommitMessage::Qualified

#9027 fix(components): [el-menu] horizontal mode menu drag causes browser crash
  packages/components/menu/src/menu.ts
Labels: CommitMessage::Qualified

#9022 fix(components): [carousel] computed interval prop
  packages/components/carousel/src/carousel.vue
Labels: CommitMessage::Qualified

#9019 fix(components): [tooltip] related components are controlled
  packages/components/cascader/src/index.vue
  packages/components/color-picker/src/index.vue
  packages/components/select-v2/src/select.vue
  packages/components/slider/src/button.vue
  packages/components/table/src/filter-panel.vue
Labels: CommitMessage::Qualified

#8961 fix(components): [time-picker] fix clear for range mode
  packages/components/time-picker/__tests__/time-picker.test.ts
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8920 feat(components): [image] Add show event to img component
  packages/components/image/src/image.ts
  packages/components/image/src/image.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#8711 fix(hooks): [use-lockscreen] fix namespace
  packages/components/virtual-list/src/builders/build-grid.ts
  packages/hooks/use-lockscreen/index.ts
  packages/utils/dom/scroll.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8966 fix(components): [table] `clearFilter` not work
  packages/components/table/src/table.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8879 fix(theme-chalk): [picker] adjust range picker input height
  packages/theme-chalk/src/date-picker/picker.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9034 fix(components): [dropdown] fix style
  packages/components/dropdown/style/css.ts
  packages/components/dropdown/style/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9011 fix(components): [table] fix scrollbar maxHeight doesn't consider footer height
  packages/components/table/src/table/style-helper.ts
Labels: CommitMessage::Qualified

#8960 refactor(utils): drop off/on/once, use EventListener instead
  packages/components/color-picker/src/draggable.ts
  packages/components/dropdown/src/useDropdown.ts
  packages/components/message-box/src/index.vue
  packages/components/roving-focus-group/src/roving-focus-group-impl.vue
  packages/components/tree/src/model/useKeydown.ts
  packages/utils/dom/event.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8880 fix(directives): [mousewheel] fix type error
  package.json
  packages/directives/mousewheel/index.ts
  packages/element-plus/package.json
  pnpm-lock.yaml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8959 fix(theme-chalk): [rate] fix vertical offset
  packages/theme-chalk/src/rate.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9044 fix: [el-time-picker] clicking on prefix does not open the panel
  packages/components/time-picker/src/common/picker.vue
Labels: CommitMessage::Qualified

#9004 fix(components): [slider] disabled slider button can still be focused
  packages/components/slider/src/button.vue
  packages/components/slider/src/composables/use-slider-button.ts
Labels: CommitMessage::Qualified

#8794 fix(components): [cascader] pass forced param to syncMenuState
  packages/components/cascader-panel/src/index.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8318 style(components): [table] prettier format, no code changes
  packages/components/table/src/table/defaults.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9033 refactor(components): [color-picker] use JSX in Unit test
  packages/components/color-picker/__tests__/color-picker.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8060 fix(hooks): [use-escape-keydown] fix memory leak (#8005)
  packages/hooks/use-escape-keydown/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9015 docs: body cancel el-scrollbar
  docs/.vitepress/vitepress/components/doc-content/vp-table-of-content.vue
  docs/.vitepress/vitepress/components/vp-app.vue
  docs/.vitepress/vitepress/composables/active-bar.ts
  docs/.vitepress/vitepress/styles/base.scss
  docs/.vitepress/vitepress/styles/scrollbar.scss
Labels: CommitMessage::Qualified

#9051 chore: Update changelog 2.2.11
  CHANGELOG.en-US.md
Labels: CommitMessage::Qualified

#9049 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/vitepress/components/doc-content/vp-table-of-content.vue
  docs/.vitepress/vitepress/components/vp-app.vue
  docs/.vitepress/vitepress/composables/active-bar.ts
  docs/.vitepress/vitepress/styles/base.scss
  docs/.vitepress/vitepress/styles/scrollbar.scss
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/menu.md
  docs/en-US/guide/installation.md
  internal/build/src/tasks/full-bundle.ts
  package.json
  packages/components/carousel/src/carousel.vue
  packages/components/cascader-panel/src/index.vue
  packages/components/cascader/src/index.vue
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/checkbox/src/checkbox-group.vue
  packages/components/color-picker/__tests__/color-picker.test.tsx
  packages/components/color-picker/src/draggable.ts
  packages/components/color-picker/src/index.vue
  packages/components/dropdown/src/useDropdown.ts
  packages/components/dropdown/style/css.ts
  packages/components/dropdown/style/index.ts
  packages/components/image/src/image.ts
  packages/components/image/src/image.vue
  packages/components/menu/src/menu.ts
  packages/components/message-box/src/index.vue
  packages/components/roving-focus-group/src/roving-focus-group-impl.vue
  packages/components/select-v2/src/select.vue
  packages/components/select/src/select.vue
  packages/components/slider/src/button.vue
  packages/components/slider/src/composables/use-slider-button.ts
  packages/components/table/src/filter-panel.vue
  packages/components/table/src/table.vue
  packages/components/table/src/table/defaults.ts
  packages/components/table/src/table/style-helper.ts
  packages/components/time-picker/__tests__/time-picker.test.ts
  packages/components/time-picker/src/common/picker.vue
  packages/components/tree/src/model/useKeydown.ts
  packages/components/virtual-list/src/builders/build-grid.ts
  packages/directives/mousewheel/index.ts
  packages/element-plus/make-installer.ts
  packages/element-plus/package.json
  packages/hooks/use-escape-keydown/index.ts
  packages/hooks/use-lockscreen/index.ts
  packages/theme-chalk/src/date-picker/picker.scss
  packages/theme-chalk/src/rate.scss
  packages/theme-chalk/src/table-v2.scss
  packages/utils/dom/event.ts
  packages/utils/dom/scroll.ts
  pnpm-lock.yaml
  tsconfig.vitest.json
Labels: 🚀 Ready for takeoff, CommitMessage::Unqualified, Needs Review

#9061 fix(components): [color-picker] element event binding error
  packages/components/color-picker/src/draggable.ts
Labels: CommitMessage::Qualified

#9069 fix(components): [menu] expand active menu item
  packages/components/menu/src/menu.ts
Labels: ready to merge, Contribution::Community, CommitMessage::Qualified

#9064 chore: update readme
  README.md
  docs/.vitepress/config/sponsors.ts
Labels: CommitMessage::Qualified, Needs Review

#9074 fix(theme-chalk): [message] long text support newline
  packages/theme-chalk/src/message.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9080 fix(components): [notification] correct offset value
  packages/components/notification/src/notify.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9085 docs: modify the background color of the navigation bar toggle button
  docs/.vitepress/vitepress/components/navbar/vp-theme-toggler.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9087 style(message): Message support adaptive width
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/message.scss
Labels: CommitMessage::Qualified

#9063 fix(components): [table] header scroll height error
  packages/components/table/src/table/style-helper.ts
Labels: CommitMessage::Qualified

#9083 docs(components): [notification] add `zIndex` attribute
  docs/en-US/component/notification.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#9052 refactor(components): [switch] use JSX in Unit test
  packages/components/switch/__tests__/switch.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8388 fix(components): [carousel] reset the timer
  packages/components/carousel/src/carousel.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8905 fix(hooks): [use-namespace] exclude invalid CSS variables
  packages/hooks/__tests__/use-namespace.test.tsx
  packages/hooks/use-namespace/index.ts
Labels: CommitMessage::Qualified

#8992 fix(components): [space] extract nested fragment children
  packages/components/space/src/space.ts
Labels: CommitMessage::Qualified

#9104 style: vertical menu
  packages/theme-chalk/src/menu.scss
Labels: CommitMessage::Qualified

#9038 docs(components): update el-input slot docs
  docs/en-US/component/input.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9101 refactor(components): [time-select] use JSX in Unit test
  packages/components/time-select/__tests__/time-select.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review
