Repository element-plus/element-plus, pull requests merged in 2022-11, with the labels that each got.

#10340 fix(components): [tree-v2] add missing icon
  packages/components/tree-v2/src/tree-node.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10342 fix(components): [tree-v2] default icon render test
  packages/components/tree-v2/__tests__/tree.test.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10334 docs(components): [button] api complement
  docs/en-US/component/button.md
Labels: CommitMessage::Qualified

#10346 feat(docs): vite-press new component
  docs/.vitepress/vitepress/components/globals/vp-api-typing.vue
  docs/.vitepress/vitepress/index.ts
  docs/components.d.ts
Labels: Project::Documentation, CommitMessage::Qualified

#10349 style(theme-chalk): fix input-number style
  packages/theme-chalk/src/input-number.scss
Labels: CommitMessage::Qualified

#10353 feat(docs): api typing shortcuts
  docs/.vitepress/vitepress/components/globals/vp-api-enum.vue
  docs/.vitepress/vitepress/components/globals/vp-api-function.vue
  docs/.vitepress/vitepress/components/globals/vp-api-typing.vue
  docs/.vitepress/vitepress/index.ts
  docs/components.d.ts
Labels: Project::Documentation, CommitMessage::Qualified

#10345 docs(components): [affix]
  docs/.vitepress/vitepress/components/globals/vp-api-enum.vue
  docs/.vitepress/vitepress/components/globals/vp-api-function.vue
  docs/.vitepress/vitepress/components/globals/vp-api-typing.vue
  docs/en-US/component/affix.md
  packages/components/affix/src/affix.ts
  packages/components/affix/src/affix.vue
Labels: Project::Documentation, CommitMessage::Qualified

#10355 docs(components): [api-typing]
  docs/.vitepress/vitepress/components/globals/vp-api-typing.vue
Labels: CommitMessage::Qualified

#10362 perf(utils): addUnit support string number
  packages/utils/dom/style.ts
  packages/utils/types.ts
Labels: CommitMessage::Qualified

#10356 docs(components): [api-external]
  docs/.vitepress/vitepress/components/globals/vp-api-external.vue
  docs/.vitepress/vitepress/index.ts
  docs/components.d.ts
Labels: CommitMessage::Qualified

#10374 feat(docs): [components] additions
  docs/.vitepress/vitepress/components/globals/vp-api-bool.vue
  docs/.vitepress/vitepress/components/globals/vp-api-number.vue
  docs/.vitepress/vitepress/components/globals/vp-api-primitive.vue
  docs/.vitepress/vitepress/components/globals/vp-api-string.vue
  docs/.vitepress/vitepress/index.ts
  docs/components.d.ts
Labels: Project::Documentation, CommitMessage::Qualified

#10381 style(theme-chalk): fix select style
  packages/theme-chalk/src/select.scss
Labels: CommitMessage::Qualified

#10390 style(theme-chalk): fix input style
  packages/theme-chalk/src/input.scss
Labels: CommitMessage::Qualified

#10392 style(theme-chalk): fix date-picker style
  packages/theme-chalk/src/date-picker/picker.scss
Labels: CommitMessage::Qualified

#10393 chore(play): update unplugin-vue-components
  play/package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#10373 docs(components): [alert]
  docs/en-US/component/alert.md
  packages/components/alert/index.ts
  packages/components/alert/src/alert.ts
  packages/components/alert/src/instance.ts
Labels: Refactor, CommitMessage::Qualified

#10419 chore(build): optimize the conversion of type in documents
  internal/build/package.json
  internal/build/src/tasks/helper.ts
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#10405 docs(components): [autocomplete]
  docs/.vitepress/vitepress/components/globals/vp-api-ref.vue
  docs/.vitepress/vitepress/components/globals/vp-api-typing.vue
  docs/.vitepress/vitepress/index.ts
  docs/.vitepress/vitepress/styles/base.scss
  docs/.vitepress/vitepress/styles/css-vars.scss
  docs/components.d.ts
  docs/en-US/component/autocomplete.md
Labels: CommitMessage::Qualified

#10426 fix(docs): [autocomplete]
  docs/.vitepress/config/plugins.ts
  docs/.vitepress/plugins/api-table.ts
  docs/.vitepress/vitepress/components/globals/vp-api-function.vue
  docs/en-US/component/autocomplete.md
Labels: CommitMessage::Qualified

#10435 docs(build): add a plugin to display the type details
  docs/.vitepress/config/plugins.ts
  docs/.vitepress/plugins/tooltip.ts
  docs/.vitepress/vitepress/components/globals/vp-api-typing.vue
Labels: CommitMessage::Qualified

#10437 chore(build): optimize the type conversion of tooltip plugin in docs
  internal/build/src/tasks/helper.ts
Labels: CommitMessage::Qualified

#10439 fix(components): [cascader] remove extra space in the search text
  packages/components/cascader/src/index.vue
Labels: CommitMessage::Qualified

#10440 refactor(docs): tooltip plugin
  docs/.vitepress/plugins/tooltip.ts
  internal/build/src/tasks/helper.ts
Labels: CommitMessage::Qualified

#10443 fix(docs): [autocomplete] [affix]
  docs/en-US/component/affix.md
  docs/en-US/component/autocomplete.md
Labels: CommitMessage::Qualified

#10221 fix(component): [table] can't select row children
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/util.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10444 chore(docs): [autocomplete] remove extra quotes
  docs/en-US/component/autocomplete.md
Labels: CommitMessage::Qualified

#10460 fix(docs): [alert]
  docs/en-US/component/alert.md
Labels: CommitMessage::Qualified

#10467 fix(docs): [vp-api-typing]
  docs/.vitepress/vitepress/components/globals/vp-api-typing.vue
Labels: CommitMessage::Qualified

#10478 docs(components): [autocomplete]
  docs/en-US/component/autocomplete.md
Labels: CommitMessage::Qualified

#10397 docs(components): [a11y] add tag
  docs/.vitepress/vitepress/components/dev/a11y-tag.vue
  docs/components.d.ts
Labels: CommitMessage::Qualified

#10483 docs(components): [a11y-tag]
  docs/.vitepress/vitepress/components/dev/a11y-tag.vue
  docs/components.d.ts
Labels: CommitMessage::Qualified

#10505 docs(components): [DateTimePicker]
  docs/en-US/component/datetime-picker.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10506 docs(components): [Popconfirm]
  docs/en-US/component/popconfirm.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10507 docs(components): [Virtualized Tree]
  docs/en-US/component/tree-v2.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10508 docs(components): [Transfer]
  docs/en-US/component/transfer.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10510 docs(components): [Skeleton]
  docs/en-US/component/skeleton.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10511 docs(components): [Tree]
  docs/en-US/component/tree.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10512 docs(components): [api-typing] use inline-flex
  docs/.vitepress/vitepress/components/globals/vp-api-typing.vue
Labels: CommitMessage::Qualified

#10503 rename variable
  docs/examples/pagination/more-elements.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10532 fix(components): [dropdown-item] prevent click if disabled
  packages/components/dropdown/src/dropdown-item.vue
Labels: CommitMessage::Qualified

#10531 chore(docs): [table-v2] update column attribute name
  docs/en-US/component/table-v2.md
Labels: CommitMessage::Qualified

#10535 fix(components): [focus-trap] input select text
  packages/components/focus-trap/src/utils.ts
  packages/theme-chalk/src/input.scss
Labels: CommitMessage::Qualified

#10513 docs(components): [input]
  docs/en-US/component/input.md
  packages/components/input/src/input.ts
Labels: CommitMessage::Qualified

#9863 fix(components): [checkbox] wrong checked status when label is Object
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/checkbox/src/composables/use-checkbox-status.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10543 docs(components): [dialog] add faq
  docs/en-US/component/dialog.md
Labels: CommitMessage::Qualified

#10538 fix(components): [cascader] set height correctly
  packages/components/cascader/src/index.vue
Labels: CommitMessage::Qualified

#10568 fix(components): [image-viewer] `hide-on-click-modal` not work
  packages/theme-chalk/src/image-viewer.scss
Labels: CommitMessage::Qualified

#10585 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/vitepress/components/dev/a11y-tag.vue
  docs/.vitepress/vitepress/components/globals/vp-api-typing.vue
  docs/components.d.ts
  docs/en-US/component/alert.md
  docs/en-US/component/autocomplete.md
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/dialog.md
  docs/en-US/component/input.md
  docs/en-US/component/popconfirm.md
  docs/en-US/component/skeleton.md
  docs/en-US/component/table-v2.md
  docs/en-US/component/transfer.md
  docs/en-US/component/tree-v2.md
  docs/en-US/component/tree.md
  docs/examples/pagination/more-elements.vue
  packages/components/calendar/__tests__/calendar.test.tsx
  packages/components/calendar/src/use-calendar.ts
  packages/components/cascader/src/index.vue
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/checkbox/src/composables/use-checkbox-status.ts
  packages/components/dropdown/src/dropdown-item.vue
  packages/components/focus-trap/src/utils.ts
  packages/components/input/src/input.ts
  packages/components/select-v2/src/select.vue
  packages/theme-chalk/src/image-viewer.scss
  packages/theme-chalk/src/input.scss
  packages/theme-chalk/src/select-v2.scss
  packages/theme-chalk/src/select.scss
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#10588 docs(components): [a11y-tag] border-color in light
  docs/.vitepress/vitepress/components/dev/a11y-tag.vue
Labels: CommitMessage::Qualified

#10587 docs: fix error text
  docs/en-US/component/input.md
  packages/components/input/src/input.ts
Labels: CommitMessage::Qualified, Needs Review

#10562 docs(components): tag left spacing
  docs/.vitepress/vitepress/components/dev/DeprecatedTag.vue
  docs/.vitepress/vitepress/components/dev/deprecated-tag.vue
  docs/.vitepress/vitepress/components/dev/version-tag.vue
  docs/components.d.ts
  docs/en-US/component/button.md
  docs/en-US/component/dialog.md
  docs/en-US/component/image.md
  docs/en-US/component/select.md
  docs/en-US/component/table-v2.md
  docs/en-US/component/table.md
  docs/en-US/guide/dark-mode.md
  docs/en-US/guide/namespace.md
Labels: CommitMessage::Qualified

#10563 style(components): [pagination] Refactor pagination style
  packages/components/pagination/src/components/jumper.ts
  packages/components/pagination/src/components/jumper.vue
  packages/components/pagination/src/components/pager.vue
  packages/components/pagination/src/pagination.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/pagination.scss
Labels: CommitMessage::Qualified

#10575 fix(components): [select-v2] case-insensitive when filterable
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10589 docs(components): [input] edit events header name
  docs/en-US/component/input.md
Labels: CommitMessage::Qualified

#10564 docs(components): [scrollbar]
  docs/en-US/component/scrollbar.md
  packages/components/scrollbar/src/scrollbar.ts
  packages/components/scrollbar/src/scrollbar.vue
  packages/components/table/src/table-layout.ts
  packages/components/table/src/table/style-helper.ts
Labels: CommitMessage::Qualified

#10593 docs(components): [input][scrollbar]
  docs/en-US/component/input.md
  docs/en-US/component/scrollbar.md
Labels: CommitMessage::Qualified

#10594 docs(components): [button]
  docs/en-US/component/button.md
  packages/components/button/src/button-group.ts
  packages/components/button/src/button.ts
Labels: CommitMessage::Qualified

#10596 docs(components): [scrollbar] note warpRef
  docs/en-US/component/scrollbar.md
Labels: CommitMessage::Qualified

#10597 docs(components): [scrollbar] exposes header name
  docs/en-US/component/scrollbar.md
Labels: CommitMessage::Qualified

#10603 chore: update i18n dayjs
  docs/en-US/guide/i18n.md
Labels: CommitMessage::Qualified, Needs Review

#10618 docs(components): [scrollbar] add wrapRef
  docs/en-US/component/scrollbar.md
Labels: CommitMessage::Qualified

#10641 chore: update gen script
  scripts/gc.sh
Labels: CommitMessage::Qualified

#10628 docs(components): [button] add api prefix
  docs/en-US/component/button.md
Labels: CommitMessage::Qualified

#10650 chore: update input doc
  docs/en-US/component/input.md
Labels: CommitMessage::Qualified

#10649 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/vitepress/components/dev/DeprecatedTag.vue
  docs/.vitepress/vitepress/components/dev/a11y-tag.vue
  docs/.vitepress/vitepress/components/dev/deprecated-tag.vue
  docs/.vitepress/vitepress/components/dev/version-tag.vue
  docs/components.d.ts
  docs/en-US/component/button.md
  docs/en-US/component/dialog.md
  docs/en-US/component/image.md
  docs/en-US/component/input.md
  docs/en-US/component/scrollbar.md
  docs/en-US/component/select.md
  docs/en-US/component/table-v2.md
  docs/en-US/component/table.md
  docs/en-US/guide/dark-mode.md
  docs/en-US/guide/i18n.md
  docs/en-US/guide/namespace.md
  packages/components/button/src/button-group.ts
  packages/components/button/src/button.ts
  packages/components/input/src/input.ts
  packages/components/pagination/src/components/jumper.ts
  packages/components/pagination/src/components/jumper.vue
  packages/components/pagination/src/components/pager.vue
  packages/components/pagination/src/pagination.ts
  packages/components/scrollbar/src/scrollbar.ts
  packages/components/scrollbar/src/scrollbar.vue
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/useSelect.ts
  packages/components/table/src/table-layout.ts
  packages/components/table/src/table/style-helper.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/pagination.scss
  scripts/gc.sh
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#10663 fix(components): [upload] use useDisabled
  packages/components/upload/src/upload-content.vue
  packages/components/upload/src/upload-dragger.vue
  packages/components/upload/src/upload-list.vue
Labels: CommitMessage::Qualified

#10669 fix(components): [cascader] collapse tags tooltip style
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/src/index.vue
  packages/theme-chalk/src/cascader.scss
Labels: CommitMessage::Qualified

#10480 fix(components): [menu] menus that are not in the expanded path do not open
  packages/components/menu/__tests__/menu.test.ts
  packages/components/menu/src/menu.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10674 fix(components): [input] prefix and suffix add click focus event
  packages/components/input/src/input.vue
Labels: CommitMessage::Qualified

#10666 fix(components): [pagination] Nesting causes missing styles
  packages/theme-chalk/src/pagination.scss
Labels: CommitMessage::Qualified

#10633 docs(components): [tree] fix import error type
  docs/examples/tree/draggable.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10677 fix(components): [table] optimizate types export
  packages/components/table/index.ts
  packages/components/table/src/table/defaults.ts
Labels: CommitMessage::Qualified

#10541 fix(components): [tooltip] SSR hydration error caused by random ID
  packages/components/autocomplete/__tests__/autocomplete.test.tsx
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/dropdown/__tests__/dropdown.test.ts
  packages/components/popconfirm/__tests__/popconfirm.test.tsx
  packages/components/popover/__tests__/popover.test.tsx
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select/__tests__/select.test.ts
  packages/components/tooltip/src/content.ts
  packages/components/tooltip/src/content.vue
  packages/hooks/__tests__/use-id.test.tsx
  packages/hooks/__tests__/use-popper-container.test.tsx
  packages/hooks/use-id/index.ts
  packages/hooks/use-popper-container/index.ts
Labels: CommitMessage::Qualified

#10692 style(theme-chalk): [Pagination] Fix pagination style
  packages/theme-chalk/src/pagination.scss
Labels: CommitMessage::Qualified

#10683 docs(components): [link]
  docs/en-US/component/link.md
  packages/components/link/src/link.ts
  packages/components/link/src/link.vue
Labels: CommitMessage::Qualified

#10681 docs(components): [icon]
  docs/en-US/component/icon.md
  packages/components/icon/src/icon.ts
Labels: CommitMessage::Qualified

#10329 fix(components): [input-number] Input actions can update values
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10680 docs(components): [container]
  docs/en-US/component/container.md
  packages/components/container/src/aside.vue
  packages/components/container/src/container.vue
  packages/components/container/src/footer.vue
  packages/components/container/src/header.vue
Labels: CommitMessage::Qualified

#10682 docs(components): [layout]
  docs/en-US/component/layout.md
  packages/components/col/src/col.ts
  packages/components/col/src/col.vue
  packages/components/row/src/row.ts
  packages/components/row/src/row.vue
Labels: CommitMessage::Qualified

#10685 docs(components): [space]
  docs/en-US/component/space.md
  packages/components/space/src/space.ts
Labels: CommitMessage::Qualified

#9943 fix(components): [table] fix expand icon center
  packages/theme-chalk/src/table.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10719 fix(components): [page-header] display if breadcrumb slot exists
  packages/components/page-header/src/page-header.vue
Labels: CommitMessage::Qualified

#10745 fix: add drawer deprecated custom-class warning
  packages/components/drawer/src/drawer.vue
Labels: CommitMessage::Qualified

#10744 docs: update drawer doc deprecated custom-class
  docs/en-US/component/drawer.md
Labels: CommitMessage::Qualified

#10709 docs(components): [avatar]
  docs/en-US/component/avatar.md
  packages/components/avatar/index.ts
  packages/components/avatar/src/avatar.ts
  packages/components/avatar/src/instance.ts
Labels: CommitMessage::Qualified

#10753 docs(components): [rate] fix typo
  docs/en-US/component/rate.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10757 D2M
  CHANGELOG.en-US.md
  docs/en-US/component/avatar.md
  docs/en-US/component/container.md
  docs/en-US/component/drawer.md
  docs/en-US/component/icon.md
  docs/en-US/component/layout.md
  docs/en-US/component/link.md
  docs/en-US/component/rate.md
  docs/en-US/component/space.md
  docs/examples/tree/draggable.vue
  packages/components/autocomplete/__tests__/autocomplete.test.tsx
  packages/components/avatar/index.ts
  packages/components/avatar/src/avatar.ts
  packages/components/avatar/src/instance.ts
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/src/index.vue
  packages/components/col/src/col.ts
  packages/components/col/src/col.vue
  packages/components/container/src/aside.vue
  packages/components/container/src/container.vue
  packages/components/container/src/footer.vue
  packages/components/container/src/header.vue
  packages/components/drawer/src/drawer.vue
  packages/components/dropdown/__tests__/dropdown.test.ts
  packages/components/icon/src/icon.ts
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
  packages/components/input/src/input.vue
  packages/components/link/src/link.ts
  packages/components/link/src/link.vue
  packages/components/menu/__tests__/menu.test.ts
  packages/components/menu/src/menu.ts
  packages/components/page-header/src/page-header.vue
  packages/components/popconfirm/__tests__/popconfirm.test.tsx
  packages/components/popover/__tests__/popover.test.tsx
  packages/components/row/src/row.ts
  packages/components/row/src/row.vue
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select/__tests__/select.test.ts
  packages/components/space/src/space.ts
  packages/components/table/index.ts
  packages/components/table/src/table/defaults.ts
  packages/components/tooltip/src/content.ts
  packages/components/tooltip/src/content.vue
  packages/components/upload/src/upload-content.vue
  packages/components/upload/src/upload-dragger.vue
  packages/components/upload/src/upload-list.vue
  packages/hooks/__tests__/use-id.test.tsx
  packages/hooks/__tests__/use-popper-container.test.tsx
  packages/hooks/use-id/index.ts
  packages/hooks/use-popper-container/index.ts
  packages/theme-chalk/src/cascader.scss
  packages/theme-chalk/src/pagination.scss
  packages/theme-chalk/src/table.scss
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#10769 Revert "fix(components): [menu] menus that are not in the expanded path do not open"
  packages/components/menu/__tests__/menu.test.ts
  packages/components/menu/src/menu.ts
Labels: CommitMessage::Qualified

#10772 chore: update doc
  README.md
Labels: CommitMessage::Qualified

#10770 D2M
  CHANGELOG.en-US.md
  README.md
  packages/components/menu/__tests__/menu.test.ts
  packages/components/menu/src/menu.ts
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#10773 revert: "fix(components): [table] fix expand icon center (#9943)"
  packages/theme-chalk/src/table.scss
Labels: CommitMessage::Qualified

#10774 fix(components): [popconfirm] import missing button style
  packages/components/popconfirm/style/css.ts
  packages/components/popconfirm/style/index.ts
Labels: CommitMessage::Qualified

#10775 D2M
  CHANGELOG.en-US.md
  packages/components/popconfirm/style/css.ts
  packages/components/popconfirm/style/index.ts
  packages/theme-chalk/src/table.scss
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#10713 fix(components): [table] fix error in dynamic change table-column
  packages/components/table/src/store/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10777 docs(components): [table] better types introduced
  docs/examples/table/filter.vue
  docs/examples/table/rowspan-and-colspan.vue
  docs/examples/table/sort.vue
  docs/examples/table/summary.vue
Labels: CommitMessage::Qualified

#10778 docs(components): [table] treeLazy better presentation
  docs/examples/table/tree-and-lazy.vue
Labels: CommitMessage::Qualified

#10779 docs(components): [autocomplete] better presentation
  docs/examples/autocomplete/autocomplete.vue
Labels: CommitMessage::Qualified

#10780 docs(components): [cascader] better presentation
  docs/examples/cascader/any-level.vue
  docs/examples/cascader/basic.vue
  docs/examples/cascader/filterable.vue
  docs/examples/cascader/multiple-selection.vue
Labels: CommitMessage::Qualified

#10781 docs(components): [date-picker] better presentation
  docs/examples/date-picker/date-range.vue
  docs/examples/date-picker/enter-date.vue
Labels: CommitMessage::Qualified

#10782 docs(components): [select] better presentation
  docs/examples/select/multiple.vue
  docs/examples/select/remote-search.vue
Labels: CommitMessage::Qualified

#10783 docs(components): [switch] support add multiple content example
  docs/examples/switch/text-description.vue
Labels: CommitMessage::Qualified

#10784 docs(components): [popover] better presentation
  docs/examples/popover/basic-usage.vue
Labels: CommitMessage::Qualified

#10786 chore: move the types entry point to the very beginning
  packages/element-plus/package.json
Labels: CommitMessage::Qualified

#10737 fix(components): [date-picker] default-time affects now result(#10729)
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10787 fix(components): [input-number] Fix decrease and increase disabled
  packages/components/input-number/src/input-number.vue
Labels: CommitMessage::Qualified

#10759 fix(components): [select-v2] initial value compatibility
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/select.vue
Labels: CommitMessage::Qualified

#10789 docs(components): [badge] enhancement
  docs/en-US/component/badge.md
  packages/components/badge/index.ts
  packages/components/badge/src/badge.ts
  packages/components/badge/src/instance.ts
Labels: Project::Documentation, CommitMessage::Qualified

#10788 docs(components): [backtop]
  docs/en-US/component/backtop.md
  packages/components/backtop/src/backtop.ts
Labels: CommitMessage::Qualified

#10812 fix(components): [tree] revert inherits the label class
  packages/components/tree/src/tree-node-content.vue
  packages/theme-chalk/src/tree.scss
Labels: CommitMessage::Qualified

#10716 fix(components): [TreeSelect] incorrect label when child not rendered
  docs/en-US/component/tree-select.md
  docs/examples/tree-select/lazy.vue
  packages/components/tree-select/__tests__/tree-select.test.tsx
  packages/components/tree-select/src/cache-options.ts
  packages/components/tree-select/src/tree-select.vue
  packages/components/tree-select/src/tree.ts
  packages/components/tree-select/src/utils.ts
Labels: CommitMessage::Qualified, Needs Review
