Repository element-plus/element-plus, pull requests merged in 2022-12, with the labels that each got.

#10828 fix(theme-chalk): [menu] optimize the SubMenu title style
  packages/theme-chalk/src/menu.scss
Labels: CommitMessage::Qualified

#10816 fix(components): [table]fix the problem that show-overflow-tooltip will also be displayed when the browser is zoomed
  packages/components/table/src/table-body/events-helper.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10867 feat(components): [menu] add `popper-effect` menu attribute
  packages/components/menu/src/menu-item.vue
  packages/components/menu/src/menu.ts
Labels: CommitMessage::Qualified

#10868 docs: [menu] add `popper-effect` attribute
  docs/en-US/component/menu.md
Labels: CommitMessage::Qualified

#10869 style(theme-chalk): fix carousel button style
  packages/theme-chalk/src/carousel.scss
Labels: CommitMessage::Qualified

#10870 D2M
  CHANGELOG.en-US.md
  docs/en-US/component/backtop.md
  docs/en-US/component/badge.md
  docs/en-US/component/menu.md
  docs/en-US/component/tree-select.md
  docs/examples/autocomplete/autocomplete.vue
  docs/examples/cascader/any-level.vue
  docs/examples/cascader/basic.vue
  docs/examples/cascader/filterable.vue
  docs/examples/cascader/multiple-selection.vue
  docs/examples/date-picker/date-range.vue
  docs/examples/date-picker/enter-date.vue
  docs/examples/popover/basic-usage.vue
  docs/examples/select/multiple.vue
  docs/examples/select/remote-search.vue
  docs/examples/switch/text-description.vue
  docs/examples/table/filter.vue
  docs/examples/table/rowspan-and-colspan.vue
  docs/examples/table/sort.vue
  docs/examples/table/summary.vue
  docs/examples/table/tree-and-lazy.vue
  docs/examples/tree-select/lazy.vue
  packages/components/backtop/src/backtop.ts
  packages/components/badge/index.ts
  packages/components/badge/src/badge.ts
  packages/components/badge/src/instance.ts
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/input-number/src/input-number.vue
  packages/components/menu/src/menu-item.vue
  packages/components/menu/src/menu.ts
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/select.vue
  packages/components/table/src/store/index.ts
  packages/components/table/src/table-body/events-helper.ts
  packages/components/tree-select/__tests__/tree-select.test.tsx
  packages/components/tree-select/src/cache-options.ts
  packages/components/tree-select/src/tree-select.vue
  packages/components/tree-select/src/tree.ts
  packages/components/tree-select/src/utils.ts
  packages/components/tree/src/tree-node-content.vue
  packages/element-plus/package.json
  packages/theme-chalk/src/carousel.scss
  packages/theme-chalk/src/menu.scss
  packages/theme-chalk/src/tree.scss
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#10875 docs(components): [popconfirm] better presentation
  docs/examples/popconfirm/customize.vue
Labels: CommitMessage::Qualified

#10876 docs(components): [button]
  docs/en-US/component/button.md
Labels: CommitMessage::Qualified

#10877 docs(components): [container]
  docs/en-US/component/container.md
Labels: CommitMessage::Qualified

#10878 docs(components): [layout]
  docs/en-US/component/layout.md
Labels: CommitMessage::Qualified

#10879 docs(components): [link]
  docs/en-US/component/link.md
Labels: CommitMessage::Qualified

#10880 docs(components): [space]
  docs/en-US/component/space.md
Labels: CommitMessage::Qualified

#10796 fix(components): [notification] option zIndex for notification can't effect
  packages/components/notification/src/notify.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10891 docs(components): [button/input/scrollbar/autocomplete] object
  docs/en-US/component/autocomplete.md
  docs/en-US/component/button.md
  docs/en-US/component/input.md
  docs/en-US/component/scrollbar.md
Labels: CommitMessage::Qualified

#10885 fix(components): [tree-select] props `cacheData` not reactive
  packages/components/tree-select/__tests__/tree-select.test.tsx
  packages/components/tree-select/src/cache-options.ts
Labels: CommitMessage::Qualified

#10912 docs(components): [form] improves doc readability
  docs/examples/form/validation.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10894 docs(components): [pagination] format the Type value
  docs/en-US/component/pagination.md
  packages/components/pagination/src/pagination.ts
Labels: CommitMessage::Qualified

#10888 docs(components): [checkbox]
  docs/en-US/component/checkbox.md
  packages/components/checkbox/src/checkbox-button.vue
  packages/components/checkbox/src/checkbox-group.ts
  packages/components/checkbox/src/checkbox-group.vue
  packages/components/checkbox/src/checkbox.ts
  packages/components/checkbox/src/checkbox.vue
Labels: CommitMessage::Qualified

#10606 fix(components): [focus-trap] input selection
  packages/components/date-picker/src/date-picker-com/basic-date-table.vue
  packages/components/focus-trap/src/focus-trap.vue
  packages/components/focus-trap/src/utils.ts
  packages/theme-chalk/src/cascader.scss
  packages/theme-chalk/src/date-picker/picker.scss
  packages/theme-chalk/src/select.scss
Labels: CommitMessage::Qualified

#10930 feat(components): el-image support set zoom-rate
  docs/en-US/component/image.md
  docs/examples/image/image-preview.vue
  packages/components/image-viewer/src/image-viewer.ts
  packages/components/image-viewer/src/image-viewer.vue
  packages/components/image/src/image.ts
  packages/components/image/src/image.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10956 docs(components): [Image] format doc
  docs/en-US/component/image.md
Labels: CommitMessage::Qualified

#10961 docs(components): [cascader] fix type error
  docs/examples/cascader/basic.vue
  docs/examples/cascader/dynamic-loading.vue
Labels: CommitMessage::Qualified

#10960 fix(theme-chalk): [menu] arrow position error in popup
  packages/theme-chalk/src/menu.scss
Labels: CommitMessage::Qualified

#10914 Update i18n.md
  docs/en-US/guide/i18n.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10913 Add Kurdish language (Sorani - ckb)
  packages/locale/lang/ckb.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10881 docs(components): [config-provider]
  docs/en-US/component/config-provider.md
  packages/components/config-provider/src/config-provider.ts
Labels: CommitMessage::Qualified

#10813 style(theme-chalk): [Menu] Fix menu style
  packages/theme-chalk/src/menu.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10958 fix(theme-chalk): [menu] the popup style error
  packages/theme-chalk/src/menu.scss
Labels: CommitMessage::Qualified

#10971 refactor(components): [transfer] remove useless code
  packages/components/transfer/src/transfer-panel.ts
  packages/components/transfer/src/transfer-panel.vue
Labels: CommitMessage::Qualified

#10962 docs(components): [breadcrumb]
  docs/en-US/component/breadcrumb.md
  packages/components/breadcrumb/index.ts
  packages/components/breadcrumb/src/breadcrumb-item.ts
  packages/components/breadcrumb/src/breadcrumb.ts
  packages/components/breadcrumb/src/instances.ts
Labels: CommitMessage::Qualified

#10978 docs(components): [card]
  docs/en-US/component/card.md
  packages/components/card/index.ts
  packages/components/card/src/card.ts
  packages/components/card/src/instance.ts
Labels: CommitMessage::Qualified

#10991 perf(components): [tabs] update test case
  packages/components/tabs/__tests__/tabs.test.tsx
Labels: CommitMessage::Qualified

#10982 docs(ssr): component ssr/ssg usage tips
  docs/en-US/component/autocomplete.md
  docs/en-US/component/cascader.md
  docs/en-US/component/color-picker.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/dialog.md
  docs/en-US/component/drawer.md
  docs/en-US/component/dropdown.md
  docs/en-US/component/menu.md
  docs/en-US/component/popconfirm.md
  docs/en-US/component/popover.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/slider.md
  docs/en-US/component/table-v2.md
  docs/en-US/component/table.md
  docs/en-US/component/time-picker.md
  docs/en-US/component/time-select.md
  docs/en-US/component/tooltip-v2.md
  docs/en-US/component/tooltip.md
  docs/en-US/component/tree-select.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10989 fix(components): [tabs] correct active bar position
  packages/components/tabs/src/tab-bar.vue
Labels: CommitMessage::Qualified

#10980 fix(components): input-number 0 can not triger change event
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
Labels: CommitMessage::Qualified

#11006 docs: remove statistic
  docs/.vitepress/crowdin/en-US/pages/component.json
Labels: CommitMessage::Qualified

#10983 feat(hooks): [use-popper]
  packages/hooks/__tests__/use-popper.test.tsx
  packages/hooks/index.ts
  packages/hooks/use-popper/index.ts
Labels: CommitMessage::Qualified

#11020 fix(components): [input-number] fix args order
  packages/components/input-number/src/input-number.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11013 refactor(components): [cascader] use script-setup syntax
  packages/components/cascader-panel/src/config.ts
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/index.ts
  packages/components/cascader/src/cascader.ts
  packages/components/cascader/src/cascader.vue
  packages/components/cascader/src/index.vue
  packages/components/cascader/src/instances.ts
Labels: CommitMessage::Qualified

#11031 fix(components): [cascader] placeholder is not displayed correctly
  packages/components/cascader/src/cascader.vue
Labels: CommitMessage::Qualified

#10984 feat(components): [table] overflow tooltip supports `enterable` and customization
  docs/en-US/component/table.md
  packages/components/table/__tests__/table-column.test.ts
  packages/components/table/src/table-body/defaults.ts
  packages/components/table/src/table-body/events-helper.ts
  packages/components/table/src/table-body/render-helper.ts
  packages/components/table/src/table-column/defaults.ts
  packages/components/table/src/table-column/index.ts
  packages/components/table/src/table.vue
  packages/components/table/src/table/defaults.ts
  packages/components/table/src/util.ts
Labels: CommitMessage::Qualified

#11057 docs(components): [upload] onExceed
  docs/en-US/component/upload.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11072 fix(docs): some wrong examples in the document
  docs/en-US/component/drawer.md
  docs/examples/drawer/basic-usage.vue
  docs/examples/drawer/customization-content.vue
  docs/examples/tree/draggable.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11100 fix(element-plus): exposing ElSubMenu component
  packages/element-plus/component.ts
Labels: CommitMessage::Qualified

#11109 D2M
  CHANGELOG.en-US.md
  docs/en-US/component/drawer.md
  docs/en-US/component/table.md
  docs/en-US/component/upload.md
  docs/examples/drawer/basic-usage.vue
  docs/examples/drawer/customization-content.vue
  docs/examples/tree/draggable.vue
  packages/components/cascader-panel/src/config.ts
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/index.ts
  packages/components/cascader/src/cascader.ts
  packages/components/cascader/src/cascader.vue
  packages/components/cascader/src/index.vue
  packages/components/cascader/src/instances.ts
  packages/components/input-number/src/input-number.ts
  packages/components/table/__tests__/table-column.test.ts
  packages/components/table/src/table-body/defaults.ts
  packages/components/table/src/table-body/events-helper.ts
  packages/components/table/src/table-body/render-helper.ts
  packages/components/table/src/table-column/defaults.ts
  packages/components/table/src/table-column/index.ts
  packages/components/table/src/table.vue
  packages/components/table/src/table/defaults.ts
  packages/components/table/src/util.ts
  packages/element-plus/component.ts
  packages/hooks/__tests__/use-popper.test.tsx
  packages/hooks/index.ts
  packages/hooks/use-popper/index.ts
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review
