Repository element-plus/element-plus, pull requests merged in 2023-12, with the labels that each got.

#14711 docs(components): [slider] use new display tag
  docs/en-US/component/slider.md
  packages/components/slider/src/slider.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14963 docs(components): [alert] use new display tag
  docs/en-US/component/alert.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14962 docs(components): [breadcrumb] fix attr typo
  docs/en-US/component/breadcrumb.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14822 fix(components): [watermark] mutationObserver should work
  packages/components/watermark/src/watermark.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14961 docs(components): [affix] use new display tag
  docs/en-US/component/affix.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14831 fix(docs): Algolia highlight error
  docs/.vitepress/vitepress/components/navbar/vp-search.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15016 fix(components): [table-v2] cell, header-cell, empty slots not displayed
  packages/components/table-v2/__tests__/table-v2.test.tsx
  packages/components/table-v2/src/components/cell.tsx
  packages/components/table-v2/src/components/header-cell.tsx
  packages/components/table-v2/src/renderers/cell.tsx
  packages/components/table-v2/src/renderers/empty.tsx
  packages/components/table-v2/src/renderers/header-cell.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15035 fix(components): [table] header slot not displayed
  packages/components/table/src/table-column/render-helper.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15036 fix(components): [data-picker] use renderSlot simplified code
  packages/components/date-picker/src/date-picker-com/basic-cell-render.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15051 feat(components): [menu] add popperOffset and ellipsisIcon props(#14923)
  docs/en-US/component/menu.md
  docs/examples/menu/popper-offset.vue
  packages/components/menu/src/menu.ts
  packages/components/menu/src/sub-menu.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14741 fix(components): [table] tooltipOptions.showAfter is not effective
  packages/components/table/src/util.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15078 feat(components): [switch] (in)active icon slot
  docs/en-US/component/switch.md
  docs/examples/switch/custom-action-slot.vue
  packages/components/switch/__tests__/switch.test.tsx
  packages/components/switch/src/switch.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15092 fix(ci): git workflows not work
  .github/workflows/pr-docs-build.yml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15066 fix(components): [input-number] Fix not trigger change event and incorrect value display
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
Labels: CommitMessage::Qualified

#15113 test(hooks): fix typo
  packages/hooks/__tests__/use-namespace.test.tsx
  packages/hooks/__tests__/use-teleport.test.tsx
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14828 feat(components): [pagination] add change event
  docs/en-US/component/pagination.md
  packages/components/pagination/__tests__/pagination.test.tsx
  packages/components/pagination/src/pagination.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15137 chore: format
  docs/en-US/component/affix.md
  docs/en-US/component/card.md
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/descriptions.md
  docs/en-US/component/form.md
  docs/en-US/component/image.md
  docs/en-US/component/select.md
  docs/en-US/component/slider.md
  docs/en-US/component/typography.md
  docs/en-US/component/upload.md
  docs/en-US/component/watermark.md
  packages/theme-chalk/src/card.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/form.scss
  packages/theme-chalk/src/reset.scss
Labels: CommitMessage::Qualified

#14801 fix(components): [collapse-transition] collapse get el exists height
  docs/examples/transitions/collapse.vue
  packages/components/collapse-transition/src/collapse-transition.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15079 fix(components): [date-picker] tagName judgement error
  packages/components/date-picker/src/date-picker-com/basic-month-table.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15152 fix(build): fix built component source contains unsafe file path
  internal/build/src/tasks/modules.ts
Labels: CommitMessage::Qualified

#14742 feat(components): [el-menu] allow user to hide menu when clicking outside
  docs/en-US/component/menu.md
  packages/components/menu/src/menu.ts
  packages/components/menu/src/sub-menu.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15157 docs(components): [menu,pagination,switch] modify version
  docs/en-US/component/menu.md
  docs/en-US/component/pagination.md
  docs/en-US/component/switch.md
Labels: CommitMessage::Qualified

#15150 fix(components): [tree] filter expand loaded node
  packages/components/tree/src/model/tree-store.ts
Labels: CommitMessage::Qualified

#15173 fix(docs): algolia search
  docs/.vitepress/config.mts
  docs/.vitepress/vitepress/components/navbar/vp-search.vue
Labels: CommitMessage::Qualified

#15005 fix(components): [tree] node drag error when using custom `allowDrop` method
  packages/components/tree/src/model/useDragNode.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15175 test(components): [tree] filter expand loaded node
  packages/components/tree/__tests__/tree.test.ts
Labels: CommitMessage::Qualified

#15174 fix(components): [input] input-style rendering error
  packages/components/input/src/input.vue
Labels: CommitMessage::Qualified

#15180 feat(docs): add translations for doc search
  docs/.vitepress/crowdin/en-US/component/search.json
  docs/.vitepress/vitepress/components/navbar/vp-search.vue
Labels: CommitMessage::Qualified

#15181 fix(docs): fix doc search option doesn't update after switching language
  docs/.vitepress/vitepress/components/navbar/vp-search.vue
Labels: CommitMessage::Qualified

#15182 fix(docs): replace `fonts.loli.net` with original `fonts.googleapis.com`
  docs/.vitepress/config/head.ts
Labels: CommitMessage::Qualified

#15212 refactor(components): [input] get maxlength and minlength from props instead of attrs
  docs/en-US/component/input.md
  packages/components/input/src/input.ts
  packages/components/input/src/input.vue
Labels: CommitMessage::Qualified

#15190 style(theme-chalk): replace word-break with overflow-wrap
  docs/.vitepress/vitepress/components/globals/resource.vue
  docs/.vitepress/vitepress/styles/content.scss
  packages/theme-chalk/src/date-picker/picker.scss
  packages/theme-chalk/src/image-viewer.scss
  packages/theme-chalk/src/message-box.scss
  packages/theme-chalk/src/message.scss
  packages/theme-chalk/src/notification.scss
  packages/theme-chalk/src/popover.scss
  packages/theme-chalk/src/popper.scss
  packages/theme-chalk/src/step.scss
  packages/theme-chalk/src/table-v2.scss
  packages/theme-chalk/src/table.scss
  packages/theme-chalk/src/text.scss
Labels: CommitMessage::Qualified

#15220 fix(components): [input] remove unnecessary properties
  packages/components/input/src/input.vue
Labels: CommitMessage::Qualified

#15197 fix(components): [date-picker] handleFocusPicker delay
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
Labels: CommitMessage::Qualified

#15215 docs(docs) 穿梭框的自定义部分有误
  docs/examples/transfer/customizable.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15193 feat(components): [menu] add `popper-class`、`subMenuTimeout` props
  docs/en-US/component/menu.md
  packages/components/menu/src/menu.ts
  packages/components/menu/src/sub-menu.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15242 fix(components): [collapse] emit value type check error
  packages/components/collapse/src/collapse.ts
Labels: CommitMessage::Qualified

#15243 chore: pr template remove copilot
  .github/pull_request_template.md
Labels: CommitMessage::Qualified

#15206 feat(components): [autocomplete] add `loading` slot
  docs/en-US/component/autocomplete.md
  docs/examples/autocomplete/custom-loading.vue
  packages/components/autocomplete/src/autocomplete.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15085 fix(style): [col] media sm max-wdith 768 to 767
  packages/theme-chalk/src/common/var.scss
Labels: CommitMessage::Qualified

#15252 fix(components): [date-picker] add first click demo
  packages/components/date-picker/__tests__/date-time-picker.test.tsx
Labels: CommitMessage::Qualified

#14959 docs(components): [statistic] add transition example
  docs/en-US/component/statistic.md
  docs/examples/statistic/basic.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14954 chore(components): [carousel] class optimization in code
  packages/components/carousel/src/carousel-item.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14955 docs(components): [collapse] use new display tag
  docs/en-US/component/collapse.md
  packages/components/collapse/src/collapse-item.ts
  packages/components/collapse/src/collapse.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14952 feat(components): tour component
  docs/.vitepress/crowdin/en-US/pages/component.json
  docs/en-US/component/tour.md
  docs/examples/tour/basic.vue
  docs/examples/tour/indicator.vue
  docs/examples/tour/mask.vue
  docs/examples/tour/non-modal.vue
  docs/examples/tour/placement.vue
  packages/components/index.ts
  packages/components/tour-step/style/css.ts
  packages/components/tour-step/style/index.ts
  packages/components/tour/__tests__/tour.test.tsx
  packages/components/tour/index.ts
  packages/components/tour/src/content.ts
  packages/components/tour/src/content.vue
  packages/components/tour/src/helper.ts
  packages/components/tour/src/mask.ts
  packages/components/tour/src/mask.vue
  packages/components/tour/src/step.ts
  packages/components/tour/src/step.vue
  packages/components/tour/src/steps.ts
  packages/components/tour/src/tour.ts
  packages/components/tour/src/tour.vue
  packages/components/tour/src/types.ts
  packages/components/tour/style/css.ts
  packages/components/tour/style/index.ts
  packages/element-plus/component.ts
  packages/locale/lang/de.ts
  packages/locale/lang/en.ts
  packages/locale/lang/eu.ts
  packages/locale/lang/fa.ts
  packages/locale/lang/ja.ts
  packages/locale/lang/ko.ts
  packages/locale/lang/lt.ts
  packages/locale/lang/pl.ts
  packages/locale/lang/pt-br.ts
  packages/locale/lang/ru.ts
  packages/locale/lang/sv.ts
  packages/locale/lang/th.ts
  packages/locale/lang/uk.ts
  packages/locale/lang/vi.ts
  packages/locale/lang/zh-cn.ts
  packages/locale/lang/zh-tw.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/index.scss
  packages/theme-chalk/src/tour.scss
  typings/components.d.ts
Labels: Contribution::Community, Project::New Component, CommitMessage::Qualified, Needs Review

#15295 fix(docs): fix tip text overflows when no result
  docs/.vitepress/vitepress/components/navbar/vp-search.vue
Labels: CommitMessage::Qualified

#15184 fix(components): [input-number] Displayed values is different from modelValue when use model-value
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
Labels: CommitMessage::Qualified

#15293 feat(components): [tree] export TreeInstance
  packages/components/tree/index.ts
  packages/components/tree/src/instance.ts
Labels: CommitMessage::Qualified

#15304 refactor(docs): [tour] use `ButtonInstance` and format code
  docs/en-US/component/tour.md
  docs/examples/tour/basic.vue
  docs/examples/tour/indicator.vue
  docs/examples/tour/mask.vue
  docs/examples/tour/non-modal.vue
  docs/examples/tour/placement.vue
  packages/theme-chalk/src/tour.scss
Labels: CommitMessage::Qualified

#15306 fix(components): [select-v2] clear icon invalid when status-icon is set
  packages/theme-chalk/src/select-v2.scss
Labels: CommitMessage::Qualified

#15266 fix(components): [link] add target attribute and relevant docs
  docs/en-US/component/link.md
  packages/components/link/src/link.ts
  packages/components/link/src/link.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14930 feat(components): [form] FormContext adds the getField method
  packages/components/form/src/form-item.vue
  packages/components/form/src/form.vue
  packages/components/form/src/types.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15101 chore: update pnpm to v8.12.0
  package.json
  pnpm-lock.yaml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review
