Repository element-plus/element-plus, pull requests merged in 2023-03, with the labels that each got.

#10561 docs: error when frontmatter does not exist
  docs/.vitepress/plugins/markdown-transform.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10332 refactor(components): [color-picker] alpha-slider
  packages/components/color-picker/src/components/alpha-slider.vue
  packages/components/color-picker/src/composables/use-alpha-slider.ts
  packages/components/color-picker/src/props/alpha-slider.ts
Labels: Refactor, CommitMessage::Qualified

#10091 fix(components): [autocomplete] the blur event is not triggered
  packages/components/autocomplete/__tests__/autocomplete.test.tsx
  packages/components/autocomplete/src/autocomplete.vue
Labels: CommitMessage::Qualified

#10427 refactor(components): [steps]
  packages/components/steps/src/item.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11777 fix(components): circular referencing issue
  packages/components/button/src/button.ts
  packages/components/cascader/src/cascader.ts
  packages/components/checkbox/src/checkbox-group.ts
  packages/components/checkbox/src/checkbox.ts
  packages/components/color-picker/src/color-picker.ts
  packages/components/config-provider/src/config-provider-props.ts
  packages/components/config-provider/src/hooks/use-global-config.ts
  packages/components/descriptions/src/description.ts
  packages/components/form/src/hooks/use-form-common-props.ts
  packages/components/input-number/src/input-number.ts
  packages/components/input/src/input.ts
  packages/components/radio/src/radio-group.ts
  packages/components/radio/src/radio.ts
  packages/components/rate/src/rate.ts
  packages/components/slider/src/slider.ts
  packages/components/table/src/table/defaults.ts
  packages/components/time-picker/src/common/props.ts
  packages/components/time-select/src/time-select.ts
  packages/hooks/index.ts
  packages/hooks/use-size/index.ts
Labels: CommitMessage::Qualified

#11745 docs(components): Adds tip about disabling validator trigger
  docs/en-US/component/form.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11283 fix(theme-chalk): [tab] correct padding of card item on hover
  packages/theme-chalk/src/tabs.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11792 chore(ci): update issue-labled.yml link
  .github/workflows/issue-labeled.yml
Labels: CommitMessage::Qualified

#11797 chore: update doc padding
  docs/en-US/component/select.md
Labels: CommitMessage::Qualified

#11807 Revert "docs: error when frontmatter does not exist"
  docs/.vitepress/plugins/markdown-transform.ts
Labels: CommitMessage::Qualified, Needs Review

#11809 docs(components): [icon] using shallowRef instead of ref
  docs/.vitepress/vitepress/components/globals/icons.vue
Labels: CommitMessage::Qualified

#11815 fix(components): [table-v2] class of column is not valid
  packages/components/table-v2/src/renderers/cell.tsx
Labels: CommitMessage::Qualified

#11225 fix(components): [tree-select] cache data update incorrect
  packages/components/tree-select/__tests__/tree-select.test.tsx
  packages/components/tree-select/src/cache-options.ts
Labels: CommitMessage::Qualified

#11822 docs: fix the nav menu overlap
  docs/.vitepress/vitepress/styles/css-vars.scss
Labels: CommitMessage::Qualified

#11847 fix(components): [global-config]
  packages/components/autocomplete/__tests__/autocomplete.test.tsx
  packages/components/config-provider/__tests__/config-provider.test.tsx
  packages/components/config-provider/src/hooks/use-global-config.ts
  packages/components/loading/src/loading.ts
  packages/components/loading/src/service.ts
  packages/components/message-box/src/index.vue
  packages/components/message/src/message.vue
  packages/components/notification/__tests__/notification.test.tsx
  packages/components/notification/src/notification.vue
  packages/components/notification/src/notify.ts
  packages/components/select/__tests__/select.test.ts
  packages/hooks/__tests__/use-id.test.tsx
  packages/hooks/__tests__/use-locale.test.tsx
  packages/hooks/__tests__/use-namespace.test.tsx
  packages/hooks/__tests__/use-popper-container.test.tsx
  packages/hooks/use-locale/index.ts
  packages/hooks/use-namespace/index.ts
  packages/hooks/use-popper-container/index.ts
  packages/hooks/use-z-index/index.ts
Labels: CommitMessage::Qualified

#11868 fix(components): [select] console warning
  packages/components/select/src/options.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#11866 fix(components): [global-config]
  packages/components/config-provider/__tests__/config-provider.test.tsx
  packages/components/config-provider/src/hooks/use-global-config.ts
  packages/components/message-box/src/index.vue
Labels: CommitMessage::Qualified

#11881 fix(components): [overlay] namespace issue
  packages/components/message-box/src/index.vue
  packages/components/overlay/__tests__/overlay.test.tsx
  packages/components/overlay/src/overlay.ts
  packages/hooks/__tests__/use-lockscreen.test.tsx
  packages/hooks/use-lockscreen/index.ts
Labels: CommitMessage::Qualified

#11882 D2M
  CHANGELOG.en-US.md
  packages/components/config-provider/__tests__/config-provider.test.tsx
  packages/components/config-provider/src/hooks/use-global-config.ts
  packages/components/message-box/src/index.vue
  packages/components/overlay/__tests__/overlay.test.tsx
  packages/components/overlay/src/overlay.ts
  packages/components/select/src/options.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/hooks/__tests__/use-lockscreen.test.tsx
  packages/hooks/use-lockscreen/index.ts
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified

#11884 fix(components): [select] Filter duplicate emits of "update options"
  packages/components/select/src/options.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11891 chore(components): [table-v2] accessibility improvement
  docs/examples/table-v2/grouping-header.vue
  packages/components/table-v2/src/components/header-row.tsx
  packages/components/table-v2/src/components/header.tsx
  packages/components/table-v2/src/components/row.tsx
  packages/components/table-v2/src/renderers/cell.tsx
  packages/components/table-v2/src/renderers/header-cell.tsx
  packages/components/table-v2/src/table-grid.tsx
  packages/components/virtual-list/src/builders/build-grid.ts
  packages/components/virtual-list/src/props.ts
Labels: CommitMessage::Qualified

#11909 fix(components): [select] filter all ElOption item labels
  packages/components/select/src/options.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11899 fix(components): [global-config] global injection
  packages/components/config-provider/src/hooks/use-global-config.ts
  packages/components/message-box/src/index.vue
  packages/components/overlay/src/overlay.ts
Labels: CommitMessage::Qualified

#11912 D2M
  CHANGELOG.en-US.md
  docs/examples/table-v2/grouping-header.vue
  packages/components/config-provider/src/hooks/use-global-config.ts
  packages/components/message-box/src/index.vue
  packages/components/overlay/src/overlay.ts
  packages/components/select/src/options.ts
  packages/components/table-v2/src/components/header-row.tsx
  packages/components/table-v2/src/components/header.tsx
  packages/components/table-v2/src/components/row.tsx
  packages/components/table-v2/src/renderers/cell.tsx
  packages/components/table-v2/src/renderers/header-cell.tsx
  packages/components/table-v2/src/table-grid.tsx
  packages/components/table/src/table-body/events-helper.ts
  packages/components/table/src/util.ts
  packages/components/virtual-list/src/builders/build-grid.ts
  packages/components/virtual-list/src/props.ts
Labels: CommitMessage::Qualified

#11921 fix: [message-box] lock scroll
  packages/components/message-box/src/index.vue
Labels: CommitMessage::Qualified

#11850 docs(components): [tooltip]
  docs/en-US/component/tooltip.md
  packages/components/popper/src/content.ts
  packages/components/tooltip/src/content.ts
  packages/components/tooltip/src/tooltip.ts
  packages/components/tooltip/src/tooltip.vue
  packages/components/tooltip/src/trigger.ts
  packages/hooks/use-delayed-toggle/index.ts
Labels: CommitMessage::Qualified, 2.3.0

#11825 docs: accessibility improvement
  docs/.vitepress/crowdin/en-US/component/api-typing.json
  docs/.vitepress/crowdin/en-US/component/navbar.json
  docs/.vitepress/crowdin/en-US/component/skip-link.json
  docs/.vitepress/crowdin/en-US/component/translation.json
  docs/.vitepress/vitepress/components/common/vp-switch.vue
  docs/.vitepress/vitepress/components/full-screen/vp-theme-toggler.vue
  docs/.vitepress/vitepress/components/full-screen/vp-translation.vue
  docs/.vitepress/vitepress/components/globals/vp-api-typing.vue
  docs/.vitepress/vitepress/components/navbar/vp-hamburger.vue
  docs/.vitepress/vitepress/components/navbar/vp-theme-toggler.vue
  docs/.vitepress/vitepress/components/navbar/vp-translation.vue
  docs/.vitepress/vitepress/components/subnav/toggle-sidebar-btn.vue
  docs/.vitepress/vitepress/components/vp-app.vue
  docs/.vitepress/vitepress/components/vp-content.vue
  docs/.vitepress/vitepress/components/vp-demo.vue
  docs/.vitepress/vitepress/components/vp-skip-link.vue
  docs/.vitepress/vitepress/components/vp-subnav.vue
  docs/.vitepress/vitepress/composables/navbar-locale.ts
  docs/.vitepress/vitepress/composables/translation.ts
  docs/.vitepress/vitepress/styles/base.scss
  docs/.vitepress/vitepress/styles/common/switch.scss
  docs/.vitepress/vitepress/styles/content.scss
  docs/components.d.ts
Labels: Project::Documentation, CommitMessage::Qualified, 2.3.0

#11833 fix(components): [popover | tooltip] keep autoClose prop
  packages/components/tooltip/src/tooltip.vue
  packages/hooks/use-delayed-toggle/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11928 fix(components): [table-v2] endReached triggered twice when first
  packages/components/table-v2/src/composables/use-row.ts
  packages/components/table-v2/src/use-table.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review, Component::TableV2

#11830 style(components): [select-v2] input-icon margin-left (not first)
  packages/theme-chalk/src/select-v2.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11826 docs(components): [popconfirm]
  docs/en-US/component/popconfirm.md
  packages/components/popconfirm/src/popconfirm.ts
  packages/components/popconfirm/src/popconfirm.vue
Labels: CommitMessage::Qualified

#11816 fix(components): [input] update input value length calculate
  packages/components/input/__tests__/input.test.tsx
  packages/components/input/src/input.vue
Labels: CommitMessage::Qualified

#11812 docs(build): optimize the regular
  docs/.vitepress/plugins/markdown-transform.ts
Labels: Project::Documentation, Project::Build, CommitMessage::Qualified

#11956 fix(components): [loading] namespace config
  packages/components/loading/src/loading.ts
  packages/hooks/use-namespace/index.ts
Labels: Component::Loading, CommitMessage::Qualified, 2.3.0

#11957 test(components): add tests for select options
  packages/components/select/__tests__/options.test.tsx
Labels: CommitMessage::Qualified

#11405 feat(components): [select-v2] Add max-collapse-tags prop
  docs/en-US/component/select-v2.md
  docs/examples/select-v2/hide-extra-tags.vue
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/useSelect.ts
Labels: CommitMessage::Qualified

#11378 feat(components): [select] Add max-collapse-tags prop
  docs/en-US/component/select.md
  docs/examples/select/multiple.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified, 2.3.0

#11781 feat(components): [cascader] Adjust expose and typo
  packages/components/cascader-panel/index.ts
  packages/components/cascader-panel/src/instance.ts
  packages/components/cascader/src/cascader.vue
Labels: CommitMessage::Qualified

#11920 style(theme-chalk): [rate] size
  packages/theme-chalk/src/rate.scss
Labels: CommitMessage::Qualified

#11653 feat(components): add el-text component
  docs/.vitepress/crowdin/en-US/pages/component.json
  docs/en-US/component/text.md
  docs/examples/text/basic.vue
  docs/examples/text/mixed.vue
  docs/examples/text/override.vue
  docs/examples/text/sizes.vue
  docs/examples/text/truncated.vue
  packages/components/index.ts
  packages/components/text/__tests__/text.test.tsx
  packages/components/text/index.ts
  packages/components/text/src/text.ts
  packages/components/text/src/text.vue
  packages/components/text/style/css.ts
  packages/components/text/style/index.ts
  packages/element-plus/component.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/index.scss
  packages/theme-chalk/src/text.scss
Labels: release candidate, Contribution::Community, 1st contribution, Project::New Component, CommitMessage::Qualified, Needs Review

#11968 chore: update ko translation
  packages/locale/lang/ko.ts
Labels: CommitMessage::Qualified

#11940 fix(components): [tooltip] remove mousemove listener when unmount
  docs/examples/tooltip/virtual-trigger.vue
Labels: Contribution::Community, Component::Tooltip, Component::Popover, CommitMessage::Qualified, Needs Review, 2.3.0

#11972 docs: update tooltip text
  docs/en-US/component/tooltip.md
Labels: CommitMessage::Qualified, Needs Review

#11498 fix(components): [select] iOS keyboard not appear when focus
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/theme-chalk/src/select.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11997 fix(components): [cascader] clickoutside
  docs/en-US/component/cascader.md
  packages/components/cascader/src/cascader.vue
Labels: CommitMessage::Qualified

#11889 style(theme-chalk): use variable instead of '-'
  packages/theme-chalk/src/mixins/mixins.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11705 fix(components): [table-column] first default column set placeholder
  packages/components/table/src/table-column/render-helper.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12017 docs: enable lazy loading for contributor avatars to improve page loading speed
  docs/.vitepress/vitepress/components/globals/contributors.vue
Labels: CommitMessage::Qualified

#11969 style(theme-chalk): [select-v2] text overflow
  packages/theme-chalk/src/select-v2.scss
Labels: CommitMessage::Qualified, Needs Review

#12007 fix(components): [input-number] modelValue incorrect update
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12056 fix(hooks): [use-delayed-toggle] clear timer when call onClose
  packages/hooks/__tests__/use-delayed-toggle.test.ts
  packages/hooks/use-delayed-toggle/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12086 fix(style): [message-box] border box
  packages/theme-chalk/src/message-box.scss
Labels: CommitMessage::Qualified

#12094 style(components): [input] update exceed style
  packages/theme-chalk/src/input.scss
Labels: CommitMessage::Qualified

#12121 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/vitepress/components/globals/contributors.vue
  docs/en-US/component/cascader.md
  packages/components/cascader/src/cascader.vue
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/components/table/src/table-column/render-helper.ts
  packages/hooks/__tests__/use-delayed-toggle.test.ts
  packages/hooks/use-delayed-toggle/index.ts
  packages/hooks/use-prop/index.ts
  packages/theme-chalk/src/input.scss
  packages/theme-chalk/src/message-box.scss
  packages/theme-chalk/src/mixins/mixins.scss
  packages/theme-chalk/src/select-v2.scss
  packages/theme-chalk/src/select.scss
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#12090 fix(components): [select-v2] reset hoverindex when close dropdown list
  packages/components/select-v2/src/useSelect.ts
Labels: CommitMessage::Qualified

#10137 fix(components): [input] scrollbar not hide after autosize
  packages/components/input/src/input.vue
Labels: CommitMessage::Qualified

#12131 chore: update website
  docs/.vitepress/config/sponsors.ts
  docs/public/images/jnpfsoft.jpg
  docs/public/images/sponsors/jnpfsoft.jpg
Labels: CommitMessage::Qualified

#12132 docs(style): add pointer cursor for `summary` element
  docs/.vitepress/vitepress/styles/base.scss
Labels: CommitMessage::Qualified

#12160 fix(docs): [tabs] example type error
  docs/examples/tabs/dynamic-tabs.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12177 docs: [tabs] fix type
  docs/examples/tabs/dynamic-tabs.vue
Labels: CommitMessage::Qualified

#12164 feat(components): [form] scroll-into-view options
  docs/en-US/component/form.md
  packages/components/form/src/form.ts
  packages/components/form/src/form.vue
Labels: CommitMessage::Qualified

#12087 fix(components): [input] textarea height calc
  packages/components/input/src/input.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12015 fix(components): [select] multiple disabled style
  packages/components/select/src/select.vue
  packages/theme-chalk/src/select.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12186 docs: [upload] Fix typo
  docs/examples/upload/basic.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12134 fix(components): [pagination] delete input value display empty string
  packages/components/pagination/src/components/jumper.vue
Labels: CommitMessage::Qualified

#12029 fix: Upload data is not independent
  packages/components/upload/src/upload-content.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12281 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/vitepress/styles/base.scss
  docs/en-US/component/form.md
  docs/examples/tabs/dynamic-tabs.vue
  docs/examples/upload/basic.vue
  docs/public/images/jnpfsoft.jpg
  docs/public/images/sponsors/jnpfsoft.jpg
  packages/components/form/src/form.ts
  packages/components/form/src/form.vue
  packages/components/input/src/input.vue
  packages/components/pagination/src/components/jumper.vue
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/select.vue
  packages/components/upload/src/upload-content.vue
  packages/theme-chalk/src/select.scss
  packages/theme-chalk/src/tabs.scss
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review
