Repository element-plus/element-plus, pull requests merged in 2023-04, with the labels that each got.

#11942 feat(components): [color-picker] add `show` `hide` expose
  docs/en-US/component/color-picker.md
  packages/components/color-picker/src/color-picker.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12283 refactor(components): [table] remove useless brackets
  packages/components/table/src/table.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12255 fix(components): [tree-select] add to global components
  global.d.ts
  typings/components.d.ts
Labels: CommitMessage::Qualified

#12287 fix(components): [upload] add before-upload test
  packages/components/upload/__tests__/upload.test.tsx
Labels: CommitMessage::Qualified

#12323 feat(components): [date-picker] support numpadEnter
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
Labels: CommitMessage::Qualified

#12324 fix(components): [statistic] add to global components
  global.d.ts
  typings/components.d.ts
Labels: CommitMessage::Qualified

#12339 docs(components): [text] Supplementary release notes
  docs/.vitepress/crowdin/en-US/pages/component.json
Labels: CommitMessage::Qualified

#12206 fix(components): [menu] Avoid call router when index is not provided
  packages/components/menu/src/menu.ts
Labels: CommitMessage::Qualified

#12310 chore: update contributing.md
  CONTRIBUTING.md
Labels: CommitMessage::Qualified

#12321 fix(components): [popover] default trigger
  packages/components/popover/src/popover.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12342 docs: [popover] modify the default value of trigger
  docs/en-US/component/popover.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12296 docs(components): [loading]
  docs/en-US/component/loading.md
  packages/components/loading/src/types.ts
Labels: CommitMessage::Qualified

#12295 docs(components): [message]
  docs/en-US/component/message.md
  packages/components/message/src/message.ts
Labels: CommitMessage::Qualified

#12293 docs(components): [notification] api
  docs/en-US/component/notification.md
  packages/components/notification/src/notification.ts
Labels: CommitMessage::Qualified

#11854 docs(components): [steps]
  docs/en-US/component/steps.md
  packages/components/steps/src/item.ts
  packages/components/steps/src/steps.ts
Labels: CommitMessage::Qualified

#12354 D2M
  CHANGELOG.en-US.md
  CONTRIBUTING.md
  README.md
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/crowdin/en-US/pages/component.json
  docs/en-US/component/color-picker.md
  docs/en-US/component/loading.md
  docs/en-US/component/message.md
  docs/en-US/component/notification.md
  docs/en-US/component/popover.md
  docs/en-US/component/steps.md
  global.d.ts
  packages/components/color-picker/src/color-picker.vue
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/loading/src/types.ts
  packages/components/menu/src/menu.ts
  packages/components/message/src/message.ts
  packages/components/notification/src/notification.ts
  packages/components/steps/src/item.ts
  packages/components/steps/src/steps.ts
  packages/components/table/src/table.vue
  packages/components/upload/__tests__/upload.test.tsx
  typings/components.d.ts
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#12180 build(components): fix generateExternal use wrong reference
  internal/build/src/utils/rollup.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11590 chore(build): optimize the type conversion of tag plugin
  internal/build/src/tasks/helper.ts
Labels: CommitMessage::Qualified

#11600 fix(components): [image] Display error content when picture loading fails
  packages/components/image/src/image.vue
  packages/theme-chalk/src/image.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11657 docs(components): [time-picker]
  docs/en-US/component/time-picker.md
  packages/components/time-picker/src/common/props.ts
  packages/components/time-picker/src/props/shared.ts
  packages/components/time-picker/src/time-picker.tsx
Labels: CommitMessage::Qualified

#11848 style(theme-chalk): [menu] horizontal mode submenu line-high
  packages/theme-chalk/src/menu.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11648 docs(style): use new display tag
  docs/en-US/component/autocomplete.md
  docs/en-US/component/button.md
  docs/en-US/component/checkbox.md
  docs/en-US/component/dialog.md
  docs/en-US/component/drawer.md
  docs/en-US/component/image.md
  docs/en-US/component/input-number.md
  docs/en-US/component/input.md
  docs/en-US/component/radio.md
  docs/en-US/component/rate.md
  docs/en-US/component/select.md
  docs/en-US/component/table-v2.md
  docs/en-US/component/table.md
  docs/en-US/guide/dark-mode.md
  docs/en-US/guide/namespace.md
Labels: CommitMessage::Qualified

#11853 feat(components): [button] add tag attribute
  docs/en-US/component/button.md
  docs/examples/button/tag.vue
  packages/components/button/__tests__/button.test.tsx
  packages/components/button/src/button.ts
  packages/components/button/src/button.vue
  packages/components/button/src/use-button.ts
Labels: Project::Enhancement, release candidate, CommitMessage::Qualified, 2.3.0

#12333 feat(components): [progress] support set striped progress bar
  docs/en-US/component/progress.md
  docs/examples/progress/striped-progress.vue
  packages/components/progress/__tests__/progress.test.tsx
  packages/components/progress/src/progress.ts
  packages/components/progress/src/progress.vue
  packages/theme-chalk/src/progress.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12200 fix(components): [select] delete key should not choose tag
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12199 fix(components): [date-picker] optimize props definition and export
  packages/components/date-picker/index.ts
  packages/components/date-picker/src/date-picker.tsx
  packages/components/date-picker/src/props/date-picker.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12319 fix(components): [menu] change declartion of ulStyle to setup function
  packages/components/menu/src/sub-menu.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12154 fix(components): [input] Write Chinese in parenthesis, letters repeat
  packages/utils/i18n.ts
Labels: CommitMessage::Qualified

#12470 docs(components): [tooltip] Fix typos objcet -> object
  docs/en-US/component/tooltip.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12454 style(theme-chalk): [transfer] improve transfer filter style
  packages/theme-chalk/src/transfer.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12442 fix(components): [loading] fix zIndex
  packages/components/loading/src/loading.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12459 feat(components): [tree] support customize content when data is empty
  docs/en-US/component/tree.md
  packages/components/tree/src/tree.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12485 test: configure namespace and zindex for loading
  packages/components/config-provider/__tests__/config-loading.test.tsx
Labels: CommitMessage::Qualified

#12505 docs(components): [iamge] update referrerPolicy
  docs/en-US/component/image.md
Labels: CommitMessage::Qualified

#12514 fix(components): [dropdown] improve types
  docs/examples/dropdown/dropdown-methods.vue
  packages/components/dropdown/index.ts
  packages/components/dropdown/src/instance.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11973 fix(components): [select] correct update selectSize
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12543 fix(components): [table] text node not have closest method
  packages/components/table/src/table-header/event-helper.ts
Labels: CommitMessage::Qualified

#12608 chore: code format
  packages/theme-chalk/src/image.scss
  packages/theme-chalk/src/progress.scss
  packages/theme-chalk/src/text.scss
Labels: CommitMessage::Qualified

#12606 feat(docs): right menu tag convert
  docs/.vitepress/vitepress/components/doc-content/vp-table-of-content.vue
Labels: CommitMessage::Qualified

#12604 docs(components): [progress]
  docs/en-US/component/progress.md
  packages/components/progress/src/progress.ts
Labels: CommitMessage::Qualified

#12660 docs(components): [tooltip] use new tag
  docs/en-US/component/tooltip.md
Labels: CommitMessage::Qualified

#12661 docs(style): [result] use new display tag
  docs/en-US/component/result.md
  packages/components/result/src/result.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12662 docs(components): [empty] use new display tag
  docs/en-US/component/empty.md
  packages/components/empty/src/empty.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12377 fix(components): [loading] Compatible with vue3.2.0~12
  packages/components/loading/src/service.ts
Labels: CommitMessage::Qualified

#12664 docs(components): [timeline] use new display tag
  docs/en-US/component/timeline.md
  packages/components/timeline/src/timeline-item.ts
  packages/components/timeline/src/timeline-item.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review
