Repository element-plus/element-plus, pull requests merged in 2023-02, with the labels that each got.

#11377 fix(components): [popper]
  packages/components/popper/__tests__/content.test.tsx
  packages/components/popper/src/content.vue
Labels: CommitMessage::Qualified

#11352 fix(components): [form-item] fix error message animation
  packages/components/form/src/form-item.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11335 fix(components): [cascader] fix warning when clear
  packages/components/cascader/src/cascader.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11385 docs: how to use Element Plus in Nuxt
  docs/en-US/guide/quickstart.md
Labels: CommitMessage::Qualified

#11397 chore: format code
  docs/.vitepress/vitepress/styles/css-vars.scss
  docs/en-US/component/card.md
  docs/en-US/component/drawer.md
  docs/en-US/component/image.md
  docs/en-US/component/message-box.md
  docs/en-US/component/rate.md
  docs/en-US/component/skeleton.md
  docs/en-US/component/table.md
  docs/en-US/component/tree-select.md
  docs/en-US/component/tree-v2.md
  docs/en-US/component/tree.md
  docs/en-US/component/upload.md
  docs/en-US/guide/i18n.md
  packages/theme-chalk/src/menu.scss
Labels: CommitMessage::Qualified

#11420 feat(components): [statistic]
  docs/.vitepress/crowdin/en-US/pages/component.json
  docs/examples/statistic/card.vue
  docs/examples/statistic/countdown.vue
Labels: CommitMessage::Qualified

#11281 docs(components): [cascader] adjust some formats
  docs/en-US/component/cascader.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11265 docs: update quickstart.md
  docs/en-US/guide/quickstart.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11251 refactor(tokens): use Symbol as injection key
  packages/components/descriptions/src/token.ts
  packages/components/select-v2/src/token.ts
  packages/components/select/src/token.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11374 fix(components): [select] recalculate input height when display change
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11187 fix(components): [input] use v-if throw exception
  packages/components/input/src/input.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11071 docs(components): [form]
  docs/en-US/component/form.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11326 refactor(locale): change short months naming
  packages/locale/lang/th.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11421 fix(components): [tree] update refNode type
  packages/components/tree/src/model/tree-store.ts
  packages/components/tree/src/tree.vue
Labels: CommitMessage::Qualified

#11445 chore(components): [table] fix tests typo
  packages/components/table/__tests__/table.test.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11431 fix(components): [dropdown]
  packages/components/dropdown/src/dropdown-item-impl.vue
  packages/components/dropdown/src/dropdown-item.vue
  packages/components/dropdown/src/dropdown-menu.vue
Labels: CommitMessage::Qualified

#11456 fix(theme-chalk): [table] the cell missing padding style
  docs/en-US/component/table.md
  packages/theme-chalk/src/table.scss
Labels: CommitMessage::Qualified

#11472 fix(components): fix virtual list scroll&wheel handler
  packages/components/virtual-list/src/builders/build-grid.ts
  packages/components/virtual-list/src/hooks/use-grid-wheel.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11475 fix(components): [virtual-list] scroll issue
  packages/components/virtual-list/src/hooks/use-grid-wheel.ts
Labels: CommitMessage::Qualified

#11499 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/crowdin/en-US/pages/component.json
  docs/en-US/component/cascader.md
  docs/en-US/component/form.md
  docs/en-US/component/table.md
  docs/en-US/guide/quickstart.md
  docs/examples/statistic/card.vue
  docs/examples/statistic/countdown.vue
  packages/components/descriptions/src/token.ts
  packages/components/dropdown/src/dropdown-item-impl.vue
  packages/components/dropdown/src/dropdown-item.vue
  packages/components/dropdown/src/dropdown-menu.vue
  packages/components/input/src/input.vue
  packages/components/select-v2/src/token.ts
  packages/components/select/src/token.ts
  packages/components/select/src/useSelect.ts
  packages/components/table/__tests__/table.test.ts
  packages/components/tree/src/model/tree-store.ts
  packages/components/tree/src/tree.vue
  packages/components/virtual-list/src/builders/build-grid.ts
  packages/components/virtual-list/src/hooks/use-grid-wheel.ts
  packages/locale/lang/th.ts
  packages/theme-chalk/src/table.scss
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#11483 fix(components): [carousel] delete the indicator props
  packages/components/carousel/src/carousel.ts
Labels: CommitMessage::Qualified

#11503 enhancement(theme-chalk): [checkbox] refactor checkbox disabled style
  packages/theme-chalk/src/checkbox.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11495 fix(components): [cascader-panel] clear active style
  packages/components/cascader-panel/src/index.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11494 refactor(components): [empty]
  packages/components/empty/index.ts
  packages/components/empty/src/empty.ts
  packages/components/empty/src/empty.vue
  packages/components/empty/src/img-empty.vue
  packages/components/empty/src/instance.ts
Labels: CommitMessage::Qualified

#11092 fix(components): [upload-dragger] Avoid firefox open file
  packages/components/upload/src/upload-dragger.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11026 docs(components): [autocomplete]
  docs/en-US/component/autocomplete.md
  packages/components/autocomplete/src/autocomplete.ts
Labels: CommitMessage::Qualified

#11404 fix(hooks): [use-lockscreen] prevent flaky unit tests
  packages/hooks/use-lockscreen/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11510 fix: translate arabic language
  packages/locale/lang/ar.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11021 docs(components): [form]
  docs/en-US/component/form.md
  packages/components/form/src/form-item.ts
  packages/components/form/src/form-item.vue
  packages/components/form/src/form.ts
  packages/components/form/src/form.vue
Labels: CommitMessage::Qualified

#11063 docs(components): [input-number]
  docs/en-US/component/input-number.md
  packages/components/input-number/src/input-number.ts
Labels: CommitMessage::Qualified

#11518 fix(components): [input] box-shadow noise
  packages/theme-chalk/src/input.scss
Labels: CommitMessage::Qualified

#11509 refactor(components): [menu] add deprecated mark to popperAppendToBody
  docs/en-US/component/menu.md
  packages/components/menu/src/sub-menu.ts
Labels: CommitMessage::Qualified

#11205 fix(components): [select] ensure select options respect filter query during initialization
  packages/components/select/src/useOption.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11508 fix(components): [select] i18n issue of select placeholder
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11581 chore: update doc
  docs/.vitepress/config/sponsors.ts
Labels: CommitMessage::Qualified

#10977 docs(components): [calendar]
  docs/en-US/component/calendar.md
  packages/components/calendar/src/calendar.ts
Labels: CommitMessage::Qualified

#10689 docs: special handling about SSR/SSG
  docs/.vitepress/crowdin/en-US/pages/guide.json
  docs/en-US/guide/ssr.md
Labels: CommitMessage::Qualified

#11580 docs(build): add a plugin to display tag
  docs/.vitepress/config/plugins.ts
  docs/.vitepress/plugins/tag.ts
  docs/.vitepress/vitepress/styles/base.scss
  docs/.vitepress/vitepress/styles/content.scss
  docs/.vitepress/vitepress/styles/content/tag-content.scss
  docs/.vitepress/vitepress/styles/css-vars.scss
Labels: CommitMessage::Qualified

#11376 fix(components): [input] fix textarea autosize
  packages/components/input/src/utils.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11559 feat(components): [cascader] add togglePopperVisible for expose
  docs/en-US/component/cascader.md
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/src/cascader.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11390 fix(components): [tree] setCheckedKeys keys attribute add type
  packages/components/tree/src/tree.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11575 feat(components): [descriptions] render null when empty label
  packages/components/descriptions/__tests__/descriptions.test.tsx
  packages/components/descriptions/src/descriptions-cell.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11586 fix(components): [dropdown] fix focus after close
  packages/components/dropdown/src/dropdown.vue
  packages/components/focus-trap/src/focus-trap.vue
Labels: CommitMessage::Qualified

#11556 docs(components): [cascader]
  docs/en-US/component/cascader.md
  packages/components/cascader-panel/src/config.ts
  packages/components/cascader-panel/src/index.vue
  packages/components/cascader-panel/src/node.ts
  packages/components/cascader/src/cascader.ts
  packages/components/cascader/src/cascader.vue
Labels: CommitMessage::Qualified

#11633 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/config/plugins.ts
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/crowdin/en-US/pages/guide.json
  docs/.vitepress/plugins/tag.ts
  docs/.vitepress/vitepress/components/sidebar/vp-sidebar-link.vue
  docs/.vitepress/vitepress/styles/base.scss
  docs/.vitepress/vitepress/styles/content.scss
  docs/.vitepress/vitepress/styles/content/tag-content.scss
  docs/.vitepress/vitepress/styles/css-vars.scss
  docs/en-US/component/autocomplete.md
  docs/en-US/component/calendar.md
  docs/en-US/component/cascader.md
  docs/en-US/component/divider.md
  docs/en-US/component/form.md
  docs/en-US/component/input-number.md
  docs/en-US/component/menu.md
  docs/en-US/guide/ssr.md
  packages/components/autocomplete/src/autocomplete.ts
  packages/components/calendar/src/calendar.ts
  packages/components/carousel/src/carousel.ts
  packages/components/cascader-panel/src/config.ts
  packages/components/cascader-panel/src/index.vue
  packages/components/cascader-panel/src/node.ts
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/src/cascader.ts
  packages/components/cascader/src/cascader.vue
  packages/components/descriptions/__tests__/descriptions.test.tsx
  packages/components/descriptions/src/descriptions-cell.ts
  packages/components/divider/src/divider.ts
  packages/components/dropdown/src/dropdown.vue
  packages/components/empty/index.ts
  packages/components/empty/src/empty.ts
  packages/components/empty/src/empty.vue
  packages/components/empty/src/img-empty.vue
  packages/components/empty/src/instance.ts
  packages/components/focus-trap/src/focus-trap.vue
  packages/components/form/src/form-item.ts
  packages/components/form/src/form-item.vue
  packages/components/form/src/form.ts
  packages/components/form/src/form.vue
  packages/components/input-number/src/input-number.ts
  packages/components/input/src/utils.ts
  packages/components/menu/src/sub-menu.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useOption.ts
  packages/components/select/src/useSelect.ts
  packages/components/tree/src/tree.vue
  packages/components/upload/src/upload-dragger.vue
  packages/hooks/use-lockscreen/index.ts
  packages/locale/lang/ar.ts
  packages/theme-chalk/src/checkbox.scss
  packages/theme-chalk/src/input.scss
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#11204 fix(components): [table] fix an undefined reference in table-layout
  packages/components/table/src/table-layout.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11273 fix(components): [cascader] add focus and blur event when set filterable
  packages/components/cascader/src/cascader.vue
Labels: CommitMessage::Qualified

#11649 fix(components): [dropdown] unmounted error
  packages/components/dropdown/src/dropdown.vue
Labels: CommitMessage::Qualified

#11654 D2M
  CHANGELOG.en-US.md
  packages/components/cascader/src/cascader.vue
  packages/components/dropdown/src/dropdown.vue
  packages/components/table/src/table-layout.ts
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified

#11522 feat(components): [tree-v2] add item-size attribute
  docs/en-US/component/tree-v2.md
  packages/components/tree-v2/__tests__/tree.test.ts
  packages/components/tree-v2/src/tree-node.vue
  packages/components/tree-v2/src/tree.vue
  packages/components/tree-v2/src/virtual-tree.ts
Labels: CommitMessage::Qualified

#11635 fix(theme-chalk): [upload] wrong hover style when disabled
  packages/theme-chalk/src/upload.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11676 chore: update doc
  docs/.vitepress/config/sponsors.ts
  docs/public/images/sponsors/jeeplus.png
  docs/public/images/sponsors/jeeplus_banner.jpg
Labels: CommitMessage::Qualified

#11661 docs(components): [table] 筛选demo在ElementPlusPlayground中无预览效果
  docs/examples/table/filter.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11681 refactor(components): [slider] remove useless code
  packages/components/slider/src/composables/use-watch.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11677 fix(components): [input-number] prevent input wheel events
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11708 chore: update contributing.md
  .github/CONTRIBUTING.en-US.md
  .github/CONTRIBUTING.es.md
  .github/CONTRIBUTING.fr-FR.md
  .github/CONTRIBUTING.zh-CN.md
  CONTRIBUTING.md
Labels: CommitMessage::Qualified

#11555 docs(components): [date-picker] add popper-options prop
  docs/en-US/component/date-picker.md
  docs/en-US/component/form.md
Labels: CommitMessage::Qualified

#11714 fix(components): [autocomplete] clearable and disabled props not working
  packages/components/autocomplete/src/autocomplete.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11700 chore(components): [table] fix table config typo
  packages/components/table/src/config.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11718 fix(docs): [search] fix navigate error when enter pressed
  docs/.vitepress/vitepress/components/navbar/vp-search.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11711 docs: [form] add FormRules type assertion
  docs/examples/form/custom-validation.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11682 fix(components): adjust menu close api
  packages/components/menu/src/menu.ts
Labels: CommitMessage::Qualified

#11683 style(components): [breadcrumb] item use inline-flex
  packages/theme-chalk/src/breadcrumb.scss
Labels: CommitMessage::Qualified

#11297 fix(components): [select] fix the hoverIndex display error
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#11724 fix(components): [tabs] add deep attribute to watch
  packages/components/tabs/src/tab-nav.tsx
Labels: CommitMessage::Qualified

#11734 fix(components): [select] add popper-options prop
  docs/en-US/component/select.md
  packages/components/select/src/select.vue
Labels: CommitMessage::Qualified

#11749 refactor(components): [config-provider]
  packages/components/button/src/use-button.ts
  packages/components/config-provider/__tests__/config-provider.test.tsx
  packages/components/config-provider/index.ts
  packages/components/config-provider/src/config-provider-props.ts
  packages/components/config-provider/src/config-provider.ts
  packages/components/config-provider/src/constants.ts
  packages/components/config-provider/src/hooks/use-global-config.ts
  packages/components/dialog/src/use-dialog.ts
  packages/components/form/src/hooks/use-form-common-props.ts
  packages/components/message/__tests__/message.test.ts
  packages/components/message/src/message.vue
  packages/components/message/src/method.ts
  packages/element-plus/make-installer.ts
  packages/hooks/__tests__/use-locale.test.tsx
  packages/hooks/__tests__/use-namespace.test.tsx
  packages/hooks/index.ts
  packages/hooks/use-id/index.ts
  packages/hooks/use-locale/index.ts
  packages/hooks/use-namespace/index.ts
  packages/hooks/use-popper-container/index.ts
  packages/hooks/use-z-index/index.ts
  packages/tokens/index.ts
Labels: CommitMessage::Qualified

#11731 fix(components): [tabs] tab-bar need to adapt to tabs width change
  packages/components/tabs/src/tab-nav.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11660 refactor(tooltip): replace any to OnlyChildExpose
  packages/components/tooltip/src/trigger.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review
