Repository element-plus/element-plus, pull requests merged in 2023-08, with the labels that each got.

#11462 fix(components): [cascader] checkbox sync error
  packages/components/cascader-panel/src/index.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13844 fix(components): [avatar] set img tag's width attribute
  packages/theme-chalk/src/avatar.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13804 Doc/figma
  docs/.vitepress/crowdin/en-US/pages/resource.json
  docs/.vitepress/vitepress/components/globals/resource.vue
  docs/.vitepress/vitepress/components/globals/resources/figma-variables-svg.vue
  docs/components.d.ts
  docs/unocss.config.ts
Labels: CommitMessage::Qualified

#13699 fix(components): [select] abnormal focus when click tags
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/components/tooltip/src/tooltip.vue
Labels: CommitMessage::Qualified

#13833 docs: logo and parallax add drop-shadow
  docs/.vitepress/vitepress/components/globals/parallax-home.vue
  docs/.vitepress/vitepress/components/vp-navbar.vue
Labels: CommitMessage::Qualified

#13533 fix(components): [select] clearIcon did not work with form statusIcon
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13849 docs: fix example ts error
  docs/examples/autocomplete/remote-search.vue
Labels: CommitMessage::Qualified

#13876 chore(components): [date-picker] correct typo in test file
  packages/components/date-picker/__tests__/date-picker.test.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13743 docs(components): [pagination] correct text & icon priority
  docs/en-US/component/pagination.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13799 feat(ci): enable provenance
  .github/workflows/publish-npm-nightly.yml
  scripts/publish.sh
Labels: CommitMessage::Qualified

#13902 test(components): [tree] custom label and children test case
  packages/components/tree/__tests__/tree.test.ts
Labels: CommitMessage::Qualified

#13911 docs: fix official migration reference link
  docs/en-US/guide/migration.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13913 refactor(components): [form-label-wrap] use getStyle method
  packages/components/form/src/form-label-wrap.tsx
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13879 fix(components): [select] fix set value error(#13872)
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13918 refactor(components): [table] reuse rAF
  packages/components/table/src/table-body/index.ts
Labels: CommitMessage::Qualified

#13773 test(components): add test case for delay of dialog
  packages/components/dialog/__tests__/dialog.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12216 fix(components): [autocomplete] tooltip offset
  packages/components/autocomplete/src/autocomplete.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11869 feat(components): [card] add body class
  docs/en-US/component/card.md
  packages/components/card/__tests__/card.test.tsx
  packages/components/card/src/card.ts
  packages/components/card/src/card.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13651 refactor: [date-picker] rename time-arrow-control
  docs/en-US/component/datetime-picker.md
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
Labels: CommitMessage::Qualified

#13950 docs(components): [form] modify props description
  docs/en-US/component/form.md
  packages/components/form/src/form-item.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10640 fix(components): fix the problem that chrome 72 table doesnotdisplaydata
  packages/components/table/src/table-body/render-helper.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13908 fix(components): [table] add table selection checkbox aria-labels
  packages/components/table/src/config.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13490 fix(components): [upload] fix empty array error
  packages/components/upload/src/ajax.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11995 fix(components): [select] backspace delete disabled option
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13935 fix(components): [tree-v2] modify the condition for when the value of currentKey is 0
  packages/components/tree-v2/__tests__/tree.test.ts
  packages/components/tree-v2/src/composables/useTree.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13584 fix(components): [table-v2] calculate the width of MainTable in the same way
  packages/components/table-v2/src/table-v2.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13936 fix(components): [radio checkbox] fix click event triggered twice
  packages/components/checkbox/src/checkbox-button.vue
  packages/components/checkbox/src/checkbox.vue
  packages/components/radio/src/radio-button.vue
  packages/components/radio/src/radio.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13504 fix(components): fix the attribute conflict
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/__tests__/date-time-picker.test.tsx
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13979 chore(components): [autocomplete] fix the comment description error
  packages/components/autocomplete/src/autocomplete.ts
Labels: CommitMessage::Qualified

#13988 chore: update readme
  README.md
Labels: CommitMessage::Qualified

#13301 docs(components): [select] use new display tag
  docs/en-US/component/select.md
  packages/components/select/src/option-group.vue
  packages/components/select/src/option.vue
  packages/components/select/src/select.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14014 chore(docs): updating the implementation of the theme switch button
  docs/.vitepress/vitepress/components/common/vp-switch.vue
  docs/.vitepress/vitepress/components/common/vp-theme-toggler.vue
  docs/.vitepress/vitepress/components/icons/dark.vue
  docs/.vitepress/vitepress/components/icons/light.vue
  docs/components.d.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13212 fix(components): [dropdown] adjust onItemLeave trigger
  packages/components/dropdown/src/dropdown.vue
Labels: CommitMessage::Qualified

#14037 chore: format code
  docs/en-US/component/select.md
  docs/en-US/component/table-v2.md
Labels: CommitMessage::Qualified

#14053 refactor(components): [upload] remove useless useSlot
  packages/components/upload/src/upload.vue
Labels: CommitMessage::Qualified

#13374 fix(components): [select] fix the logic of updating selected data
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13641 docs(components): add attr version tag
  docs/en-US/component/cascader.md
  docs/en-US/component/color-picker.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/dialog.md
  docs/en-US/component/dropdown.md
  docs/en-US/component/form.md
  docs/en-US/component/image.md
  docs/en-US/component/input-number.md
  docs/en-US/component/menu.md
  docs/en-US/component/message-box.md
  docs/en-US/component/rate.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/table.md
  docs/en-US/component/time-picker.md
  docs/en-US/component/tree-v2.md
  docs/en-US/component/tree.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13377 fix(components): [date-picker] fix the logic of checking the date range
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13033 docs(components): [transfer] use new display tag
  docs/en-US/component/transfer.md
  packages/components/transfer/src/transfer.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13386 feat(components): [cascader] add max-collpase-tags prop
  docs/en-US/component/cascader.md
  docs/examples/cascader/multiple-selection.vue
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/src/cascader.ts
  packages/components/cascader/src/cascader.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13976 fix(components): [date-picker] correct onCalendarChange param type
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13822 feat(components): added aria-level attributes for dialog and drawer headers; Fixed input-number's aria-valuenow being null
  docs/en-US/component/dialog.md
  docs/en-US/component/drawer.md
  packages/components/dialog/src/dialog-content.ts
  packages/components/dialog/src/dialog-content.vue
  packages/components/dialog/src/dialog.ts
  packages/components/dialog/src/dialog.vue
  packages/components/drawer/src/drawer.ts
  packages/components/drawer/src/drawer.vue
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14082 docs: [cascader] add version tag
  docs/en-US/component/cascader.md
Labels: CommitMessage::Qualified

#14083 docs: [card] add version tag
  docs/en-US/component/card.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14099 chore(test): [message] wrong tag typo
  packages/components/message/__tests__/message.test.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14106 Revert "refactor(components): [form-label-wrap] use getStyle method (…
  packages/components/form/src/form-label-wrap.tsx
Labels: CommitMessage::Qualified

#14115 D2M
  CHANGELOG.en-US.md
  docs/en-US/component/card.md
  packages/components/form/src/form-label-wrap.tsx
  packages/components/message/__tests__/message.test.ts
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#14074 fix(components): [select] gurad value type error
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14126 refactor(components): [upload] reuse revkoeObjectURL function
  packages/components/upload/src/upload.vue
  packages/components/upload/src/use-handlers.ts
Labels: CommitMessage::Qualified

#14061 fix(components): [collapse] allow nested inputs in ElCollapseItem to …
  packages/components/collapse/src/collapse-item.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14033 chore(docs): [select-v2] add item-height attribute into doc
  docs/en-US/component/select-v2.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14092 fix(components): [rate] bind the textColor property
  docs/en-US/component/rate.md
  packages/components/rate/__tests__/rate.test.tsx
  packages/components/rate/src/rate.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14147 chore(ci): modify nightly release `PKG_NAME` value
  scripts/nightly.sh
Labels: CommitMessage::Qualified

#14020 fix(components): [table] add tabindex to tbody to fix #13991
  packages/components/table/src/table-body/index.ts
  packages/theme-chalk/src/table.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12635 fix(components): [select] fix hover index error when creating option
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review
