Repository element-plus/element-plus, pull requests merged in 2023-05, with the labels that each got.

#12612 fix(components): [tree] fix always trigger drag
  packages/components/tree/src/model/useDragNode.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12596 fix(components): [image] fixed lazyLoad scroll end not loading
  packages/components/image/src/image.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12667 docs(components): [skeleton] use new display tag
  docs/en-US/component/skeleton.md
  packages/components/skeleton/src/skeleton-item.ts
  packages/components/skeleton/src/skeleton.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12519 fix(components): [table-v2] Adjust the expandable
  packages/components/table-v2/__tests__/table-v2.test.tsx
  packages/components/table-v2/src/renderers/cell.tsx
Labels: CommitMessage::Qualified

#12392 docs: [tooltip] Modify sample code
  docs/examples/tooltip/singleton.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12659 docs(style): [tag] use new display tag
  docs/en-US/component/tag.md
  packages/components/check-tag/src/check-tag.ts
  packages/components/check-tag/src/check-tag.vue
  packages/components/tag/src/tag.ts
  packages/components/tag/src/tag.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12677 improvement(locale) : [fa language] in locale package updated.
  packages/locale/lang/fa.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12698 docs(components): [select] create example using value-key attribute
  docs/en-US/component/select.md
  docs/examples/select/value-key.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12575 fix(components): [upload] before-upload change data in promise
  packages/components/upload/__tests__/upload.test.tsx
  packages/components/upload/src/upload-content.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12567 docs(components): [tree] fix description of tree setCheckedKeys method
  docs/en-US/component/tree.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12743 chore(ci): add first pr merge comment
  .github/triage.yml
Labels: CommitMessage::Qualified

#12741 fix(components): [input-number] add Judging if the max is greater than the min
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12511 fix(components): [tree] Fix TreeOptionProps
  packages/components/tree/src/tree.type.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11051 fix(components): [select] fix placeholder display
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12370 fix(components): [TreeSelect] incorrect check event params
  packages/components/tree-select/__tests__/tree-select.test.tsx
  packages/components/tree-select/src/tree.ts
Labels: CommitMessage::Qualified

#12388 feat(components): [carousel] If the carousel height is auto apply item height
  docs/en-US/component/carousel.md
  docs/examples/carousel/auto-height.vue
  docs/examples/carousel/vertical.vue
  packages/components/carousel/__tests__/carousel.test.tsx
  packages/components/carousel/src/carousel-item.vue
  packages/components/carousel/src/carousel.vue
  packages/components/carousel/src/constants.ts
  packages/components/carousel/src/use-carousel-item.ts
  packages/components/carousel/src/use-carousel.ts
  packages/theme-chalk/src/carousel-item.scss
  packages/theme-chalk/src/carousel.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12367 fix(components): [TreeSelect] checking node reset checked cache node
  packages/components/tree-select/__tests__/tree-select.test.tsx
  packages/components/tree-select/src/tree.ts
Labels: CommitMessage::Qualified

#12826 fix(components): [tree-select] incorrect selection when using `checkOnClickNode` without checkbox
  packages/components/tree-select/__tests__/tree-select.test.tsx
  packages/components/tree-select/src/tree.ts
Labels: CommitMessage::Qualified

#12830 chore: update readme
  docs/.vitepress/config/sponsors.ts
  docs/public/images/js-design.png
Labels: CommitMessage::Qualified

#12663 docs(components): [tree-select] use new display tag
  docs/en-US/component/tree-select.md
  packages/components/tree-select/src/tree-select.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12665 docs(components): [page-header] use new display tag
  docs/en-US/component/page-header.md
  packages/components/page-header/src/page-header.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12839 docs: anchor link doesn't scroll to the correct anchor point
  docs/en-US/component/config-provider.md
  docs/en-US/component/icon.md
  docs/en-US/component/table-v2.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12700 docs(components): [time-select] use new display tag
  docs/en-US/component/time-select.md
  packages/components/time-select/src/time-select.ts
  packages/components/time-select/src/time-select.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12842 chore: update readme png
  docs/public/images/js-design.png
  docs/public/images/sponsors/buildadmin.png
Labels: CommitMessage::Qualified

#12801 chore: optimize md plugin config
  docs/.vitepress/plugins/markdown-transform.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12833 fix(components): [popper] prioritise user's popper-style
  packages/components/popper/__tests__/content.test.tsx
  packages/components/popper/src/composables/use-content-dom.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12755 fix(components): [select-v2] Fix border color error
  packages/theme-chalk/src/form.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12913 chore: edit pr template, use copilot pr
  .github/pull_request_template.md
Labels: CommitMessage::Qualified

#12680 docs(components): [pagination] use new display tag
  docs/en-US/component/pagination.md
  packages/components/pagination/src/components/pager.vue
  packages/components/pagination/src/pagination.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12921 chore: update readme
  docs/.vitepress/config/sponsors.ts
  docs/public/images/js-design.png
Labels: CommitMessage::Qualified

#12942 docs: update the tree component filter example data type
  docs/examples/tree/filtering.vue
Labels: CommitMessage::Qualified

#12949 test: [notification] add zIndex test case
  packages/components/notification/__tests__/notification.test.tsx
Labels: CommitMessage::Qualified

#11646 refactor(components): [message-box] remove useRestoreActive
  packages/components/message-box/src/index.vue
  packages/hooks/__tests__/use-restore-active.test.ts
  packages/hooks/index.ts
  packages/hooks/use-restore-active/index.ts
Labels: CommitMessage::Qualified

#11524 fix(components): [select] optimize the triggering of blur event
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/option.vue
  packages/components/select/src/select.vue
  packages/components/select/src/token.ts
  packages/components/select/src/useSelect.ts
  packages/components/tree-select/src/tree.ts
Labels: CommitMessage::Qualified

#12973 chore: format docs
  docs/en-US/component/result.md
  docs/en-US/component/tag.md
Labels: CommitMessage::Qualified

#12349 fix(components): [table] maxHeight shark
  packages/components/table/src/table/style-helper.ts
Labels: CommitMessage::Qualified

#12896 fix(components): [steps] preserve the order of subcomponents
  packages/components/steps/__tests__/steps.test.tsx
  packages/components/steps/src/item.vue
  packages/components/steps/src/steps.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review
