Repository element-plus/element-plus, pull requests merged in 2023-11, with the labels that each got.

#14557 docs(components): [autocomplete] fix website display
  docs/en-US/component/autocomplete.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13175 fix(components): [table] tooltipOptions.showAfter is not effective
  packages/components/table/src/util.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14735 Revert "fix(components): [table] tooltipOptions.showAfter is not effe…
  packages/components/table/src/util.ts
Labels: CommitMessage::Qualified

#14736 D2M
  CHANGELOG.en-US.md
  docs/en-US/component/autocomplete.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/watermark.md
  docs/examples/select-v2/props.vue
  packages/components/dialog/src/use-dialog.ts
  packages/components/rate/__tests__/rate.test.tsx
  packages/components/rate/src/rate.vue
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/option-item.vue
  packages/components/select-v2/src/select-dropdown.tsx
  packages/components/select-v2/src/select.types.ts
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/token.ts
  packages/components/select-v2/src/useAllowCreate.ts
  packages/components/select-v2/src/useProps.ts
  packages/components/select-v2/src/useSelect.ts
  packages/components/select-v2/src/util.ts
  packages/components/tree-select/__tests__/tree-select.test.tsx
  packages/components/tree-select/src/select.ts
  packages/components/watermark/src/useClips.ts
  packages/components/watermark/src/watermark.ts
  packages/components/watermark/src/watermark.vue
  packages/hooks/use-draggable/index.ts
  packages/locale/lang/sw.ts
  packages/theme-chalk/src/form.scss
  packages/theme-chalk/src/rate.scss
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#10357 feat(components): [card] adds footer slot
  docs/en-US/component/card.md
  docs/examples/card/basic.vue
  packages/components/card/src/card.ts
  packages/components/card/src/card.vue
  packages/theme-chalk/src/card.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14602 fix(components): [select] style error in multiple collapseTags
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14754 docs(components): [date-picker] use new dispaly tag
  docs/en-US/component/date-picker.md
  packages/components/date-picker/src/props/date-picker.ts
  packages/components/time-picker/src/common/props.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14317 feat(components): [dialog] append dialog to any element
  docs/en-US/component/dialog.md
  packages/components/dialog/src/dialog.ts
  packages/components/dialog/src/dialog.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14815 docs(docs): fix typo errors in pagination component
  docs/en-US/component/pagination.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14823 test(components): [button] change slot mode
  packages/components/button/__tests__/button.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14871 fix(docs): [watermark] adjusting the text color in dark mode
  docs/examples/watermark/basic.vue
  docs/examples/watermark/multi-line.vue
Labels: CommitMessage::Qualified

#14922 feat(docs): add 2023 figma ui kit
  docs/.vitepress/crowdin/en-US/pages/resource.json
  docs/.vitepress/vitepress/components/globals/resource.vue
  docs/.vitepress/vitepress/components/globals/resources/figma-ui-kit-svg.vue
  docs/components.d.ts
Labels: CommitMessage::Qualified

#14876 feat(components): [select] add header and footer slot
  docs/en-US/component/select.md
  docs/examples/select/custom-footer.vue
  docs/examples/select/custom-header.vue
  packages/components/select/src/select-dropdown.vue
  packages/components/select/src/select.vue
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/select-dropdown.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14968 chore(element-plus): update @element-plus/icons-vue version
  docs/package.json
  package.json
  packages/components/rate/src/rate.ts
  packages/components/rate/src/rate.vue
  packages/element-plus/package.json
  play/package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#14939 fix(components): [tree] default slots not displayed
  packages/components/tree/__tests__/tree.test.ts
  packages/components/tree/src/tree-node-content.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14969 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/crowdin/en-US/pages/resource.json
  docs/.vitepress/vitepress/components/globals/resource.vue
  docs/.vitepress/vitepress/components/globals/resources/figma-ui-kit-svg.vue
  docs/components.d.ts
  docs/en-US/component/card.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/dialog.md
  docs/en-US/component/pagination.md
  docs/en-US/component/select.md
  docs/examples/card/basic.vue
  docs/examples/select/custom-footer.vue
  docs/examples/select/custom-header.vue
  docs/examples/watermark/basic.vue
  docs/examples/watermark/multi-line.vue
  docs/package.json
  package.json
  packages/components/button/__tests__/button.test.tsx
  packages/components/card/src/card.ts
  packages/components/card/src/card.vue
  packages/components/date-picker/src/props/date-picker.ts
  packages/components/dialog/src/dialog.ts
  packages/components/dialog/src/dialog.vue
  packages/components/rate/src/rate.ts
  packages/components/rate/src/rate.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select-dropdown.vue
  packages/components/select/src/select.vue
  packages/components/time-picker/src/common/props.ts
  packages/components/tree/__tests__/tree.test.ts
  packages/components/tree/src/tree-node-content.vue
  packages/element-plus/package.json
  packages/theme-chalk/src/card.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/date-picker/picker.scss
  packages/theme-chalk/src/select-dropdown.scss
  play/package.json
  pnpm-lock.yaml
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#14982 chore: update readme
  README.md
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/vitepress/components/doc-content/vp-table-of-content.vue
  docs/.vitepress/vitepress/components/home/home-sponsors.vue
  docs/.vitepress/vitepress/components/sponsors/right-big-logo-list.vue
  docs/components.d.ts
  docs/public/images/sponsors/CRMEB-l.png
  docs/public/images/sponsors/CRMEB.png
Labels: CommitMessage::Qualified

#14996 chore: update readme
  README.md
  docs/public/images/sponsors/CRMEB-l.png
  docs/public/images/sponsors/CRMEB.png
Labels: CommitMessage::Qualified

#14534 [Docs] Update homepage
  docs/.vitepress/config.mts
  docs/.vitepress/crowdin/en-US/pages/home.json
  docs/.vitepress/vitepress/components/globals/parallax-home.vue
  docs/en-US/component/typography.md
  docs/examples/watermark/custom.vue
  docs/public/fonts/Inter-ExtraBold.woff2
  packages/theme-chalk/src/reset.scss
Labels: CommitMessage::Qualified

#15000 chore: Update README
  README.md
Labels: CommitMessage::Qualified

#15014 fix(components): [select-v2] popup height is not accurate (#15012)
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15011 chore(docs): Use online fonts in docs
  docs/.vitepress/config/head.ts
  docs/.vitepress/vitepress/components/globals/parallax-home.vue
  docs/en-US/component/typography.md
  docs/public/fonts/Inter-ExtraBold.woff2
  packages/theme-chalk/src/reset.scss
Labels: CommitMessage::Qualified
