Repository element-plus/element-plus, pull requests merged in 2023-09, with the labels that each got.

#14164 fix(i18n): improve Dutch(nl) translation
  packages/locale/lang/nl.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14179 docs(components): message-box
  docs/en-US/component/message-box.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14072 feat(components): [el-pagination] add `teleported` prop
  docs/en-US/component/pagination.md
  packages/components/pagination/src/components/sizes.ts
  packages/components/pagination/src/components/sizes.vue
  packages/components/pagination/src/pagination.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14138 feat(components): [image-viewer] Add rotate event when rotating images
  docs/en-US/component/image.md
  packages/components/image-viewer/src/image-viewer.ts
  packages/components/image-viewer/src/image-viewer.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14200 chore: format
  docs/en-US/component/card.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/input-number.md
  docs/en-US/component/pagination.md
  docs/en-US/component/rate.md
  docs/en-US/component/time-picker.md
  docs/en-US/component/transfer.md
Labels: CommitMessage::Qualified

#14149 refactor(components): [date-picker] add aria-labels to date picker btns
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14209 fix(components): [color-picker] first click should be trigger
  packages/components/color-picker/src/color-picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14015 feat(components): [upload] support async data
  docs/en-US/component/upload.md
  packages/components/upload/__tests__/upload.test.tsx
  packages/components/upload/src/upload-content.vue
  packages/components/upload/src/upload.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14237 fix(docs): [date-picker] `calendar-change` event parameter type error
  docs/en-US/component/date-picker.md
Labels: CommitMessage::Qualified

#14036 docs: refactor switch theme
  docs/.vitepress/vitepress/components/common/vp-theme-toggler.vue
  docs/.vitepress/vitepress/components/full-screen/vp-theme-toggler.vue
  docs/.vitepress/vitepress/components/navbar/vp-theme-toggler.vue
Labels: CommitMessage::Qualified

#14242 fix(docs): [upload] fix the version of supporting async data
  docs/en-US/component/upload.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10344 refactor(components): [date-picker] basic-date-table
  packages/components/date-picker/src/composables/use-basic-date-table.ts
  packages/components/date-picker/src/date-picker-com/basic-date-table.vue
  packages/components/date-picker/src/props/basic-date-table.ts
Labels: Refactor, CommitMessage::Qualified

#13832 fix(components): [collapse] fix accessibility issues
  packages/components/collapse/src/collapse-item.vue
  packages/components/collapse/src/collapse.vue
  packages/theme-chalk/src/collapse.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14262 fix(components): [date-picker] month range should emit `calendar-change`
  docs/en-US/component/date-picker.md
  packages/components/date-picker/src/date-picker-com/panel-month-range.vue
  packages/components/date-picker/src/props/panel-month-range.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14246 fix(components): [input] missing autofocus types
  packages/components/input/src/input.ts
  packages/components/input/src/input.vue
Labels: CommitMessage::Qualified

#14285 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/vitepress/components/common/vp-theme-toggler.vue
  docs/.vitepress/vitepress/components/full-screen/vp-theme-toggler.vue
  docs/.vitepress/vitepress/components/navbar/vp-theme-toggler.vue
  docs/en-US/component/card.md
  docs/en-US/component/collapse.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/form.md
  docs/en-US/component/image.md
  docs/en-US/component/input-number.md
  docs/en-US/component/message-box.md
  docs/en-US/component/pagination.md
  docs/en-US/component/rate.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/time-picker.md
  docs/en-US/component/transfer.md
  docs/en-US/component/upload.md
  packages/components/collapse/src/collapse-item.vue
  packages/components/collapse/src/collapse.vue
  packages/components/color-picker/src/color-picker.vue
  packages/components/date-picker/src/composables/use-basic-date-table.ts
  packages/components/date-picker/src/date-picker-com/basic-date-table.vue
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  packages/components/date-picker/src/date-picker-com/panel-month-range.vue
  packages/components/date-picker/src/props/basic-date-table.ts
  packages/components/date-picker/src/props/panel-month-range.ts
  packages/components/form/src/types.ts
  packages/components/image-viewer/src/image-viewer.ts
  packages/components/image-viewer/src/image-viewer.vue
  packages/components/input/src/input.ts
  packages/components/input/src/input.vue
  packages/components/pagination/src/components/sizes.ts
  packages/components/pagination/src/components/sizes.vue
  packages/components/pagination/src/pagination.ts
  packages/components/rate/__tests__/rate.test.tsx
  packages/components/rate/src/rate.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
  packages/components/table/src/table-body/index.ts
  packages/components/upload/__tests__/upload.test.tsx
  packages/components/upload/src/upload-content.vue
  packages/components/upload/src/upload.ts
  packages/components/upload/src/upload.vue
  packages/components/upload/src/use-handlers.ts
  packages/locale/lang/nl.ts
  packages/theme-chalk/src/collapse.scss
  packages/theme-chalk/src/table.scss
  scripts/nightly.sh
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#14294 chore: update ci npm version
  .github/workflows/publish-npm-nightly.yml
  .github/workflows/publish-npm.yml
Labels: CommitMessage::Qualified

#14295 D2M
  .github/workflows/publish-npm-nightly.yml
  .github/workflows/publish-npm.yml
  CHANGELOG.en-US.md
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#14300 chore: update crowdin version to fix jdk error
  docs/package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#14284 fix(components): [menu] export MenuInstance
  packages/components/menu/index.ts
  packages/components/menu/src/instance.ts
Labels: CommitMessage::Qualified

#13011 fix(components): [carousel] Watch items causing state loss(#13010)
  packages/components/carousel/src/use-carousel.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14307 feat: add menu horizontal height for img center
  docs/examples/menu/left-and-right.vue
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/menu.scss
Labels: CommitMessage::Qualified, Needs Review

#14310 docs(descriptions): fix the `customed style` example
  docs/examples/descriptions/customized-style.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14308 fix(components): [collapse] fix triggering form action when inside it
  packages/components/collapse/src/collapse-item.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14254 docs: [table-v2] modify the type definition of the row slot
  docs/en-US/component/table-v2.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14314 chore(test-utils): fix typos in test description
  packages/components/button/__tests__/button.test.tsx
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14312 fix(docs): [form] `label-position` type error
  docs/examples/form/alignment.vue
Labels: CommitMessage::Qualified

#14225 fix(components): row-class-name bgColor can not cover fixed column
  packages/theme-chalk/src/table.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14325 docs(form): add that `prop` supports dot notation string
  docs/en-US/component/form.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14224 fix(components): [tabs] Fix some events accidentally firing
  packages/components/tabs/src/tabs.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14313 refactor(descriptions): improve types
  packages/components/descriptions/src/description-item.ts
  packages/components/descriptions/src/description.vue
  packages/components/descriptions/src/descriptions-cell.ts
  packages/components/descriptions/src/descriptions-row.ts
  packages/components/descriptions/src/descriptions-row.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12970 feat(components): [tabs] add addIcon slot
  docs/en-US/component/tabs.md
  docs/examples/tabs/customized-add-button-icon.vue
  packages/components/tabs/src/tabs.tsx
Labels: CommitMessage::Qualified

#14337 test(components): [teleport] Fixed spelling error ElTelport to ElTelepot
  packages/components/teleport/__tests__/teleport.test.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14344 feat(components): [form-item]Label attribute for judging modification
  packages/components/form/src/form-item.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14352 refactor(components): [tabs] enhance instance type
  packages/components/tabs/src/tab-nav.tsx
  packages/components/tabs/src/tabs.tsx
Labels: CommitMessage::Qualified

#13698 fix: cannot find type definition file for `element-plus/global`
  packages/element-plus/package.json
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14345 refactor(components): [select] use utils function
  packages/components/select/src/useOption.ts
Labels: CommitMessage::Qualified

#14299 fix(components): [description] use `withDirectives` add custom directive
  packages/components/descriptions/src/descriptions-cell.ts
Labels: CommitMessage::Qualified

#14287 fix(components): fix: update timepicker options when changing locale
  packages/components/time-select/src/time-select.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review
