Repository element-plus/element-plus, pull requests merged in 2023-01, with the labels that each got.

#11107 refactor(components): [image] use standard wheel event
  packages/components/image-viewer/src/image-viewer.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11103 refactor(components): [backtop] use scrollTo with smooth
  packages/components/backtop/src/use-backtop.ts
  packages/utils/__tests__/animation.test.ts
  packages/utils/animation.ts
  packages/utils/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11090 fix(components): [dialog] remove "word-break: break-all;"
  packages/theme-chalk/src/dialog.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11084 fix(components): [InfiniteScroll] keep-alive dom undefined
  packages/components/infinite-scroll/src/index.ts
Labels: CommitMessage::Qualified

#11185 docs: update tree select table
  docs/en-US/component/tree-select.md
Labels: CommitMessage::Qualified, Needs Review

#11003 fix(component): [badge] fix auto width
  docs/examples/badge/basic.vue
  packages/theme-chalk/src/badge.scss
Labels: Contribution::Community, CommitMessage::Qualified

#11149 fix(components): [select] display tags correctly
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#11065 docs(components): [rate]
  docs/en-US/component/rate.md
  packages/components/rate/src/rate.ts
  packages/components/rate/src/rate.vue
Labels: CommitMessage::Qualified

#11064 docs(components): [radio]
  docs/en-US/component/radio.md
  packages/components/radio/src/radio-button.ts
  packages/components/radio/src/radio-group.ts
  packages/components/radio/src/radio.ts
Labels: CommitMessage::Qualified

#11261 chore(components): [tabs] optimize code
  packages/components/tabs/src/tab-nav.tsx
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11270 docs: update dev-faq.md
  docs/en-US/guide/dev-faq.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10670 fix(components): [tree-select] disabled attribute does not take effect
  packages/components/tree-select/src/tree.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11268 fix(components): [message] fix space when offset exists
  packages/components/message/__tests__/message-manager.test.tsx
  packages/components/message/src/instance.ts
  packages/components/message/src/message.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11282 docs(components): [card] fix loading error
  docs/en-US/component/card.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10708 fix(components): default table cell padding SCSS variable fix
  docs/en-US/component/table.md
  packages/components/table/src/table/defaults.ts
  packages/theme-chalk/src/table.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10679 fix(components): [table-column] column miss update due to key (#8528)
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/store/index.ts
  packages/components/table/src/store/watcher.ts
  packages/components/table/src/table-column/index.ts
  packages/components/table/src/table-column/render-helper.ts
  packages/components/table/src/table.vue
  packages/components/table/src/table/key-render-helper.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11357 fix(components): [link] fix the link jump to element-ui
  docs/examples/link/basic.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11325 docs(docs): replaced the discord
  .github/CONTRIBUTING.en-US.md
  .github/CONTRIBUTING.es.md
  .github/CONTRIBUTING.fr-FR.md
  .github/CONTRIBUTING.zh-CN.md
  README.md
  docs/.vitepress/vitepress/components/globals/vp-footer.vue
  docs/en-US/component/table-v2.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11045 feat: integrate use popper
  packages/components/popper/__tests__/content.test.tsx
  packages/components/popper/src/arrow.vue
  packages/components/popper/src/composables/index.ts
  packages/components/popper/src/composables/use-content-dom.ts
  packages/components/popper/src/composables/use-content.ts
  packages/components/popper/src/composables/use-focus-trap.ts
  packages/components/popper/src/content.vue
  packages/components/popper/src/utils.ts
  packages/components/slider/__tests__/slider.test.tsx
  packages/hooks/use-popper/index.ts
  packages/tokens/popper.ts
Labels: CommitMessage::Qualified

#11373 docs(components): [Radio]Fix typo
  docs/en-US/component/radio.md
  packages/components/radio/src/radio-group.ts
  packages/components/radio/src/radio.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review
