Repository element-plus/element-plus, pull requests merged in 2023-06, with the labels that each got.

#12968 chore: rm china mirror redirect
  docs/.vitepress/vitepress/components/vp-app.vue
Labels: CommitMessage::Qualified

#13054 D2M
  .github/pull_request_template.md
  CHANGELOG.en-US.md
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/plugins/markdown-transform.ts
  docs/.vitepress/vitepress/components/vp-app.vue
  docs/en-US/component/pagination.md
  docs/en-US/component/result.md
  docs/en-US/component/tag.md
  docs/examples/tree/filtering.vue
  docs/public/images/js-design.png
  packages/components/message-box/src/index.vue
  packages/components/notification/__tests__/notification.test.tsx
  packages/components/notification/src/notification.ts
  packages/components/notification/src/notification.vue
  packages/components/pagination/src/components/pager.vue
  packages/components/pagination/src/pagination.ts
  packages/components/popper/__tests__/content.test.tsx
  packages/components/popper/src/composables/use-content-dom.ts
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/option.vue
  packages/components/select/src/select.vue
  packages/components/select/src/token.ts
  packages/components/select/src/useSelect.ts
  packages/components/steps/__tests__/steps.test.tsx
  packages/components/steps/src/item.vue
  packages/components/steps/src/steps.vue
  packages/components/table/src/table/style-helper.ts
  packages/components/tree-select/src/tree.ts
  packages/hooks/__tests__/use-restore-active.test.ts
  packages/hooks/index.ts
  packages/hooks/use-restore-active/index.ts
  packages/theme-chalk/src/form.scss
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#13069 fix(components): [backtop] change default visible
  packages/components/backtop/__tests__/backtop.test.tsx
  packages/components/backtop/src/use-backtop.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13007 docs(components): [form] use new display tag
  docs/en-US/component/form.md
  packages/components/form/src/form.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12676 fix(components): [table] add missing append height
  packages/components/table/src/table/defaults.ts
  packages/components/table/src/table/style-helper.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13024 refactor(components): [image] update class by computed and new docs
  docs/en-US/component/image.md
  packages/components/image-viewer/src/image-viewer.ts
  packages/components/image-viewer/src/image-viewer.vue
  packages/components/image/src/image.ts
  packages/components/image/src/image.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12920 fix(components): [table] width of columns become 0 unexpectedly
  packages/components/table/src/store/watcher.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12837 fix(components):[time-picker] add parseFloat to resolve TimePicker offset
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12691 docs(components): [time-picker] use new display tag
  docs/en-US/component/time-picker.md
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/time-picker-com/panel-time-range.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12622 fix(components): [input] fix formatter and parse problem
  packages/components/input/__tests__/input.test.tsx
  packages/components/input/src/input.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12390 perf(components): [select-v2] performance enhancement for initStates
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12678 docs(components): [switch] use new display tag
  docs/en-US/component/switch.md
  packages/components/switch/src/switch.ts
  packages/components/switch/src/switch.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12897 feat(theme-chalk): [form] add default width to Input in inline form
  docs/en-US/component/form.md
  docs/examples/form/inline-form.vue
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/date-picker/picker.scss
  packages/theme-chalk/src/form.scss
  packages/theme-chalk/src/input.scss
Labels: CommitMessage::Qualified

#13116 docs(components): [progress] mark the versions of striped & striped-flow
  docs/en-US/component/progress.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13143 docs(components): [dialog] add deprecated describe
  docs/en-US/component/dialog.md
  packages/components/dialog/src/dialog-content.ts
Labels: CommitMessage::Qualified

#13149 fix(components): [table] fix clearFilter type
  packages/components/table/src/table/utils-helper.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13125 fix(locale) : improve sr translation
  packages/locale/lang/sr.ts
Labels: Contribution::Community, i18n, 1st contribution, CommitMessage::Qualified, Needs Review

#13120 style(theme-chalk): change input-number hover style
  packages/theme-chalk/src/input-number.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13107 style(theme-chalk): change border-left:0 to border-left-color:transparent
  packages/theme-chalk/src/checkbox-button.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12549 fix(components): [form] improve types
  docs/examples/form/custom-validation.vue
  docs/examples/form/validation.vue
  packages/components/form/src/types.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13200 docs(components): [select-v2] correct the description of placeholder
  docs/en-US/component/select-v2.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13165 fix(components): [calendar] improve types
  docs/examples/calendar/header.vue
  packages/components/calendar/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12106 fix(components): [select] filter shake
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#13235 fix(components): [tag] element vertically centered
  packages/theme-chalk/src/tag.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13227 test(components): [cascader] change way to get defineExpose data
  packages/components/cascader/__tests__/cascader.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13231 feat(components): [upload] item add title attribute
  packages/components/upload/src/upload-list.vue
Labels: CommitMessage::Qualified

#13169 feat(components): [Table] add show-overflow-tooltip props
  docs/en-US/component/table.md
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/table-column/index.ts
  packages/components/table/src/table/defaults.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13291 chore: update doc site
  docs/.vitepress/config/sponsors.ts
Labels: CommitMessage::Qualified

#13282 fix(components): [table] adjust the showOverflowTooltip value logic
  packages/components/table/src/table-column/defaults.ts
  packages/components/table/src/table-column/index.ts
Labels: CommitMessage::Qualified

#13325 docs(components): [image] update image slot viewer description
  docs/en-US/component/image.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13132 fix: correct sass map has-key parameter
  docs/.vitepress/vitepress/styles/mixins.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13122 docs(components): [dialog] add description of props modal-class
  docs/en-US/component/dialog.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12181 fix(components): [date-picker] One input affect the other input
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
Labels: CommitMessage::Qualified

#13319 fix(components): [virtual-list] Resetting the vertical scrollbar state
  packages/components/virtual-list/src/builders/build-grid.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#9770 fix(components): [tree] fix node can drop inner
  packages/components/tree/src/model/useDragNode.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13434 chore: update doc
  README.md
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/vitepress/components/home/sponsor-list.vue
  docs/.vitepress/vitepress/components/sponsors/right-richtext-list.vue
  docs/public/images/sponsors/MISBoot.png
Labels: CommitMessage::Qualified

#13375 fix(theme-chalk): [form] remove default width of Input in inline form
  docs/en-US/component/form.md
  docs/en-US/component/input.md
  docs/examples/form/inline-form.vue
  packages/theme-chalk/src/form.scss
Labels: CommitMessage::Qualified

#13435 chore: update doc
  README.md
Labels: CommitMessage::Qualified
