Repository element-plus/element-plus, pull requests merged in 2023-10, with the labels that each got.

#14375 fix(components): [popper] invalid when props z-index is zero
  packages/components/popper/src/composables/use-content-dom.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14335 chore(MessageBox): unused keyframe
  packages/theme-chalk/src/message-box.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14443 fix(theme-chalk): tabel tr bg in dark mode
  packages/theme-chalk/src/common/var.scss
Labels: CommitMessage::Qualified

#14354 fix(components): [date-picker] slot compatible with Vue3.3.x
  packages/components/date-picker/src/date-picker-com/basic-cell-render.tsx
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14473 chore(components): [table] fix typo
  packages/components/table/src/table-header/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14321 fix(components): [select-v2] read properties of null
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14480 fix(play): apply esbuild plugin to tsx component
  play/vite.config.ts
Labels: CommitMessage::Qualified

#14064 fix(components): [color-picker] exposed show method wrong behavior
  packages/components/color-picker/src/color-picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14236 feat(components): watermark component
  docs/.vitepress/crowdin/en-US/pages/component.json
  docs/en-US/component/watermark.md
  docs/examples/watermark/basic.vue
  docs/examples/watermark/custom.vue
  docs/examples/watermark/image.vue
  docs/examples/watermark/multi-line.vue
  packages/components/watermark/__tests__/__snapshots__/watermark.test.tsx.snap
  packages/components/watermark/__tests__/watermark.test.tsx
  packages/components/watermark/index.ts
  packages/components/watermark/src/useClips.ts
  packages/components/watermark/src/utils.ts
  packages/components/watermark/src/watermark.ts
  packages/components/watermark/src/watermark.vue
  packages/components/watermark/style/index.ts
  packages/element-plus/component.ts
  typings/components.d.ts
Labels: Contribution::Community, 1st contribution, Project::New Component, CommitMessage::Qualified, Needs Review

#14496 docs(components): [dialog] docs description abnormal
  docs/en-US/component/dialog.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14500 docs(components): [watermark] update doc
  docs/en-US/component/watermark.md
Labels: CommitMessage::Qualified

#11742 fix(components): [table] table-layout auto fixed by sticky
  packages/components/table/src/table.vue
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/table.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14011 refactor(components): [checkbox] set the label default value to `undefined`
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/checkbox/src/checkbox.ts
  packages/components/checkbox/src/composables/use-checkbox-status.ts
Labels: breaking change, CommitMessage::Qualified

#12174 fix(components): [carousel] two length transform optimize
  packages/components/carousel/__tests__/carousel.test.tsx
  packages/components/carousel/src/carousel.vue
  packages/components/carousel/src/use-carousel.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14244 feat(components): [color-picker] add focus and blur event
  docs/en-US/component/color-picker.md
  packages/components/color-picker/__tests__/color-picker.test.tsx
  packages/components/color-picker/src/color-picker.ts
  packages/components/color-picker/src/color-picker.vue
  packages/hooks/__tests__/use-focus-controller.test.tsx
  packages/hooks/use-focus-controller/index.ts
  packages/theme-chalk/src/color-picker.scss
Labels: CommitMessage::Qualified

#12673 docs(components): [descriptions] use new display tag
  docs/en-US/component/descriptions.md
  packages/components/descriptions/src/description-item.ts
  packages/components/descriptions/src/description.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14117 fix(components): inline style doesn't use the custom sass setting value
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14315 fix(components): [table] fix summary row cells on table with layout auto not aligned with data cells
  packages/components/table/src/table-footer/index.ts
  packages/components/table/src/table.vue
  packages/theme-chalk/src/table.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14471 fix(components): [upload] icon style abnormal
  packages/theme-chalk/src/upload.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14489 feat(docs): theme switch use startViewTransition api
  docs/.vitepress/vitepress/components/common/vp-theme-toggler.vue
  docs/.vitepress/vitepress/styles/base.scss
Labels: CommitMessage::Qualified

#14523 fix(components): [table] show-summary style error when table-layout=auto
  packages/components/table/src/table.vue
  packages/theme-chalk/src/table.scss
Labels: CommitMessage::Qualified

#14322 fix(components): [checkbox] indeterminate checkbox a11y fix
  packages/components/checkbox/src/checkbox.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14503 feat(components): [select] accessibility enhancement
  docs/en-US/component/scrollbar.md
  packages/components/scrollbar/src/scrollbar.ts
  packages/components/scrollbar/src/scrollbar.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/option.vue
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#14120 feat(components): [image-viewer] add `minScale` and `maxScale`
  docs/en-US/component/image.md
  docs/examples/image/image-preview.vue
  packages/components/image-viewer/src/image-viewer.ts
  packages/components/image-viewer/src/image-viewer.vue
  packages/components/image/src/image.ts
  packages/components/image/src/image.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14532 docs: update version tag
  docs/.vitepress/crowdin/en-US/pages/component.json
  docs/en-US/component/tabs.md
Labels: CommitMessage::Qualified

#13135 fix(components): [sub-menu] style error in collapsed state
  packages/theme-chalk/src/menu.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13693 fix(components): [menu] remove excess inline styles
  packages/components/menu/src/sub-menu.ts
  packages/theme-chalk/src/menu.scss
Labels: CommitMessage::Qualified

#14330 feat(components): [date-picker] add dateFormat and timeFormat props
  docs/en-US/component/datetime-picker.md
  docs/examples/datetime-picker/date-and-time-formats-panel.vue
  packages/components/date-picker/__tests__/date-time-picker.test.tsx
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  packages/components/date-picker/src/props/shared.ts
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/common/props.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#11976 fix(components): [text] not support multi-line ellipsis
  docs/en-US/component/text.md
  docs/examples/text/truncated.vue
  packages/components/text/__tests__/text.test.tsx
  packages/components/text/src/text.ts
  packages/components/text/src/text.vue
  packages/theme-chalk/src/text.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13263 refactor(components)!: [select-v2] value-key is used for object select
  docs/examples/select-v2/use-valueKey.vue
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/select-dropdown.tsx
  packages/components/select-v2/src/useSelect.ts
Labels: breaking change, CommitMessage::Qualified

#14541 chore: action memory
  .github/workflows/publish-docs-deploy-manual.yml
  .github/workflows/publish-docs-deploy.yml
Labels: CommitMessage::Qualified

#14542 docs(components): [watermark] update font
  docs/en-US/component/watermark.md
Labels: CommitMessage::Qualified

#14551 test(components): [alert] change test case to match description
  packages/components/alert/__tests__/alert.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14552 fix(components): inconsistent style rounded button
  packages/theme-chalk/src/button.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14553 fix(components): prevent carousel from auto playing
  packages/components/carousel/src/use-carousel.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12701 docs(components): [upload] use new display tag
  docs/en-US/component/upload.md
  packages/components/upload/src/upload-list.vue
  packages/components/upload/src/upload.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14319 feat(components): [switch] add label attribute for accessibility
  docs/en-US/component/switch.md
  packages/components/switch/src/switch.ts
  packages/components/switch/src/switch.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14564 fix(components): [watermark] missing the CSS file
  global.d.ts
  packages/components/index.ts
  packages/components/watermark/style/css.ts
Labels: CommitMessage::Qualified

#14573 fix(theme-chalk): menu horizontal popover height, close #14566
  packages/theme-chalk/src/menu.scss
Labels: CommitMessage::Qualified

#14565 fix(components): [select] input height calculation error
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#14587 D2M
  .github/workflows/publish-docs-deploy-manual.yml
  .github/workflows/publish-docs-deploy.yml
  CHANGELOG.en-US.md
  docs/en-US/component/switch.md
  docs/en-US/component/upload.md
  docs/en-US/component/watermark.md
  global.d.ts
  packages/components/alert/__tests__/alert.test.tsx
  packages/components/carousel/src/use-carousel.ts
  packages/components/index.ts
  packages/components/select/src/useSelect.ts
  packages/components/switch/src/switch.ts
  packages/components/switch/src/switch.vue
  packages/components/upload/src/upload-list.vue
  packages/components/upload/src/upload.ts
  packages/components/watermark/style/css.ts
  packages/theme-chalk/src/button.scss
  packages/theme-chalk/src/menu.scss
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#12757 fix(components): [select] Fix border and shadow color error
  packages/theme-chalk/src/form.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14618 fix(components): [message-box] uncaught on draggable
  packages/hooks/use-draggable/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14660 feat(i18n): add Swahili(sw) translation
  packages/locale/lang/sw.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14656 fix(components): [select-v2] label error when value not in the options
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/useSelect.ts
Labels: CommitMessage::Qualified

#14622 fix(components): [rate] Fix the background rate when decimal
  packages/components/rate/__tests__/rate.test.tsx
  packages/components/rate/src/rate.vue
  packages/theme-chalk/src/rate.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14373 fix(components): [dialog] fix el-dialog z-index bug
  packages/components/dialog/src/use-dialog.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14688 fix(components): [dialog] consistent imports of lodash
  packages/components/dialog/src/use-dialog.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14603 fix(components): [tree-select] v-model invalid when source changes
  packages/components/tree-select/__tests__/tree-select.test.tsx
  packages/components/tree-select/src/select.ts
Labels: CommitMessage::Qualified
