Repository element-plus/element-plus, pull requests merged in 2023-07, with the labels that each got.

#13440 chore: update doc
  docs/.vitepress/config/sponsors.ts
Labels: CommitMessage::Qualified

#13402 fix(components): [checkbox] default after border color is transparent
  packages/theme-chalk/src/checkbox.scss
Labels: CommitMessage::Qualified

#12805 fix(components): [table] multiple line ellipsis tooltip takes effect
  packages/components/table/src/table-body/events-helper.ts
Labels: CommitMessage::Qualified

#13424 fix(style): [select] tooltip positioning is incorrect
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13446 fix: tree content checkbox height larger than item height, close #13396
  packages/theme-chalk/src/checkbox.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/tree.scss
Labels: CommitMessage::Qualified

#13465 docs: [progress] remove useless style
  docs/examples/progress/circular-progress-bar.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13462 docs: tooltip set max-width
  docs/.vitepress/vitepress/components/globals/vp-api-typing.vue
Labels: CommitMessage::Qualified

#13467 chore: format code
  docs/en-US/component/dialog.md
  docs/en-US/component/progress.md
  packages/theme-chalk/src/checkbox-button.scss
Labels: CommitMessage::Qualified

#13470 docs(components): [message-box]
  docs/en-US/component/message-box.md
Labels: CommitMessage::Qualified

#13484 docs(components): [tree-v2] add some disabled nodes
  docs/examples/tree-v2/disabled.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13498 fix: add more exports types
  packages/element-plus/package.json
Labels: CommitMessage::Qualified

#13516 fix(components): [color-picker] fix incorrect cursor position
  packages/components/color-picker/__tests__/color-picker.test.tsx
  packages/components/color-picker/src/color-picker.vue
Labels: CommitMessage::Qualified

#13536 chore: update renovate config
  .github/renovate.json5
Labels: CommitMessage::Qualified

#13556 style(theme-chalk): [table] fix th font weight
  packages/components/table/style/css.ts
  packages/components/table/style/index.ts
  packages/theme-chalk/src/table.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13264 fix(components): [input] lose focus when click suffix icon
  packages/components/input/src/input.vue
  packages/hooks/__tests__/use-focus-controller.test.tsx
  packages/hooks/index.ts
  packages/hooks/use-focus-controller/index.ts
  packages/theme-chalk/src/input.scss
Labels: CommitMessage::Qualified

#13591 D2M
  .github/renovate.json5
  CHANGELOG.en-US.md
  README.md
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/vitepress/components/globals/vp-api-typing.vue
  docs/.vitepress/vitepress/components/home/sponsor-list.vue
  docs/.vitepress/vitepress/components/sponsors/right-richtext-list.vue
  docs/.vitepress/vitepress/styles/mixins.scss
  docs/en-US/component/dialog.md
  docs/en-US/component/form.md
  docs/en-US/component/image.md
  docs/en-US/component/input.md
  docs/en-US/component/message-box.md
  docs/en-US/component/progress.md
  docs/examples/form/inline-form.vue
  docs/examples/progress/circular-progress-bar.vue
  docs/examples/tree-v2/disabled.vue
  docs/public/images/sponsors/MISBoot.png
  packages/components/color-picker/__tests__/color-picker.test.tsx
  packages/components/color-picker/src/color-picker.vue
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  packages/components/input/src/input.vue
  packages/components/progress/src/progress.vue
  packages/components/select/src/option.vue
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/table-body/events-helper.ts
  packages/components/table/style/css.ts
  packages/components/table/style/index.ts
  packages/components/tree/src/model/useDragNode.ts
  packages/components/virtual-list/src/builders/build-grid.ts
  packages/element-plus/package.json
  packages/hooks/__tests__/use-focus-controller.test.tsx
  packages/hooks/index.ts
  packages/hooks/use-focus-controller/index.ts
  packages/theme-chalk/src/checkbox-button.scss
  packages/theme-chalk/src/checkbox.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/form.scss
  packages/theme-chalk/src/input.scss
  packages/theme-chalk/src/table.scss
  packages/theme-chalk/src/tree.scss
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#13620 refactor(components): [input] extract InputInstance
  packages/components/input/index.ts
  packages/components/input/src/instance.ts
Labels: CommitMessage::Qualified

#13632 fix(components): [input] fix textarea disabled box-shadow
  packages/theme-chalk/src/input.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13644 docs: [input] list the acceptable values of type
  docs/en-US/component/input.md
Labels: CommitMessage::Qualified

#13362 docs(components): [table-v2] update the type description for Events
  docs/en-US/component/table-v2.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13358 fix(components): [collapse-transition] fixed transition canceled bug
  packages/components/collapse-transition/src/collapse-transition.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13499 docs(components): [dialog] use new display tag
  docs/en-US/component/dialog.md
  packages/components/dialog/src/dialog-content.ts
  packages/components/dialog/src/dialog-content.vue
  packages/components/dialog/src/dialog.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13616 fix(components): [tree] fix expand-icon.is-leaf prevent click event
  packages/theme-chalk/src/tree.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13676 chore(docs): format message-box
  docs/en-US/component/message-box.md
Labels: CommitMessage::Qualified

#13691 docs(build): add required attribute to the tag plugin
  docs/.vitepress/plugins/tag.ts
  docs/.vitepress/vitepress/styles/content/tag-content.scss
  docs/en-US/component/table-v2.md
Labels: CommitMessage::Qualified

#13158 fix(components): [focus-trap] Fixed the function that removed the listener
  packages/components/focus-trap/src/focus-trap.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13121 fix(components): [table] add filteredValue watcher
  packages/components/table/src/table-column/watcher-helper.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12647 fix(components): [autocomplete] improve a11y
  packages/components/autocomplete/__tests__/autocomplete.test.tsx
  packages/components/autocomplete/src/autocomplete.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13637 refactor(components): [upload] fix the type of file
  packages/components/upload/src/upload.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13677 docs(components): [drawer]
  docs/en-US/component/drawer.md
Labels: CommitMessage::Qualified

#13664 fix(components): [select] fix for confusing click behaviour
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13696 refactor(components): [menu] adjust default value of fallbackPlacements
  packages/components/menu/src/sub-menu.ts
Labels: CommitMessage::Qualified

#13695 fix(theme-chalk): [menu] the popup menu has 2px border at the bottom
  packages/theme-chalk/src/menu.scss
Labels: CommitMessage::Qualified

#13550 fix(components): [row] align="top" is not working properly
  packages/components/row/src/row.ts
  packages/components/row/src/row.vue
  packages/theme-chalk/src/row.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13562 docs(components): [row] remove the default value of align
  docs/en-US/component/layout.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12189 chore: prevent warnings while running test cases
  packages/components/breadcrumb/src/breadcrumb-item.vue
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/hooks/__tests__/use-id.test.tsx
  packages/hooks/__tests__/use-lockscreen.test.tsx
  packages/hooks/__tests__/use-popper-container.test.tsx
  packages/hooks/use-namespace/index.ts
  packages/hooks/use-z-index/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12294 fix(components): [cascader] reactive size change
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/src/cascader.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13715 fix(components): [collapse-transition] remove redundant code
  packages/components/collapse-transition/src/collapse-transition.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13749 fix(hooks): [use-focus-controller] remove unnecessary role attributes
  packages/hooks/use-focus-controller/index.ts
Labels: CommitMessage::Qualified

#13768 chore(components): [input] fix inputStyle comment typo
  packages/components/input/src/input.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13618 chore(components): [date-picker] export instasnce type
  packages/components/date-picker/index.ts
  packages/components/date-picker/src/date-picker.tsx
  packages/components/date-picker/src/instance.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13655 fix(components): [date-picker] disable button if now is disabled
  packages/components/date-picker/__tests__/date-time-picker.test.tsx
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
Labels: CommitMessage::Qualified

#13726 test(components): [button] add test cases for using props of form and form-item
  packages/components/button/__tests__/button.test.tsx
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13746 feat(components): [switch] add custom action icon prop
  docs/en-US/component/switch.md
  docs/examples/switch/custom-action-icon.vue
  packages/components/switch/__tests__/switch.test.tsx
  packages/components/switch/src/switch.ts
  packages/components/switch/src/switch.vue
Labels: CommitMessage::Qualified

#12938 fix(components): [el-table] rangeWidth dealing with loss of precision
  packages/components/table/src/table-body/events-helper.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13752 docs: align ::marker and anchor on the same line in firefox
  docs/.vitepress/vitepress/styles/content/table-of-content.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#13771 docs(components): [switch] add version tag & fix typo
  docs/en-US/component/switch.md
  packages/components/switch/src/switch.ts
Labels: CommitMessage::Qualified
