Repository element-plus/element-plus, pull requests merged in 2024-05, with the labels that each got.

#16733 docs: change some examples label to aria-label
  docs/examples/date-picker/date-range.vue
  docs/examples/date-picker/enter-date.vue
  docs/examples/form/accessibility.vue
  docs/examples/form/alignment.vue
  docs/examples/form/size-control.vue
  docs/examples/form/validation.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16740 docs(examples): change el-date-picker label to aria-label
  docs/examples/form/size-control.vue
  docs/examples/form/validation.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16744 chore(dev): add unocss and delete vite vscode config
  .vscode/extensions.json
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16743 chore(scripts): fix type error
  scripts/build-table.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16727 test: add coverage exlude
  vitest.config.mts
Labels: CommitMessage::Qualified

#16764 chore: update cn site link
  README.md
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/vitepress/components/globals/vp-footer.vue
  docs/.vitepress/vitepress/components/sponsors/right-logo-small-list.vue
  docs/public/images/sponsors/fantastic-admin-l.png
  docs/public/images/sponsors/fantastic-admin.png
Labels: CommitMessage::Qualified

#16765 chore: rm hot jar
  docs/.vitepress/config/head.ts
Labels: CommitMessage::Qualified

#16752 chore(dev): add code save auto fix eslint warn
  .vscode/settings.json
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16771 chore: update doc ui
  docs/.vitepress/vitepress/components/sponsors/right-big-logo-list.vue
  docs/.vitepress/vitepress/components/sponsors/right-logo-small-list.vue
  docs/.vitepress/vitepress/components/sponsors/right-richtext-list.vue
  docs/.vitepress/vitepress/components/vp-sponsors.vue
Labels: CommitMessage::Qualified

#16772 chore(other): update badge
  README.md
Labels: CommitMessage::Qualified

#16755 feat(components): [form] export fields
  docs/en-US/component/form.md
  packages/components/form/__tests__/form.test.tsx
  packages/components/form/src/form.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16737 chore: set `package-manager-strict` to false
  .npmrc
Labels: CommitMessage::Qualified

#16791 chore(test-utils): update vitest version
  package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#16778 docs(examples): delete form validate return and perfect types
  docs/en-US/component/form.md
  docs/examples/form/custom-validation.vue
  docs/examples/form/form-items.vue
  docs/examples/form/number-validate.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16820 chore(css): format segmented.scss
  packages/theme-chalk/src/segmented.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16824 test(components): [select] modify the grouping of several test cases
  packages/components/select/__tests__/select.test.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16833 chore: update doc ui
  docs/.vitepress/vitepress/components/sponsors/right-big-logo-list.vue
  docs/.vitepress/vitepress/components/sponsors/right-logo-small-list.vue
  docs/.vitepress/vitepress/components/sponsors/right-richtext-list.vue
  docs/.vitepress/vitepress/components/vp-sponsors.vue
Labels: CommitMessage::Qualified

#16849 D2M
  .npmrc
  .nvmrc
  .vscode/extensions.json
  .vscode/settings.json
  CHANGELOG.en-US.md
  README.md
  docs/.vitepress/config/head.ts
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/vitepress/components/globals/vp-footer.vue
  docs/.vitepress/vitepress/components/sponsors/right-big-logo-list.vue
  docs/.vitepress/vitepress/components/sponsors/right-logo-small-list.vue
  docs/.vitepress/vitepress/components/sponsors/right-richtext-list.vue
  docs/.vitepress/vitepress/components/vp-sponsors.vue
  docs/en-US/component/form.md
  docs/en-US/component/menu.md
  docs/examples/date-picker/date-range.vue
  docs/examples/date-picker/enter-date.vue
  docs/examples/form/accessibility.vue
  docs/examples/form/alignment.vue
  docs/examples/form/custom-validation.vue
  docs/examples/form/form-items.vue
  docs/examples/form/number-validate.vue
  docs/examples/form/size-control.vue
  docs/examples/form/validation.vue
  docs/public/images/sponsors/fantastic-admin-l.png
  docs/public/images/sponsors/fantastic-admin.png
  internal/metadata/package.json
  package.json
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/form/__tests__/form.test.tsx
  packages/components/form/src/form.vue
  packages/components/infinite-scroll/src/index.ts
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/message-box/src/message-box.type.ts
  packages/components/pagination/src/components/jumper.vue
  packages/components/radio/__tests__/radio.test.tsx
  packages/components/select/__tests__/select.test.ts
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/store/watcher.ts
  packages/components/time-picker/src/common/picker.vue
  packages/theme-chalk/src/segmented.scss
  packages/theme-chalk/src/tour.scss
  packages/utils/__tests__/vue/global-node.test.ts
  packages/utils/__tests__/vue/icon.test.ts
  packages/utils/__tests__/vue/install.test.ts
  packages/utils/__tests__/vue/vnode.test.ts
  pnpm-lock.yaml
  scripts/build-table.ts
  vitest.config.mts
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#16841 docs: add guide for on-demand import with Rspack
  docs/en-US/guide/quickstart.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16834 fix(components): [popper] remove unnecessary conditional judgment
  packages/components/popper/src/content.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16804 fix(types): non-null assertion component name
  packages/components/cascader-panel/index.ts
  packages/components/cascader/index.ts
  packages/components/collapse-transition/index.ts
  packages/components/date-picker/index.ts
  packages/components/select-v2/index.ts
  packages/components/time-picker/index.ts
  packages/components/time-select/index.ts
  packages/components/tree-select/index.ts
  packages/components/tree/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16852 ci: run `test-unit` on node20
  .github/workflows/test-unit.yml
Labels: CommitMessage::Qualified

#16862 docs: add meta `og:description`
  docs/.vitepress/config/head.ts
Labels: CommitMessage::Qualified

#16794 chore: fixed `@element-plus/build-constants` version
  internal/build/package.json
  pnpm-lock.yaml
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16870 chore(build): fix cdn process error
  internal/build/package.json
  internal/build/src/tasks/full-bundle.ts
  pnpm-lock.yaml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16863 test: fix ci image/avatar test error
  packages/components/avatar/__tests__/avatar.test.tsx
  packages/components/image/__tests__/image.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16872 refactor(hooks): unite import origin
  packages/hooks/use-lockscreen/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16888 docs(examples): [form] remove unused ref
  docs/examples/form/size-control.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16868 fix(components): [table] cell tooltip display error
  packages/components/table/src/table-body/events-helper.ts
Labels: CommitMessage::Qualified

#16757 fix(components): [input] unify `async-validator` string length calc
  package.json
  patches/async-validator@4.2.5.patch
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#16929 refactor(components): [virtual-list] remove use-wheel ts-nocheck comments
  packages/components/virtual-list/src/hooks/use-wheel.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16832 fix(components): [select & select-v2] remove-tag when use backspace
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16840 test(component): select remove-tag event triggered by keydown.delelte
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select/__tests__/select.test.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16977 docs(examples): [tree] fix online display abnormality
  docs/examples/tree/custom-node-class.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16943 fix(components): [tree-select] empty slot display error
  packages/components/tree/src/tree.vue
  packages/theme-chalk/src/tree-select.scss
Labels: CommitMessage::Qualified

#16887 fix(components): [color-picker] attrs class
  packages/components/color-picker/src/color-picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16973 docs: [select] add width tip eg link
  docs/en-US/component/select.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17005 docs: `tree-select` group adjustment
  docs/.vitepress/crowdin/en-US/pages/component.json
Labels: CommitMessage::Qualified

#16960 feat(components): [select & select-v2] add label slot
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/examples/select-v2/custom-label.vue
  docs/examples/select/custom-label.vue
  packages/components/select-v2/src/select.vue
  packages/components/select/src/select.vue
Labels: CommitMessage::Qualified

#17009 style(components): [select & select-v2] remove split dash
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/group-item.vue
  packages/components/select-v2/src/useSelect.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/option-group.scss
Labels: CommitMessage::Qualified

#17022 feat(play): feedback components style
  play/main.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15080 fix(components): [date-picker] modelValue typo
  packages/components/time-picker/src/common/props.ts
Labels: CommitMessage::Qualified

#17020 test(components): [select] fix option type warning
  packages/components/select/__tests__/options.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17042 Revert "docs: add guide for on-demand import with Rspack"
  docs/en-US/guide/quickstart.md
Labels: CommitMessage::Qualified

#17043 D2M
  .github/workflows/test-unit.yml
  CHANGELOG.en-US.md
  docs/.vitepress/config/head.ts
  docs/.vitepress/crowdin/en-US/pages/component.json
  docs/.vitepress/vitepress/components/vp-sponsors.vue
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/examples/form/size-control.vue
  docs/examples/select-v2/custom-label.vue
  docs/examples/select/custom-label.vue
  docs/examples/tree/custom-node-class.vue
  internal/build/package.json
  internal/build/src/tasks/full-bundle.ts
  package.json
  packages/components/avatar/__tests__/avatar.test.tsx
  packages/components/cascader-panel/index.ts
  packages/components/cascader/index.ts
  packages/components/collapse-transition/index.ts
  packages/components/color-picker/src/color-picker.vue
  packages/components/date-picker/index.ts
  packages/components/image/__tests__/image.test.tsx
  packages/components/popper/src/content.vue
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/index.ts
  packages/components/select-v2/src/group-item.vue
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/__tests__/options.test.tsx
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/components/table/src/table-body/events-helper.ts
  packages/components/time-picker/index.ts
  packages/components/time-picker/src/common/props.ts
  packages/components/time-select/index.ts
  packages/components/tree-select/index.ts
  packages/components/tree/index.ts
  packages/components/tree/src/tree.vue
  packages/components/virtual-list/src/hooks/use-wheel.ts
  packages/hooks/use-lockscreen/index.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/dropdown.scss
  packages/theme-chalk/src/option-group.scss
  packages/theme-chalk/src/tree-select.scss
  patches/async-validator@4.2.5.patch
  play/main.ts
  pnpm-lock.yaml
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review
