Repository element-plus/element-plus, pull requests merged in 2024-04, with the labels that each got.

#16310 fix(components): [input-number] wrapper padding style is overridden
  packages/theme-chalk/src/input-number.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16363 docs(components): [layout] format responsive layout example
  docs/examples/layout/responsive-layout.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16308 fix(components): [input-number] fix cascading style order
  packages/components/input-number/style/css.ts
  packages/components/input-number/style/index.ts
  packages/theme-chalk/src/index.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16090 refactor(components): [button] use buttonkls
  packages/components/button/src/button.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#12378 fix(components): [table-v2] fixed mode hovering rerender cell
  packages/components/table-v2/src/composables/use-row.ts
  packages/components/table-v2/src/renderers/row.tsx
  packages/components/table-v2/src/table-v2.tsx
  packages/components/table-v2/src/tokens.ts
  packages/components/table-v2/src/use-table.ts
Labels: CommitMessage::Qualified

#16306 docs: fix import locale
  docs/en-US/guide/i18n.md
Labels: CommitMessage::Qualified

#16415 docs(components): [table-v2] `minWidth` and `maxWidth` support type typo
  docs/en-US/component/table-v2.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16190 feat: support node 18+ & update tsx and vitest
  .github/workflows/lint-commit-message.yml
  .github/workflows/pr-docs-build.yml
  .github/workflows/publish-build-product.yml
  .github/workflows/publish-docs-deploy-manual.yml
  .github/workflows/publish-docs-deploy.yml
  .github/workflows/publish-npm-nightly.yml
  .github/workflows/publish-npm.yml
  .github/workflows/publish-size-report.yml
  .github/workflows/staging-docs.yml
  .github/workflows/test-coverage.yml
  .github/workflows/test-ssr.yml
  .github/workflows/test-unit.yml
  CONTRIBUTING.md
  internal/metadata/package.json
  package.json
  packages/components/anchor/__tests__/__snapshots__/anchor.test.tsx.snap
  packages/components/autocomplete/__tests__/autocomplete.test.tsx
  packages/components/watermark/__tests__/__snapshots__/watermark.test.tsx.snap
  packages/hooks/__tests__/use-id.test.tsx
  packages/utils/__tests__/error.test.ts
  packages/utils/__tests__/raf.test.ts
  packages/utils/__tests__/strings.test.ts
  pnpm-lock.yaml
  vitest.config.ts
Labels: CommitMessage::Qualified, Minor Version

#16395 test(hooks): add test for use-intermediate-render
  packages/hooks/__tests__/use-intermediate-render.test.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16473 fix(components): [select-v2] manually set object type modelValue error
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/useSelect.ts
Labels: CommitMessage::Qualified, Needs Review

#16361 feat(components): add empty-values and value-on-clear props
  docs/en-US/component/cascader.md
  docs/en-US/component/config-provider.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/time-picker.md
  docs/en-US/component/time-select.md
  docs/examples/config-provider/empty-values.vue
  docs/examples/select-v2/empty-values.vue
  docs/examples/select/empty-values.vue
  packages/components/cascader/src/cascader.ts
  packages/components/cascader/src/cascader.vue
  packages/components/config-provider/src/config-provider-props.ts
  packages/components/config-provider/src/hooks/use-global-config.ts
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/select.ts
  packages/components/select/src/useSelect.ts
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/common/props.ts
  packages/components/time-select/src/time-select.ts
  packages/components/time-select/src/time-select.vue
  packages/hooks/__tests__/use-empty-values.test.tsx
  packages/hooks/index.ts
  packages/hooks/use-empty-values/index.ts
Labels: breaking change, CommitMessage::Qualified, Minor Version

#16456 fix(components): [select & select-v2] fix filterable double click error
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified, Needs Review

#16443 fix(components): [table] fixed hover on colSpan > 2 background is error
  packages/components/table/src/table-body/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16434 feat(components): [badge] add dotClass、dotStyle、offset props
  docs/en-US/component/badge.md
  docs/examples/badge/offset.vue
  packages/components/badge/src/badge.ts
  packages/components/badge/src/badge.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16498 test(hooks): [use-teleport] add no-client test
  packages/hooks/__tests__/use-teleport.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16508 fix(hooks): [empty-values] warning on modifying computead value
  packages/hooks/use-empty-values/index.ts
Labels: CommitMessage::Qualified

#16499 test(hooks): add use-throttle-render test
  packages/hooks/__tests__/use-throttle-render.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16392 style(components): [col] fix gutter will be hidden when present
  packages/theme-chalk/src/col.scss
  packages/theme-chalk/src/mixins/_col.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16495 fix(components): [input-number] fix binding wheel event warning
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16573 chore: update README
  README.md
  docs/.vitepress/config/sponsors.ts
Labels: CommitMessage::Qualified

#16449 fix(components): [table] fix cell tooltip display error
  packages/components/table/src/table-body/events-helper.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16583 docs: add mastergo ui kit
  docs/.vitepress/crowdin/en-US/pages/resource.json
  docs/.vitepress/vitepress/components/globals/resource.vue
  docs/.vitepress/vitepress/components/globals/resources/master-go-ui-kit-svg.vue
  docs/components.d.ts
Labels: CommitMessage::Qualified

#16585 feat(components): [badge] Add badge-style and badge-class
  docs/en-US/component/badge.md
  packages/components/badge/src/badge.ts
  packages/components/badge/src/badge.vue
Labels: CommitMessage::Qualified

#16517 fix(components): [table] hover style error
  packages/components/table/__tests__/table-test-common.ts
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/table-body/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16433 fix(components): [table] fix grouping head when dynamic column
  packages/components/table/src/table-column/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16590 fix(components): [select-v2] fix has existing option when allow create
  packages/components/select-v2/src/useAllowCreate.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16544 fix(components): [table] table body rerendered when use row-key
  packages/components/table/src/table-body/render-helper.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16572 test: reomve reporter json
  vitest.config.mts
Labels: CommitMessage::Qualified

#16606 docs(examples): [input-number] decrease slot name typo
  docs/examples/input-number/custom.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16542 docs: copy icon content remove unnecessary attribute
  docs/.vitepress/vitepress/components/globals/icons.vue
Labels: CommitMessage::Qualified

#16634 feat(components): [color-picker] add `teleported` prop
  docs/en-US/component/color-picker.md
  packages/components/color-picker/src/color-picker.ts
  packages/components/color-picker/src/color-picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16633 fix: 🐛 update autocomplete default width
  packages/theme-chalk/src/autocomplete.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16635 docs(components): [table-v2] fix dynamic-height examples error
  docs/examples/table-v2/dynamic-height.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16654 improvement(other): Minor change to English phrasing
  packages/components/affix/src/affix.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16621 fix(components): [select] group error when custom option component
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/option-group.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16650 docs(components): [select] unify and enhance version tip
  docs/en-US/component/select.md
  docs/en-US/guide/changelog.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16648 fix(components): [table] return type of function summary-method supports VNode
  docs/en-US/component/table.md
  docs/examples/table/summary.vue
  packages/components/table/src/table/defaults.ts
Labels: CommitMessage::Qualified

#16504 fix(test-utils): fix main export error
  packages/test-utils/package.json
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16323 fix(components): Add missing export
  packages/components/descriptions/index.ts
  packages/components/descriptions/src/description-item.ts
  packages/components/form/src/form.ts
  packages/components/space/src/item.ts
  packages/components/tour/index.ts
  packages/components/tour/src/content.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16668 chore: update readme
  README.md
  docs/.vitepress/config/sponsors.ts
  docs/public/images/sponsors/mele-banner.png
  docs/public/images/sponsors/mele.png
Labels: CommitMessage::Qualified

#16652 feat(components): [form] add validate callback promise type
  packages/components/form/src/form.vue
  packages/components/form/src/types.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16470 fix(components): [table-v2] fix scrolling fail
  packages/components/table-v2/src/table-grid.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16669 test(components): [form] add validate callback call order test
  packages/components/form/__tests__/form.test.tsx
Labels: CommitMessage::Qualified

#16419 fix(components): [select] `isDisabled` is not fresh
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16666 fix(components): [progress] bar background support gradient
  packages/components/progress/__tests__/progress.test.tsx
  packages/components/progress/src/progress.vue
Labels: CommitMessage::Qualified

#16664 fix(components): [select-v2] custom options init error in multiple
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15850 docs: [menu] capitalize descriptions
  docs/en-US/component/menu.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16682 fix(components): [pagination] jumper input label warning
  packages/components/pagination/src/components/jumper.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16688 chore(components): fix test warning
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/form/__tests__/form.test.tsx
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/radio/__tests__/radio.test.tsx
Labels: CommitMessage::Qualified

#16592 fix(compoents): [message-box] adapt `Parameters` extraction rules
  packages/components/message-box/src/message-box.type.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16216 test(utils): [vue] add icon,install,vnode and global-node test
  packages/utils/__tests__/vue/global-node.test.ts
  packages/utils/__tests__/vue/icon.test.ts
  packages/utils/__tests__/vue/install.test.ts
  packages/utils/__tests__/vue/vnode.test.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16720 chore(dev): consistent with the node version required in `package.json`
  .nvmrc
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16665 feat(components): [time-picker] @touchstart add passive
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16725 style(components): tour delete content outline style
  packages/theme-chalk/src/tour.scss
Labels: CommitMessage::Qualified, Needs Review

#16732 docs(examples): perfect some type
  docs/examples/form/size-control.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review
