Repository element-plus/element-plus, pull requests merged in 2024-06, with the labels that each got.

#17049 feat(components): [input] add `is-focus` class name when textarea focus
  packages/components/input/src/input.vue
Labels: CommitMessage::Qualified

#17033 docs: update content using nuxt
  docs/en-US/guide/quickstart.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17039 style(components): [table] th text can be selected
  packages/theme-chalk/src/table.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17036 refactor(components): [watermark] change textBaseline default value to `hanging`
  docs/en-US/component/watermark.md
  packages/components/watermark/src/watermark.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17067 docs(components): [image] change `@error` parameter types
  docs/en-US/component/image.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17078 style(docs): fix fill color of badge in dark mode
  docs/.vitepress/vitepress/components/overview-icons/ov-badge.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17099 docs: change cdn online demo link to correct show result
  docs/en-US/guide/installation.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17113 chore: update doc ui
  README.md
  docs/.vitepress/config/sponsors.ts
  docs/public/images/sponsors/baidayun-logo.png
  docs/public/images/sponsors/baidayun.png
Labels: CommitMessage::Qualified

#17118 D2M
  CHANGELOG.en-US.md
  README.md
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/vitepress/components/overview-icons/ov-badge.vue
  docs/en-US/component/image.md
  docs/en-US/component/watermark.md
  docs/en-US/guide/installation.md
  docs/en-US/guide/quickstart.md
  docs/public/images/sponsors/baidayun-logo.png
  docs/public/images/sponsors/baidayun.png
  packages/components/input/src/input.vue
  packages/components/watermark/src/watermark.vue
  packages/theme-chalk/src/table.scss
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#17098 docs: [table] add example with show overflow tooltip
  docs/en-US/component/table.md
  docs/examples/table/multi-select.vue
  docs/examples/table/show-overflow-tooltip.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17114 docs(examples): [table] column width shows full
  docs/examples/table/fixed-column-and-group-header.vue
  docs/examples/table/fixed-column-and-header.vue
  docs/examples/table/fixed-column.vue
  docs/examples/table/fixed-header-with-fluid-header.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17015 fix(components): [color-picker] replenish enableAlpha contral
  packages/components/color-picker/src/color-picker.vue
  packages/components/color-picker/src/components/predefine.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17127 fix(components): [select] invalid name setting
  packages/components/select/src/select.vue
Labels: CommitMessage::Qualified

#17093 fix(components): [table] dragging cell should not trigger `header-click`
  packages/components/table/src/table-header/index.ts
Labels: CommitMessage::Qualified

#16989 fix(components): [table-v2] the selector is invalid when `row-key` is a number
  packages/components/table-v2/src/composables/use-row.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16364 docs: format docs
  docs/en-US/component/autocomplete.md
  docs/en-US/component/badge.md
  docs/en-US/component/cascader.md
  docs/en-US/component/checkbox.md
  docs/en-US/component/color-picker.md
  docs/en-US/component/config-provider.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/form.md
  docs/en-US/component/input-number.md
  docs/en-US/component/input.md
  docs/en-US/component/message.md
  docs/en-US/component/radio.md
  docs/en-US/component/rate.md
  docs/en-US/component/segmented.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/slider.md
  docs/en-US/component/switch.md
  docs/en-US/component/time-picker.md
  docs/en-US/component/time-select.md
  docs/en-US/component/watermark.md
  play/main.ts
Labels: CommitMessage::Qualified

#17173 docs(docs): uniform default
  docs/en-US/component/anchor.md
  docs/en-US/component/table-v2.md
  docs/en-US/component/tabs.md
  docs/en-US/component/text.md
  docs/en-US/component/tour.md
  docs/en-US/component/tree-v2.md
  docs/en-US/component/tree.md
  docs/en-US/component/watermark.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17181 docs(components): [autocomplete] fetch-suggestions revise type
  docs/en-US/component/autocomplete.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17194 fix(components): [input] class bind error corresponding to dynamic slot
  packages/components/input/src/input.vue
Labels: CommitMessage::Qualified

#17023 fix(components): [table] fit set to false bottom border error
  packages/theme-chalk/src/table.scss
Labels: CommitMessage::Qualified

#17172 chore(vscode): set `md` defaultFormatter to prettier
  .vscode/settings.json
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17096 chore(locale): add non-existing fr translations
  packages/locale/lang/fr.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16748 fix(components): date-picker minDate change unexpectedly
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17252 feat(components): [table] export columns
  docs/en-US/component/table.md
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/table-header/utils-helper.ts
  packages/components/table/src/table.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16714 fix(components): [select-v2] with `teleported="false"` dropdown closes abnormally
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/select.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16393 fix(components): fix iOS select click event listening
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16858 feat(pagination) : add `size` prop
  docs/en-US/component/pagination.md
  docs/examples/pagination/more-elements.vue
  docs/examples/pagination/small-pagination.vue
  packages/components/pagination/__tests__/pagination.test.tsx
  packages/components/pagination/src/pagination.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/pagination.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17235 fix(components): [progress] setting both color and striped is invalid
  packages/components/progress/__tests__/progress.test.tsx
  packages/components/progress/src/progress.vue
Labels: CommitMessage::Qualified

#17161 fix(components): [date-picker] support dynamic setting of `format`
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  packages/components/date-picker/src/date-picker-com/panel-month-range.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17111 feat(components): [form-item]: add `label-position` prop
  docs/en-US/component/form.md
  docs/examples/form/alignment.vue
  packages/components/form/__tests__/form-item.test.tsx
  packages/components/form/src/form-item.ts
  packages/components/form/src/form-item.vue
  packages/components/form/src/form-label-wrap.tsx
  packages/theme-chalk/src/form.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17306 fix(components): [pagination] `size` global adaptation
  packages/components/pagination/src/pagination.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17101 style: css uniformly uses `px`
  packages/theme-chalk/src/drawer.scss
  packages/theme-chalk/src/upload.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17150 feat(components): improve event and supplement docs
  docs/en-US/component/autocomplete.md
  docs/en-US/component/cascader.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/time-picker.md
  docs/en-US/component/time-select.md
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/src/cascader.ts
  packages/components/cascader/src/cascader.vue
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-select/src/time-select.vue
Labels: Contribution::Community, CommitMessage::Qualified

#16990 fix(components): [tree] add missing type reject for LoadFunction
  packages/components/tree/src/tree.type.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17319 flx(component): buttonColor is calculated in the 'var' case
  packages/components/button/src/button-custom.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review
