Repository element-plus/element-plus, pull requests merged in 2024-12, with the labels that each got.

#19079 fix(components): [input-tag] trigger the add of tag when Chinese is Composing
  packages/components/input-tag/src/composables/use-input-tag.ts
Labels: CommitMessage::Qualified

#19084 docs: [table] correct array type display
  docs/en-US/component/table.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19072 docs: [tree-v2] fix props.class type in zh-CN
  docs/en-US/component/tree-v2.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19110 docs: add an overview icon for InputTag
  docs/.vitepress/vitepress/components/overview-icons/index.ts
  docs/.vitepress/vitepress/components/overview-icons/ov-input-tag.vue
  docs/components.d.ts
Labels: CommitMessage::Qualified

#17860 chore(components): improve type for popper effect
  packages/components/menu/src/menu.ts
  packages/components/popper/src/content.ts
  packages/components/popper/src/popper.ts
  packages/components/select-v2/src/defaults.ts
  packages/components/select/src/select.ts
  packages/components/time-select/src/time-select.ts
  packages/components/tooltip-v2/src/content.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19108 chore: stop re-exporting isVNode
  packages/components/message-box/src/messageBox.ts
  packages/components/message/src/method.ts
  packages/components/notification/src/notify.ts
  packages/hooks/use-ordered-children/index.ts
  packages/utils/__tests__/types.test.ts
  packages/utils/types.ts
Labels: CommitMessage::Qualified

#19131 test(components): [notification] `dangerouslyUseHTMLString` test case
  packages/components/notification/__tests__/notify.test.tsx
Labels: CommitMessage::Qualified

#19137 fix(components): [select] use option.isDisabled as the source of truth
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#19101 perf(components): [tree-v2] optimize the performance of setCheckedKeys
  packages/components/tree-v2/src/composables/useCheck.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19145 chore: [form] organize test-related files into test folder
  packages/components/form/__tests__/form-item.test.tsx
  packages/components/form/__tests__/form.test.tsx
  packages/components/form/__tests__/mock-data.tsx
Labels: CommitMessage::Qualified

#19085 refactor(components): [alert] introduce hasDesc helper
  packages/components/alert/src/alert.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19124 feat(components): [dropdown] add triggerKeys attribute
  docs/en-US/component/dropdown.md
  packages/components/dropdown/src/dropdown.ts
  packages/components/dropdown/src/dropdown.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19176 fix(components): [input] disabled state wrapper cursor style
  packages/theme-chalk/src/input.scss
Labels: CommitMessage::Qualified

#19177 feat(components): [tree-v2] `filter-method` support third parameter
  docs/en-US/component/tree-v2.md
  packages/components/tree-v2/src/composables/useFilter.ts
  packages/components/tree-v2/src/types.ts
Labels: CommitMessage::Qualified

#19185 docs:[card] delete excess for card doc
  docs/en-US/component/card.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19140 fix(components): [select-v2] empty value check error in inputRef
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18931 fix(components): [select] modify the logic of update the watch option
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18922 feat(components): [badge] add `content` slot
  docs/en-US/component/badge.md
  docs/examples/badge/customize.vue
  packages/components/badge/__tests__/badge.test.tsx
  packages/components/badge/src/badge.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19204 docs: [tooltip] improve document content and examples
  docs/en-US/component/tooltip.md
  docs/examples/tooltip/advanced-usage.vue
  docs/examples/tooltip/animations.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19219 docs: [container] update example
  docs/examples/container/layout-am.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19238 chore: update doc
  README.md
  docs/.vitepress/config/sponsors.ts
Labels: CommitMessage::Qualified

#19082 fix(components): [table-v2] dynamic height causes overall calculation errors
  packages/components/table-v2/src/composables/use-styles.ts
  packages/components/table-v2/src/use-table.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19252 debug: staging pkg.pr.new
  .github/workflows/publish-pr-commit-pkg.yml
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19254 fix: revert pkg pr new to main version
  .github/workflows/publish-pr-commit-pkg.yml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19258 D2M
  .github/workflows/publish-pr-commit-pkg.yml
  CHANGELOG.en-US.md
  README.md
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/vitepress/components/overview-icons/index.ts
  docs/.vitepress/vitepress/components/overview-icons/ov-input-tag.vue
  docs/.vitepress/vitepress/components/vp-sponsors.vue
  docs/components.d.ts
  docs/en-US/component/badge.md
  docs/en-US/component/card.md
  docs/en-US/component/dropdown.md
  docs/en-US/component/table.md
  docs/en-US/component/tooltip.md
  docs/en-US/component/tree-v2.md
  docs/examples/badge/customize.vue
  docs/examples/container/layout-am.vue
  docs/examples/tooltip/advanced-usage.vue
  docs/examples/tooltip/animations.vue
  packages/components/alert/src/alert.vue
  packages/components/badge/__tests__/badge.test.tsx
  packages/components/badge/src/badge.vue
  packages/components/dropdown/src/dropdown.ts
  packages/components/dropdown/src/dropdown.vue
  packages/components/form/__tests__/form-item.test.tsx
  packages/components/form/__tests__/form.test.tsx
  packages/components/form/__tests__/mock-data.tsx
  packages/components/input-tag/src/composables/use-input-tag.ts
  packages/components/menu/src/menu.ts
  packages/components/message-box/src/messageBox.ts
  packages/components/message/src/method.ts
  packages/components/notification/__tests__/notify.test.tsx
  packages/components/notification/src/notify.ts
  packages/components/popper/src/content.ts
  packages/components/popper/src/popper.ts
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.ts
  packages/components/select/src/useSelect.ts
  packages/components/table-v2/src/composables/use-styles.ts
  packages/components/table-v2/src/use-table.ts
  packages/components/time-select/src/time-select.ts
  packages/components/tooltip-v2/src/content.ts
  packages/components/tree-v2/src/composables/useCheck.ts
  packages/components/tree-v2/src/composables/useFilter.ts
  packages/components/tree-v2/src/types.ts
  packages/hooks/use-ordered-children/index.ts
  packages/theme-chalk/src/input.scss
  packages/utils/__tests__/types.test.ts
  packages/utils/types.ts
  play/vite.config.mts
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#19200 docs(components): update Dialog
  docs/en-US/component/dialog.md
  docs/examples/dialog/events.vue
  docs/examples/dialog/fullscreen.vue
  docs/examples/dialog/modal.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19244 fix(components): [select] resolve 'false' display issue when dropdown hides on search clear
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19278 docs: add Playground link in navbar
  docs/.vitepress/config/nav.ts
  docs/.vitepress/crowdin/en-US/pages/sidebar.json
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16795 fix(components): [date-picker] model-value unexpected changes when type is week
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
Labels: CommitMessage::Qualified

#19164 fix(components): [menu] fix `sliceIndex` calculation error
  packages/components/menu/src/menu.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19291 docs(components): [segmented] `item` maybe declared in the upper scope
  docs/examples/segmented/custom-content.vue
  docs/examples/segmented/custom-direction.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19275 docs: remove dialog example animation
  docs/examples/dialog/events.vue
Labels: CommitMessage::Qualified

#19296 docs(components): [dialog] update demo
  docs/en-US/component/dialog.md
Labels: CommitMessage::Qualified

#17843 docs(components): [message-box] add description of props modalClass
  docs/en-US/component/message-box.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19280 chore: [table] optimization type check
  packages/components/table/src/filter-panel.vue
  packages/components/table/src/h-helper.ts
  packages/components/table/src/store/current.ts
  packages/components/table/src/store/helper.ts
  packages/components/table/src/store/index.ts
  packages/components/table/src/table-body/render-helper.ts
  packages/components/table/src/table-body/styles-helper.ts
  packages/components/table/src/table-column/render-helper.ts
  packages/components/table/src/table-header/event-helper.ts
  packages/components/table/src/table-layout.ts
  packages/components/table/src/util.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19355 docs(components): [config-provider] example error
  docs/examples/config-provider/empty-values.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19353 ci: fix ssr test error
  ssr-testing/demo.spec.puppeteer.tsx
Labels: CommitMessage::Qualified

#19357 ci: stop run when merge to dev
  .github/workflows/publish-pr-commit-pkg.yml
Labels: CommitMessage::Qualified

#17052 style(components): [notification] word wrap
  packages/theme-chalk/src/notification.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19365 docs: [select] remove demos sass
  docs/examples/layout/basic-layout.vue
  docs/examples/select-v2/custom-footer.vue
  docs/examples/select-v2/custom-header.vue
  docs/examples/select/custom-footer.vue
  docs/examples/select/custom-header.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19272 fix(components): [focus-trap] tryFocus is invalid for document.body
  packages/components/focus-trap/__tests__/utils.test.ts
  packages/components/focus-trap/src/utils.ts
  packages/components/tooltip/src/content.vue
  packages/components/tooltip/src/tooltip.vue
Labels: CommitMessage::Qualified

#18834 feat(components): [select-v2] add `fit-input-width` prop
  docs/en-US/component/select-v2.md
  docs/examples/select-v2/custom-width.vue
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/select.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19042 fix(components): [inputnumber, input] resolve styling issues caused by using `prefix` and `suffix`
  packages/theme-chalk/src/input-number.scss
  packages/theme-chalk/src/input.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18872 fix(components): [color-picker] optimize the flickering issue
  packages/components/color-picker/src/color-picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19386 fix(theme-chalk): [input-tag] correct input-tag placeholder color
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/input-tag.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19320 fix(components): prevent blur event when is disabled
  packages/components/mention/src/mention.vue
  packages/theme-chalk/src/color-picker.scss
  packages/theme-chalk/src/date-picker/picker.scss
  packages/theme-chalk/src/input-tag.scss
  packages/theme-chalk/src/input.scss
  packages/theme-chalk/src/mention.scss
  packages/theme-chalk/src/select.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19293 docs(components): [anchor] add `selectScrollTop` prop
  docs/en-US/component/anchor.md
  packages/components/anchor/src/anchor.ts
  packages/components/anchor/src/anchor.vue
Labels: CommitMessage::Qualified

#19419 fix(types): packing unexpected types
  packages/components/autocomplete/src/autocomplete.vue
  packages/components/mention/src/mention.vue
  packages/components/tooltip/src/tooltip.vue
  packages/components/transfer/src/transfer.vue
Labels: CommitMessage::Qualified

#19440 fix(components): [table] the overflowTooltip cannot be refreshed
  packages/components/table/src/table-body/events-helper.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19459 chore(ci): test pr.new
  .github/workflows/publish-pr-commit-pkg.yml
Labels: CommitMessage::Qualified

#19437 fix(components): [upload] unable to delete files in removeFile
  packages/components/upload/src/use-handlers.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review
