Repository element-plus/element-plus, pull requests merged in 2024-03, with the labels that each got.

#15980 feat(components): [date-picker] add type years for year multiple select
  docs/en-US/component/date-picker.md
  packages/components/date-picker/src/date-picker-com/basic-year-table.vue
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/date-picker/src/date-picker.type.ts
  packages/components/date-picker/src/props/basic-date-table.ts
  packages/components/date-picker/src/props/basic-year-table.ts
  packages/components/date-picker/src/props/shared.ts
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/constants.ts
  packages/constants/date.ts
  packages/theme-chalk/src/date-picker/date-table.scss
  packages/theme-chalk/src/date-picker/month-table.scss
  packages/theme-chalk/src/date-picker/year-table.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15997 fix(components): [tree-v2] fix issue in tree-v2 for setCheckedKeys invalid
  packages/components/tree-v2/src/composables/useCheck.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15697 docs(components): [table] use new display tag
  docs/en-US/component/table.md
  packages/components/table/src/table-column/defaults.ts
  packages/components/table/src/table.vue
  packages/components/table/src/table/defaults.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16002 style(components): [button] remove focus styles, Fix outline flickering when foucs-visible
  packages/theme-chalk/src/button.scss
Labels: CommitMessage::Qualified

#15995 feat(components): [select & select-v2] support empty string dynamically
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
Labels: Component::Select, breaking change, Component::SelectV2, CommitMessage::Qualified

#16005 chore: update README and doc style
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/vitepress/styles/sidebar.scss
  docs/public/images/sponsors/vform-banner.png
  docs/public/images/vform-banner.png
Labels: CommitMessage::Qualified

#16017 refactor(components): [tree & date-picker] use public function and type
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/tree-select/src/tree.ts
Labels: CommitMessage::Qualified

#16022 docs: [anchor] add locale
  docs/.vitepress/crowdin/en-US/component/anchor.json
  docs/examples/anchor/affix.vue
  docs/examples/anchor/basic.vue
  docs/examples/anchor/change.vue
  docs/examples/anchor/horizontal.vue
  docs/examples/anchor/underline.vue
Labels: CommitMessage::Qualified, Needs Review

#16023 style(components): [anchor] marker transition change
  packages/components/anchor/src/anchor.vue
  packages/theme-chalk/src/anchor.scss
  packages/utils/dom/scroll.ts
Labels: CommitMessage::Qualified, Needs Review

#16040 docs(components): [anchor] word error
  docs/.vitepress/crowdin/en-US/component/anchor.json
  docs/en-US/component/anchor.md
  docs/examples/anchor/affix.vue
  docs/examples/anchor/basic.vue
  docs/examples/anchor/change.vue
  docs/examples/anchor/underline.vue
Labels: CommitMessage::Qualified, Needs Review

#16034 fix(components): fix deprecated warning
  docs/examples/checkbox/button-style.vue
  docs/examples/date-picker/date-range.vue
  docs/examples/date-picker/enter-date.vue
  docs/examples/descriptions/sizes.vue
  docs/examples/descriptions/vertical-list.vue
  docs/examples/drawer/basic-usage.vue
  docs/examples/form/alignment.vue
  docs/examples/form/basic-form.vue
  docs/examples/form/size-control.vue
  docs/examples/form/validation.vue
  docs/examples/menu/collapse.vue
  docs/examples/pagination/more-elements.vue
  docs/examples/space/control-size.vue
  docs/examples/space/fill-ratio.vue
  docs/examples/table/table-layout.vue
  docs/examples/tabs/tab-position.vue
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/filter-panel.vue
  packages/components/transfer/src/transfer-panel.vue
  ssr-testing/cases/radio.vue
Labels: CommitMessage::Qualified

#16051 fix(components): [checkbox] fix true-value and false-value
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/checkbox/src/checkbox-button.vue
  packages/components/checkbox/src/checkbox.vue
  packages/components/checkbox/src/composables/use-checkbox-event.ts
  packages/components/checkbox/src/composables/use-checkbox.ts
Labels: CommitMessage::Qualified

#16078 fix(components): [anchor] querySelector error
  packages/utils/dom/element.ts
Labels: CommitMessage::Qualified, Needs Review

#16079 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/crowdin/en-US/component/anchor.json
  docs/.vitepress/vitepress/styles/sidebar.scss
  docs/en-US/component/anchor.md
  docs/en-US/component/badge.md
  docs/en-US/component/carousel.md
  docs/en-US/component/checkbox.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/menu.md
  docs/en-US/component/radio.md
  docs/en-US/component/table.md
  docs/examples/anchor/affix.vue
  docs/examples/anchor/basic.vue
  docs/examples/anchor/change.vue
  docs/examples/anchor/horizontal.vue
  docs/examples/anchor/underline.vue
  docs/examples/checkbox/button-style.vue
  docs/examples/date-picker/date-range.vue
  docs/examples/date-picker/enter-date.vue
  docs/examples/descriptions/sizes.vue
  docs/examples/descriptions/vertical-list.vue
  docs/examples/drawer/basic-usage.vue
  docs/examples/form/alignment.vue
  docs/examples/form/basic-form.vue
  docs/examples/form/size-control.vue
  docs/examples/form/validation.vue
  docs/examples/menu/collapse.vue
  docs/examples/pagination/more-elements.vue
  docs/examples/space/control-size.vue
  docs/examples/space/fill-ratio.vue
  docs/examples/table/table-layout.vue
  docs/examples/tabs/tab-position.vue
  packages/components/anchor/src/anchor.vue
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/checkbox/src/checkbox-button.vue
  packages/components/checkbox/src/checkbox.vue
  packages/components/checkbox/src/composables/use-checkbox-event.ts
  packages/components/checkbox/src/composables/use-checkbox.ts
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/filter-panel.vue
  packages/components/transfer/src/transfer-panel.vue
  packages/components/tree-select/src/tree.ts
  packages/locale/lang/zh-tw.ts
  packages/theme-chalk/src/anchor-link.scss
  packages/theme-chalk/src/anchor.scss
  packages/theme-chalk/src/input.scss
  packages/utils/dom/element.ts
  packages/utils/dom/scroll.ts
  ssr-testing/cases/radio.vue
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#16086 docs(components): [overview] optimize search
  docs/.vitepress/vitepress/components/globals/overview.vue
Labels: CommitMessage::Qualified

#16084 docs(components): [drawer] remove duplicate value
  docs/en-US/component/drawer.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16089 feat(components): [breadcrumb] aria-label uses locale
  packages/components/breadcrumb/src/breadcrumb.vue
  packages/locale/lang/af.ts
  packages/locale/lang/ar-eg.ts
  packages/locale/lang/ar.ts
  packages/locale/lang/az.ts
  packages/locale/lang/bg.ts
  packages/locale/lang/bn.ts
  packages/locale/lang/ca.ts
  packages/locale/lang/ckb.ts
  packages/locale/lang/cs.ts
  packages/locale/lang/da.ts
  packages/locale/lang/de.ts
  packages/locale/lang/el.ts
  packages/locale/lang/en.ts
  packages/locale/lang/eo.ts
  packages/locale/lang/es.ts
  packages/locale/lang/et.ts
  packages/locale/lang/eu.ts
  packages/locale/lang/fa.ts
  packages/locale/lang/fi.ts
  packages/locale/lang/fr.ts
  packages/locale/lang/he.ts
  packages/locale/lang/hr.ts
  packages/locale/lang/hu.ts
  packages/locale/lang/hy-am.ts
  packages/locale/lang/id.ts
  packages/locale/lang/it.ts
  packages/locale/lang/ja.ts
  packages/locale/lang/kk.ts
  packages/locale/lang/km.ts
  packages/locale/lang/ko.ts
  packages/locale/lang/ku.ts
  packages/locale/lang/ky.ts
  packages/locale/lang/lt.ts
  packages/locale/lang/lv.ts
  packages/locale/lang/mg.ts
  packages/locale/lang/mn.ts
  packages/locale/lang/nb-no.ts
  packages/locale/lang/nl.ts
  packages/locale/lang/pa.ts
  packages/locale/lang/pl.ts
  packages/locale/lang/pt-br.ts
  packages/locale/lang/pt.ts
  packages/locale/lang/ro.ts
  packages/locale/lang/ru.ts
  packages/locale/lang/sk.ts
  packages/locale/lang/sl.ts
  packages/locale/lang/sr.ts
  packages/locale/lang/sv.ts
  packages/locale/lang/sw.ts
  packages/locale/lang/ta.ts
  packages/locale/lang/th.ts
  packages/locale/lang/tk.ts
  packages/locale/lang/tr.ts
  packages/locale/lang/ug-cn.ts
  packages/locale/lang/uk.ts
  packages/locale/lang/uz-uz.ts
  packages/locale/lang/vi.ts
  packages/locale/lang/zh-cn.ts
  packages/locale/lang/zh-tw.ts
Labels: CommitMessage::Qualified

#16100 style(components): [anchor] marker transition expression incorrect
  packages/theme-chalk/src/anchor.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16102 fix(components): [anchor] `type` default value typo
  packages/components/anchor/src/anchor.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16068 fix(components): [cascader] form nested causing clear icon invalid
  packages/components/cascader/src/cascader.vue
  packages/theme-chalk/src/cascader.scss
Labels: CommitMessage::Qualified

#16101 chore: format code
  docs/en-US/component/drawer.md
  packages/theme-chalk/src/anchor.scss
Labels: CommitMessage::Qualified

#16119 fix(components): [anchor,tour] the `type` type typo
  docs/en-US/component/anchor.md
  docs/examples/anchor/scroll.vue
  packages/components/tour/src/step.ts
  packages/components/tour/src/tour.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16127 docs(components): [message-box/select/tooltip] fix typo
  docs/en-US/component/message-box.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/tooltip.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16066 docs: color values are uniformly lowercase
  docs/en-US/component/checkbox.md
  docs/en-US/component/icon.md
  docs/en-US/component/menu.md
  docs/en-US/component/radio.md
  docs/en-US/component/rate.md
Labels: CommitMessage::Qualified

#15521 docs(components): [tree-v2] replace mention of filter-node-method attribute with filter-method.
  docs/en-US/component/tree-v2.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16151 fix(components): [select] stop the click event propagation of `header/footer` slot
  packages/components/select/src/select.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16154 style: remove duplicate style
  packages/theme-chalk/src/var.scss
Labels: CommitMessage::Qualified

#16130 fix(components): [tree] the value of append can be zero
  packages/components/tree/src/model/tree-store.ts
Labels: CommitMessage::Qualified

#16149 fix(components): [select & select-v2] click toggleMenu add prevent
  packages/components/select-v2/src/select.vue
  packages/components/select/src/select.vue
Labels: CommitMessage::Qualified

#16056 fix(theme-chalk): replace `gulp-clean-css` with `cssnano`
  packages/theme-chalk/gulpfile.ts
  packages/theme-chalk/package.json
  pnpm-lock.yaml
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16174 fix(components): [tag] remove duplicate style
  packages/theme-chalk/src/tag.scss
Labels: CommitMessage::Qualified

#16200 style(docs): [overview] replace `::v-deep` with `:deep`
  docs/.vitepress/vitepress/components/globals/overview.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16175 fix(hooks): SSR hydration error caused by z-index
  docs/en-US/guide/ssr.md
  packages/hooks/__tests__/use-z-index.test.tsx
  packages/hooks/use-z-index/index.ts
Labels: CommitMessage::Qualified

#16198 fix(components): [cascader-panel] get the reactive proxy of `node` to trigger side effects
  packages/components/cascader-panel/__tests__/cascader-panel.test.tsx
  packages/components/cascader-panel/src/index.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16209 chore(build): [ElAnchor & ElAnchorLink] update global types
  global.d.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Component::Anchor

#16201 test(utils): [vue] add refs, size and validator test
  packages/utils/__tests__/vue/refs.test.ts
  packages/utils/__tests__/vue/size.test.ts
  packages/utils/__tests__/vue/validator.test.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16194 test(hooks): [use-id] add debug-warn test
  packages/hooks/__tests__/use-id.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16099 feat(components): [tree] lazy load provide reject
  docs/en-US/component/tree.md
  docs/examples/tree/multiple-times-load.vue
  packages/components/tree/src/model/node.ts
Labels: CommitMessage::Qualified

#16213 chore(docs): [tree] update version
  docs/en-US/component/tree.md
Labels: CommitMessage::Qualified

#16192 feat(locale): update ru locale
  packages/locale/lang/ru.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16214 feat(components): [message] add plain prop
  docs/en-US/component/message.md
  docs/examples/message/plain.vue
  packages/components/message/src/message.ts
  packages/components/message/src/message.vue
  packages/theme-chalk/src/message.scss
Labels: CommitMessage::Qualified

#16242 fix(components): [icon] remove repeat style
  packages/components/icon/style/css.ts
  packages/components/icon/style/index.ts
Labels: CommitMessage::Qualified, Needs Review

#16234 fix(components): [select] fix error in low versions of vue
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#16268 docs(components): [select] add width change description
  docs/en-US/component/select.md
Labels: CommitMessage::Qualified

#16262 docs(components): [date-picker] update calculation of shortcut key values
  docs/examples/datetime-picker/date-and-time-range.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16117 docs(components): [dropdown] fix the actual showTimeout property value
  docs/en-US/component/dropdown.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15835 fix(components): [date-picker] click the clear to reset the date panel
  packages/components/date-picker/__tests__/date-time-picker.test.tsx
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16305 docs(components): [overview] add keyboard control selection component
  docs/.vitepress/vitepress/components/globals/overview.vue
Labels: CommitMessage::Qualified

#16275 feat(components): [input-number] support slot custom icons
  docs/en-US/component/input-number.md
  docs/examples/input-number/custom.vue
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16069 feat(components): [badge] add color prop
  docs/en-US/component/badge.md
  docs/examples/badge/basic.vue
  packages/components/badge/src/badge.ts
  packages/components/badge/src/badge.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14830 fix(components): [tree] dragging a node will deselect the node
  packages/components/tree/src/model/node.ts
  packages/components/tree/src/model/useDragNode.ts
  packages/components/tree/src/tree-node.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16316 docs(components): [datetime-picker] update calculation of shortcut key values
  docs/examples/datetime-picker/date-and-time.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16319 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/vitepress/components/globals/overview.vue
  docs/en-US/component/badge.md
  docs/en-US/component/dropdown.md
  docs/en-US/component/input-number.md
  docs/en-US/component/message.md
  docs/en-US/component/select.md
  docs/en-US/component/tree.md
  docs/examples/badge/basic.vue
  docs/examples/datetime-picker/date-and-time-range.vue
  docs/examples/datetime-picker/date-and-time.vue
  docs/examples/input-number/custom.vue
  docs/examples/message/plain.vue
  docs/examples/tree/multiple-times-load.vue
  packages/components/badge/src/badge.ts
  packages/components/badge/src/badge.vue
  packages/components/date-picker/__tests__/date-time-picker.test.tsx
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  packages/components/icon/style/css.ts
  packages/components/icon/style/index.ts
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
  packages/components/message/src/message.ts
  packages/components/message/src/message.vue
  packages/components/select/src/useSelect.ts
  packages/components/tree/src/model/node.ts
  packages/components/tree/src/model/useDragNode.ts
  packages/components/tree/src/tree-node.vue
  packages/hooks/__tests__/use-id.test.tsx
  packages/locale/lang/ru.ts
  packages/theme-chalk/src/message.scss
  packages/utils/__tests__/vue/refs.test.ts
  packages/utils/__tests__/vue/size.test.ts
  packages/utils/__tests__/vue/validator.test.ts
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified
