Repository element-plus/element-plus, pull requests merged in 2024-10, with the labels that each got.

#18427 chore: fix docs/play dev sass deprecation warning
  docs/.vitepress/config/vite.ts
  docs/.vitepress/vitepress/components/navbar/vp-search.vue
  docs/.vitepress/vitepress/styles/css-vars.scss
  play/vite.config.ts
Labels: CommitMessage::Qualified

#18428 docs: add sass compatible version description
  docs/en-US/guide/installation.md
Labels: CommitMessage::Qualified

#18423 docs(components): [transfer] add transfer and transfer panel exposes
  docs/en-US/component/transfer.md
  packages/components/transfer/src/transfer.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18432 ci: the node version supported by action is consistent with GitHub
  .github/workflows/lint-commit-message.yml
  .github/workflows/pr-docs-build.yml
  .github/workflows/publish-build-product.yml
  .github/workflows/publish-docs-deploy-manual.yml
  .github/workflows/publish-docs-deploy.yml
  .github/workflows/publish-npm-nightly.yml
  .github/workflows/publish-npm.yml
  .github/workflows/publish-pr-commit-pkg.yml
  .github/workflows/publish-size-report.yml
  .github/workflows/staging-docs.yml
  .github/workflows/test-coverage.yml
  .github/workflows/test-ssr.yml
  .github/workflows/test-unit.yml
Labels: CommitMessage::Qualified

#18416 fix(components): [transfer] render the option's label correctly when there's only an empty comment in the default slot
  packages/components/transfer/__tests__/transfer.test.tsx
  packages/components/transfer/src/transfer.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18440 fix(components): [table] cancel layout update when component unmount
  packages/components/table/src/table.vue
Labels: CommitMessage::Qualified

#18445 fix(hooks): [lockscreen] compatible with document non-existence
  packages/hooks/use-lockscreen/index.ts
Labels: CommitMessage::Qualified

#18449 chore: update doc
  docs/.vitepress/vitepress/components/vp-sponsors.vue
Labels: CommitMessage::Qualified

#18447 feat(i18n): update germany translations
  packages/locale/lang/de.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18477 chore: update doc
  docs/.vitepress/vitepress/components/vp-sponsors.vue
Labels: CommitMessage::Qualified

#18481 docs: add installation-version get unpublished content
  docs/en-US/guide/installation.md
Labels: CommitMessage::Qualified

#18453 fix(components): [mention] native event triggered twice
  packages/components/mention/src/mention.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18460 feat(components): [mention] explicit export dropdownVisible
  docs/en-US/component/mention.md
  packages/components/mention/src/mention.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18335 fix(components): [select] use `blur` in the tooltip slot has no effect
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#18490 docs: disambiguate description of `autoInsertSpace`
  docs/en-US/component/config-provider.md
Labels: CommitMessage::Qualified

#18482 fix(hooks): rendering multiple popper container DOM in SSR/SSG
  packages/hooks/use-popper-container/index.ts
Labels: CommitMessage::Qualified

#18478 fix(components): [select] the blur not triggered when click the outside
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#18350 feat(components): [select & select-v2] explicit export `selectedLabel`
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/select.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
Labels: ready to merge, CommitMessage::Qualified

#18444 fix(components): [table] the last column shuld not allow drag
  packages/components/table/src/table-header/event-helper.ts
Labels: CommitMessage::Qualified

#18513 D2M
  .github/workflows/lint-commit-message.yml
  .github/workflows/pr-docs-build.yml
  .github/workflows/publish-build-product.yml
  .github/workflows/publish-docs-deploy-manual.yml
  .github/workflows/publish-docs-deploy.yml
  .github/workflows/publish-npm-nightly.yml
  .github/workflows/publish-npm.yml
  .github/workflows/publish-pr-commit-pkg.yml
  .github/workflows/publish-size-report.yml
  .github/workflows/staging-docs.yml
  .github/workflows/test-coverage.yml
  .github/workflows/test-ssr.yml
  .github/workflows/test-unit.yml
  CHANGELOG.en-US.md
  docs/.vitepress/config/index.mts
  docs/.vitepress/config/vite.ts
  docs/.vitepress/vitepress/components/home/svg/guide-svg.vue
  docs/.vitepress/vitepress/components/navbar/vp-search.vue
  docs/.vitepress/vitepress/components/vp-sponsors.vue
  docs/.vitepress/vitepress/styles/css-vars.scss
  docs/en-US/component/config-provider.md
  docs/en-US/component/mention.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/transfer.md
  docs/en-US/guide/installation.md
  docs/en-US/guide/nav.md
  docs/en-US/guide/quickstart.md
  docs/package.json
  package.json
  packages/components/badge/__tests__/badge.test.tsx
  packages/components/badge/src/badge.vue
  packages/components/mention/src/mention.vue
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/components/table/src/table-header/event-helper.ts
  packages/components/table/src/table.vue
  packages/components/transfer/__tests__/transfer.test.tsx
  packages/components/transfer/src/transfer.vue
  packages/hooks/use-lockscreen/index.ts
  packages/hooks/use-popper-container/index.ts
  packages/locale/lang/de.ts
  packages/theme-chalk/src/badge.scss
  packages/theme-chalk/src/color/index.scss
  packages/theme-chalk/src/mixins/_var.scss
  play/package.json
  play/scripts/init.mjs
  play/vite.config.ts
  pnpm-lock.yaml
  tsconfig.vite-config.json
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#18412 docs: improve language matching logic
  docs/.vitepress/lang.js
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18340 fix(components): [dropdown-item] remove redundant attributes
  packages/components/dropdown/src/dropdown-item-impl.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18535 perf(components): [table] body render performance optimize
  packages/components/table/src/table-body/render-helper.ts
  packages/components/table/src/table-body/td-wrapper.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review, Performance Optimization

#18536 docs: [date-picker] unified format
  docs/en-US/component/datetime-picker.md
Labels: CommitMessage::Qualified

#18527 docs(components): [segmented] update custom styles, add scope parameter
  docs/en-US/component/segmented.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18547 docs: move deprecated APIs to the end of the table
  docs/en-US/component/autocomplete.md
  docs/en-US/component/cascader.md
  docs/en-US/component/checkbox.md
  docs/en-US/component/color-picker.md
  docs/en-US/component/dialog.md
  docs/en-US/component/drawer.md
  docs/en-US/component/input-number.md
  docs/en-US/component/input.md
  docs/en-US/component/menu.md
  docs/en-US/component/pagination.md
  docs/en-US/component/radio.md
  docs/en-US/component/rate.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/slider.md
  docs/en-US/component/switch.md
  docs/en-US/component/tabs.md
  docs/en-US/component/time-picker.md
Labels: CommitMessage::Qualified

#18458 feat(components): [input] show pwd visible icon when the input is readonly
  packages/components/input/src/input.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18553 chore(docs): switch Vue to the version used by VitePress
  docs/.vitepress/config/index.mts
  docs/.vitepress/config/vite.ts
  docs/.vitepress/config/vue-compiler.ts
  docs/package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#18334 fix(components): [select-v2] data echo abnormality
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18509 fix(components): [segmented] no option to not render
  packages/components/segmented/src/segmented.vue
Labels: CommitMessage::Qualified

#18586 fix: progress bar get stuck when navigating between routes
  docs/.vitepress/vitepress/components/vp-content.vue
Labels: CommitMessage::Qualified

#18588 D2M
  CHANGELOG.en-US.md
  README.md
  docs/.vitepress/config/index.mts
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/config/vite.ts
  docs/.vitepress/config/vue-compiler.ts
  docs/.vitepress/lang.js
  docs/.vitepress/vitepress/components/vp-content.vue
  docs/en-US/component/autocomplete.md
  docs/en-US/component/cascader.md
  docs/en-US/component/checkbox.md
  docs/en-US/component/color-picker.md
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/dialog.md
  docs/en-US/component/drawer.md
  docs/en-US/component/input-number.md
  docs/en-US/component/input.md
  docs/en-US/component/menu.md
  docs/en-US/component/pagination.md
  docs/en-US/component/radio.md
  docs/en-US/component/rate.md
  docs/en-US/component/segmented.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/slider.md
  docs/en-US/component/switch.md
  docs/en-US/component/tabs.md
  docs/en-US/component/time-picker.md
  docs/package.json
  packages/components/dropdown/src/dropdown-item-impl.vue
  packages/components/input/src/input.vue
  packages/components/segmented/src/segmented.vue
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/useSelect.ts
  packages/components/table/src/table-body/render-helper.ts
  packages/components/table/src/table-body/td-wrapper.vue
  packages/theme-chalk/src/table-v2.scss
  pnpm-lock.yaml
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#18612 chore: fix typo in messageBox.ts comments
  packages/components/message-box/src/messageBox.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18628 fix(components): [table-v2] header rendering is misplaced
  packages/components/table-v2/src/components/header.tsx
  packages/components/table-v2/src/table-grid.tsx
Labels: CommitMessage::Qualified

#18625 feat(components): [date-picker] add `show-now` prop
  docs/en-US/component/datetime-picker.md
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/date-picker/src/props/shared.ts
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/common/props.ts
Labels: CommitMessage::Qualified

#18608 docs: [tree] unified format
  docs/en-US/component/tree.md
Labels: CommitMessage::Qualified

#18578 fix(components): [tree] highlight the corresponding node after data reset
  packages/components/tree/__tests__/tree.test.ts
  packages/components/tree/src/model/tree-store.ts
  packages/components/tree/src/tree-node.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18644 chore(components): [descriptions] optimize the labelAlign
  packages/components/descriptions/src/descriptions-cell.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18109 feat(components): [date-picker] accessibility enhancement
  docs/en-US/component/date-picker.md
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/time-picker.md
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/src/date-picker.tsx
  packages/components/date-picker/src/instance.ts
  packages/components/input/src/input.vue
  packages/components/popper/src/trigger.vue
  packages/components/time-picker/__tests__/time-picker.test.tsx
  packages/components/time-picker/src/common/picker-range-trigger.vue
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/common/props.ts
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
  packages/components/time-picker/src/time-picker.tsx
  packages/utils/dom/aria.ts
Labels: CommitMessage::Qualified

#18663 ci: update action vertion
  .github/workflows/lint-commit-message.yml
  .github/workflows/pr-docs-build.yml
  .github/workflows/publish-build-product.yml
  .github/workflows/publish-docs-deploy-manual.yml
  .github/workflows/publish-docs-deploy.yml
  .github/workflows/publish-npm-nightly.yml
  .github/workflows/publish-npm.yml
  .github/workflows/publish-size-report.yml
  .github/workflows/staging-docs.yml
  .github/workflows/test-coverage.yml
  .github/workflows/test-ssr.yml
  .github/workflows/test-unit.yml
Labels: CommitMessage::Qualified

#18668 chore(components): [tour] remove redundant check for 'open' variable
  packages/components/tour/src/helper.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18667 fix(components): [slider] no render popper dom when showTooltip is false
  packages/components/slider/src/button.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18660 docs(components): [tree] declare data type
  docs/en-US/component/tree.md
Labels: CommitMessage::Qualified

#18647 fix(hooks): [useId] SSR hydration error caused by id in vue@3.5+
  packages/hooks/__tests__/use-id.test.tsx
  packages/hooks/use-id/index.ts
Labels: CommitMessage::Qualified

#18635 style(components): [popper] popper border error
  packages/theme-chalk/src/popper.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18671 refactor: replace `Array.isArray` with the built-in `isArray`
  packages/components/cascader-panel/src/node.ts
  packages/components/date-picker/src/composables/use-basic-date-table.ts
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/form/src/form-item.vue
  packages/components/image/src/image.vue
  packages/components/menu/src/menu-item.ts
  packages/components/menu/src/menu.ts
  packages/components/pagination/src/components/sizes.vue
  packages/components/slider/src/composables/use-lifecycle.ts
  packages/components/slider/src/composables/use-watch.ts
  packages/components/table-v2/src/composables/use-data.ts
  packages/components/table/src/store/tree.ts
  packages/components/table/src/store/watcher.ts
  packages/components/table/src/table-body/styles-helper.ts
  packages/components/table/src/table-column/index.ts
  packages/components/table/src/table-column/render-helper.ts
  packages/components/table/src/util.ts
  packages/components/tree-select/src/utils.ts
  packages/components/tree/src/model/node.ts
  packages/components/watermark/src/useClips.ts
  packages/components/watermark/src/watermark.vue
  packages/directives/click-outside/index.ts
  packages/utils/arrays.ts
  packages/utils/vue/vnode.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18551 fix(components): [select-v2] group label overflow hidden
  packages/theme-chalk/src/option-group.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18573 chore: update dependencies
  internal/build/package.json
  internal/eslint-config/index.js
  internal/eslint-config/package.json
  package.json
  packages/components/config-provider/src/config-provider-props.ts
  packages/components/popper/src/popper.ts
  packages/components/table-v2/src/utils.ts
  packages/components/time-picker/src/common/picker.vue
  packages/components/upload/src/upload.ts
  packages/utils/__tests__/vue/props.test.ts
  packages/utils/arrays.ts
  packages/utils/objects.ts
  pnpm-lock.yaml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14173 fix(components): [select] error parameters of getValueIndex
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#18705 refactor: replace typeof fn with the built-in isFunction
  packages/components/message-box/src/index.vue
  packages/components/table/src/config.ts
  packages/components/table/src/table-body/styles-helper.ts
  packages/components/table/src/table-header/style.helper.ts
  packages/components/table/src/util.ts
  packages/components/tree/src/model/node.ts
  packages/components/tree/src/model/useDragNode.ts
  packages/utils/dom/scroll.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18710 chore: update doc
  docs/.vitepress/vitepress/components/vp-sponsors.vue
Labels: CommitMessage::Qualified

#18706 refactor: replace typeof number with the built-in isNumber
  packages/components/slider/src/composables/use-lifecycle.ts
  packages/components/slider/src/composables/use-watch.ts
  packages/components/table/src/config.ts
  packages/components/table/src/table-layout.ts
  packages/components/table/src/util.ts
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18720 refactor: replace type checking with built-in functions
  packages/components/color-picker/src/utils/color.ts
  packages/components/message-box/src/index.vue
  packages/components/notification/src/notify.ts
  packages/components/table/src/config.ts
  packages/components/table/src/store/tree.ts
  packages/components/table/src/store/watcher.ts
  packages/components/table/src/table-body/render-helper.ts
  packages/components/table/src/table-body/styles-helper.ts
  packages/components/table/src/table-header/style.helper.ts
  packages/components/table/src/table-layout.ts
  packages/components/table/src/util.ts
  packages/components/tree-v2/src/virtual-tree.ts
  packages/components/tree/src/model/node.ts
  packages/utils/types.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18653 feat(components): segmented support vertical direction
  docs/en-US/component/segmented.md
  docs/examples/segmented/custom-direction.vue
  packages/components/segmented/src/segmented.ts
  packages/components/segmented/src/segmented.vue
  packages/theme-chalk/src/segmented.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review
