Repository element-plus/element-plus, pull requests merged in 2024-09, with the labels that each got.

#18112 test(components): [select] add case for disabled and automatic-dropdown
  packages/components/select/__tests__/select.test.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18107 ci: stick to pkg-pr-new@0.0.20 & only publish approved pr pkg
  .github/workflows/pkg-pr-new.yml
Labels: CommitMessage::Qualified

#18104 docs: replace `delete` with `deprecated` and format
  docs/en-US/component/button.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/dropdown.md
  docs/en-US/component/pagination.md
  docs/en-US/component/segmented.md
  docs/en-US/component/tree-v2.md
  docs/en-US/component/watermark.md
  packages/theme-chalk/src/date-picker/month-table.scss
  packages/theme-chalk/src/date-picker/picker.scss
  packages/theme-chalk/src/date-picker/year-table.scss
  packages/theme-chalk/src/mention.scss
  packages/theme-chalk/src/menu.scss
  packages/theme-chalk/src/upload.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18106 feat(components): [config-provider] support more message config
  docs/en-US/component/config-provider.md
  packages/components/config-provider/__tests__/config-provider.test.tsx
  packages/components/message/src/message.ts
  packages/components/message/src/method.ts
Labels: CommitMessage::Qualified

#17903 fix(components): [el-tree-select] fix lazy and multiple select node
  packages/components/tree-select/__tests__/tree-select.test.tsx
  packages/components/tree-select/src/tree.ts
  packages/components/tree/src/tree-node.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18116 fix(theme-chalk): [select] remove unnecessary codes of the select border
  packages/theme-chalk/src/select.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17691 fix(components): [select] call the exposes blur is invalid
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#18119 fix(components): [mention] replace props.disabled with useFormDisabled
  packages/components/mention/__tests__/mention.test.tsx
  packages/components/mention/src/mention.vue
Labels: CommitMessage::Qualified

#18077 fix(components): [tree-v2] expand all ancestor nodes of the specified node
  packages/components/tree-v2/__tests__/tree.test.ts
  packages/components/tree-v2/src/composables/useTree.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18120 fix(theme-chalk): [select] box-shadow noise
  packages/theme-chalk/src/select.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18051 chore: optimize dts imports
  docs/tsconfig.json
  internal/build/gulpfile.ts
  tsconfig.base.json
  tsconfig.play.json
  typings/components.d.ts
  typings/global.d.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18088 revert(components): [select] cancel type conversion at initialization
  docs/en-US/component/select.md
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
  packages/components/tree-select/__tests__/tree-select.test.tsx
Labels: CommitMessage::Qualified

#18127 chore(components): [dialog] add instance type
  packages/components/dialog/src/dialog.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18121 fix(hooks): PopperContainer cannot be recreated when body is recreated
  packages/hooks/__tests__/use-popper-container.test.tsx
  packages/hooks/use-popper-container/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18125 fix(components): [calendar] improve range validation
  packages/components/calendar/src/use-calendar.ts
Labels: CommitMessage::Qualified

#17891 fix(components): [table-v2] columns missing key field
  docs/en-US/component/table-v2.md
  packages/components/table-v2/src/components/header-row.tsx
  packages/components/table-v2/src/components/row.tsx
  packages/components/table-v2/src/composables/use-columns.ts
  packages/components/table-v2/src/renderers/header-cell.tsx
  packages/components/table-v2/src/types.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18165 fix(components): [tabs] active-bar not move with the tab label changes
  packages/components/tabs/src/tab-bar.vue
Labels: CommitMessage::Qualified

#18189 fix(components): [message] max affects grouping display
  packages/components/message/src/method.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18179 fix(components): [table-v2] header checkbox cover fixedHeader when scroll
  packages/theme-chalk/src/table-v2.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18210 docs: site translation icon style optimization
  docs/.vitepress/vitepress/components/navbar/vp-translation.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18211 test(components): [select] fix test warning
  packages/components/select/__tests__/options.test.tsx
  packages/components/select/__tests__/select.test.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18190 chore(docs): cleanup dependencies
  docs/.vitepress/config/plugins.ts
  docs/.vitepress/plugins/api-table.ts
  docs/.vitepress/plugins/demo.ts
  docs/.vitepress/plugins/external-link-icon.ts
  docs/.vitepress/plugins/headers.ts
  docs/.vitepress/plugins/table-wrapper.ts
  docs/.vitepress/plugins/tag.ts
  docs/.vitepress/plugins/tooltip.ts
  docs/package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#18208 docs(components): [table] revise `getSelectionRows` type
  docs/en-US/component/table.md
Labels: CommitMessage::Qualified

#18122 fix(components): [menu] move ulStyle from render to setup to fix memory leak
  packages/components/menu/src/menu.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18217 test(components): [slider] remove console.log
  packages/components/slider/__tests__/slider.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18218 fix(components): [table-v2] sass declaration deprecation error
  packages/theme-chalk/src/table-v2.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14320 feat(components): [scrollbar] add tabindex to scrollbar wrap content
  docs/en-US/component/scrollbar.md
  docs/en-US/component/table.md
  packages/components/scrollbar/src/scrollbar.ts
  packages/components/scrollbar/src/scrollbar.vue
  packages/components/table/src/table.vue
  packages/components/table/src/table/defaults.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18128 fix(components): [select-v2] label display error when re-rendering
  packages/components/select-v2/src/useSelect.ts
Labels: CommitMessage::Qualified

#18207 fix(components): [tooltip] change ariaHidden value after closed the dropdown
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/time-picker/__tests__/time-picker.test.tsx
  packages/components/tooltip/src/content.vue
Labels: CommitMessage::Qualified

#16935 feat(components): [tree-v2] support `node-drop` event
  docs/en-US/component/tree-v2.md
  packages/components/tree-v2/__tests__/tree.test.ts
  packages/components/tree-v2/src/composables/useTree.ts
  packages/components/tree-v2/src/tree-node.vue
  packages/components/tree-v2/src/tree.vue
  packages/components/tree-v2/src/virtual-tree.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18135 fix(components): [color-picker] supports dynamic change of colorFormat
  packages/components/color-picker/__tests__/color-picker.test.tsx
  packages/components/color-picker/src/color-picker.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15390 fix(components): [time-picker] close pick when click clear on pick open
  packages/components/time-picker/__tests__/time-picker.test.tsx
  packages/components/time-picker/src/common/picker.vue
Labels: ready to merge, Contribution::Community, CommitMessage::Qualified, Needs Review

#18215 feat(components): [collapse] collpase item supports custom icon
  docs/en-US/component/collapse.md
  docs/examples/collapse/custom-icon.vue
  packages/components/collapse/src/collapse-item.ts
  packages/components/collapse/src/collapse-item.vue
Labels: ready to merge, Contribution::Community, CommitMessage::Qualified, Needs Review

#16274 feat(components): [cascader-panel] add `empty` slot
  docs/en-US/component/cascader.md
  packages/components/cascader-panel/src/index.vue
  packages/components/cascader-panel/src/menu.vue
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/src/cascader.vue
Labels: CommitMessage::Qualified

#18255 chore: upgrade to pnpm 9
  package.json
  pnpm-lock.yaml
Labels: ready to merge, CommitMessage::Qualified

#18034 fix(components): [table] the disabled checkbox are selected
  docs/en-US/component/table.md
  docs/examples/table/multi-select.vue
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/store/watcher.ts
  packages/components/table/src/table/utils-helper.ts
Labels: CommitMessage::Qualified

#18219 ci: release pr commit is made on the original repository dev
  .github/workflows/publish-pr-commit-pkg.yml
Labels: ready to merge, CommitMessage::Qualified

#17904 fix(components): [table] selection fixed unexpected
  packages/components/table/__tests__/table-column.test.ts
  packages/components/table/src/store/watcher.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18269 chore: update doc
  README.md
  docs/public/images/sponsors/CRMEB-l.png
Labels: CommitMessage::Qualified

#18266 D2M
  .github/workflows/publish-pr-commit-pkg.yml
  CHANGELOG.en-US.md
  README.md
  docs/.vitepress/config/plugins.ts
  docs/.vitepress/plugins/api-table.ts
  docs/.vitepress/plugins/demo.ts
  docs/.vitepress/plugins/external-link-icon.ts
  docs/.vitepress/plugins/headers.ts
  docs/.vitepress/plugins/table-wrapper.ts
  docs/.vitepress/plugins/tag.ts
  docs/.vitepress/plugins/tooltip.ts
  docs/.vitepress/vitepress/components/navbar/vp-translation.vue
  docs/en-US/component/cascader.md
  docs/en-US/component/collapse.md
  docs/en-US/component/scrollbar.md
  docs/en-US/component/table.md
  docs/en-US/component/tree-v2.md
  docs/examples/collapse/custom-icon.vue
  docs/examples/table/multi-select.vue
  docs/package.json
  docs/public/images/sponsors/CRMEB-l.png
  package.json
  packages/components/cascader-panel/src/index.vue
  packages/components/cascader-panel/src/menu.vue
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/src/cascader.vue
  packages/components/collapse/src/collapse-item.ts
  packages/components/collapse/src/collapse-item.vue
  packages/components/color-picker/__tests__/color-picker.test.tsx
  packages/components/color-picker/src/color-picker.vue
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/menu/src/menu.ts
  packages/components/scrollbar/src/scrollbar.ts
  packages/components/scrollbar/src/scrollbar.vue
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/__tests__/options.test.tsx
  packages/components/select/__tests__/select.test.ts
  packages/components/slider/__tests__/slider.test.tsx
  packages/components/table/__tests__/table-column.test.ts
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/store/watcher.ts
  packages/components/table/src/table.vue
  packages/components/table/src/table/defaults.ts
  packages/components/table/src/table/utils-helper.ts
  packages/components/time-picker/__tests__/time-picker.test.tsx
  packages/components/time-picker/src/common/picker.vue
  packages/components/tooltip/src/content.vue
  packages/components/tree-v2/__tests__/tree.test.ts
  packages/components/tree-v2/src/composables/useTree.ts
  packages/components/tree-v2/src/tree-node.vue
  packages/components/tree-v2/src/tree.vue
  packages/components/tree-v2/src/virtual-tree.ts
  packages/theme-chalk/src/table-v2.scss
  pnpm-lock.yaml
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#18272 chore: update doc
  docs/.vitepress/vitepress/components/vp-sponsors.vue
Labels: CommitMessage::Qualified

#18199 fix(components): [segmented] item may be undefined
  docs/en-US/component/segmented.md
  packages/components/segmented/src/segmented.vue
  packages/components/segmented/src/types.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18281 docs(components): [table] optimize FAQ code display
  docs/en-US/component/table.md
Labels: CommitMessage::Qualified

#18224 chore(build): remove redundant code
  internal/metadata/package.json
  internal/metadata/src/components.ts
Labels: CommitMessage::Qualified

#18277 fix(components): `step-strictly` is true and should keep the initial value and step matching
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18311 fix(components): [scrollbar] compatibility with `wrapRef` does not exist
  packages/components/scrollbar/src/scrollbar.vue
Labels: CommitMessage::Qualified

#18237 feat(components): [autocomplete] add getData to exposes
  docs/en-US/component/autocomplete.md
  packages/components/autocomplete/src/autocomplete.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18293 style(components): [form-item] top-label change to `inline-block` element
  packages/theme-chalk/src/form.scss
Labels: CommitMessage::Qualified

#18187 fix(components): [checkbox] default false if no false-value attr
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/checkbox/src/checkbox-button.vue
  packages/components/checkbox/src/checkbox.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18329 fix(components): [carousel] fix style when use motionBlur
  packages/components/carousel/src/carousel.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18310 feat(components): [date-picker] add `placement` & `fallback-placements`
  docs/en-US/component/date-picker.md
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/common/props.ts
Labels: CommitMessage::Qualified

#18330 fix(components): [descriptions-cell] redundant slot function calls
  packages/components/descriptions/src/descriptions-cell.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18303 fix(components): [avatar] remove outline from el-avatar component
  packages/theme-chalk/src/avatar.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18280 fix(components): [color-picker] support dynamic change of showAlpha prop
  packages/components/color-picker/__tests__/color-picker.test.tsx
  packages/components/color-picker/src/color-picker.vue
Labels: ready to merge, Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16746 chore: remove ts-nocheck comments in select-v2
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/group-item.vue
  packages/components/select-v2/src/option-item.vue
  packages/components/select-v2/src/select-dropdown.tsx
  packages/components/select-v2/src/select.types.ts
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/token.ts
  packages/components/select-v2/src/useAllowCreate.ts
  packages/components/select-v2/src/useOption.ts
  packages/components/select-v2/src/useSelect.ts
  packages/components/virtual-list/index.ts
  packages/components/virtual-list/src/builders/build-list.ts
  packages/components/virtual-list/src/components/dynamic-size-list.ts
  packages/components/virtual-list/src/components/fixed-size-list.ts
  packages/components/virtual-list/src/hooks/use-cache.ts
  packages/utils/vue/typescript.ts
  typings/env.d.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17993 feat(components): [input-number] add prefix and suffix
  docs/en-US/component/input-number.md
  docs/examples/input-number/with-prefix-suffix.vue
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18336 chore: update doc
  docs/.vitepress/vitepress/components/vp-sponsors.vue
Labels: CommitMessage::Qualified

#18338 feat(components): [cascader] update cascader component to expost presentText
  docs/en-US/component/cascader.md
  packages/components/cascader/src/cascader.vue
Labels: CommitMessage::Qualified

#18339 chore(play): remove useless .eslintrc.json
  play/.eslintrc.json
Labels: CommitMessage::Qualified

#18352 docs(components): [mention] the document display format is unified
  docs/en-US/component/mention.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18351 style(components): [transfer] delete input__inner `border-radius`
  packages/theme-chalk/src/transfer.scss
Labels: CommitMessage::Qualified

#14318 feat(components): add the ability to append table filter panel, select and pagination size dropdowns to any element
  docs/en-US/component/pagination.md
  docs/en-US/component/select.md
  docs/en-US/component/table.md
  packages/components/pagination/src/components/sizes.ts
  packages/components/pagination/src/components/sizes.vue
  packages/components/pagination/src/pagination.ts
  packages/components/select/src/select.ts
  packages/components/select/src/select.vue
  packages/components/table/src/filter-panel.vue
  packages/components/table/src/table-header/index.ts
  packages/components/table/src/table.vue
  packages/components/table/src/table/defaults.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17709 feat(components): [table] export `updateKeyChildren` method & correct version
  docs/en-US/component/table.md
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/store/tree.ts
  packages/components/table/src/store/watcher.ts
  packages/components/table/src/table.vue
  packages/components/table/src/table/utils-helper.ts
Labels: ready to merge, Contribution::Community, CommitMessage::Qualified, Needs Review

#18360 refactor(components): [badge] show-zero implement
  packages/components/badge/__tests__/badge.test.tsx
  packages/components/badge/src/badge.vue
  packages/theme-chalk/src/badge.scss
Labels: CommitMessage::Qualified

#18381 fix(play): dayjs cahce miss
  play/vite.config.ts
Labels: CommitMessage::Qualified

#18400 docs: remove outdated descriptions of unplugin-element-plus
  docs/en-US/guide/quickstart.md
Labels: CommitMessage::Qualified

#18413 docs(components): [transfer] fix the missing scope parameter
  docs/en-US/component/transfer.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18411 docs: add the missed full stop
  docs/en-US/guide/nav.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18385 chore(play): use the postinstall hook to run the init script
  play/package.json
  play/scripts/init.mjs
  play/vite.config.ts
  tsconfig.vite-config.json
Labels: CommitMessage::Qualified

#18417 docs: remove invalid path tag
  docs/.vitepress/vitepress/components/home/svg/guide-svg.vue
Labels: CommitMessage::Qualified

#18376 fix(theme-chalk): upgrade SASS version and fix deprecated color function
  package.json
  packages/theme-chalk/src/color/index.scss
  packages/theme-chalk/src/mixins/_var.scss
  pnpm-lock.yaml
Labels: ready to merge, Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review
