Repository element-plus/element-plus, pull requests merged in 2024-07, with the labels that each got.

#17341 fix(components): [image] imageViewer crossorigin configuration missing
  packages/components/image-viewer/src/image-viewer.vue
  packages/components/image/src/image.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17374 fix(components): [carousel] disable the last monitoblur effect
  packages/components/carousel/src/use-carousel.ts
Labels: CommitMessage::Qualified

#17419 ci: bump pnpm/action-setup from 2 to 4
  .github/workflows/lint-commit-message.yml
  .github/workflows/pr-docs-build.yml
  .github/workflows/publish-build-product.yml
  .github/workflows/publish-docs-deploy-manual.yml
  .github/workflows/publish-docs-deploy.yml
  .github/workflows/publish-npm-nightly.yml
  .github/workflows/publish-npm.yml
  .github/workflows/publish-size-report.yml
  .github/workflows/staging-docs.yml
  .github/workflows/test-coverage.yml
  .github/workflows/test-ssr.yml
  .github/workflows/test-unit.yml
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17404 docs: add single closed tag tip for using CDN in `HTML`
  docs/en-US/guide/installation.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17445 feat(components): [select & select-v2] add `tag-effect` prop
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/select.vue
  packages/components/select/src/select.ts
  packages/components/select/src/select.vue
  packages/theme-chalk/src/select.scss
Labels: Project::Enhancement, Contribution::Community, CommitMessage::Qualified, Needs Review

#17447 chore(play): add breakpoint debugging config for VS Code
  .vscode/launch.json
  play/vite.config.ts
Labels: CommitMessage::Qualified

#17460 fix(ssr): [tree-select] document is not defined
  packages/components/tree-select/src/cache-options.ts
Labels: CommitMessage::Qualified

#17473 fix(components): [tree-select] fix filter no matching data error
  packages/components/tree-select/__tests__/tree-select.test.tsx
  packages/components/tree-select/src/tree-select-option.ts
  packages/components/tree-select/src/tree.ts
Labels: CommitMessage::Qualified, Needs Review

#17448 fix(hooks): cannot access 'useEmptyValuesProps' before initialization
  packages/components/config-provider/src/hooks/use-global-config.ts
  packages/hooks/use-empty-values/index.ts
Labels: CommitMessage::Qualified

#17484 feat(i18n): add fr translation for el-tour
  packages/locale/lang/fr.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17506 chore: update doc
  docs/.vitepress/config/sponsors.ts
  docs/public/images/sponsors/CRMEB-l.png
Labels: CommitMessage::Qualified

#17475 feat: prepare seperate release for package constants
  clean-package.json
  packages/constants/package.json
  packages/constants/tsconfig.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#17051 docs(components): [radio & checkbox] add using `value` tip and perf examples
  docs/en-US/component/checkbox.md
  docs/en-US/component/radio.md
  docs/examples/checkbox/basic.vue
  docs/examples/radio/basic-usage.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17511 fix(components): [tree-v2] component activation content not displayed
  packages/components/virtual-list/src/builders/build-list.ts
Labels: CommitMessage::Qualified

#17444 refactor(docs): upgrade vitepress
  .gitignore
  docs/.vitepress/config/index.mts
  docs/.vitepress/config/index.ts
  docs/.vitepress/config/plugins.ts
  docs/.vitepress/plugins/api-table.ts
  docs/.vitepress/plugins/headers.ts
  docs/.vitepress/plugins/markdown-transform.ts
  docs/.vitepress/plugins/tag.ts
  docs/.vitepress/theme/style.css
  docs/.vitepress/utils/highlight.ts
  docs/.vitepress/vitepress/components/common/vp-link.vue
  docs/.vitepress/vitepress/components/demo/vp-source-code.vue
  docs/.vitepress/vitepress/components/doc-content/vp-table-of-content.vue
  docs/.vitepress/vitepress/components/navbar/vp-menu-link.vue
  docs/.vitepress/vitepress/components/sidebar/vp-sidebar-link.vue
  docs/.vitepress/vitepress/components/vp-app.vue
  docs/.vitepress/vitepress/composables/page-nav.ts
  docs/.vitepress/vitepress/composables/sidebar.ts
  docs/.vitepress/vitepress/styles/code.scss
  docs/.vitepress/vitepress/utils/index.ts
  docs/components.d.ts
  docs/package.json
  docs/unocss.config.ts
  docs/vite.config.ts
  internal/build-constants/package.json
  internal/build-utils/package.json
  pnpm-lock.yaml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16692 fix(components): [radio-button] model-value click style lost and format test file
  packages/components/radio/__tests__/radio.test.tsx
  packages/theme-chalk/src/radio-button.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17526 feat(components): [cascader] add persistent props to cascader to improve performace
  docs/en-US/component/cascader.md
  packages/components/cascader/src/cascader.ts
  packages/components/cascader/src/cascader.vue
Labels: CommitMessage::Qualified

#17545 fix(components): [color-picker/tree-v2] build error typechecking fails with error TS2300
  packages/components/color-picker/src/color-picker.ts
  packages/components/tree-v2/src/virtual-tree.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17588 docs: perf highlight display and simplify code
  docs/en-US/component/checkbox.md
  docs/en-US/component/radio.md
  docs/en-US/guide/i18n.md
  docs/en-US/guide/quickstart.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17342 feat(components): [date-picker] `type` add `months` params
  docs/components.d.ts
  docs/en-US/component/date-picker.md
  docs/examples/date-picker/other-measurements.vue
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/src/date-picker-com/basic-month-table.vue
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/date-picker/src/date-picker.type.ts
  packages/components/date-picker/src/props/basic-date-table.ts
  packages/components/date-picker/src/props/shared.ts
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/constants.ts
  packages/constants/date.ts
  packages/utils/__tests__/vue/validator.test.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17592 docs(components): [message-box] fix api prop description
  docs/en-US/component/message-box.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17449 fix(components): [cascader] reactive prop `collapse-tags`
  packages/components/cascader/src/cascader.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17441 fix(components): [tree]calling method to expand node accordion mode fail
  packages/components/tree/src/tree.vue
Labels: CommitMessage::Qualified

#17333 fix(components): [table] expand-row-keys change to explicit type
  docs/en-US/component/table.md
  packages/components/table/src/table/defaults.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17600 chore: uodate element plus email address
  .github/workflows/publish-docs-deploy-manual.yml
  .github/workflows/publish-docs-deploy.yml
  .github/workflows/staging-docs.yml
Labels: CommitMessage::Qualified

#17443 feat(components): [cascader] add `tag-effect` prop
  docs/en-US/component/cascader.md
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/src/cascader.ts
  packages/components/cascader/src/cascader.vue
  packages/theme-chalk/src/cascader.scss
Labels: Project::Enhancement, Contribution::Community, CommitMessage::Qualified, Needs Review

#17549 fix: sass declaration deprecation error
  packages/theme-chalk/src/button-group.scss
  packages/theme-chalk/src/button.scss
  packages/theme-chalk/src/col.scss
  packages/theme-chalk/src/input-number.scss
  packages/theme-chalk/src/menu.scss
  packages/theme-chalk/src/mixins/_col.scss
  packages/theme-chalk/src/overlay.scss
  packages/theme-chalk/src/switch.scss
  packages/theme-chalk/src/table-v2.scss
  packages/theme-chalk/src/tag.scss
  packages/theme-chalk/src/upload.scss
Labels: Quality::Style Related, CommitMessage::Qualified

#17603 fix(components): [message-box] vue wraning when button state is loading
  packages/components/message-box/src/index.vue
Labels: CommitMessage::Qualified

#17291 docs(docs): [skeleton] fix layout error in example
  docs/examples/skeleton/rendering-with-data.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17085 fix(components): [input] add prop "row" explicit declare
  packages/components/input/src/input.ts
  packages/components/input/src/input.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17607 refactor(components): [button-group] optimize code
  packages/components/button/src/button-group.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17430 chore(build): update declare module name for volar
  global.d.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17610 refactor(components): [link & text] optimize boolean type
  packages/components/link/src/link.ts
  packages/components/text/src/text.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17174 feat(components): [loading] replenish loading attributes
  docs/en-US/component/loading.md
  packages/components/loading/src/service.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15387 docs(components): [popover] use new display tag
  docs/en-US/component/popover.md
  packages/components/popover/src/popover.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16986 fix(components): [tabs] add button misalignment in vertical layout
  packages/components/tabs/src/tabs.tsx
  packages/theme-chalk/src/tabs.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17016 fix(components): [tabs] bar width is error when only one bar
  packages/components/tabs/src/tab-bar.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16848 fix(components): [form] not use status-icon and use slot icon style error
  packages/theme-chalk/src/form.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15380 docs(components): [tabs] use new display tag
  docs/en-US/component/tabs.md
  packages/components/tabs/src/tab-pane.ts
  packages/components/tabs/src/tabs.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14953 docs(components): [carousel] use new display tag
  docs/en-US/component/carousel.md
  packages/components/carousel/src/carousel-item.ts
  packages/components/carousel/src/carousel.ts
  packages/components/carousel/src/carousel.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15378 docs(components): [dropdown] use new display tag
  docs/en-US/component/dropdown.md
  packages/components/dropdown/src/dropdown.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17635 chore(eslint-config): ignore the vitepress cache folder
  .eslintignore
  .prettierignore
Labels: CommitMessage::Qualified

#15385 docs(components): [menu] use new display tag
  docs/en-US/component/menu.md
  packages/components/menu/src/menu-item-group.ts
  packages/components/menu/src/menu-item.ts
  packages/components/menu/src/menu.ts
  packages/components/menu/src/sub-menu.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16735 feat(docs): support playground sync theme
  docs/.vitepress/vitepress/composables/use-playground.ts
Labels: CommitMessage::Qualified

#16511 feat(components): [time-select] export TimeSelectProps and Instance
  packages/components/time-select/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17644 chore(vscode): fix `unocss` highlighting on `windows` caused by node path diff
  docs/unocss.config.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17628 test(components): [badge] complete test cases
  packages/components/badge/__tests__/badge.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17611 test(components): [tag] replace closeTransition with disableTransitions
  packages/components/tag/__tests__/tag.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17316 docs: add `Style` source link
  docs/.vitepress/crowdin/en-US/component/footer.json
  docs/.vitepress/plugins/markdown-transform.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17272 feat(components): [table-column] add `filter-icon` slot
  docs/en-US/component/table.md
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/filter-panel.vue
  packages/components/table/src/table-column/render-helper.ts
  packages/components/table/src/table-header/index.ts
Labels: Project::Enhancement, CommitMessage::Qualified

#17651 fix(components): [cascader] failed to retrieve value when value is `0`
  packages/components/cascader/src/cascader.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17622 refactor(components): optimize component boolean type
  packages/components/breadcrumb/src/breadcrumb-item.ts
  packages/components/check-tag/src/check-tag.ts
  packages/components/descriptions/src/description.ts
  packages/components/dialog/src/dialog.ts
  packages/components/input/src/input.ts
  packages/components/notification/src/notification.ts
  packages/components/overlay/src/overlay.ts
  packages/components/progress/src/progress.ts
  packages/components/rate/src/rate.ts
  packages/components/switch/src/switch.ts
  packages/components/teleport/src/teleport.ts
  packages/components/timeline/src/timeline-item.ts
  packages/components/tooltip-v2/src/content.ts
  packages/components/tooltip/src/content.ts
  packages/components/upload/src/upload.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17621 feat(components): [carousel] add `cardScale` prop
  docs/en-US/component/carousel.md
  packages/components/carousel/__tests__/carousel.test.tsx
  packages/components/carousel/src/carousel.ts
  packages/components/carousel/src/constants.ts
  packages/components/carousel/src/use-carousel-item.ts
  packages/components/carousel/src/use-carousel.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17650 feat(components): [carousel] export `activeIndex`
  docs/en-US/component/carousel.md
  packages/components/carousel/__tests__/carousel.test.tsx
  packages/components/carousel/src/carousel.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17656 fix(components): [segmented] `modelValue` boolean type validation warning
  docs/en-US/component/segmented.md
  packages/components/segmented/src/segmented.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16741 improvement(components): @touchstart @touchmove @wheel add passive
  packages/components/color-picker/src/utils/draggable.ts
  packages/components/slider/src/button.vue
  packages/components/slider/src/composables/use-slider-button.ts
  packages/components/slider/src/slider.vue
  packages/components/virtual-list/src/builders/build-grid.ts
  packages/components/virtual-list/src/builders/build-list.ts
  packages/components/virtual-list/src/components/scrollbar.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17654 fix(build-utils): ignore the effects of directories when exclude files
  internal/build-utils/src/pkg.ts
Labels: CommitMessage::Qualified

#17685 fix(components): [select] exceeding the limit will still trigger update
  packages/components/select/src/option.vue
Labels: CommitMessage::Qualified

#15328 fix(components): [slider] set slider precision
  packages/components/slider/__tests__/slider.test.tsx
  packages/components/slider/src/slider.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17629 fix(components): [table] cover more edge cases for `show-overflow-tooltip`
  packages/components/table/src/table-body/events-helper.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17608 fix(components): [table] fix sorting issue in table-column
  packages/components/table/src/table-header/event-helper.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17599 chore: improve intellisense in codebase
  docs/components.d.ts
  docs/package.json
  pnpm-lock.yaml
  tsconfig.web.json
  typings/components.d.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#11363 fix(components): [scrollbar] restore scroll position in onActivated hook
  packages/components/scrollbar/src/scrollbar.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15061 perf(hooks): replace the ref object with a plain object
  packages/hooks/use-cursor/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17594 docs(components): [menu] fix invalid HTML code in the example
  docs/examples/menu/left-and-right.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14240 refactor(hooks): rewrite composition as a composable function
  packages/components/cascader/src/cascader.vue
  packages/components/input/src/input.vue
  packages/components/select-v2/src/useInput.ts
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/useSelect.ts
  packages/hooks/index.ts
  packages/hooks/use-composition/index.ts
Labels: CommitMessage::Qualified

#17271 chore: fix warn info & ts error
  docs/examples/table/filter.vue
Labels: CommitMessage::Qualified

#17690 chore(components): [select] remove unused Input component
  packages/components/select/src/select.vue
  packages/components/select/style/css.ts
  packages/components/select/style/index.ts
Labels: CommitMessage::Qualified

#15402 fix(components): [slider] data anomaly when the input value is undefined
  packages/components/slider/src/composables/use-slide.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15183 fix(components): [tabs] optimize SSR
  packages/components/tabs/src/constants.ts
  packages/components/tabs/src/tab-pane.vue
  packages/components/tabs/src/tabs.tsx
  packages/hooks/use-ordered-children/index.ts
  packages/theme-chalk/src/tabs.scss
Labels: Contribution::Community, breaking change, CommitMessage::Qualified, Needs Review, Minor Version

#15260 fix(style): [radio] marginRight 30px same as checkbox
  packages/theme-chalk/src/radio.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17362 fix(components): [select-v2] corrent focus to input when select clicked
  packages/components/select-v2/__tests__/select.test.ts
  packages/hooks/use-focus-controller/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17675 chore(utils): improve code style for global-node
  packages/utils/vue/global-node.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14135 fix(components):[tabs] reactive objects may lose reactivity in label slot
  packages/components/tabs/src/tab-nav.tsx
  packages/components/tabs/src/tabs.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17664 docs: add keyboard control switch theme
  docs/.vitepress/vitepress/components/common/vp-theme-toggler.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#14245 feat(components): [color-picker] alpha-slider a11y
  packages/components/color-picker/__tests__/color-picker.test.tsx
  packages/components/color-picker/src/components/alpha-slider.vue
  packages/components/color-picker/src/composables/use-alpha-slider.ts
  packages/locale/lang/en.ts
  packages/locale/lang/zh-cn.ts
  packages/theme-chalk/src/color-picker.scss
Labels: CommitMessage::Qualified

#17726 docs: format the tree-select component code
  docs/examples/tree-select/slots.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review
