Repository element-plus/element-plus, pull requests merged in 2024-02, with the labels that each got.

#15524 fix(components): [upload] Add crossorigin property
  docs/en-US/component/upload.md
  packages/components/upload/src/upload-list.ts
  packages/components/upload/src/upload-list.vue
  packages/components/upload/src/upload.ts
  packages/components/upload/src/upload.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15727 feat(components): [check-tag] add type prop
  docs/en-US/component/tag.md
  docs/examples/tag/basic.vue
  docs/examples/tag/checkable.vue
  docs/examples/tag/editable.vue
  docs/examples/tag/removable.vue
  docs/examples/tag/rounded.vue
  docs/examples/tag/sizes.vue
  docs/examples/tag/theme.vue
  packages/components/check-tag/src/check-tag.ts
  packages/components/check-tag/src/check-tag.vue
  packages/components/tag/src/tag.ts
  packages/components/tag/src/tag.vue
  packages/theme-chalk/src/check-tag.scss
  packages/theme-chalk/src/tag.scss
Labels: CommitMessage::Qualified

#15753 test(components): [tree] setCheckedNodes with disabled node
  packages/components/tree/__tests__/tree.test.ts
Labels: CommitMessage::Qualified

#15733 fix(components): [tabs] slot name use kebab-case style
  docs/en-US/component/tabs.md
  docs/examples/tabs/customized-add-button-icon.vue
  packages/components/tabs/src/tabs.tsx
Labels: CommitMessage::Qualified

#15773 style(eslint-config): add eslint rules to restrict the imports of lodash
  internal/build/src/tasks/full-bundle.ts
  internal/eslint-config/index.js
  internal/metadata/src/contributor.ts
  packages/components/infinite-scroll/__tests__/infinite-scroll.test.ts
  packages/components/tour/src/step.vue
  packages/test-utils/define-getter.ts
  packages/test-utils/make-mount.ts
  packages/utils/__tests__/arrays.test.ts
Labels: CommitMessage::Qualified

#15774 D2M
  CHANGELOG.en-US.md
  internal/build/src/tasks/full-bundle.ts
  internal/eslint-config/index.js
  internal/metadata/src/contributor.ts
  packages/components/infinite-scroll/__tests__/infinite-scroll.test.ts
  packages/components/tour/src/step.vue
  packages/test-utils/define-getter.ts
  packages/test-utils/make-mount.ts
  packages/utils/__tests__/arrays.test.ts
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#15579 fix(components): [carousel] improve a11y
  packages/components/carousel/src/carousel.vue
  packages/locale/lang/af.ts
  packages/locale/lang/ar-eg.ts
  packages/locale/lang/ar.ts
  packages/locale/lang/az.ts
  packages/locale/lang/bg.ts
  packages/locale/lang/bn.ts
  packages/locale/lang/ca.ts
  packages/locale/lang/ckb.ts
  packages/locale/lang/cs.ts
  packages/locale/lang/da.ts
  packages/locale/lang/de.ts
  packages/locale/lang/el.ts
  packages/locale/lang/en.ts
  packages/locale/lang/eo.ts
  packages/locale/lang/es.ts
  packages/locale/lang/et.ts
  packages/locale/lang/eu.ts
  packages/locale/lang/fa.ts
  packages/locale/lang/fi.ts
  packages/locale/lang/fr.ts
  packages/locale/lang/he.ts
  packages/locale/lang/hr.ts
  packages/locale/lang/hu.ts
  packages/locale/lang/hy-am.ts
  packages/locale/lang/id.ts
  packages/locale/lang/it.ts
  packages/locale/lang/ja.ts
  packages/locale/lang/kk.ts
  packages/locale/lang/km.ts
  packages/locale/lang/ko.ts
  packages/locale/lang/ku.ts
  packages/locale/lang/ky.ts
  packages/locale/lang/lt.ts
  packages/locale/lang/lv.ts
  packages/locale/lang/mg.ts
  packages/locale/lang/mn.ts
  packages/locale/lang/nb-no.ts
  packages/locale/lang/nl.ts
  packages/locale/lang/pa.ts
  packages/locale/lang/pl.ts
  packages/locale/lang/pt-br.ts
  packages/locale/lang/pt.ts
  packages/locale/lang/ro.ts
  packages/locale/lang/ru.ts
  packages/locale/lang/sk.ts
  packages/locale/lang/sl.ts
  packages/locale/lang/sr.ts
  packages/locale/lang/sv.ts
  packages/locale/lang/sw.ts
  packages/locale/lang/ta.ts
  packages/locale/lang/th.ts
  packages/locale/lang/tk.ts
  packages/locale/lang/tr.ts
  packages/locale/lang/ug-cn.ts
  packages/locale/lang/uk.ts
  packages/locale/lang/uz-uz.ts
  packages/locale/lang/vi.ts
  packages/locale/lang/zh-cn.ts
  packages/locale/lang/zh-tw.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15211 fix(components): [number-input] cannot scroll the container when the mouse pointer over an input
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15588 feat(style): add og-image & apply lint
  .github/triage.yml
  docs/.vitepress/config/head.ts
  docs/en-US/component/cascader.md
  docs/en-US/component/image.md
  docs/en-US/component/link.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/public/images/element-plus-og-image.png
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/form.scss
  packages/theme-chalk/src/input.scss
  packages/theme-chalk/src/select.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15768 fix(components): [tree-select] always focus when using filters
  packages/components/tree-select/__tests__/tree-select.test.tsx
  packages/components/tree-select/src/tree.ts
Labels: CommitMessage::Qualified

#15529 fix(components): [table] row has rowspan when hover it only has background on the first row of this rowspan
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/table-body/events-helper.ts
  packages/components/table/src/table-body/index.ts
  packages/theme-chalk/src/table.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15276 fix : toc link overflow
  docs/.vitepress/vitepress/styles/content/table-of-content.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15765 feat(components): [select] & [select-v2] add fallbackPlacements prop
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/tooltip.md
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/select.vue
  packages/components/select/src/select.ts
  packages/components/select/src/select.vue
Labels: CommitMessage::Qualified, Needs Review

#15838 fix(components): [select-v2] Tags not update when options sync added
  packages/components/select-v2/src/useSelect.ts
Labels: CommitMessage::Qualified

#15844 docs: add upgrade changes link
  docs/.vitepress/vitepress/components/globals/vp-changelog.vue
  docs/en-US/guide/changelog.md
Labels: CommitMessage::Qualified

#15847 docs(link): fix link doc
  docs/en-US/component/link.md
Labels: CommitMessage::Qualified

#15855 chore: format code
  docs/.vitepress/vitepress/styles/content/table-of-content.scss
  docs/en-US/component/dialog.md
  docs/en-US/component/link.md
  docs/en-US/component/message-box.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/tag.md
  docs/en-US/component/tour.md
  docs/en-US/component/upload.md
  packages/theme-chalk/src/dialog.scss
  packages/theme-chalk/src/message-box.scss
  packages/theme-chalk/src/tour.scss
Labels: CommitMessage::Qualified

#15854 feat(docs): preview page jumps to github with pr number
  docs/.vitepress/vitepress/components/navbar/vp-social-link.vue
Labels: CommitMessage::Qualified

#15861 fix(components): [upload] drag use before-upload to intercepting files
  packages/components/upload/src/upload-dragger.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15865 fix(components): [input] type hidden use class
  packages/components/input/src/input.vue
  packages/theme-chalk/src/input.scss
Labels: CommitMessage::Qualified

#15900 fix(components): [drawer] use dynamic zIndex from useDialog hook(#15641)
  packages/components/drawer/src/drawer.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15920 fix(components): [select] the font color does not change when disabled
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/select.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15867 chore: update husky
  .husky/commit-msg
  .husky/pre-commit
  package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#15912 style(components): [message] Update message style
  docs/examples/message/basic.vue
  docs/examples/message/closable.vue
  docs/examples/message/different-types.vue
  docs/examples/message/grouping.vue
  docs/examples/message/raw-html.vue
  packages/components/message/__tests__/message-manager.test.tsx
  packages/components/message/src/instance.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/message.scss
Labels: CommitMessage::Qualified

#15911 style(components): [alert] Update alert style
  docs/examples/alert/basic.vue
  docs/examples/alert/center.vue
  docs/examples/alert/close-button.vue
  docs/examples/alert/description.vue
  docs/examples/alert/icon-description.vue
  docs/examples/alert/icon.vue
  docs/examples/alert/theme.vue
  packages/components/alert/src/alert.vue
  packages/theme-chalk/src/alert.scss
  packages/theme-chalk/src/common/var.scss
Labels: CommitMessage::Qualified

#15670 feat(components): anchor component
  docs/.vitepress/crowdin/en-US/pages/component.json
  docs/.vitepress/vitepress/components/doc-content/vp-table-of-content.vue
  docs/.vitepress/vitepress/composables/active-bar.ts
  docs/.vitepress/vitepress/styles/content/table-of-content.scss
  docs/en-US/component/anchor.md
  docs/examples/anchor/affix.vue
  docs/examples/anchor/basic.vue
  docs/examples/anchor/change.vue
  docs/examples/anchor/horizontal.vue
  docs/examples/anchor/scroll.vue
  docs/examples/anchor/underline.vue
  packages/components/anchor-link/style/css.ts
  packages/components/anchor-link/style/index.ts
  packages/components/anchor/__tests__/__snapshots__/anchor.test.tsx.snap
  packages/components/anchor/__tests__/anchor.test.tsx
  packages/components/anchor/index.ts
  packages/components/anchor/src/anchor-link.ts
  packages/components/anchor/src/anchor-link.vue
  packages/components/anchor/src/anchor.ts
  packages/components/anchor/src/anchor.vue
  packages/components/anchor/src/constants.ts
  packages/components/anchor/style/css.ts
  packages/components/anchor/style/index.ts
  packages/components/index.ts
  packages/element-plus/component.ts
  packages/theme-chalk/src/anchor-link.scss
  packages/theme-chalk/src/anchor.scss
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/index.scss
  packages/utils/dom/element.ts
  packages/utils/dom/index.ts
  packages/utils/dom/scroll.ts
  packages/utils/easings.ts
  packages/utils/index.ts
  packages/utils/throttleByRaf.ts
  packages/utils/types.ts
  typings/components.d.ts
Labels: CommitMessage::Qualified, Needs Review, Minor Version, Component::Anchor

#15944 feat(components): [badge] add show-zero prop
  docs/en-US/component/badge.md
  packages/components/badge/__tests__/badge.test.tsx
  packages/components/badge/src/badge.ts
  packages/components/badge/src/badge.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review, Minor Version

#15950 fix(components): [table-v2] header style error
  packages/components/table-v2/src/composables/use-styles.ts
Labels: CommitMessage::Qualified

#15970 fix(components): [tour] focusout error
  packages/components/tour/src/content.vue
Labels: CommitMessage::Qualified, Needs Review

#15725 fix(components): [input-number] fix default value reset error (#15725)
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15972 fix(components): [tour] floating-ui autoUpdate error
  packages/components/tour/src/helper.ts
Labels: CommitMessage::Qualified, Needs Review

#15918 fix(components): [date-picker] selected value comparison logic error
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/src/composables/use-basic-date-table.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15964 fix(components): [select-v2] show header and footer slots when empty
  packages/components/select-v2/src/select-dropdown.tsx
Labels: CommitMessage::Qualified

#15962 perf(components): [select & select-v2] optimize performance
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#15922 chore(components): clear deprecated API
  docs/en-US/component/menu.md
  packages/components/calendar/src/calendar.vue
  packages/components/calendar/src/use-calendar.ts
  packages/components/menu/src/sub-menu.ts
  packages/components/select/src/select.ts
  packages/components/select/src/useSelect.ts
  packages/components/switch/__tests__/switch.test.tsx
  packages/components/switch/src/switch.ts
  packages/components/switch/src/switch.vue
  packages/components/tabs/src/tabs.tsx
Labels: CommitMessage::Qualified, Minor Version

#15525 feat(components): [checkbox & radio] Use value instead of label act as value
  docs/en-US/component/checkbox.md
  docs/en-US/component/radio.md
  docs/examples/checkbox/basic.vue
  docs/examples/checkbox/button-style.vue
  docs/examples/checkbox/grouping.vue
  docs/examples/checkbox/intermediate.vue
  docs/examples/checkbox/limitation.vue
  docs/examples/checkbox/with-border.vue
  docs/examples/radio/basic-usage.vue
  docs/examples/radio/button-style.vue
  docs/examples/radio/disabled.vue
  docs/examples/radio/radio-button-group.vue
  docs/examples/radio/with-borders.vue
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/checkbox/src/checkbox-button.vue
  packages/components/checkbox/src/checkbox.ts
  packages/components/checkbox/src/checkbox.vue
  packages/components/checkbox/src/composables/use-checkbox-event.ts
  packages/components/checkbox/src/composables/use-checkbox-status.ts
  packages/components/checkbox/src/composables/use-checkbox.ts
  packages/components/radio/__tests__/radio.test.tsx
  packages/components/radio/src/radio-button.ts
  packages/components/radio/src/radio-button.vue
  packages/components/radio/src/radio-group.ts
  packages/components/radio/src/radio.ts
  packages/components/radio/src/radio.vue
  packages/components/radio/src/use-radio.ts
Labels: breaking change, CommitMessage::Qualified, Minor Version

#15981 fix(components): [select-v2] set modalValue when filtering display error
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/useSelect.ts
Labels: CommitMessage::Qualified

#15603 feat(components): [Carousel] Add motion blur functionality
  docs/en-US/component/carousel.md
  docs/examples/carousel/motion-blur.vue
  packages/components/carousel/__tests__/carousel.test.tsx
  packages/components/carousel/src/carousel.ts
  packages/components/carousel/src/carousel.vue
  packages/components/carousel/src/use-carousel.ts
  packages/theme-chalk/src/carousel.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15953 fix(components): [menu] Fixing Menu component's flickering issue with surplus sub-items on insufficient page height.
  packages/components/menu/src/menu.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15974 fix(components): [tree-select] remote method and selected override
  packages/components/tree-select/__tests__/tree-select.test.tsx
  packages/components/tree-select/src/select.ts
  packages/components/tree-select/src/tree.ts
Labels: CommitMessage::Qualified
