Repository element-plus/element-plus, pull requests merged in 2024-08, with the labels that each got.

#17694 fix(theme-chalk): [tabs] padding is incorrect while hovering on `border-card`-shaped tab
  packages/theme-chalk/src/tabs.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17292 refactor(components): [slider]optimize ts types
  packages/components/slider/src/button.ts
  packages/components/slider/src/composables/use-slider-button.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17735 chore(components): remove deprecated 2.8.0
  packages/components/badge/src/badge.ts
  packages/components/badge/src/badge.vue
  packages/components/checkbox/src/checkbox-group.ts
  packages/components/checkbox/src/checkbox-group.vue
  packages/components/checkbox/src/checkbox.ts
  packages/components/checkbox/src/checkbox.vue
  packages/components/checkbox/src/composables/use-checkbox.ts
  packages/components/color-picker/src/color-picker.ts
  packages/components/color-picker/src/color-picker.vue
  packages/components/input-number/src/input-number.ts
  packages/components/input-number/src/input-number.vue
  packages/components/input/src/input.ts
  packages/components/input/src/input.vue
  packages/components/radio/src/radio-group.ts
  packages/components/radio/src/radio-group.vue
  packages/components/rate/src/rate.ts
  packages/components/rate/src/rate.vue
  packages/components/slider/src/slider.ts
  packages/components/slider/src/slider.vue
  packages/components/switch/src/switch.ts
  packages/components/switch/src/switch.vue
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/common/props.ts
Labels: CommitMessage::Qualified, Minor Version

#17692 fix(components): [image] cannot trigger event when image is loaded error
  packages/components/image/src/image.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14050 feat(components): [tree-v2] add scrollTo method
  docs/en-US/component/tree-v2.md
  packages/components/tree-v2/__tests__/tree.test.ts
  packages/components/tree-v2/src/composables/useTree.ts
  packages/components/tree-v2/src/tree.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17752 docs: [menu] fix descriptions for deprecated attributes
  docs/en-US/component/menu.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17758 fix(components): [abort popper] fix effect type error
  docs/en-US/component/menu.md
  docs/en-US/component/popover.md
  packages/components/menu/src/menu.ts
  packages/components/popper/src/content.ts
  packages/components/select-v2/src/defaults.ts
  packages/components/select/src/select.ts
  packages/components/time-select/src/time-select.ts
  packages/components/tooltip-v2/src/content.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#13157 refactor(components): [image-viewer] optimise translate calc method
  packages/components/image-viewer/src/image-viewer.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12943 fix(components): [date-picker] fix user input error in monthrange
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/src/date-picker-com/panel-month-range.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15332 fix(components): [slider] click on marks is inaccurately positioned
  packages/components/slider/src/composables/use-slide.ts
  packages/components/slider/src/slider.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17274 fix(components): [date-picker] clear button repeatedly triggers `update:model-value`
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17551 fix(components): SSR hydration error caused by disabled prop of teleport
  packages/components/dialog/src/dialog.vue
  packages/components/drawer/src/drawer.vue
  packages/components/image-viewer/src/image-viewer.vue
  packages/components/teleport/__tests__/teleport.test.ts
  packages/components/teleport/__tests__/teleport.test.tsx
  packages/components/teleport/src/teleport.ts
  packages/components/teleport/src/teleport.vue
  packages/components/tooltip-v2/src/tooltip.vue
  packages/components/tooltip/src/content.vue
  packages/components/tour/src/tour.vue
Labels: CommitMessage::Qualified

#17696 fix(components): [drawer] fix low animation fps without graphics acceleration
  packages/theme-chalk/src/drawer.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#12617 docs(components): [dropdown] add placement property example doc
  docs/en-US/component/dropdown.md
  docs/examples/dropdown/placements.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17760 docs(components): [mention] example error
  docs/examples/mention/loading.vue
Labels: CommitMessage::Qualified, Needs Review

#17761 feat(components): [drawer] add append-to
  docs/en-US/component/drawer.md
  packages/components/drawer/src/drawer.vue
Labels: CommitMessage::Qualified

#13519 feat(components): [table] tree children add check strictly
  docs/en-US/component/table.md
  docs/examples/table/check-strictly.vue
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/store/helper.ts
  packages/components/table/src/store/tree.ts
  packages/components/table/src/store/watcher.ts
  packages/components/table/src/table/defaults.ts
  packages/components/table/src/util.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review, Minor Version

#17763 chore(utils): improve setTimeout type
  packages/components/loading/src/loading.ts
  packages/hooks/use-throttle-render/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17737 fix(i18n): Compared with traditional Chinese, add simplified Chinese …
  packages/locale/lang/zh-cn.ts
  packages/locale/lang/zh-tw.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17768 fix(i18n): zh-cn lang typo
  packages/locale/lang/zh-cn.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17775 chore: Update publish-docs-deploy.yml
  .github/workflows/publish-docs-deploy.yml
Labels: CommitMessage::Qualified

#17585 fix(components): [tree] check isLeaf using lazy and default-expand-all
  packages/components/tree/src/model/node.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17699 feat(hooks): use-draggable support resetPostion
  docs/en-US/component/dialog.md
  packages/components/dialog/src/dialog-content.vue
  packages/components/dialog/src/dialog.vue
  packages/hooks/use-draggable/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10465 chore(components): [dropdown] format
  packages/components/dropdown/src/dropdown-item.vue
  packages/components/dropdown/src/dropdown-menu.vue
  packages/components/dropdown/src/dropdown.vue
  packages/components/dropdown/src/useDropdown.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17548 fix(components): [select/tree-select] with `teleported="false"` dropdown closes abnormally
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
  packages/components/time-select/__tests__/time-select.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17606 refactor(components): [select] cancel type conversion at initialization
  docs/en-US/component/select.md
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useOption.ts
  packages/components/select/src/useSelect.ts
  packages/components/tree-select/__tests__/tree-select.test.tsx
Labels: CommitMessage::Qualified, Minor Version

#17214 fix(components): [select] equal objects cannot destroy instances
  packages/components/select/src/useOption.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17143 feat(components): [upload] added index parameter to default slot
  docs/en-US/component/upload.md
  packages/components/upload/src/upload-list.vue
  packages/components/upload/src/upload.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17047 fix(components): [radio] change not trigger
  packages/components/radio/__tests__/radio.test.tsx
  packages/components/radio/src/radio.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#16715 fix(components): [upload] remove file when fileList does not use v-model
  packages/components/upload/src/use-handlers.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17719 refactor(hooks): determine the focus by event listening
  packages/components/autocomplete/__tests__/autocomplete.test.tsx
  packages/components/color-picker/__tests__/color-picker.test.tsx
  packages/components/color-picker/src/color-picker.vue
  packages/components/input/src/input.vue
  packages/components/mention/src/mention.vue
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/hooks/__tests__/use-focus-controller.test.tsx
  packages/hooks/use-focus-controller/index.ts
Labels: CommitMessage::Qualified

#14804 feat(components): [date-picker] add type yearrange for DatePicker
  docs/en-US/component/date-picker.md
  docs/examples/date-picker/year-range.vue
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/src/composables/use-year-range-header.ts
  packages/components/date-picker/src/date-picker-com/basic-year-table.vue
  packages/components/date-picker/src/date-picker-com/panel-year-range.vue
  packages/components/date-picker/src/date-picker.type.ts
  packages/components/date-picker/src/panel-utils.ts
  packages/components/date-picker/src/props/basic-year-table.ts
  packages/components/date-picker/src/props/panel-year-range.ts
  packages/components/time-picker/src/constants.ts
  packages/constants/date.ts
  packages/theme-chalk/src/date-picker/year-table.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review, Minor Version

#17798 fix(components): [statistic] fix excessive decimals when value is NAN
  packages/components/statistic/src/statistic.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17344 fix(components): fixed add listeners not remove on beforeunmount
  docs/.vitepress/config/index.mts
  internal/build/src/tasks/full-bundle.ts
  internal/build/src/tasks/modules.ts
  packages/components/autocomplete/src/autocomplete.vue
  packages/components/focus-trap/src/focus-trap.vue
  packages/components/popper/src/trigger.vue
  packages/components/time-picker/src/common/picker.vue
  packages/components/tooltip/src/content.vue
  packages/directives/click-outside/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review, conflict pending, Minor Version

#17748 fix(components): [date-picker] slot not take effect when type is month
  docs/en-US/component/date-picker.md
  docs/examples/date-picker/custom-content.vue
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/src/date-picker-com/basic-cell-render.tsx
  packages/components/date-picker/src/date-picker-com/basic-month-table.vue
  packages/components/date-picker/src/date-picker-com/basic-year-table.vue
  packages/components/date-picker/src/date-picker.type.ts
  packages/theme-chalk/src/date-picker/month-table.scss
  packages/theme-chalk/src/date-picker/year-table.scss
Labels: CommitMessage::Qualified

#11802 fix(components): [date-picker] Return to normal when reopened
  packages/components/date-picker/__tests__/date-time-picker.test.tsx
  packages/components/date-picker/src/composables/use-range-picker.ts
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  packages/components/date-picker/src/props/panel-date-range.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17453 feat(components): [date-picker] add icon slots
  docs/en-US/component/date-picker.md
  docs/en-US/component/datetime-picker.md
  docs/examples/date-picker/custom-icon.vue
  docs/examples/datetime-picker/custom-icon.vue
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  packages/components/date-picker/src/date-picker-com/panel-month-range.vue
  packages/components/date-picker/src/date-picker-com/panel-year-range.vue
  packages/components/date-picker/src/date-picker.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review, Minor Version

#17814 fix(components): [dialog] `appendTo` type error
  docs/en-US/component/dialog.md
  packages/components/dialog/src/dialog.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17819 chore: update doc UI
  docs/.vitepress/vitepress/components/vp-sponsors.vue
Labels: CommitMessage::Qualified

#17836 fix(components): [input] blur event fails when using textarea
  packages/components/input/__tests__/input.test.tsx
  packages/components/input/src/input.vue
Labels: CommitMessage::Qualified

#17837 test(components): default slot test case with type of month or year
  packages/components/date-picker/__tests__/date-picker.test.ts
Labels: CommitMessage::Qualified

#15848 fix(components): [date-picker] disabledDate is invalid when selecting year or month picker
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/src/date-picker-com/basic-month-table.vue
  packages/components/date-picker/src/date-picker-com/basic-year-table.vue
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/date-picker/src/props/shared.ts
  packages/components/date-picker/src/utils.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17840 feat(components): [cascader] support `placement` & `fallback-placements`
  docs/en-US/component/cascader.md
  packages/components/cascader/src/cascader.ts
  packages/components/cascader/src/cascader.vue
Labels: CommitMessage::Qualified

#17852 docs: remove tip about client-only
  docs/en-US/component/autocomplete.md
  docs/en-US/component/cascader.md
  docs/en-US/component/color-picker.md
  docs/en-US/component/date-picker.md
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/dialog.md
  docs/en-US/component/drawer.md
  docs/en-US/component/dropdown.md
  docs/en-US/component/menu.md
  docs/en-US/component/popconfirm.md
  docs/en-US/component/popover.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/en-US/component/slider.md
  docs/en-US/component/table-v2.md
  docs/en-US/component/table.md
  docs/en-US/component/time-picker.md
  docs/en-US/component/time-select.md
  docs/en-US/component/tooltip-v2.md
  docs/en-US/component/tooltip.md
  docs/en-US/component/tree-select.md
  docs/en-US/guide/ssr.md
Labels: CommitMessage::Qualified

#17855 fix(components): [dialog] error calling `resetPostion` before dialog is rendered
  packages/components/dialog/src/dialog.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17859 feat(components): [description] export props types
  packages/components/descriptions/src/description-item.ts
  packages/components/descriptions/src/description.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17826 style(components): [popper] fix arrow style
  packages/theme-chalk/src/popper.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#10639 style(theme-chalk): [input-number] fix controlled comps style
  packages/theme-chalk/src/date-picker/picker.scss
  packages/theme-chalk/src/input-number.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10509 docs(components): [Space] typo
  docs/en-US/component/space.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17848 feat(components): [mention] accessibility enhancement
  packages/components/mention/__tests__/mention.test.tsx
  packages/components/mention/src/mention-dropdown.ts
  packages/components/mention/src/mention-dropdown.vue
  packages/components/mention/src/mention.vue
Labels: CommitMessage::Qualified

#17765 feat(i18n): add Burmese(my) translation
  packages/locale/index.ts
  packages/locale/lang/my.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17876 fix(components): [select] binding click event is invalid
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/select.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
Labels: CommitMessage::Qualified

#17849 fix(components): [tree] FireFox dargging dataTransfer judge
  packages/components/tree/src/model/useDragNode.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17893 chore(components): [select] remove unnecessary assertions
  packages/components/select/src/options.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17884 fix(components): [table] toggleRowSelection restores previous behavior
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/store/watcher.ts
Labels: CommitMessage::Qualified

#8340 fix(components): [table] emptyText/sumText empty string is invalid
  packages/components/table/src/table.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17813 fix(components): [time-picker] avoid update initial value when using disabledHours & isRange
  packages/components/time-picker/__tests__/time-picker.test.tsx
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17907 chore(components): [input] remove repeated export of InputInstance
  docs/examples/tag/editable.vue
  packages/components/input/__tests__/input.test.tsx
  packages/components/input/src/input.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17804 fix(components): [button] use tag and disabled comp click triggered
  packages/components/button/__tests__/button.test.tsx
  packages/components/button/src/use-button.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17895 ci: automatically comment when adding conclict label
  .github/workflows/pr-conflict.yml
Labels: CommitMessage::Qualified, conflict pending

#17885 fix(components): [table] use isEqual to determine whether it is selected
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/store/watcher.ts
Labels: CommitMessage::Qualified

#17716 fix(components): [segmented] fix async disabled style of selected item
  packages/components/segmented/__tests__/segmented.test.tsx
  packages/components/segmented/src/segmented.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10195 fix(components): tree nodesMap leak
  packages/components/tree/src/model/tree-store.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17929 refactor(components): [affix] optimized code logic
  packages/components/affix/src/affix.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17949 fix(components): add segmented component type to `global.d.ts` file
  global.d.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#8284 perf(components): [virtual-list] wrap row with Fragment and set key on it
  packages/components/virtual-list/src/builders/build-grid.ts
  packages/components/virtual-list/src/builders/build-list.ts
Labels: Contribution::Community, 1st contribution, Component::Virtual List, CommitMessage::Qualified, Needs Review

#17900 fix(components): [dialog] rename resetPostion to resetPosition
  docs/en-US/component/dialog.md
  packages/components/dialog/src/dialog-content.vue
  packages/components/dialog/src/dialog.vue
  packages/hooks/use-draggable/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17575 style(components): [select] add a unique class name for the clear icon
  packages/components/select-v2/src/select.vue
  packages/components/select/src/select.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17472 docs: rendering example demos on the server side
  docs/.vitepress/config/index.mts
  docs/.vitepress/config/plugins.ts
  docs/.vitepress/plugins/demo.ts
  docs/.vitepress/plugins/markdown-transform.ts
  docs/.vitepress/theme/index.ts
  docs/.vitepress/vitepress/components/common/vp-theme-toggler.vue
  docs/.vitepress/vitepress/components/demo/vp-example.vue
  docs/.vitepress/vitepress/components/demo/vp-source-code.vue
  docs/.vitepress/vitepress/components/doc-content/vp-table-of-content.vue
  docs/.vitepress/vitepress/components/vp-demo.vue
  docs/components.d.ts
  docs/examples/border/radius.vue
  docs/examples/statistic/countdown.vue
  pnpm-lock.yaml
  typings/components.d.ts
Labels: CommitMessage::Qualified

#17958 refactor(components): [carousel] use var to replace raw string
  packages/components/carousel/src/carousel-item.vue
  packages/components/carousel/src/constants.ts
  packages/components/carousel/src/use-carousel-item.ts
  packages/components/carousel/src/use-carousel.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17975 chore(components): [dialog] change border-radius to base
  packages/theme-chalk/src/common/var.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#10314 feat(components): [descriptions] add rowspan
  docs/en-US/component/descriptions.md
  docs/examples/descriptions/rowspan.vue
  packages/components/descriptions/src/description-item.ts
  packages/components/descriptions/src/description.vue
  packages/components/descriptions/src/descriptions-cell.ts
  packages/components/descriptions/src/descriptions.type.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#17957 feat(components): [popconfirm] add actions slot
  docs/en-US/component/popconfirm.md
  docs/examples/popconfirm/customize.vue
  packages/components/popconfirm/__tests__/popconfirm.test.tsx
  packages/components/popconfirm/src/popconfirm.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15499 fix(theme-chalk): replace margin with padding
  packages/theme-chalk/src/date-picker/date-picker.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17981 chore: add vitest extensions
  .vscode/extensions.json
  vitest.workspace.ts
Labels: CommitMessage::Qualified

#17995 chore: Update publish-docs-deploy.yml
  .github/workflows/publish-docs-deploy.yml
Labels: CommitMessage::Qualified

#17980 docs(components): [form] update form clearValidate description
  docs/en-US/component/form.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18013 chore: add countdown component type to global.d.ts file
  global.d.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18018 docs(components): [table-v2] refine inline editing examples
  docs/examples/table-v2/inline-editing.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18020 chore(docs): [table] fix typo
  docs/examples/table/tree-and-lazy.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18006 fix(components): [tag] leave animations not working
  packages/components/tag/src/tag.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18048 refactor: import shared utilities from `@element-plus/utils`
  packages/components/autocomplete/__tests__/autocomplete.test.tsx
  packages/components/autocomplete/src/autocomplete.ts
  packages/components/cascader-panel/src/config.ts
  packages/components/cascader-panel/src/node.ts
  packages/components/cascader/src/cascader.vue
  packages/components/infinite-scroll/src/index.ts
  packages/components/input/src/input.ts
  packages/components/loading/src/directive.ts
  packages/components/popper/src/content.vue
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/options.ts
  packages/components/select/src/useSelect.ts
  packages/components/slot/src/only-child.tsx
  packages/components/space/src/space.ts
  packages/components/switch/src/switch.vue
  packages/components/tree-v2/__tests__/tree.test.ts
  packages/components/tree-v2/src/composables/useFilter.ts
  packages/components/tree/src/tree-node.vue
  packages/components/upload/src/upload-content.ts
  packages/components/upload/src/upload-content.vue
  packages/components/upload/src/upload-list.ts
  packages/components/upload/src/upload.ts
  packages/components/virtual-list/src/components/dynamic-size-grid.ts
  packages/hooks/__tests__/use-form-item.test.tsx
  packages/hooks/__tests__/use-teleport.test.tsx
  packages/hooks/use-model-toggle/index.ts
  packages/hooks/use-same-target/index.ts
  packages/hooks/use-teleport/index.ts
  packages/utils/functions.ts
  packages/utils/types.ts
  packages/utils/vue/install.ts
  packages/utils/vue/vnode.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18030 fix(components): [select] switching single/multiple generates an error
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#18087 chore: update doc ui
  docs/.vitepress/vitepress/components/vp-sponsors.vue
Labels: CommitMessage::Qualified

#17946 workflow: set up continuous release with pkg.pr.new
  .github/workflows/pkg-pr-new.yml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17936 feat(components): [check-tag] add `disabled` prop
  docs/en-US/component/tag.md
  docs/examples/tag/checkable.vue
  packages/components/check-tag/__tests__/check-tag.test.tsx
  packages/components/check-tag/src/check-tag.ts
  packages/components/check-tag/src/check-tag.vue
  packages/theme-chalk/src/check-tag.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18102 fix(docs): persist color themes
  docs/.vitepress/config/head.ts
  docs/.vitepress/dark-mode.js
  docs/.vitepress/vitepress/composables/dark.ts
Labels: CommitMessage::Qualified

#18099 chore: upgrade vitest
  package.json
  packages/components/form/__tests__/form-item.test.tsx
  packages/components/notification/__tests__/notification.test.tsx
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#18108 fix: the disabled state should not trigger focus
  packages/components/input/src/input.vue
  packages/components/mention/src/mention.vue
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/useSelect.ts
  packages/hooks/__tests__/use-focus-controller.test.tsx
  packages/hooks/use-focus-controller/index.ts
Labels: CommitMessage::Qualified

#18113 docs(theme-chalk): [menu] add how to set menu default height
  docs/en-US/component/menu.md
Labels: CommitMessage::Qualified
