Repository element-plus/element-plus, pull requests merged in 2024-11, with the labels that each got.

#18737 fix: downgrade vue-tsc to 2.0.28
  package.json
  packages/components/tabs/src/tab-bar.vue
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#18733 docs(components): add direction api description for segmented
  docs/en-US/component/segmented.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18649 fix(utils):[vue] ensure `flattedChildren` traverse component's subTree
  packages/utils/__tests__/vue/vnode.test.ts
  packages/utils/vue/vnode.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18738 chore: upgrade dayjs 1.11.3 to 1.11.13
  package.json
  pnpm-lock.yaml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18761 chore(play): update logo link
  play/index.html
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18765 chore: upgrade dayjs from 1.11.3 to 1.11.13
  packages/element-plus/package.json
  pnpm-lock.yaml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18752 fix(components): [select] prevent keyboard from deleting disabled option
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18769 docs: describes the pnpm version for debugging source code
  CONTRIBUTING.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18704 chore: gen script does not support hyphens
  scripts/gc.sh
Labels: CommitMessage::Qualified

#18711 fix(theme-chalk): sass `!global assignments` deprecation warning
  packages/theme-chalk/src/mixins/mixins.scss
Labels: CommitMessage::Qualified

#18767 fix(components): [picker] fix popup not opening when editable is false
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18751 fix(components): [mention] keyboard control options not work as expected
  packages/components/mention/src/mention-dropdown.vue
Labels: CommitMessage::Qualified

#18762 docs: fix type error for autocomplete
  docs/examples/autocomplete/autocomplete-template.vue
  docs/examples/autocomplete/autocomplete.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18768 docs: use native fetch for changelogs
  docs/.vitepress/vitepress/components/globals/vp-changelog.vue
  docs/package.json
  pnpm-lock.yaml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18798 feat(components): [select-v2] add `append-to` prop
  docs/en-US/component/select-v2.md
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/select.vue
Labels: CommitMessage::Qualified

#18786 chore: remove deprecated package @types/sass
  package.json
  pnpm-lock.yaml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18818 fix(components): [segmented] invisible active indicator after clearing selection
  packages/components/segmented/src/segmented.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18804 docs(components): correct the select and select-v2 documents
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18773 improvement: [select] optimize the effect of keyboard switching options
  packages/components/select-v2/src/option-item.vue
  packages/components/select/src/option.vue
Labels: CommitMessage::Qualified

#18809 chore(deps): update vite related dependency for play and docs
  docs/.vitepress/build/rebuild-pwa.ts
  docs/package.json
  docs/tsconfig.json
  docs/unocss.config.ts
  package.json
  play/main.ts
  play/package.json
  play/vite.config.mts
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#18824 docs(components): use `""` replace null for no icon setting
  docs/en-US/component/page-header.md
  docs/examples/page-header/additional-sections.vue
  docs/examples/page-header/no-icon.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18787 fix(components): [mention] ref dom array order error when list changes
  packages/components/mention/src/mention-dropdown.vue
Labels: CommitMessage::Qualified, Component::Mention

#18810 refactor(components): [select] simplify code
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#18842 docs: optimize sidebar style
  docs/.vitepress/vitepress/components/doc-content/vp-table-of-content.vue
Labels: CommitMessage::Qualified

#18317 fix(components): [table] failed to insert tooltip when show-overflow-tooltip is enabled
  packages/components/table/src/util.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18837 feat(components): [select] add `offset` and `show-arrow` prop
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/select.vue
  packages/components/select/src/select.ts
  packages/components/select/src/select.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18864 ci: remove `needs more info` label when edited
  .github/workflows/issue-remove-inactive.yml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18867 fix(components): [select] `getValueIndex` empty error
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#18869 feat(style): support vitepress vp-code-group
  docs/.vitepress/theme/index.ts
  docs/en-US/component/icon.md
  docs/en-US/guide/installation.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18101 fix(components): [select & select-v2] status-icon is invalid
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18878 fix(components): [pagination] input style loss
  packages/components/pagination/style/css.ts
  packages/components/pagination/style/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14216 fix(components): time-picker disabled-[hours/minutes/seconds] (#13364)
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18388 fix(components): [select-v2] resolve overlap of tags and placeholder
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#16054 fix(components): [table] repeat setting the height style
  packages/components/table/src/table.vue
  packages/components/table/src/table/style-helper.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18914 chore: update ui
  docs/.vitepress/vitepress/components/vp-sponsors.vue
Labels: CommitMessage::Qualified

#18920 chore: fix type error of the tree customNodeClass demo
  docs/examples/tree/custom-node-class.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18911 feat(components): [tree-v2] add `props.class` prop
  docs/en-US/component/tree-v2.md
  docs/examples/tree-v2/custom-node-class.vue
  packages/components/tree-v2/__tests__/tree.test.ts
  packages/components/tree-v2/src/tree-node.vue
  packages/components/tree-v2/src/types.ts
  packages/components/tree-v2/src/virtual-tree.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18549 fix(components): [select] keep the selected label
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/option.vue
Labels: CommitMessage::Qualified

#18923 improvement(components): [tooltip] dom ref types
  docs/en-US/component/tooltip.md
  packages/components/tooltip/src/content.vue
  packages/components/tooltip/src/tooltip.vue
Labels: CommitMessage::Qualified

#18926 chore: fix type error of the tree-v2 props.value docs
  docs/en-US/component/tree-v2.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18927 docs(components): fix type error of the tree-v2 filter demo
  docs/examples/tree-v2/filter.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18930 ci: remove `need reproduction` label
  .github/workflows/issue-remove-inactive.yml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18558 feat(components): [notification] add support for message as a Function
  .vscode/settings.json
  docs/en-US/component/notification.md
  docs/examples/notification/use-vnode.vue
  packages/components/notification/src/notification.ts
  packages/components/notification/src/notify.ts
Labels: ready to merge, Contribution::Community, CommitMessage::Qualified, Needs Review

#18942 fix(types): improve styles type by CSSProperties
  packages/components/time-picker/src/common/picker-range-trigger.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#17919 fix(components): [image-viewer] unable to capture focus
  packages/components/image-viewer/src/image-viewer.vue
  packages/theme-chalk/src/image-viewer.scss
Labels: CommitMessage::Qualified

#18950 docs(locale): add Malay(ms) translation
  docs/en-US/guide/i18n.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18928 fix(components): [tag] make stubbed Transition work in tests
  packages/components/tag/src/tag.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18937 docs(components): [table-v2] unified display style of parameters
  docs/en-US/component/table-v2.md
Labels: CommitMessage::Qualified

#18969 test(components): fix test cases in select.test.ts
  packages/components/select/__tests__/select.test.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18980 feat(components): [tree-v2] add slot `empty`
  docs/en-US/component/tree-v2.md
  packages/components/tree-v2/__tests__/tree.test.ts
  packages/components/tree-v2/src/tree.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18987 docs: makeup built-in zoom-in-left transition
  docs/en-US/guide/transitions.md
  docs/examples/transitions/zoom.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18988 test(components): [input-number] ensure that length restriction exceptions can be caught
  packages/components/input-number/__tests__/input-number.test.tsx
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18981 fix(components): [tree-select] expose `selectedLabel`
  packages/components/tree-select/src/tree-select.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18285 fix(components): [cascader] multiple selection mode tag causes height change
  packages/components/cascader/src/cascader.vue
  packages/theme-chalk/src/cascader.scss
  packages/theme-chalk/src/common/var.scss
Labels: breaking change, Component::Cascader, Minor Version

#17050 style(components): [button] keep default hover color of link unchanged
  packages/theme-chalk/src/common/var.scss
Labels: breaking change, Minor Version

#18993 chore(components): [time-picker] fix ts error
  packages/components/time-picker/src/common/picker.vue
Labels: CommitMessage::Qualified

#18888 fix(components): [date-picker] resolve v-model type inconsistency
  packages/components/date-picker/src/date-picker.tsx
  packages/components/time-picker/__tests__/time-picker.test.tsx
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/utils.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18999 chore: format code
  docs/en-US/component/icon.md
  docs/en-US/guide/installation.md
  packages/theme-chalk/src/segmented.scss
Labels: CommitMessage::Qualified

#18929 feat(components): [transfer] add custom empty slot for transfer panels
  docs/en-US/component/transfer.md
  docs/examples/transfer/empty-content.vue
  packages/components/transfer/__tests__/transfer.test.tsx
  packages/components/transfer/src/transfer-panel.vue
  packages/components/transfer/src/transfer.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19003 fix(components): [input] the cursor error when click show-password
  packages/components/input/__tests__/input.test.tsx
  packages/components/input/src/input.vue
Labels: CommitMessage::Qualified

#19008 docs: [menu-item] update route attr types
  docs/en-US/component/menu.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19010 fix(components): [select] change states.filtertedOptionsCount to filteredOptionsCount.value
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#19017 chore: update doc
  docs/.vitepress/config/sponsors.ts
  docs/.vitepress/vitepress/components/vp-sponsor-large.vue
  docs/.vitepress/vitepress/components/vp-sponsor-small.vue
  docs/public/images/CRMEB-l.png
  docs/public/images/CRMEB.png
  docs/public/images/MISBoot.png
  docs/public/images/baidayun-logo.png
  docs/public/images/baidayun.png
  docs/public/images/buildadmin-l.png
  docs/public/images/buildadmin.png
  docs/public/images/fantastic-admin-l.png
  docs/public/images/fantastic-admin.png
  docs/public/images/fantasticadmin.png
  docs/public/images/jeeplus.png
  docs/public/images/jeeplus_banner.jpg
  docs/public/images/jnpfsoft.png
  docs/public/images/mele-banner.png
  docs/public/images/mele.png
  docs/public/images/sponsors/jnpfsoft.jpg
  docs/public/images/vform-banner.png
Labels: CommitMessage::Qualified

#19020 fix(components): [table] fixed column style when lazyload title
  packages/components/table/src/table-header/index.ts
Labels: CommitMessage::Qualified

#19024 chore(deps): update gulp-sass use new Sass JS API
  packages/theme-chalk/package.json
  pnpm-lock.yaml
Labels: Sass

#19034 feat(components): [select] add tabindex attribute
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/select.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.ts
  packages/components/select/src/select.vue
Labels: CommitMessage::Qualified

#18670 build(build): [package] remove imports with side effects
  internal/build/src/tasks/modules.ts
  packages/components/package.json
Labels: breaking change, CommitMessage::Qualified, Minor Version

#19018 fix(components): [input-number] Chinese can be displayed in the numeric input box
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19044 chore: [input-number] add comment
  packages/components/input-number/src/input-number.vue
Labels: CommitMessage::Qualified

#19046 fix(components): [time-picker] add passive modifier on touchstart event
  packages/components/time-picker/src/common/picker-range-trigger.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#18951 fix(components): [notification] type declaration error and four types of methods are missing context parameters
  packages/components/notification/__tests__/notify.test.tsx
  packages/components/notification/src/notification.ts
  packages/components/notification/src/notify.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18938 fix(components): [time-picker] click the Cancel button twice to close time picker
  packages/components/time-picker/src/time-picker-com/panel-time-range.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18885 feat(components): [input-tag] new component
  docs/.vitepress/crowdin/en-US/pages/component.json
  docs/en-US/component/input-tag.md
  docs/examples/input-tag/basic.vue
  docs/examples/input-tag/clearable.vue
  docs/examples/input-tag/disabled.vue
  docs/examples/input-tag/draggable.vue
  docs/examples/input-tag/max.vue
  docs/examples/input-tag/prefix-suffix.vue
  docs/examples/input-tag/size.vue
  docs/examples/input-tag/tag.vue
  docs/examples/input-tag/trigger.vue
  packages/components/index.ts
  packages/components/input-tag/__tests__/input-tag.test.tsx
  packages/components/input-tag/index.ts
  packages/components/input-tag/src/composables/index.ts
  packages/components/input-tag/src/composables/use-drag-tag.ts
  packages/components/input-tag/src/composables/use-hovering.ts
  packages/components/input-tag/src/composables/use-input-tag-dom.ts
  packages/components/input-tag/src/composables/use-input-tag.ts
  packages/components/input-tag/src/input-tag.ts
  packages/components/input-tag/src/input-tag.vue
  packages/components/input-tag/src/instance.ts
  packages/components/input-tag/style/css.ts
  packages/components/input-tag/style/index.ts
  packages/element-plus/component.ts
  packages/hooks/__tests__/use-calc-input-width.test.tsx
  packages/hooks/index.ts
  packages/hooks/use-calc-input-width/index.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/form.scss
  packages/theme-chalk/src/index.scss
  packages/theme-chalk/src/input-tag.scss
  typings/global.d.ts
Labels: Project::New Component, CommitMessage::Qualified, Minor Version

#19063 chore: update changelog 2.9.0
  CHANGELOG.en-US.md
Labels: CommitMessage::Qualified
