Repository element-plus/element-plus, pull requests merged in 2024-01, with the labels that each got.

#15233 fix(components): [message] type is not working after customizing icon
  packages/components/message/src/message.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15318 chore(ci): bump maintain-one-comment to 3.1.1
  .github/workflows/pr-docs-deploy.yml
  .github/workflows/pr-docs-start.yml
  .github/workflows/publish-build-product.yml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15309 fix(style): [tour] fixed the closebtn's hover style when type is primary
  packages/components/tour/src/content.vue
  packages/theme-chalk/src/tour.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15351 fix(components): [input] remove useless contants
  packages/components/input/src/input.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15343 style(components): [menu] Collapse mode active color
  packages/theme-chalk/src/menu.scss
Labels: CommitMessage::Qualified

#15376 fix(build): [date-picker] `type` prop error in web-types.json
  internal/build/src/tasks/helper.ts
Labels: CommitMessage::Qualified

#15342 fix(components): [menu] set `teleported`, parent menu popper not closed
  packages/components/menu/src/sub-menu.ts
Labels: CommitMessage::Qualified

#15382 fix(ci): GITHUB_TOKEN is empty in `publish-npm-nightly.yml`
  .github/workflows/publish-npm-nightly.yml
Labels: CommitMessage::Qualified

#15383 perf(components): [menu] popper close any levels in `menu-trigger:hover`
  packages/components/menu/src/sub-menu.ts
Labels: CommitMessage::Qualified

#15388 docs(components): [drawer] fix format error
  docs/en-US/component/drawer.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#14617 fix(components): [tree-select] case-insensitive when filterable
  packages/components/tree-select/src/tree.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15379 fix(build): build web-types.json compatible with windows
  internal/build/src/tasks/helper.ts
Labels: CommitMessage::Qualified

#15315 refactor(components): [tour] replace rect with path
  packages/components/tour/src/mask.vue
Labels: CommitMessage::Qualified

#15389 feat(components): [table] add `filterClassName` props in TableColumn
  packages/components/table/src/filter-panel.vue
  packages/components/table/src/table-column/defaults.ts
  packages/components/table/src/table-column/index.ts
  packages/components/table/src/table-column/watcher-helper.ts
Labels: CommitMessage::Qualified

#15391 docs(components): [table] add `filter-class-name` in Table-column
  docs/en-US/component/table.md
Labels: CommitMessage::Qualified

#15393 fix(components): [loading] complete destroy vLoading directive unmounted
  packages/components/loading/src/directive.ts
Labels: CommitMessage::Qualified

#15401 chore(build): [ElTour & ElTourStep & ElPopover] update global types
  global.d.ts
  typings/components.d.ts
Labels: CommitMessage::Qualified

#15336 fix(components): fixed total column without background color
  packages/theme-chalk/src/table.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15406 fix(components): [image, image-viewer] Add crossorigin property
  docs/en-US/component/image.md
  packages/components/image-viewer/src/image-viewer.ts
  packages/components/image-viewer/src/image-viewer.vue
  packages/components/image/src/image.ts
  packages/components/image/src/image.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15341 fix(components): [input] the cursor is misplaced when type setting number
  packages/theme-chalk/src/input.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15442 Revert "chore: update pnpm to v8.12.0 (#15101)"
  package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#15441 fix(components): [select] remove redundant named slots
  packages/components/select/src/select.vue
Labels: CommitMessage::Qualified

#15449 fix(components): [select] Fix value bind object and trigger twice in form label
  packages/components/select-v2/src/select.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#15450 fix(components): [select] exposes blur invalid
  packages/components/select/src/useSelect.ts
Labels: CommitMessage::Qualified

#15435 fix(ci): Replace jest-coverage-report-action with vitest-coverage-report-action
  .github/workflows/test-coverage.yml
  vitest.config.ts
Labels: CommitMessage::Qualified

#15451 chore: update pnpm to v8.14.1, revert 15442
  package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#15453 D2M
  .github/workflows/test-coverage.yml
  CHANGELOG.en-US.md
  package.json
  packages/components/select-v2/src/select.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  vitest.config.ts
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified

#15466 chore: remove report.json
  vitest.config.ts
Labels: CommitMessage::Qualified

#15469 [doc] unnecessary code
  docs/examples/popover/directive-usage.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15329 docs(components): [select-v2] use new display tag
  docs/en-US/component/select-v2.md
  packages/components/select-v2/src/defaults.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15320 docs(components): [tree] example of modifying custom node class
  docs/examples/tree/custom-node-class.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15478 perf(components): [select & selectV2] hide `collapse-tags-tooltip` when dropdown
  packages/components/select-v2/src/select.vue
  packages/components/select/src/select.vue
Labels: CommitMessage::Qualified

#15462 fix(components): [select select-v2] fix input click event
  packages/components/select-v2/src/select.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
Labels: CommitMessage::Qualified

#15471 docs(components): [image] add type of crossorigin
  docs/en-US/component/image.md
  packages/components/image/src/image.ts
  packages/components/image/src/image.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15496 chore: update readme
  README.md
  docs/.vitepress/config/sponsors.ts
Labels: CommitMessage::Qualified

#15483 fix(components): [image-viewer] Maximum recursive updates exceeded error
  packages/components/image-viewer/src/image-viewer.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15502 fix(docs): popover offset default value error
  docs/en-US/component/popover.md
Labels: CommitMessage::Qualified

#15500 fix(components): [collapse] SSR hydration error caused by random ID
  packages/components/collapse/src/collapse-item.ts
  packages/components/collapse/src/use-collapse-item.ts
  packages/utils/rand.ts
Labels: CommitMessage::Qualified

#15498 fix: fix doc sidebar error z-index
  docs/.vitepress/vitepress/styles/css-vars.scss
  docs/.vitepress/vitepress/styles/sidebar.scss
Labels: CommitMessage::Qualified

#15511 fix(components): [image-viewer] Fix crossorigin
  packages/components/image-viewer/src/image-viewer.ts
  packages/components/image-viewer/src/image-viewer.vue
  packages/components/image/src/image.vue
Labels: CommitMessage::Qualified

#15460 fix(components): [select] style break change in multiple collapseTags
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15470 refactor(components): [table] The overflowTooltip of the table is implemented by the Eltooltip component.
  packages/components/table/src/table-body/events-helper.ts
  packages/components/table/src/util.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15514 fix(components): [input] resolve input attributes issue for textarea
  packages/components/input/src/input.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15519 feat(components): [select-v2] Add header and footer slots
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/examples/select-v2/custom-footer.vue
  docs/examples/select-v2/custom-header.vue
  packages/components/select-v2/src/select-dropdown.tsx
  packages/components/select-v2/src/select.vue
Labels: CommitMessage::Qualified

#15501 fix(components): [select-v2] the select option style is incorrect
  packages/components/select-v2/src/useSelect.ts
Labels: CommitMessage::Qualified

#15377 fix(components): [tree] setCheckedNodes incorrectly checked node
  packages/components/tree/src/model/tree-store.ts
Labels: CommitMessage::Qualified

#15513 feat(components): [checkbox] Checkbox can uncheck exceed max value
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/checkbox/src/composables/use-checkbox-model.ts
Labels: CommitMessage::Qualified

#15551 test(components): [select] adjust case for refactored select
  packages/components/select/__tests__/select.test.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15552 test(components): [select-v2] backspace should not delete disabled tag
  packages/components/select-v2/__tests__/select.test.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15523 fix(components): [autocomplete] SSR hydration error caused by random ID
  packages/components/autocomplete/src/autocomplete.vue
Labels: CommitMessage::Qualified

#15532 fix(components): [dropdown] SSR hydration error caused by random ID
  packages/components/dropdown/src/useDropdown.ts
Labels: CommitMessage::Qualified

#15533 fix(components): [cascader-panel] SSR hydration error caused by ID
  packages/components/cascader-panel/src/menu.vue
Labels: CommitMessage::Qualified

#15544 fix(components): [select] Fix input key event
  packages/components/select-v2/src/select.vue
  packages/components/select/src/select.vue
Labels: CommitMessage::Qualified

#15557 docs(components): [cascader] doc description use setup
  docs/en-US/component/cascader.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15556 refactor(components): [drawer] use setup
  packages/components/drawer/src/drawer.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15572 docs(components): [watermark] add slots doc
  docs/en-US/component/watermark.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15540 feat(components): [select & select-v2] Add loading slot
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  docs/examples/select-v2/custom-loading.vue
  docs/examples/select/custom-loading.vue
  packages/components/select-v2/src/select-dropdown.tsx
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/theme-chalk/src/select-dropdown.scss
Labels: CommitMessage::Qualified

#15539 style(theme-chalk): [select] Fix style when calculate input width
  packages/theme-chalk/src/select.scss
Labels: CommitMessage::Qualified

#15570 docs: update supported version
  docs/en-US/guide/installation.md
Labels: CommitMessage::Qualified

#15578 feat(components): [tour] target prop add more type
  docs/en-US/component/tour.md
  docs/examples/tour/target.vue
  packages/components/tour/src/helper.ts
  packages/components/tour/src/step.ts
  packages/components/tour/src/types.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15560 fix(components): [space] Fix gap style
  packages/components/space/__tests__/space.test.tsx
  packages/components/space/src/use-space.ts
Labels: CommitMessage::Qualified

#15597 Revert "D2M" squash merge
  .github/workflows/test-coverage.yml
  CHANGELOG.en-US.md
  package.json
  packages/components/select-v2/src/select.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  vitest.config.ts
Labels: Needs Review

#15607 fix(components): [select & select-v2] select can't delete input val
  packages/components/select-v2/src/select.vue
  packages/components/select/src/select.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15628 D2M
  CHANGELOG.en-US.md
  packages/components/select-v2/src/select.vue
  packages/components/select/src/select.vue
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#15656 docs(components): [tour] fix slots name error of tour step
  docs/en-US/component/tour.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15643 feat(components): [dialog] Dialog can drag overflow the viewport
  docs/en-US/component/dialog.md
  docs/examples/dialog/align-center.vue
  docs/examples/dialog/basic-usage.vue
  docs/examples/dialog/centered-content.vue
  docs/examples/dialog/customization-content.vue
  docs/examples/dialog/customization-header.vue
  docs/examples/dialog/destroy-on-close.vue
  docs/examples/dialog/draggable-dialog.vue
  docs/examples/dialog/focus-trapping.vue
  docs/examples/dialog/nested-dialog.vue
  packages/components/dialog/src/dialog-content.ts
  packages/components/dialog/src/dialog-content.vue
  packages/components/dialog/src/dialog.vue
  packages/components/drawer/__tests__/drawer.test.ts
  packages/components/drawer/src/drawer.vue
  packages/hooks/use-draggable/index.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/dialog.scss
Labels: CommitMessage::Qualified

#15627 fix(components): [table] The namespace of the showOverflowTooltip is invalid.
  packages/components/table/src/util.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15675 docs: Sort resource
  docs/.vitepress/vitepress/components/globals/resource.vue
Labels: CommitMessage::Qualified

#15683 fix(components): [select] Remote search does not show menu when it has options and no query
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15674 feat(components): [message-box] MessageBox can drag overflow the viewport
  docs/en-US/component/message-box.md
  docs/examples/message-box/alert.vue
  docs/examples/message-box/centered-content.vue
  docs/examples/message-box/confirm.vue
  docs/examples/message-box/customization.vue
  docs/examples/message-box/customized-icon.vue
  docs/examples/message-box/distinguishable-close-cancel.vue
  docs/examples/message-box/draggable.vue
  docs/examples/message-box/prompt.vue
  docs/examples/message-box/use-html.vue
  packages/components/message-box/src/index.vue
  packages/components/message-box/src/message-box.type.ts
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/dialog.scss
  packages/theme-chalk/src/message-box.scss
Labels: CommitMessage::Qualified

#15694 fix(docs): overlay error caused by sidebar
  docs/.vitepress/vitepress/styles/sidebar.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15704 docs(components): [dropdown] make the arrow icon center
  docs/examples/dropdown/how-to-trigger.vue
Labels: CommitMessage::Qualified

#15681 fix(components): [select] Fix value with value-key not selected
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useOption.ts
Labels: CommitMessage::Qualified

#15381 chore(ci): add workflow dispatch to CI actions
  .github/workflows/test-coverage.yml
  .github/workflows/test-ssr.yml
  .github/workflows/test-unit.yml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15672 docs: [time-picker] add value-format attribute
  docs/en-US/component/time-picker.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#15706 style(components): [tour] Improve style and docs
  docs/examples/tour/basic.vue
  docs/examples/tour/indicator.vue
  docs/examples/tour/mask.vue
  docs/examples/tour/non-modal.vue
  docs/examples/tour/target.vue
  packages/components/tour/src/step.vue
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/tour.scss
Labels: CommitMessage::Qualified

#15680 fix(components): [tour] buttonProps & isSameProps errors
  packages/components/tour/__tests__/tour.test.tsx
  packages/components/tour/src/helper.ts
  packages/components/tour/src/step.ts
  packages/components/tour/src/step.vue
  packages/components/tour/src/steps.ts
  packages/components/tour/src/tour.vue
  packages/components/tour/src/types.ts
Labels: CommitMessage::Qualified, Needs Review

#15703 fix(components): [select] el-option-group error when el-option in a component
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/option-group.vue
Labels: CommitMessage::Qualified, Needs Review

#11965 fix(components): [drawer] click allow focus out
  docs/en-US/component/drawer.md
  packages/components/drawer/src/drawer.vue
Labels: CommitMessage::Qualified

#15699 fix(components): [menu] Add menu-item margin when calculating `calcSliceIndex`
  packages/components/menu/src/menu.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#15677 feat(play): custom namespace
  play/app.example.vue
  play/styles/custom.scss
  play/vite.config.ts
Labels: CommitMessage::Qualified
