Repository element-plus/element-plus, pull requests merged in 2025-04, with the labels that each got.

#20264 feat(components): [popover] add trigger-keys prop for keyboard control of popover display
  docs/en-US/component/popover.md
  packages/components/popover/src/popover.ts
  packages/components/popover/src/popover.vue
Labels: Contribution::Community, Needs Review

#20335 docs: resolve code copy button alignment issue
  docs/.vitepress/vitepress/styles/code.scss
Labels: Contribution::Community

#20311 fix(components): [tree] ensure no checked nodes in regular tree
  packages/components/tree/__tests__/tree.test.ts
  packages/components/tree/src/tree-node.vue
Labels: Contribution::Community, Needs Review

#20303 docs: optimize contributors style
  docs/.vitepress/vitepress/components/globals/contributors.vue
Labels: Contribution::Community, Needs Review

#20337 style(components): [date-picker] adjust panel border block & modify css variables
  packages/theme-chalk/src/date-picker/picker-panel.scss
Labels: Contribution::Community, 1st contribution, Needs Review

#20334 fix(components): [message] fix consecutive closeAll method calls
  packages/components/message/src/message.vue
  packages/components/message/src/method.ts
Labels: Contribution::Community, Needs Review

#20348 fix(components): [watermark] content not fully displayed
  packages/components/watermark/src/watermark.vue
Labels: Contribution::Community, Needs Review

#20338 fix(theme-chalk): [description] remove useless font-weight declaration
  packages/theme-chalk/src/descriptions.scss
Labels: Contribution::Community, Needs Review

#20347 fix(components): [message-box] `message` overflow `container`
  packages/theme-chalk/src/message-box.scss
Labels: Contribution::Community, Needs Review

#20355 refactor(components): [message] use message type constants
  packages/components/message/__tests__/message-manager.test.tsx
  packages/components/message/__tests__/message.test.ts
  packages/components/message/src/message.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#20366 fix(locale): el-upload and el-message-box Unified Chinese prompts
  packages/locale/lang/zh-cn.ts
  packages/locale/lang/zh-mo.ts
  packages/locale/lang/zh-tw.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#20370 feat(components): [select-v2] add `suffix-icon` prop with default ArrowDown
  docs/en-US/component/select-v2.md
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#20322 fix(components): [table] prevent child node selection loss during table data modification
  packages/components/table/__tests__/table-column.test.ts
  packages/components/table/src/store/watcher.ts
  packages/components/table/src/util.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#20296 refactor(components): [message] deprecate the center option
  docs/en-US/component/message.md
  docs/examples/message/centered-content.vue
  packages/components/message/src/message.ts
  packages/components/message/src/message.vue
  packages/theme-chalk/src/message.scss
Labels: Contribution::Community, Needs Review

#20384 fix(components): [tabs] ensure correct event order
  packages/components/tabs/__tests__/tabs.test.tsx
  packages/components/tabs/src/tabs.tsx
Labels: Contribution::Community, Needs Review

#20408 feat(components): [card] add `header-class` and `footer-class` for slots
  docs/en-US/component/card.md
  packages/components/card/__tests__/card.test.tsx
  packages/components/card/src/card.ts
  packages/components/card/src/card.vue
Labels: Contribution::Community, Needs Review

#20402 feat(components): [notification] add `closeIcon` option with default Close
  docs/en-US/component/notification.md
  packages/components/notification/src/notification.ts
  packages/components/notification/src/notification.vue
Labels: Contribution::Community, Needs Review

#20409 chore: run prettier on commit
  docs/en-US/component/segmented.md
  package.json
  pnpm-lock.yaml
Labels: Contribution::Community, Needs Review

#20430 feat(components): [menu] expose updateActiveIndex
  docs/en-US/component/menu.md
  packages/components/menu/src/menu.ts
Labels: Contribution::Community, Needs Review

#19464 fix(component): resolve 'cursor' style loss caused by 'pointer-events: none'
  packages/components/color-picker/src/color-picker.vue
  packages/components/mention/src/mention.vue
  packages/components/time-picker/src/common/picker-range-trigger.vue
  packages/components/time-picker/src/common/props.ts
  packages/hooks/use-focus-controller/index.ts
  packages/theme-chalk/src/color-picker.scss
  packages/theme-chalk/src/date-picker/picker.scss
  packages/theme-chalk/src/input-tag.scss
  packages/theme-chalk/src/input.scss
  packages/theme-chalk/src/mention.scss
  packages/theme-chalk/src/select.scss
Labels: Contribution::Community, Component::Select, CommitMessage::Unqualified, CommitMessage::Qualified, Needs Review

#20306 fix(components): [el-select-v2] u-tag sync with :model-value
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, Needs Review

#20438 docs: attach nprogress on router event
  docs/.vitepress/theme/index.ts
  docs/.vitepress/vitepress/components/vp-app.vue
  docs/.vitepress/vitepress/components/vp-content.vue
Labels: Contribution::Community, Needs Review

#20472 feat(components): [autocomplete] enable append-to prop
  docs/en-US/component/autocomplete.md
  packages/components/autocomplete/src/autocomplete.ts
  packages/components/autocomplete/src/autocomplete.vue
Labels: Contribution::Community, Needs Review

#20504 docs: [tour] supplementary missing attributes
  docs/en-US/component/tour.md
Labels: Contribution::Community, Needs Review

#20513 test(components): [message] add one test case for #20333
  packages/components/message/__tests__/message-manager.test.tsx
Labels: Contribution::Community, Needs Review

#20480 feat(components): [link] add control for when underlines should appear
  docs/en-US/component/link.md
  docs/examples/link/basic.vue
  docs/examples/link/disabled.vue
  docs/examples/link/underline.vue
  packages/components/link/__tests__/link.test.tsx
  packages/components/link/src/link.ts
  packages/components/link/src/link.vue
  packages/theme-chalk/src/link.scss
Labels: Contribution::Community, Needs Review

#20501 refactor(components): unify `append-to` prop type across multiple components
  docs/en-US/component/dialog.md
  docs/en-US/component/drawer.md
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  packages/components/dialog/src/dialog.ts
  packages/components/select-v2/src/defaults.ts
  packages/components/select/src/select.ts
  packages/components/table/src/filter-panel.vue
  packages/components/tooltip/src/content.ts
  packages/components/tour/src/tour.ts
Labels: Contribution::Community, Needs Review

#17065 fix(components): [table-v2] loss of precision causes `endReached` to fail to trigger
  packages/components/table-v2/src/use-table.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#20496 fix(components): [tree] enable ellipsis on label
  packages/components/tree-v2/src/tree-node-content.ts
  packages/components/tree-v2/style/css.ts
  packages/components/tree-v2/style/index.ts
  packages/components/tree/src/tree-node-content.vue
  packages/components/tree/style/css.ts
  packages/components/tree/style/index.ts
Labels: Contribution::Community, Needs Review

#20516 docs: update `append-to` prop type
  docs/en-US/component/message-box.md
  docs/en-US/component/message.md
  docs/en-US/component/notification.md
Labels: Contribution::Community, Needs Review

#20537 refactor(components): use built-in methods to check for undefined and null
  packages/components/menu/src/menu.ts
  packages/components/menu/src/sub-menu.ts
  packages/components/select-v2/src/useSelect.ts
  packages/components/tree/src/model/node.ts
  packages/components/tree/src/model/tree-store.ts
Labels: Contribution::Community, Needs Review

#20495 fix(components): [tooltip] remove some references in time
  packages/components/popper/src/composables/use-content.ts
  packages/components/tooltip/src/content.vue
Labels: Memory Leak

#20526 test(components): [notification] add cases for closeIcon prop
  docs/en-US/component/notification.md
  packages/components/notification/__tests__/notification.test.tsx
Labels: Contribution::Community, Needs Review

#20551 refactor(components): [message] remove inferable return types
  packages/components/message/src/message.vue
Labels: Contribution::Community, Needs Review

#20532 feat(components): [input-tag] add delimiter
  docs/en-US/component/input-tag.md
  docs/examples/input-tag/delimiter.vue
  packages/components/input-tag/__tests__/input-tag.test.tsx
  packages/components/input-tag/src/composables/use-input-tag.ts
  packages/components/input-tag/src/input-tag.ts
Labels: Contribution::Community, Needs Review

#20556 fix(locale): update french translation for confirm
  packages/locale/lang/fr.ts
Labels: Contribution::Community, Needs Review

#20549 fix(components): [mention] the input event is not be triggered when selecting a mention
  packages/components/mention/src/mention.ts
  packages/components/mention/src/mention.vue
Labels: Contribution::Community, Needs Review

#20267 fix(components): [tree] filter update scheduling error
  packages/components/tree/__tests__/tree.test.ts
  packages/components/tree/src/model/tree-store.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#20590 fix(components): [image] make `show-progress` prop available
  packages/components/image/__tests__/image.test.tsx
  packages/components/image/src/image.vue
Labels: Contribution::Community, Needs Review

#20552 feat(components): [tabs] expose `tabNavRef` and `tabListRef`
  docs/en-US/component/tabs.md
  packages/components/tabs/src/tab-nav.tsx
  packages/components/tabs/src/tabs.tsx
Labels: Contribution::Community, 1st contribution, Needs Review

#20602 docs(components): [collapse, collapse-item] update exposes
  docs/en-US/component/collapse.md
Labels: Contribution::Community, Needs Review
