Repository element-plus/element-plus, pull requests merged in 2025-01, with the labels that each got.

#19455 fix(components): [page-header] use `$slots` instead of `useSlots`
  packages/components/page-header/__tests__/page-header.test.tsx
  packages/components/page-header/src/page-header.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19292 fix(components): [select] input width fills the remaining width
  packages/components/select-v2/src/select.types.ts
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
  packages/theme-chalk/src/select.scss
Labels: CommitMessage::Qualified

#19379 feat(components): [select, select-v2] add loading class to validateIcon
  packages/components/select-v2/src/select.vue
  packages/components/select/src/select.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19451 perf(components): [table] prioritize use rowKey to determine whether it is selected
  docs/examples/table/multi-select.vue
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/store/watcher.ts
Labels: CommitMessage::Qualified

#19495 chore: format dropdown docs
  docs/en-US/component/dropdown.md
Labels: CommitMessage::Qualified

#19162 fix(components): [description] `labelWidth` is invalid when no border
  packages/components/descriptions/__tests__/descriptions.test.tsx
  packages/components/descriptions/src/descriptions-cell.ts
Labels: CommitMessage::Qualified

#19099 feat(components): [dialog/drawer] add custom sub classes
  docs/en-US/component/dialog.md
  docs/en-US/component/drawer.md
  packages/components/dialog/__tests__/dialog.test.tsx
  packages/components/dialog/src/dialog-content.ts
  packages/components/dialog/src/dialog-content.vue
  packages/components/dialog/src/dialog.ts
  packages/components/dialog/src/dialog.vue
  packages/components/drawer/__tests__/drawer.test.ts
  packages/components/drawer/src/drawer.vue
Labels: Contribution::Community, Component::Dialog, Component::Drawer, CommitMessage::Qualified, Needs Review

#19500 chore: upgrade puppeteer to 23.11.1
  package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified

#19521 ci: update test-ssr.yml
  .github/workflows/test-ssr.yml
Labels: CommitMessage::Qualified

#19129 fix(components): [form] on post rules update reset field
  packages/components/form/__tests__/form.test.tsx
  packages/components/form/src/form.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19483 feat(i18n): add Hindi language
  packages/locale/lang/hi.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19539 docs: [collapse] change event parameter type error
  docs/examples/collapse/basic.vue
  docs/examples/collapse/custom-icon.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19534 fix(components): [select] make sure the e-tag is not obstructed(#19529)
  packages/theme-chalk/src/select.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19543 test pr.new commit ci
  .github/workflows/publish-pr-commit-pkg.yml
Labels: CommitMessage::Qualified

#19544 ci: run pkg.new when push
  .github/workflows/publish-pr-commit-pkg.yml
Labels: CommitMessage::Qualified

#19536 docs: [button] add description
  docs/en-US/component/button.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19545 ci: stop run pkg.new when push
  .github/workflows/publish-pr-commit-pkg.yml
Labels: CommitMessage::Qualified

#19551 improvement(components): [text] keep the inherited title attribute
  packages/components/text/src/text.vue
Labels: CommitMessage::Qualified

#19471 fix(components): [dialog] fix scroll bar not resetting to top on reopen
  packages/components/dialog/src/use-dialog.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19556 test: [table] add show-overflow-tooltip trigger
  packages/components/table/__tests__/table.test.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19523 feat(i18n): add Norsk(no) language
  packages/locale/lang/no.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19586 chore: update doc ui
  docs/.vitepress/vitepress/components/vp-sponsors.vue
Labels: CommitMessage::Qualified

#19583 style(components): [dialog] no rounded when in fullscreen
  packages/theme-chalk/src/dialog.scss
Labels: CommitMessage::Qualified

#19253 feat(component): [time-select] add include end time attribute
  docs/en-US/component/time-select.md
  packages/components/time-select/__tests__/time-select.test.tsx
  packages/components/time-select/src/time-select.ts
  packages/components/time-select/src/time-select.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19610 Revert "ci: update test-ssr.yml"
  .github/workflows/test-ssr.yml
  package.json
  pnpm-lock.yaml
Labels: CommitMessage::Qualified, Needs Review

#19609 D2M
  CHANGELOG.en-US.md
  docs/.vitepress/vitepress/components/vp-sponsors.vue
  docs/en-US/component/button.md
  docs/en-US/component/dialog.md
  docs/en-US/component/drawer.md
  docs/en-US/component/dropdown.md
  docs/en-US/component/time-select.md
  docs/examples/collapse/basic.vue
  docs/examples/collapse/custom-icon.vue
  packages/components/descriptions/__tests__/descriptions.test.tsx
  packages/components/descriptions/src/descriptions-cell.ts
  packages/components/dialog/__tests__/dialog.test.tsx
  packages/components/dialog/src/dialog-content.ts
  packages/components/dialog/src/dialog-content.vue
  packages/components/dialog/src/dialog.ts
  packages/components/dialog/src/dialog.vue
  packages/components/dialog/src/use-dialog.ts
  packages/components/drawer/__tests__/drawer.test.ts
  packages/components/drawer/src/drawer.vue
  packages/components/form/__tests__/form.test.tsx
  packages/components/form/src/form.vue
  packages/components/table/__tests__/table.test.ts
  packages/components/tabs/__tests__/tabs.test.tsx
  packages/components/tabs/src/tabs.tsx
  packages/components/text/src/text.vue
  packages/components/time-select/__tests__/time-select.test.tsx
  packages/components/time-select/src/time-select.ts
  packages/components/time-select/src/time-select.vue
  packages/hooks/__tests__/use-lockscreen.test.tsx
  packages/hooks/use-lockscreen/index.ts
  packages/locale/lang/hi.ts
  packages/locale/lang/no.ts
  packages/theme-chalk/src/dialog.scss
  packages/theme-chalk/src/select.scss
  pnpm-lock.yaml
Labels: 🚀 Ready for takeoff, CommitMessage::Qualified, Needs Review

#19487 chore: [time-picker] correct typo in `timePickerRangeTriggerProps`
  packages/components/time-picker/src/common/picker-range-trigger.vue
  packages/components/time-picker/src/common/props.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19612 chore(docs): implement dynamic links for playground based on preview state
  docs/.vitepress/vitepress/components/full-screen/vp-menu-link.vue
  docs/.vitepress/vitepress/components/navbar/vp-menu-link.vue
  docs/.vitepress/vitepress/components/navbar/vp-social-link.vue
  docs/.vitepress/vitepress/composables/use-playground.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19593 docs: [calendar] add exposes
  docs/en-US/component/calendar.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19466 feat(components): [image-viewer] add showPreview method
  docs/en-US/component/image.md
  docs/examples/image/manually-preview.vue
  packages/components/image/__tests__/image.test.tsx
  packages/components/image/src/image.ts
  packages/components/image/src/image.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19615 chore: enable fileNesting config
  .vscode/settings.json
Labels: CommitMessage::Qualified

#19608 feat(locale): add language Chinese Hongkong and Chinese Macau
  packages/locale/lang/zh-hk.ts
  packages/locale/lang/zh-mo.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19589 feat(components): [select] add popup-scroll event
  docs/en-US/component/select.md
  packages/components/select/src/select.vue
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19650 docs: add lang records
  docs/en-US/guide/i18n.md
Labels: Project::Documentation, i18n

#19255 chore: [tree] remove unused arg
  packages/components/tree/src/tree-node.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19624 feat(i18n): add Telugu language
  docs/en-US/guide/i18n.md
  packages/locale/lang/te.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19465 feat(components): [image-viewer] add `progress` slot and `show-progress` props
  docs/en-US/component/image.md
  docs/examples/image/image-preview.vue
  packages/components/image-viewer/__tests__/image-viewer.test.tsx
  packages/components/image-viewer/src/image-viewer.ts
  packages/components/image-viewer/src/image-viewer.vue
  packages/components/image/src/image.ts
  packages/components/image/src/image.vue
  packages/theme-chalk/src/image-viewer.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19064 fix(components): [table-footer] update cols width on layout change
  packages/components/table/src/table-footer/index.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19668 fix(ci): types & dark theme sync with pr
  .github/workflows/pr-docs-build.yml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19671 fix(ci): move all bundle to docs dist
  .github/workflows/pr-docs-build.yml
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19670 docs: format table-v2 & use actions/upload-artifact v4
  .github/workflows/lint-commit-message.yml
  .github/workflows/pr-docs-build.yml
  docs/en-US/component/table-v2.md
Labels: CommitMessage::Qualified

#19497 feat(components): [image-viewer] add toolbar slot
  docs/en-US/component/image.md
  docs/examples/image/custom-toolbar.vue
  packages/components/image-viewer/src/image-viewer.vue
  packages/components/image/src/image.vue
  packages/theme-chalk/src/image-viewer.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19654 docs: [menu] `left-and-right` example style tag add scoped
  docs/examples/menu/left-and-right.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19681 docs: [tree-v2] fix style error and remove annotation
  docs/en-US/component/tree-v2.md
  docs/examples/tree-v2/filter.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19631 feat(components): [cascader] add `prefix` slot
  docs/en-US/component/cascader.md
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/src/cascader.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19618 fix(components): [table] `selection-change` event emit incorrectly
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/util.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19688 docs: [timeline] fix type error
  docs/examples/timeline/custom-node.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19694 docs: [dropdown] add `button-props` prop
  docs/en-US/component/dropdown.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19690 docs: [tabs] fix type error
  docs/examples/tabs/customized-trigger.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19704 docs: [switch] fix type error
  docs/examples/switch/prevent-switching.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19587 fix(components): [table] The index parameter of the selectable function is undefined
  packages/components/table/__tests__/table-column.test.ts
  packages/components/table/src/store/watcher.ts
  packages/components/table/src/util.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19669 docs: [layout] add a tip for layout column
  docs/en-US/component/layout.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19713 docs: [checkbox] fix intermediate example type error
  docs/examples/checkbox/intermediate.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19712 docs: [input-number] fix type error
  docs/examples/input-number/basic.vue
  docs/examples/input-number/controlled.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19733 docs: fix Exposes error
  docs/en-US/component/image.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19724 docs: search input default focus
  docs/.vitepress/vitepress/components/globals/overview.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19541 fix(components): [input] refused to apply inline style because it violates csp
  packages/components/input/src/utils.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19687 docs: [tooltip] fix type error
  docs/examples/tooltip/virtual-trigger.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19104 fix(components): [table-v2] make the fixed columns scroll like mainTable
  packages/components/table-v2/src/table-v2.tsx
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19100 fix(components): [cascader-panel] lazy return children can't get value
  packages/components/cascader-panel/__tests__/cascader-panel.test.tsx
  packages/components/cascader-panel/src/store.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19703 fix(components): [table] fix the logic of `selection` column when `fixed` state changes dynamically
  packages/components/table/__tests__/table-column.test.ts
  packages/components/table/src/store/watcher.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#18728 fix(components): [table] the toggleTreeExpansion failed to trigger load function
  packages/components/table/src/store/tree.ts
Labels: PR::Lack Of Tests, Contribution::Community, CommitMessage::Qualified, Needs Review

#19758 chore: format `dropdown.md`
  docs/en-US/component/dropdown.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19762 feat(locale): export zhHk/zhMo
  packages/locale/index.ts
Labels: CommitMessage::Qualified
