Repository element-plus/element-plus, pull requests merged in 2025-09, with the labels that each got.

#21976 docs(components): [select] demo for adjusting the options property
  docs/examples/select/options.vue
Labels: Contribution::Community, Needs Review

#21991 fix(components): [popover] empty node execution error
  packages/components/popper/src/composables/use-content.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#21996 perf(components): [form] optimize search for obj with certain attribute
  packages/components/form/src/form-item.vue
Labels: Contribution::Community, Needs Review

#21981 feat(components): [popConfirm] add `close-on-press-escape` prop
  docs/en-US/component/popconfirm.md
  packages/components/popconfirm/__tests__/popconfirm.test.tsx
  packages/components/popconfirm/src/popconfirm.ts
  packages/components/popconfirm/src/popconfirm.vue
Labels: Contribution::Community, Needs Review

#22001 refactor(components): [splitter] disabled class and style
  packages/components/splitter/src/split-bar.vue
  packages/theme-chalk/src/splitter.scss
Labels: Contribution::Community, Needs Review

#22027 feat(components): [loading] export `LoadingInstance`
  packages/components/loading/index.ts
Labels: Contribution::Community, Needs Review

#21543 feat(components): [radio-group] support options prop rendering
  docs/en-US/component/radio.md
  docs/examples/radio/options.vue
  packages/components/radio/__tests__/radio.test.tsx
  packages/components/radio/src/radio-group.ts
  packages/components/radio/src/radio-group.vue
Labels: Contribution::Community, Needs Review

#21746 fix(components): [time-picker] range type add id automatically
  packages/components/time-picker/src/common/picker-range-trigger.vue
Labels: Contribution::Community, Needs Review

#21828 chore(components): [cascader-panel] remove duplicate exports
  packages/components/cascader-panel/__tests__/cascader-panel.test.tsx
  packages/components/cascader-panel/src/config.ts
  packages/components/cascader-panel/src/index.vue
  packages/components/cascader-panel/src/menu.vue
  packages/components/cascader-panel/src/node.ts
  packages/components/cascader-panel/src/node.vue
  packages/components/cascader-panel/src/store.ts
  packages/components/cascader-panel/src/types.ts
  packages/components/cascader-panel/src/utils.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#22020 refactor(components): [menu] optimize condition judgment
  packages/components/menu/src/sub-menu.ts
Labels: Contribution::Community, Needs Review

#22048 docs(components): [radio] add missing default value
  docs/en-US/component/radio.md
Labels: Contribution::Community, Needs Review

#22038 feat(components): [input-tag] add drag-tag event
  docs/en-US/component/input-tag.md
  packages/components/input-tag/__tests__/input-tag.test.tsx
  packages/components/input-tag/src/composables/use-input-tag.ts
  packages/components/input-tag/src/input-tag.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#22022 fix(components): [table] fix table display error in stripe mode
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/table-body/render-helper.ts
  packages/components/table/src/table-body/styles-helper.ts
Labels: Contribution::Community, Needs Review

#22028 fix(components): [alert] show immediately when `showAfter` not needed
  packages/components/alert/__tests__/alert.test.tsx
  packages/components/alert/src/alert.ts
  packages/components/alert/src/alert.vue
Labels: Contribution::Community, Needs Review

#22075 docs: update some components `exposes title`
  docs/en-US/component/anchor.md
  docs/en-US/component/statistic.md
  docs/en-US/component/table-v2.md
  docs/en-US/component/tree-v2.md
  docs/en-US/component/tree.md
Labels: CommitMessage::Unqualified

#22095 docs(components): update API TOC and fix typo
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/dropdown.md
  docs/en-US/component/table-v2.md
  docs/en-US/component/tour.md
Labels: Contribution::Community, Needs Review

#21980 feat(components): [mention] support props prop
  docs/en-US/component/input-tag.md
  docs/en-US/component/mention.md
  packages/components/mention/__tests__/mention.test.tsx
  packages/components/mention/src/helper.ts
  packages/components/mention/src/mention.ts
  packages/components/mention/src/mention.vue
  packages/components/mention/src/types.ts
Labels: Contribution::Community, Needs Review

#21717 fix(components): [tree] correctly determine the drop type of tree node
  packages/components/tree/src/model/useDragNode.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#20123 feat(components): [select, select-v2] avoid unnecessary model updates when value unchanged
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/useSelect.ts
  packages/components/tree-select/__tests__/tree-select.test.tsx
Labels: Contribution::Community, Needs Review

#22145 fix(components): [tour] make path responsive to window size
  packages/components/tour/src/mask.vue
Labels: Contribution::Community, Needs Review

#22060 fix(components): [rate] ensure the logic of mouseleave work
  packages/components/rate/__tests__/rate.test.tsx
  packages/components/rate/src/rate.vue
Labels: Contribution::Community, Needs Review

#21245 fix(components): [autocomplete] avoid option selection by enter in IME
  packages/components/autocomplete/src/autocomplete.vue
Labels: Contribution::Community, Needs Review

#22141 style(theme-chalk): fix el-step padding-right in vertical layout
  packages/theme-chalk/src/step.scss
Labels: Contribution::Community, 1st contribution, Needs Review

#22059 fix(components): [date-picker-panel] sync clear value with `valueOnClear`
  packages/components/date-picker-panel/src/date-picker-com/panel-date-range.vue
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/time-picker/src/common/picker.vue
  packages/hooks/use-empty-values/index.ts
Labels: Contribution::Community, Needs Review

#22187 fix(components): [tabs] give priority to the `closable` prop of tab-pane
  packages/components/tabs/__tests__/tabs.test.tsx
  packages/components/tabs/src/tab-nav.tsx
  packages/components/tabs/src/tab-pane.ts
  packages/components/tabs/src/tab-pane.vue
Labels: Contribution::Community, Needs Review

#22226 refactor(components): unify BEM & CSS vars via helpers
  packages/components/date-picker-panel/src/date-picker-com/panel-date-pick.vue
  packages/components/splitter/src/splitter.vue
  packages/components/table-v2/src/table-v2.tsx
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, Needs Review

#22261 docs(components): [select/select-v2] improve the description of popper
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
Labels: Contribution::Community, Needs Review

#22265 docs(components): [loading] supplement the type of text
  docs/en-US/component/loading.md
Labels: Contribution::Community, Needs Review

#22264 fix(components): [loading] allow `setText` to accept VNode type
  packages/components/loading/__tests__/loading.test.tsx
  packages/components/loading/src/loading.ts
Labels: Contribution::Community, Needs Review

#19830 improvement(components): trigger `enter` open tooltip
  packages/components/autocomplete/__tests__/autocomplete.test.tsx
  packages/components/autocomplete/src/autocomplete.vue
  packages/components/mention/src/mention.vue
  packages/components/time-picker/__tests__/time-picker.test.tsx
  packages/components/time-picker/src/common/picker.vue
Labels: CommitMessage::Qualified

#22206 fix(components): [cascader] resolve `visibleChange` not triggered on Popper hide
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/src/cascader.vue
Labels: Contribution::Community, Needs Review

#22279 docs(components): [tree/tree-v2] explicitly specify the slot name
  docs/en-US/component/tree-v2.md
  docs/en-US/component/tree.md
Labels: Contribution::Community, Needs Review

#22306 chore(components): [tour] fix typo
  packages/components/tour/src/helper.ts
Labels: Contribution::Community, Needs Review

#22295 chore(components): [upload] remove redundant rawFile parameter from TS
  packages/components/upload/src/upload-content.ts
Labels: Contribution::Community, Needs Review

#22313 chore(components): [check-tag] remove redundant computed
  packages/components/check-tag/src/check-tag.vue
Labels: Contribution::Community, Needs Review

#22314 docs(components): [popover/popconfirm] add inherited Tooltip attributes
  docs/en-US/component/popconfirm.md
  docs/en-US/component/popover.md
Labels: Contribution::Community, Needs Review

#22330 refactor(components): replace props.options with options
  packages/components/checkbox/src/checkbox-group.vue
  packages/components/radio/src/radio-group.vue
Labels: Contribution::Community, Needs Review

#22347 refactor(components): [switch] use shallowRef and remove redundant usage
  packages/components/switch/src/switch.vue
Labels: Contribution::Community, Needs Review

#22365 chore: Remove un used deps
  docs/package.json
  package.json
  packages/element-plus/package.json
  pnpm-lock.yaml
Labels: Contribution::Community, Needs Review

#22278 feat(components): [mention/menu/dropdown/pagination] add popper-style
  docs/en-US/component/color-picker.md
  docs/en-US/component/dropdown.md
  docs/en-US/component/mention.md
  docs/en-US/component/menu.md
  docs/en-US/component/pagination.md
  packages/components/dropdown/src/dropdown.ts
  packages/components/dropdown/src/dropdown.vue
  packages/components/mention/src/mention.ts
  packages/components/mention/src/mention.vue
  packages/components/menu/src/menu.ts
  packages/components/menu/src/sub-menu.ts
  packages/components/pagination/src/components/sizes.ts
  packages/components/pagination/src/components/sizes.vue
  packages/components/pagination/src/pagination.ts
Labels: Contribution::Community, Needs Review

#21947 fix(components): [tree] correct drop indicator with tree scroll offset
  packages/components/tree/src/model/useDragNode.ts
Labels: Contribution::Community, 1st contribution, Needs Review
