Repository element-plus/element-plus, pull requests merged in 2025-06, with the labels that each got.

#20608 fix(components): [form-item] cannot be set to div tag for rendering
  packages/components/form/__tests__/form-item.test.tsx
  packages/components/form/src/form-item.vue
Labels: Contribution::Community, Needs Review

#20847 refactor(components): [color-picker] Use tinycolor to calculate color
  packages/components/color-picker/__tests__/color-picker.test.tsx
  packages/components/color-picker/src/color-picker.vue
  packages/components/color-picker/src/components/predefine.vue
  packages/components/color-picker/src/utils/color.ts
Labels: Minor Version

#20050 refactor: [select, select-v2]: unified name & supplement type
  packages/components/select-v2/src/defaults.ts
  packages/components/select-v2/src/option-item.vue
  packages/components/select-v2/src/select.vue
  packages/components/select-v2/src/token.ts
  packages/components/select-v2/src/useAllowCreate.ts
  packages/components/select-v2/src/useOption.ts
  packages/components/select-v2/src/useProps.ts
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/select.ts
  packages/components/select/src/select.vue
  packages/components/select/src/type.ts
  packages/components/select/src/useSelect.ts
  packages/components/tree-select/src/tree-select.vue
Labels: breaking change, Minor Version

#19007 fix(types): [menu-item] make `index` attribute required
  docs/en-US/component/menu.md
  packages/components/menu/src/menu-item.ts
  packages/components/menu/src/menu-item.vue
Labels: Contribution::Community, breaking change, CommitMessage::Qualified, Needs Review, Minor Version

#19594 fix(theme-chalk): [radio] update background color for checked state
  packages/theme-chalk/src/radio.scss
Labels: breaking change, Needs Review, Component::Radio

#20616 refactor(components): standardize injection keys
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/src/composables/use-panel-date-range.ts
  packages/components/date-picker/src/constants.ts
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  packages/components/date-picker/src/date-picker-com/panel-month-range.vue
  packages/components/date-picker/src/date-picker-com/panel-year-range.vue
  packages/components/date-picker/src/date-picker.tsx
  packages/components/dropdown/src/dropdown.vue
  packages/components/dropdown/src/tokens.ts
  packages/components/dropdown/src/useDropdown.ts
  packages/components/menu/index.ts
  packages/components/menu/src/menu-item.vue
  packages/components/menu/src/menu.ts
  packages/components/menu/src/sub-menu.ts
  packages/components/menu/src/tokens.ts
  packages/components/steps/index.ts
  packages/components/steps/src/item.vue
  packages/components/steps/src/steps.vue
  packages/components/steps/src/tokens.ts
  packages/components/table-v2/src/components/header.tsx
  packages/components/table-v2/src/table-grid.tsx
  packages/components/table-v2/src/tokens.ts
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/constants.ts
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
  packages/components/time-picker/src/time-picker-com/panel-time-pick.vue
  packages/components/time-picker/src/time-picker-com/panel-time-range.vue
  packages/components/time-picker/src/time-picker.tsx
  packages/components/timeline/index.ts
  packages/components/timeline/src/timeline.ts
  packages/components/timeline/src/tokens.ts
  packages/components/tree/index.ts
  packages/components/tree/src/model/useNodeExpandEventBroadcast.ts
  packages/components/tree/src/tokens.ts
  packages/components/tree/src/tree-node-content.vue
  packages/components/tree/src/tree-node.vue
  packages/components/tree/src/tree.vue
Labels: Contribution::Community, Needs Review

#16928 refactor(components): [tooltip-v2] remove `ts-nocheck` comments
  packages/components/tooltip-v2/src/content.vue
  packages/components/tooltip-v2/src/tooltip.ts
  packages/components/tooltip-v2/src/tooltip.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#20529 fix(components): [collapse] resolve space key conflict and improve accessibility
  packages/components/collapse/__tests__/collapse.test.tsx
  packages/components/collapse/src/collapse-item.vue
  packages/components/collapse/src/use-collapse-item.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#19345 fix(components): [form] the validate function is executed repeatedly
  packages/components/form/__tests__/form.test.tsx
  packages/components/form/src/form.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#20946 docs: update alert component version references to 2.10.0
  docs/en-US/component/alert.md
Labels: Contribution::Community, Needs Review

#20949 D2M
  CHANGELOG.en-US.md
  docs/en-US/component/alert.md
  packages/components/form/__tests__/form.test.tsx
  packages/components/form/src/form.vue
  packages/components/splitter-panel/style/css.ts
Labels: 🚀 Ready for takeoff

#19011 fix(theme-chalk): [drawer] replace fixed color with CSS var
  packages/theme-chalk/src/drawer.scss
Labels: CommitMessage::Qualified

#20997 docs(components): [radio] fix text-color and fill attr ownership
  docs/en-US/component/radio.md
Labels: Contribution::Community, 1st contribution, Needs Review

#20981 feat(components): [form] export getField
  docs/en-US/component/form.md
  packages/components/form/__tests__/form.test.tsx
  packages/components/form/src/form-item.vue
  packages/components/form/src/form.vue
  packages/components/form/src/types.ts
  packages/components/form/src/utils.ts
Labels: Contribution::Community, Needs Review

#21029 docs(components): [date-time-picker] add `disabled-hours` `disabled-minutes` `disabled-seconds` info
  docs/en-US/component/datetime-picker.md
Labels: Contribution::Community, Needs Review

#21034 chore: update node version requirement to 20
  .nvmrc
  README.md
Labels: Contribution::Community, Needs Review

#15600 fix(components): [tabs] fix nav height for better display
  packages/components/tabs/src/tab-nav.tsx
  packages/theme-chalk/src/tabs.scss
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#21049 fix(components): [date-picker] pass showWeekNumber to panel
  docs/en-US/component/date-picker.md
  docs/en-US/component/datetime-picker.md
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/__tests__/date-time-picker.test.tsx
  packages/components/date-picker/src/composables/use-basic-date-table.ts
  packages/components/date-picker/src/date-picker-com/basic-date-table.vue
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  packages/components/date-picker/src/props/shared.ts
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/common/props.ts
  packages/theme-chalk/src/date-picker/date-table.scss
Labels: Contribution::Community, 1st contribution, Needs Review

#20995 fix(components): [table] fix children can't be unchecked
  packages/components/table/__tests__/table-column.test.ts
  packages/components/table/src/store/expand.ts
  packages/components/table/src/store/watcher.ts
  packages/components/table/src/util.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#21069 fix(locale): update Khmer (km) locale translations
  packages/locale/lang/km.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#14997 feat(components): [input] native inputmode prop for el-input & el-input-number
  docs/en-US/component/input-number.md
  docs/en-US/component/input.md
  packages/components/input-number/src/input-number.ts
  packages/components/input-number/src/input-number.vue
  packages/components/input/src/input.ts
  packages/components/input/src/input.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#21092 perf(components): [table] remove redundant `updateSelectionByRowKey`
  packages/components/table/src/store/index.ts
  packages/components/table/src/store/watcher.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#20014 refactor(components): [cascader-panel] remove `@ts-nocheck` and optimize code
  docs/en-US/component/cascader.md
  packages/components/cascader-panel/src/config.ts
  packages/components/cascader-panel/src/index.vue
  packages/components/cascader-panel/src/instance.ts
  packages/components/cascader-panel/src/menu.vue
  packages/components/cascader-panel/src/node-content.ts
  packages/components/cascader-panel/src/node-content.tsx
  packages/components/cascader-panel/src/node.ts
  packages/components/cascader-panel/src/node.vue
  packages/components/cascader-panel/src/types.ts
  packages/components/cascader/src/cascader.ts
Labels: Contribution::Community, Needs Review

#20880 fix(components): [color-picker] Improve modelValue prop type
  packages/components/color-picker/src/color-picker.ts
  packages/components/color-picker/src/utils/color.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#21129 fix(components): [menu] expose updateActiveIndex type
  packages/components/menu/src/instance.ts
Labels: Contribution::Community, Needs Review

#20210 fix(components): [table] fix the issue where the expand-row-keys property does not support the number type
  docs/en-US/component/table.md
  packages/components/table/__tests__/table-test-common.ts
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/store/tree.ts
  packages/components/table/src/table/defaults.ts
  packages/components/table/src/util.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#21173 fix(components): [tree-v2] props defaultExpandedKeys not reactive
  packages/components/tree-v2/__tests__/tree.test.ts
  packages/components/tree-v2/src/composables/useTree.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#21093 feat(components): [select] expose selectDisabled prop to #tag slot
  docs/en-US/component/select-v2.md
  docs/en-US/component/select.md
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/select.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.vue
Labels: Contribution::Community, 1st contribution, Needs Review
