Repository element-plus/element-plus, pull requests merged in 2025-02, with the labels that each got.

#19766 docs: [calendar] add CalendarDateType Type Declarations
  docs/en-US/component/calendar.md
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19783 ci: fix corepack matching keyid error
  .github/workflows/publish-pr-commit-pkg.yml
Labels: CommitMessage::Qualified

#19697 docs: [scrollbar] fix type error
  docs/examples/scrollbar/manual-scroll.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19776 chore(components): [cascader-node] remove ts-nocheck and fix type error
  packages/components/cascader-panel/src/node.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19747 feat(locale): export Norsk(no)
  packages/locale/index.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19790 feat(locale): export missing language
  packages/locale/index.ts
Labels: CommitMessage::Qualified

#19793 docs: optimization API style
  docs/en-US/component/anchor.md
  docs/en-US/component/breadcrumb.md
  docs/en-US/component/button.md
  docs/en-US/component/carousel.md
  docs/en-US/component/cascader.md
  docs/en-US/component/checkbox.md
  docs/en-US/component/collapse.md
  docs/en-US/component/container.md
  docs/en-US/component/datetime-picker.md
  docs/en-US/component/descriptions.md
  docs/en-US/component/dropdown.md
  docs/en-US/component/form.md
  docs/en-US/component/image.md
  docs/en-US/component/layout.md
  docs/en-US/component/menu.md
  docs/en-US/component/radio.md
  docs/en-US/component/select.md
  docs/en-US/component/skeleton.md
  docs/en-US/component/statistic.md
  docs/en-US/component/steps.md
  docs/en-US/component/switch.md
  docs/en-US/component/table-v2.md
  docs/en-US/component/tabs.md
  docs/en-US/component/tag.md
  docs/en-US/component/timeline.md
  docs/en-US/component/tour.md
  docs/en-US/component/transfer.md
  docs/en-US/component/tree-v2.md
  docs/en-US/component/tree.md
Labels: Project::Documentation

#19831 chore: update doc
  docs/.vitepress/vitepress/components/vp-sponsors.vue
Labels: CommitMessage::Qualified

#19832 fix(components): [message-box] init validator
  packages/components/message-box/__tests__/message-box.test.ts
  packages/components/message-box/src/index.vue
Labels: CommitMessage::Qualified

#19833 docs: [message-box] update options default value
  docs/en-US/component/message-box.md
Labels: CommitMessage::Qualified

#19816 refactor(components): [menu] change to `script setup` writing and optimizing code
  packages/components/menu/src/menu-collapse-transition.vue
  packages/components/menu/src/menu-item-group.vue
  packages/components/menu/src/menu-item.vue
  packages/components/menu/src/menu.ts
  packages/components/menu/src/sub-menu.ts
  packages/components/menu/src/use-menu-color.ts
  packages/components/menu/src/use-menu-css-var.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19840 refactor: [menu] add necessary braces
  packages/components/menu/src/sub-menu.ts
Labels: CommitMessage::Qualified

#19803 fix(components): [tree-select] dynamic bind class invalid
  packages/components/tree-select/src/select.ts
Labels: CommitMessage::Qualified

#19859 test: [tree-select] dynamic class case
  packages/components/tree-select/__tests__/tree-select.test.tsx
Labels: CommitMessage::Qualified

#19865 chore: change create issue use
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: CommitMessage::Qualified

#19837 fix(components): [table] compatible with window non-existence
  packages/components/table/src/table/style-helper.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19874 feat(components): [menu] add `persistent` prop
  docs/en-US/component/menu.md
  packages/components/menu/src/menu-item.vue
  packages/components/menu/src/menu.ts
  packages/components/menu/src/sub-menu.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19875 refactor: [time-picker] optimize type declaration
  packages/components/time-picker/src/composables/use-time-panel.ts
  packages/components/time-picker/src/composables/use-time-picker.ts
  packages/components/time-picker/src/props/shared.ts
  packages/components/time-picker/src/types.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19709 fix(components): [select] solve memory leak
  packages/components/select/src/useOption.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19846 chore: [tree] export types
  packages/components/tree/index.ts
  packages/components/tree/src/tree.type.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19866 feat(components): [cascader] add suggestion slot
  docs/en-US/component/cascader.md
  docs/examples/cascader/custom-suggestion-item.vue
  packages/components/cascader/src/cascader.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19726 fix(components): [steps] update border-color to support safari
  packages/theme-chalk/src/step.scss
Labels: Needs Review

#19879 fix(components): [description] tsx rendering functional component error
  packages/components/descriptions/__tests__/descriptions.test.tsx
  packages/utils/vue/vnode.ts
Labels: CommitMessage::Qualified

#19897 fix(components): [cascader] prevent default behavior when pressing a key to toggle suggestion list
  packages/components/cascader/src/cascader.vue
Labels: CommitMessage::Qualified

#18168 feat(components): [message-box] support custom close icon in message-box
  docs/en-US/component/message-box.md
  packages/components/message-box/src/index.vue
  packages/components/message-box/src/message-box.type.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19901 fix(components): [message-box] vue warning when closeIcon is component
  packages/components/message-box/src/messageBox.ts
Labels: CommitMessage::Qualified

#19903 docs: [button] update default value and description
  docs/en-US/component/button.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19636 fix(components): [select] ensure scrollbar syncs when scrolling to selected option
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19895 fix(components): [tree-select] search solve memory leak
  packages/components/tree-select/__tests__/tree-select.test.tsx
  packages/components/tree-select/src/tree-select-option.ts
  packages/components/tree/src/model/tree-store.ts
Labels: CommitMessage::Qualified

#19889 feat(components): [slider] add `persistent` prop
  docs/en-US/component/slider.md
  packages/components/slider/src/button.vue
  packages/components/slider/src/composables/use-slider-button.ts
  packages/components/slider/src/slider.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19908 docs(components): [dropdown] update description and example
  docs/en-US/component/dropdown.md
  docs/examples/dropdown/triggering-element.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19907 docs(components): [tree] change `customized-node` example
  docs/examples/tree/customized-node.vue
Labels: CommitMessage::Qualified

#19922 ci: open commit run pr.new
  .github/workflows/publish-pr-commit-pkg.yml
Labels: CommitMessage::Qualified

#19912 chore: [dropdown] remove @ts-nocheck & fix type error
  docs/en-US/component/dropdown.md
  packages/components/collection/src/collection.ts
  packages/components/collection/src/tokens.ts
  packages/components/dropdown/src/dropdown-item-impl.vue
  packages/components/dropdown/src/dropdown-menu.vue
  packages/components/dropdown/src/dropdown.ts
  packages/components/dropdown/src/dropdown.vue
  packages/components/dropdown/src/tokens.ts
  packages/components/dropdown/src/useDropdown.ts
  packages/components/roving-focus-group/src/roving-focus-group-impl.vue
  packages/components/roving-focus-group/src/roving-focus-item.vue
  packages/components/roving-focus-group/src/tokens.ts
Labels: CommitMessage::Qualified

#19861 ci: remove odd version issue template
  .github/ISSUE_TEMPLATE.md
Labels: CommitMessage::Qualified

#19935 docs: [badge] correct the spelling mistakes in the description
  docs/en-US/component/badge.md
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#19965 chore: format docs
  docs/en-US/component/button.md
  docs/en-US/component/cascader.md
  docs/en-US/component/menu.md
Labels: Contribution::Community, Needs Review

#19715 refactor(components): [image] image-viewer standalone use
  docs/en-US/component/image.md
  docs/examples/image/manually-preview.vue
  packages/components/image-viewer/src/image-viewer.vue
  packages/components/image/src/image.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#19970 perf(components): [select-v2] optimize to avoid unnecessary computations
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, Component::SelectV2, Needs Review

#19494 feat(components): [tree/tree-select] add `check-on-click-leaf` attribute
  docs/en-US/component/tree-v2.md
  docs/en-US/component/tree.md
  packages/components/tree-select/__tests__/tree-select.test.tsx
  packages/components/tree-v2/__tests__/tree.test.ts
  packages/components/tree-v2/src/composables/useTree.ts
  packages/components/tree-v2/src/virtual-tree.ts
  packages/components/tree/__tests__/tree.test.ts
  packages/components/tree/src/tree-node.vue
  packages/components/tree/src/tree.type.ts
  packages/components/tree/src/tree.vue
Labels: needs discussion, Contribution::Community, Component::Tree, Component::TreeSelect, CommitMessage::Qualified, Needs Review

#19920 docs(components): add the `virtual-triggering` description of popover
  docs/en-US/component/popover.md
Labels: Contribution::Community, 1st contribution, Needs Review

#19984 fix(components): [select-v2] allow propagation of non-control key events in custom options
  packages/components/select-v2/src/select-dropdown.tsx
Labels: Contribution::Community, Needs Review

#19943 docs(components): [el-tooltip] add example using append-to API
  docs/en-US/component/tooltip.md
  docs/examples/tooltip/append-to.vue
Labels: Contribution::Community, 1st contribution, Needs Review
