Repository element-plus/element-plus, pull requests merged in 2025-03, with the labels that each got.

#19804 fix(components): [date-picker] change triggers twice when clearing
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#20000 fix(components): [input] `@change` event value formatter
  packages/components/input/src/input.vue
Labels: PR::Lack Of Tests, Contribution::Community, 1st contribution, Needs Review

#20035 fix(components): [dropdown] `button-props` as a `Partial` type
  packages/components/dropdown/src/dropdown.ts
Labels: Contribution::Community, Needs Review

#20020 fix(components): [date-picker] support remove same months from different years
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/src/date-picker-com/basic-month-table.vue
Labels: Contribution::Community, Needs Review

#20052 docs: fix typo in dropdown documentation for triggerKeys
  docs/en-US/component/dropdown.md
Labels: Contribution::Community, Needs Review

#20034 feat(components): [alert] add `icon` slot
  docs/en-US/component/alert.md
  docs/examples/alert/icon.vue
  packages/components/alert/src/alert.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#20076 ci: enable `publish-size-resport` action for all branch
  .github/workflows/publish-size-report.yml
Labels: Contribution::Community, Needs Review

#20079 refactor(components): [time-select] using built-in constants
  packages/components/time-select/src/time-select.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#20081 docs(components): add the virtual-ref description of popover
  docs/en-US/component/popover.md
Labels: Contribution::Community, 1st contribution, Needs Review

#19806 fix(components): [select] typed value causes `default-first-option` to fail
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#20104 chore: use event constants instead string
  packages/components/affix/src/affix.vue
  packages/components/anchor/__tests__/anchor.test.tsx
  packages/components/anchor/src/anchor.vue
  packages/components/carousel/src/use-carousel.ts
  packages/components/checkbox/src/checkbox-group.vue
  packages/components/checkbox/src/composables/use-checkbox-event.ts
  packages/components/color-picker/src/color-picker.vue
  packages/components/countdown/src/countdown.vue
  packages/components/date-picker/src/date-picker.tsx
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input/src/input.vue
  packages/components/mention/src/mention.vue
  packages/components/pagination/src/components/pager.vue
  packages/components/pagination/src/pagination.ts
  packages/components/radio/src/radio-group.vue
  packages/components/radio/src/radio.vue
  packages/components/rate/src/rate.vue
  packages/components/switch/__tests__/switch.test.tsx
  packages/components/time-picker/src/common/picker.vue
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
  packages/components/time-picker/src/time-picker.tsx
  packages/components/tour/src/tour.vue
Labels: Contribution::Community, Needs Review

#19899 feat(components): [table-column] preserve expanded content
  docs/en-US/component/table.md
  docs/examples/table/expandable-row.vue
  packages/components/table/__tests__/table-column.test.ts
  packages/components/table/src/table-body/render-helper.ts
  packages/components/table/src/table/defaults.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#20108 fix(components): [affix] scroll event value sync
  packages/components/affix/src/affix.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#20126 docs: add placement demo for popover/popconfirm
  docs/en-US/component/popconfirm.md
  docs/en-US/component/popover.md
  docs/examples/popconfirm/placement.vue
  docs/examples/popover/placement.vue
Labels: Contribution::Community, Needs Review

#20107 refactor(components): [description, input] use the component name constant
  packages/components/descriptions/src/constants.ts
  packages/components/descriptions/src/description-item.ts
  packages/components/descriptions/src/description.vue
  packages/components/input/src/input.vue
Labels: Contribution::Community, Needs Review

#20135 fix(components): [message-box] `ElMessageBoxOptions` type missing `modalClass`
  packages/components/message-box/src/message-box.type.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#20157 fix(components): [table] the selection column conflicts with setting both `showOverflowTooltip` and `align='center'` styles
  packages/components/table/src/table-column/index.ts
Labels: Contribution::Community, Needs Review

#20149 fix(components): [el-select-v2] use `:model-value` without changes
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#19764 fix(components): [empty] remove static ID attributes from SVG
  packages/components/empty/src/img-empty.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#20161 fix(components): [time-picker] custom format causes highlight errors
  packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#20186 Update ms.ts
  packages/locale/lang/ms.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#20195 docs(components): increase popover width
  docs/examples/popover/nested-operation.vue
Labels: Contribution::Community, Needs Review

#20201 Update ms.ts
  packages/locale/lang/ms.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#20216 chore(style): [table] remove duplicate defined style code
  packages/theme-chalk/src/table.scss
Labels: Contribution::Community, 1st contribution, Needs Review

#20242 docs: [table-v2] move row-event-handlers from events to attributes
  docs/en-US/component/table-v2.md
Labels: Contribution::Community, Needs Review

#20245 Added Lao (lo) language localization support
  docs/en-US/guide/i18n.md
  packages/locale/index.ts
  packages/locale/lang/lo.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#20236 docs: fix dark mode switch transition effect offset
  docs/.vitepress/vitepress/components/common/vp-theme-toggler.vue
Labels: Project::Documentation, Contribution::Community, 1st contribution, Needs Review

#20288 fix(components): [autocomplete] modelValue is null compatible
  packages/components/autocomplete/__tests__/autocomplete.test.tsx
  packages/components/autocomplete/src/autocomplete.vue
Labels: Contribution::Community, Needs Review

#19098 chore: [select] remove @ts-nocheck directive
  packages/components/select/index.ts
  packages/components/select/src/option-group.vue
  packages/components/select/src/option.ts
  packages/components/select/src/option.vue
  packages/components/select/src/options.ts
  packages/components/select/src/select.ts
  packages/components/select/src/select.vue
  packages/components/select/src/token.ts
  packages/components/select/src/type.ts
  packages/components/select/src/useOption.ts
  packages/components/select/src/useSelect.ts
  packages/components/tree-select/src/cache-options.ts
Labels: CommitMessage::Qualified

#20232 fix(components): [select, select-v2] blur validate not executed
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, Needs Review

#20300 chore: [form-item] redundant type assertion
  packages/components/form/src/form-item.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#20299 chore: [virtual-list] remove ts-nocheck directive and unused code
  packages/components/virtual-list/__tests__/scrollbar.test.ts
  packages/components/virtual-list/src/builders/build-grid.ts
  packages/components/virtual-list/src/builders/build-list.ts
  packages/components/virtual-list/src/components/dynamic-size-grid.ts
  packages/components/virtual-list/src/components/fixed-size-list.ts
  packages/components/virtual-list/src/components/scrollbar.ts
  packages/components/virtual-list/src/defaults.ts
  packages/components/virtual-list/src/hooks/use-wheel.ts
  packages/components/virtual-list/src/utils.ts
Labels: Contribution::Community, Needs Review

#20312 chore: format
  docs/en-US/component/popover.md
Labels: Contribution::Community, Needs Review
