Repository element-plus/element-plus, pull requests merged in 2025-05, with the labels that each got.

#20611 fix(components): [date-picker] correct injection key for default format
  packages/components/date-picker/src/date-picker-com/panel-year-range.vue
Labels: Contribution::Community, Needs Review

#20613 feat(components): [collapse-item ] enhance `title` slot with `isActive` property
  docs/en-US/component/collapse.md
  docs/examples/collapse/customization.vue
  packages/components/collapse/__tests__/collapse.test.tsx
  packages/components/collapse/src/collapse-item.vue
Labels: Contribution::Community, Needs Review

#20587 fix(components): [table] shrinked table expanded when modify data
  packages/components/table/__tests__/table.test.ts
  packages/components/table/src/store/tree.ts
  packages/components/table/src/table-footer/mapState-helper.ts
Labels: Contribution::Community, Needs Review

#20577 fix(components): [tooltip] listen clickoutside after open
  packages/components/tooltip/src/content.vue
Labels: Contribution::Community, Needs Review

#20567 refactor(components): [form] make exposed `fields` reactive
  packages/components/form/src/form.vue
Labels: Contribution::Community, Needs Review

#20615 fix(components): [select] update selection width calculation
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/useSelect.ts
Labels: Contribution::Community, Needs Review

#20528 chore: add missing path mapping for locale
  tsconfig.base.json
Labels: Contribution::Community, Needs Review

#19537 feat(components): [collapse] add expand icon position customization
  docs/en-US/component/collapse.md
  docs/examples/collapse/custom-icon-position.vue
  packages/components/collapse/src/collapse-item.vue
  packages/components/collapse/src/collapse.ts
  packages/components/collapse/src/collapse.vue
  packages/components/collapse/src/use-collapse-item.ts
  packages/components/collapse/src/use-collapse.ts
  packages/theme-chalk/src/collapse.scss
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#20550 fix(components): [date-picker] merge default-value with default-time
  packages/components/date-picker/src/composables/use-range-picker.ts
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  ssr-testing/cases/date-time-picker.vue
Labels: Contribution::Community, Needs Review

#20049 fix(components): [popper] fix arrow overflow issue
  docs/en-US/component/tooltip.md
  packages/components/popper/__tests__/arrow.test.tsx
  packages/components/popper/src/arrow.vue
  packages/components/popper/src/composables/use-content.ts
  packages/components/popper/src/constants.ts
  packages/components/popper/src/content.ts
  packages/components/popper/src/content.vue
  packages/components/tooltip/src/content.vue
  packages/components/tooltip/src/tooltip.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#20371 fix(components): [loading] inherit app context
  docs/en-US/component/loading.md
  packages/components/loading/__tests__/loading.test.tsx
  packages/components/loading/index.ts
  packages/components/loading/src/directive.ts
  packages/components/loading/src/loading.ts
  packages/components/loading/src/service.ts
Labels: Contribution::Community, Needs Review

#20668 fix(components): [select-v2] label error when multiple and remote
  packages/components/select-v2/__tests__/select.test.ts
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, Needs Review

#20688 fix(components): [select-v2] tooltipRef maybe undefined
  packages/components/select-v2/src/select-dropdown.tsx
Labels: Contribution::Community, Needs Review

#19700 feat(components): [date-picker] add quick year and month selection
  packages/components/date-picker/__tests__/date-picker.test.ts
  packages/components/date-picker/src/composables/use-panel-date-range.ts
  packages/components/date-picker/src/date-picker-com/panel-date-range.vue
  packages/theme-chalk/src/date-picker/date-range-picker.scss
Labels: Contribution::Community, Component::DatePicker, CommitMessage::Qualified, Needs Review

#20732 fix(components): [cascader] safeguard arrow modifier access in popper options
  packages/components/cascader/src/cascader.vue
Labels: Contribution::Community, Needs Review

#20726 feat(components): [config-provider] support more button config
  docs/en-US/component/config-provider.md
  docs/examples/config-provider/button.vue
  packages/components/button/src/button.ts
  packages/components/button/src/button.vue
  packages/components/button/src/use-button.ts
  packages/components/config-provider/__tests__/config-provider.test.tsx
Labels: Contribution::Community, Needs Review

#19021 fix(components): [table-v2] modify the width calculation logic
  packages/components/table-v2/src/composables/use-styles.ts
  packages/components/table-v2/src/table-v2.tsx
  packages/components/table-v2/src/use-table.ts
  packages/components/virtual-list/__tests__/scrollbar.test.ts
  packages/components/virtual-list/src/components/scrollbar.ts
Labels: Contribution::Community, CommitMessage::Qualified, Needs Review

#20743 docs: add `check-on-click-leaf` warnings
  docs/en-US/component/tree-select.md
  docs/en-US/component/tree-v2.md
  docs/en-US/component/tree.md
  docs/examples/tree-select/check-strictly.vue
Labels: Contribution::Community, Needs Review

#20758 docs: add missing button types
  docs/en-US/component/button.md
  docs/en-US/component/tooltip.md
Labels: Contribution::Community, Needs Review

#20764 docs: remove confusing dialog attributes
  docs/examples/dialog/fullscreen.vue
Labels: Contribution::Community, Needs Review

#20759 refactor: delete useless code
  packages/components/input/src/input.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#20773 feat(components): [config-provider] support `link` config
  docs/en-US/component/config-provider.md
  docs/examples/config-provider/link.vue
  packages/components/config-provider/__tests__/config-provider.test.tsx
  packages/components/config-provider/src/config-provider-props.ts
  packages/components/link/src/link.ts
  packages/components/link/src/link.vue
Labels: Contribution::Community, Needs Review

#20783 docs: update a new contributions charts
  README.md
Labels: Contribution::Community, 1st contribution, Needs Review

#20582 fix(components): [table] the selection column cannot be displayed when it is not in the first row
  packages/components/table/__tests__/table-column.test.ts
  packages/components/table/src/store/watcher.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#20202 chore: [table-v2] remove ts-nocheck directive
  packages/components/table-v2/src/composables/use-columns.ts
  packages/components/table-v2/src/renderers/row.tsx
  packages/components/table-v2/src/table-v2.tsx
Labels: Contribution::Community, Needs Review

#16124 fix(components): [input-number] Improve modelValue prop type
  docs/en-US/component/input-number.md
  packages/components/input-number/src/input-number.ts
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#20695 refactor(components): improve alignment type definitions
  docs/en-US/component/descriptions.md
  packages/components/descriptions/src/description-item.ts
  packages/components/descriptions/src/descriptions.type.ts
  packages/components/table-v2/src/types.ts
  packages/constants/column-alignment.ts
  packages/constants/index.ts
Labels: Contribution::Community, Needs Review

#20806 fix(components): [date-time-picker] inherit time across picker views
  packages/components/date-picker/__tests__/date-time-picker.test.tsx
  packages/components/date-picker/src/composables/use-panel-date-range.ts
  packages/components/date-picker/src/date-picker-com/basic-month-table.vue
  packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
  packages/components/date-picker/src/utils.ts
Labels: Contribution::Community, Needs Review

#20731 fix(components): [cascader-panel] value can be an empty string
  packages/components/cascader-panel/__tests__/cascader-panel.test.tsx
  packages/components/cascader-panel/src/store.ts
Labels: Contribution::Community, Needs Review

#20807 fix(components): [image-viewer] dont persist image preview list
  packages/components/image-viewer/__tests__/image-viewer.test.tsx
  packages/components/image-viewer/src/image-viewer.vue
  packages/components/image/__tests__/image.test.tsx
Labels: Contribution::Community, Needs Review

#20533 feat(components): [alert] add open and auto-close functionality with delays
  docs/en-US/component/alert.md
  docs/examples/alert/delayed.vue
  packages/components/alert/src/alert.ts
  packages/components/alert/src/alert.vue
Labels: Contribution::Community, Needs Review

#20832 fix: [color-picker] Fix invalid color code clearing
  packages/components/color-picker/src/color-picker.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#20863 fix(components): [config-provider] provide global config function is invalid for message
  packages/components/config-provider/__tests__/config-provider.test.tsx
  packages/components/config-provider/src/config-provider.ts
Labels: Contribution::Community, Needs Review

#20875 fix(components): [text] the title attribute loses its reactivity
  packages/components/text/src/text.vue
Labels: Contribution::Community, Needs Review

#20812 feat(components): [scrollbar] add `end-reached` event
  docs/en-US/component/scrollbar.md
  docs/examples/scrollbar/infinite-scroll.vue
  packages/components/scrollbar/__tests__/scrollbar.test.tsx
  packages/components/scrollbar/src/scrollbar.ts
  packages/components/scrollbar/src/scrollbar.vue
  packages/components/scrollbar/src/thumb.vue
Labels: Contribution::Community, Needs Review

#20750 feat(components): [table-column] add `expand` slot
  docs/en-US/component/table.md
  packages/components/table/src/config.ts
  packages/components/table/src/table-column/render-helper.ts
Labels: Contribution::Community, Needs Review
