Repository element-plus/element-plus, pull requests merged in 2025-08, with the labels that each got.

#21508 feat(components): [cascader] add `check-on-click-leaf` attribute
  docs/en-US/component/cascader.md
  docs/examples/cascader/check-on-click-node.vue
  packages/components/cascader-panel/src/config.ts
  packages/components/cascader-panel/src/node-content.tsx
  packages/components/cascader-panel/src/node.ts
  packages/components/cascader-panel/src/node.vue
  packages/components/cascader/__tests__/cascader.test.tsx
Labels: breaking change

#21579 refactor(components): [message] use `MessageType` replace `messageType`
  packages/components/message/src/message.ts
  packages/components/message/src/method.ts
Labels: Contribution::Community, Needs Review

#21586 refactor(components): [tour] improve code style
  packages/components/tour/src/mask.vue
Labels: Contribution::Community, Needs Review

#21601 style(components): Replace inset to provide better compatibility
  packages/theme-chalk/src/segmented.scss
  packages/theme-chalk/src/splitter.scss
Labels: Contribution::Community, Needs Review

#21573 fix(components): [image] support lazy inside transformed containers
  packages/components/image/src/image.vue
Labels: Contribution::Community, Needs Review

#21634 refactor(components): [message-box] remove duplicates conditional
  packages/components/message-box/src/index.vue
Labels: Contribution::Community, Needs Review

#21594 feat(components): [autocomplete] add header and footer slot
  docs/en-US/component/autocomplete.md
  docs/examples/autocomplete/custom-header-footer.vue
  packages/components/autocomplete/__tests__/autocomplete.test.tsx
  packages/components/autocomplete/src/autocomplete.vue
  packages/theme-chalk/src/autocomplete.scss
Labels: Contribution::Community, 1st contribution, Needs Review

#21685 chore(components): [config-provider] improve jsdoc navigation links
  packages/components/config-provider/src/config-provider-props.ts
Labels: Contribution::Community, Needs Review

#21687 docs(components): [dropdown] fix typo
  docs/examples/dropdown/placements.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#21690 docs: sync switch state with system color scheme
  docs/.vitepress/vitepress/components/common/vp-theme-toggler.vue
Labels: Contribution::Community, Needs Review

#21684 feat(components): [config-provider] support `dialog` config
  docs/en-US/component/config-provider.md
  docs/examples/config-provider/dialog.vue
  packages/components/config-provider/__tests__/config-provider.test.tsx
  packages/components/config-provider/src/config-provider-props.ts
  packages/components/dialog/src/dialog-content.ts
  packages/components/dialog/src/dialog-content.vue
  packages/components/dialog/src/dialog.ts
  packages/components/dialog/src/dialog.vue
  packages/components/dialog/src/use-dialog.ts
Labels: Contribution::Community, Needs Review

#21695 docs: Improve the demo of transition object in config-provider
  docs/examples/config-provider/dialog.vue
Labels: Contribution::Community, Needs Review

#21681 feat(components): [popconfirm] expose hide function and popperRef
  docs/en-US/component/popconfirm.md
  packages/components/popconfirm/src/popconfirm.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#21694 fix(components): [scrollbar] resize according to container size
  packages/components/scrollbar/src/scrollbar.vue
Labels: Contribution::Community, Needs Review

#21718 refactor(components): export `TreeV2Instance` & optimize type usage
  docs/examples/select-v2/custom-footer.vue
  docs/examples/tree-v2/filter.vue
  packages/components/tree-select/src/select.ts
  packages/components/tree-select/src/tree.ts
  packages/components/tree-v2/index.ts
  packages/components/tree-v2/src/instance.ts
Labels: Contribution::Community, Needs Review

#21736 fix(components): [carousel] special case `activeIndex` is inaccurate
  packages/components/carousel/__tests__/carousel.test.tsx
  packages/components/carousel/src/carousel.vue
  packages/components/carousel/src/use-carousel.ts
Labels: Contribution::Community, Needs Review

#21742 fix(components): [splitter] `collapsible` does not take effect dynamically
  docs/examples/splitter/collapsible.vue
  packages/components/splitter/src/split-panel.vue
Labels: Contribution::Community, Needs Review

#21652 fix(components): [cascader-panel] ensure set null after clear
  packages/components/cascader-panel/__tests__/cascader-panel.test.tsx
  packages/components/cascader-panel/src/index.vue
  packages/components/cascader-panel/src/node-content.tsx
Labels: Contribution::Community, Needs Review

#21763 docs(components): [menu] missing expose `handleResize ` method
  docs/en-US/component/menu.md
Labels: Contribution::Community, Needs Review

#21766 feat(components): [tour] support keyboard switching steps
  packages/components/tour/src/step.vue
Labels: Contribution::Community, Needs Review

#21414 fix(components): [cascader] issue when lazy loading returns leaf nodes
  packages/components/cascader-panel/__tests__/cascader-panel.test.tsx
  packages/components/cascader-panel/src/index.vue
  packages/components/cascader-panel/src/store.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#21738 fix(components): [splitter] collapse works with two-way size and min & max
  packages/components/splitter/__tests__/splitter.test.tsx
  packages/components/splitter/src/split-panel.vue
Labels: Contribution::Community, Needs Review

#21703 feat(components): add isDragging to useDraggable for dialog/message-box
  docs/examples/dialog/draggable-dialog.vue
  docs/examples/message-box/draggable.vue
  packages/components/dialog/src/dialog-content.vue
  packages/components/message-box/src/index.vue
  packages/hooks/use-draggable/index.ts
Labels: Contribution::Community, Needs Review

#21779 style(components): [collapse] adapt height when customizing title
  packages/theme-chalk/src/collapse.scss
Labels: Contribution::Community, Needs Review

#21812 fix(components): [slider] correctly reset sliderSize
  packages/components/slider/__tests__/slider.test.tsx
  packages/components/slider/src/composables/use-slide.ts
Labels: Contribution::Community, Needs Review

#21814 fix(components): [radio-group] prop-value cause ivalidate loop
  packages/components/radio/src/radio-group.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#21423 fix(build): path compatible with Windows platform
  internal/build-utils/src/paths.ts
  internal/build-utils/src/pkg.ts
  internal/build/src/tasks/helper.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#21489 docs: improve examples layout for narrow screens
  docs/.vitepress/vitepress/components/globals/icons.vue
  docs/examples/autocomplete/autocomplete.vue
  docs/examples/autocomplete/custom-loading.vue
  docs/examples/avatar/basic.vue
  docs/examples/button/basic.vue
  docs/examples/button/disabled.vue
  docs/examples/date-picker-panel/border.vue
  docs/examples/date-picker/custom-content.vue
  docs/examples/date-picker/custom-icon.vue
  docs/examples/date-picker/date-formats.vue
  docs/examples/date-picker/date-range.vue
  docs/examples/date-picker/default-value.vue
  docs/examples/date-picker/enter-date.vue
  docs/examples/date-picker/month-range.vue
  docs/examples/date-picker/other-measurements.vue
  docs/examples/date-picker/year-range.vue
  docs/examples/datetime-picker/custom-icon.vue
  docs/examples/datetime-picker/date-and-time-formats-panel.vue
  docs/examples/datetime-picker/date-and-time-formats.vue
  docs/examples/datetime-picker/date-and-time-range.vue
  docs/examples/datetime-picker/date-and-time.vue
  docs/examples/datetime-picker/default-time.vue
  docs/examples/dialog/customization-content.vue
  docs/examples/image/basic-usage.vue
  docs/examples/input-number/controlled.vue
  docs/examples/input-number/size.vue
  docs/examples/input/with-icon.vue
  docs/examples/message-box/use-vnode.vue
  docs/examples/message/basic.vue
  docs/examples/message/closable.vue
  docs/examples/message/different-types.vue
  docs/examples/message/plain.vue
  docs/examples/notification/basic.vue
  docs/examples/notification/different-types.vue
  docs/examples/notification/positioning.vue
  docs/examples/notification/use-vnode.vue
  docs/examples/statistic/basic.vue
  docs/examples/statistic/card.vue
  docs/examples/statistic/countdown.vue
  docs/examples/time-select/time-range.vue
  docs/examples/tooltip/append-to.vue
  docs/examples/transitions/collapse.vue
  docs/examples/transitions/fade.vue
  docs/examples/transitions/zoom.vue
  docs/examples/tree/checking-tree.vue
  ssr-testing/cases/transition.vue
Labels: Contribution::Community, Needs Review

#21477 feat(components): [input-tag] add `collapse-*` prop
  docs/en-US/component/input-tag.md
  docs/examples/input-tag/collapse.vue
  packages/components/input-tag/__tests__/input-tag.test.tsx
  packages/components/input-tag/src/composables/use-input-tag.ts
  packages/components/input-tag/src/input-tag.ts
  packages/components/input-tag/src/input-tag.vue
  packages/theme-chalk/src/input-tag.scss
Labels: Contribution::Community, 1st contribution, Needs Review

#21844 fix(components): [select & select-v2] avoid line break when input is empty
  packages/components/select-v2/src/useSelect.ts
  packages/components/select/src/useSelect.ts
  packages/constants/form.ts
  packages/constants/index.ts
  packages/hooks/use-calc-input-width/index.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#21859 fix(components): [color-picker-panel] sync bg-color with date-picker-panel
  packages/theme-chalk/src/color-picker-panel.scss
Labels: CommitMessage::Unqualified

#21849 fix(components): scrollbar fix thumb size calculation error
  packages/components/virtual-list/__tests__/scrollbar.test.ts
  packages/components/virtual-list/src/components/scrollbar.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#21831 fix(components): [cascader] keep panel open on checkOnClickNode
  packages/components/cascader-panel/src/node.vue
  packages/components/cascader/__tests__/cascader.test.tsx
Labels: Contribution::Community, 1st contribution, Needs Review

#21888 fix(components): [date-picker-panel] remove duplicate panels on inner date input change
  packages/components/date-picker-panel/__tests__/date-picker-panel.test.tsx
  packages/components/date-picker-panel/src/composables/use-range-picker.ts
  packages/components/date-picker-panel/src/date-picker-com/panel-date-range.vue
  packages/components/date-picker-panel/src/date-picker-com/panel-month-range.vue
  packages/components/date-picker-panel/src/date-picker-com/panel-year-range.vue
Labels: CommitMessage::Unqualified

#21904 fix(components): [notification] correctly read the first offset
  packages/components/notification/src/notify.ts
Labels: Contribution::Community, Needs Review

#21906 refactor(components): [drawer] improve slot template
  packages/components/drawer/src/drawer.vue
Labels: Contribution::Community, Needs Review

#21545 feat(components): [checkbox-group] support options
  docs/en-US/component/checkbox.md
  docs/examples/checkbox/options.vue
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/checkbox/src/checkbox-group.ts
  packages/components/checkbox/src/checkbox-group.vue
Labels: Contribution::Community, Needs Review

#21962 docs: improve drawer api tips
  docs/en-US/component/drawer.md
Labels: Contribution::Community, Needs Review

#21965 feat(components): [popConfirm] support effect
  docs/en-US/component/popconfirm.md
  packages/components/popconfirm/src/popconfirm.ts
  packages/components/popconfirm/src/popconfirm.vue
Labels: Contribution::Community, Needs Review

#21966 refactor(components): [cascader] adjust the ts type
  packages/components/cascader/src/cascader.vue
  packages/components/popper/index.ts
Labels: Contribution::Community, Needs Review
