Repository element-plus/element-plus, pull requests merged in 2025-07, with the labels that each got.

#21197 refactor(components): [table] remove `@ts-nocheck`
  packages/components/table/src/config.ts
  packages/components/table/src/filter-panel.vue
  packages/components/table/src/h-helper.ts
  packages/components/table/src/layout-observer.ts
  packages/components/table/src/store/current.ts
  packages/components/table/src/store/helper.ts
  packages/components/table/src/table-body/defaults.ts
  packages/components/table/src/table-header/index.ts
  packages/components/table/src/table/utils-helper.ts
Labels: CommitMessage::Unqualified

#19433 fix(components): [tabs] focus may still remain in pane when tabs changed
  packages/components/tabs/__tests__/tabs.test.tsx
  packages/components/tabs/src/constants.ts
  packages/components/tabs/src/tab-bar.ts
  packages/components/tabs/src/tab-bar.vue
  packages/components/tabs/src/tab-nav.tsx
  packages/components/tabs/src/tab-pane.vue
  packages/components/tabs/src/tabs.tsx
Labels: CommitMessage::Qualified

#21206 fix(components): [autocomplete] add placeholder prop type definition
  docs/en-US/component/autocomplete.md
  packages/components/autocomplete/src/autocomplete.ts
  packages/components/autocomplete/src/autocomplete.vue
  packages/components/input/src/input.ts
  packages/components/input/src/input.vue
  packages/components/time-picker/src/common/picker.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#21050 feat(components): [mention] add `whole-remove` event
  docs/en-US/component/mention.md
  packages/components/mention/src/mention.ts
  packages/components/mention/src/mention.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#19405 feat(components): [input-number] warn when exceeds the safe integer
  packages/components/input-number/src/input-number.vue
Labels: CommitMessage::Qualified

#21266 fix(types): [other] cannot find declare module types from installed packages
  internal/build/src/tasks/types-definitions.ts
  packages/utils/vue/props/util.ts
  packages/utils/vue3.3.polyfill.ts
  tsconfig.play.json
  tsconfig.vitest.json
  tsconfig.web.json
Labels: Contribution::Community, Needs Review

#20983 fix(components): [tooltip] avoid repeated onBeforeEnter execution
  packages/components/tooltip/__tests__/content.test.tsx
  packages/components/tooltip/src/content.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#21309 fix(components): [checkbox-group] dynamic prop-value cause ivalidate loop
  packages/components/checkbox/__tests__/checkbox.test.tsx
  packages/components/checkbox/src/checkbox-group.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#21300 feat(components): [notification] support updateOffsets command
  docs/en-US/component/notification.md
  packages/components/notification/__tests__/notify.test.tsx
  packages/components/notification/src/notification.ts
  packages/components/notification/src/notify.ts
Labels: Contribution::Community, Needs Review

#21367 test(components): add `close-on-press-escape` test case
  packages/components/dialog/__tests__/dialog.test.tsx
  packages/components/image-viewer/__tests__/image-viewer.test.tsx
  packages/components/image/__tests__/image.test.tsx
  packages/components/tour/__tests__/tour.test.tsx
Labels: Contribution::Community, Needs Review

#21291 feat(components): [input-number] add align prop
  docs/en-US/component/input-number.md
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.ts
  packages/components/input-number/src/input-number.vue
  packages/theme-chalk/src/input-number.scss
Labels: Contribution::Community, 1st contribution, Needs Review

#21379 fix(components): [segmented] fix label item width render
  packages/components/segmented/src/segmented.vue
Labels: Contribution::Community, Needs Review

#21388 style(theme-chalk): fix focus issue when clicking label blank area
  packages/theme-chalk/src/form.scss
Labels: Contribution::Community, Needs Review

#21319 feat(components): [input-number] disable scientific
  docs/en-US/component/input-number.md
  packages/components/input-number/__tests__/input-number.test.tsx
  packages/components/input-number/src/input-number.ts
  packages/components/input-number/src/input-number.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#21413 refactor(components): improve tab Observer name
  packages/components/tabs/src/tab-bar.vue
Labels: Contribution::Community, Needs Review

#21385 style(components): [popper] avoid incorrect word wrapping
  packages/theme-chalk/src/popper.scss
Labels: Contribution::Community, 1st contribution, Needs Review

#21419 fix(components): [select-v2] resolve invalid filter and remote methods
  packages/components/select-v2/src/useSelect.ts
Labels: Contribution::Community, Needs Review

#21371 fix(components): [pagination] reset icon hover state when page changes
  packages/components/pagination/__tests__/pagination.test.tsx
  packages/components/pagination/src/components/pager.vue
Labels: Contribution::Community, Needs Review

#21377 fix(components): [tree] keyboard nav broken after filter/collapse
  packages/components/tree/__tests__/tree.test.ts
  packages/components/tree/src/model/node.ts
  packages/components/tree/src/model/useKeydown.ts
Labels: Contribution::Community, Needs Review

#21429 style(theme-chalk): [transfer] inherit checkbox & fix last item margin
  packages/theme-chalk/src/transfer.scss
Labels: Contribution::Community, Needs Review

#21259 fix(components): [splitter] ensure `cacheCollapsedSize` is set
  packages/components/splitter/src/hooks/useResize.ts
Labels: Contribution::Community, Needs Review

#21454 fix(components): [table] fix absence of theadRef bug
  packages/components/table/src/table-header/index.ts
Labels: Contribution::Community, 1st contribution, Needs Review

#21462 docs(components): [tree-v2] prettier & correct types
  docs/en-US/component/tree-v2.md
Labels: Contribution::Community, Needs Review

#21089 feat(components): [cascader] add `checkOnClickNode` and `prefix` prop
  docs/en-US/component/cascader.md
  docs/examples/cascader/check-on-click-node.vue
  packages/components/cascader-panel/src/config.ts
  packages/components/cascader-panel/src/node-content.tsx
  packages/components/cascader-panel/src/node.ts
  packages/components/cascader-panel/src/node.vue
  packages/components/cascader/__tests__/cascader.test.tsx
  packages/components/cascader/src/cascader.ts
  packages/components/select/src/option.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#21461 fix(components): prevent prefix and suffix operations in disabled state
  packages/theme-chalk/src/input.scss
Labels: Contribution::Community, 1st contribution, Needs Review

#21473 chore(components): fix typos
  packages/components/dialog/src/use-dialog.ts
  packages/components/menu/src/menu.ts
  packages/components/message-box/src/index.vue
  packages/components/popover/__tests__/popover.test.tsx
  packages/components/statistic/__tests__/statistic.test.tsx
  packages/components/steps/__tests__/steps.test.tsx
  packages/components/table-v2/src/renderers/row.tsx
  packages/components/table/__tests__/table-column.test.ts
  packages/components/table/__tests__/table-test-common.ts
  packages/components/table/__tests__/table.test.ts
  packages/components/watermark/src/utils.ts
Labels: Contribution::Community, Needs Review

#21391 fix(components): [form] maximum recursive updates exceeded
  packages/components/form/src/hooks/use-form-item.ts
Labels: Contribution::Community, Needs Review

#20518 fix(components): [dropdown] prevent unexpected scrolling on hovering
  packages/components/dropdown/src/dropdown-item.vue
  packages/components/dropdown/src/dropdown.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#21476 style(components): [input] prevent slot element width squeeze
  packages/theme-chalk/src/input.scss
Labels: Contribution::Community, 1st contribution, Needs Review

#21472 fix(components): [table-v2] keep hover state after expanded
  packages/components/table-v2/src/composables/use-row.ts
  packages/components/table-v2/src/row.ts
Labels: Contribution::Community, Needs Review

#21486 feat(components): [cascader] add header and footer slot
  docs/en-US/component/cascader.md
  docs/examples/cascader/custom-header-footer.vue
  packages/components/cascader/src/cascader.vue
  packages/theme-chalk/src/cascader.scss
  packages/theme-chalk/src/common/var.scss
Labels: Contribution::Community, Needs Review

#21485 refactor(components): [scrollbar] Simplifying updateTriggerStatus
  packages/components/scrollbar/src/scrollbar.vue
Labels: Contribution::Community, Needs Review

#16922 feat(components): [cascader] add `show-checked-strategy` prop
  docs/en-US/component/cascader.md
  docs/examples/cascader/show-checked-strategy.vue
  packages/components/cascader/src/cascader.ts
  packages/components/cascader/src/cascader.vue
Labels: Contribution::Community, 1st contribution, CommitMessage::Qualified, Needs Review

#21008 fix(theme-chalk): [tabs]: include border-top in nav height
  packages/theme-chalk/src/tabs.scss
Labels: Contribution::Community, 1st contribution, Needs Review

#21507 feat(components): [cascader] add `effect` prop
  docs/en-US/component/cascader.md
  packages/components/cascader/src/cascader.ts
  packages/components/cascader/src/cascader.vue
Labels: Contribution::Community, Needs Review

#21503 fix(components): [tree]: fix dynamic binding `defaultCheckedKeys` trigger rerender
  packages/components/tree/src/tree.vue
Labels: Contribution::Community, Needs Review

#21516 docs(components): [tour] clean up duplicate description
  packages/components/tour/src/content.ts
Labels: Contribution::Community, Needs Review

#21203 feat(components): [select] support options prop rendering
  docs/en-US/component/select.md
  docs/examples/select/options.vue
  packages/components/select/__tests__/select.test.ts
  packages/components/select/src/select.ts
  packages/components/select/src/select.vue
Labels: Contribution::Community, 1st contribution, Needs Review

#21544 docs: fix a file name
  docs/en-US/guide/transitions.md
Labels: Contribution::Community, 1st contribution, Needs Review

#21539 feat(components): [table] support native scrollbar
  docs/en-US/component/table.md
  packages/components/table/src/table.vue
  packages/components/table/src/table/defaults.ts
Labels: Contribution::Community, Needs Review

#21552 refactor(components): [form] enhance `scrollIntoViewOptions` type
  docs/en-US/component/form.md
  packages/components/form/src/form.ts
Labels: Contribution::Community, Needs Review

#21538 fix(components): [select-v2] avoid abnormal display of new options
  packages/components/select-v2/src/useAllowCreate.ts
Labels: Contribution::Community, Needs Review
